### ISSUE TITLE
Crash on Linux+KDE(Qt GUI backend)+Multi monitor setup

### ISSUE THREAD

**Issue by new-sashok724** [RPCS3/rpcs3#10136]
## Quick summary
RPCS3 crashes when i try to launch any game not on first monitor.

## Details
I have 3 monitors on my system. When i try to launch any game not on first monitor, RPCS3 freezes and crashes in a few seconds.

Output in terminal:
```
Debugger: 0
/usr/include/c++/10.2.0/bits/stl_algo.h:3677: constexpr const _Tp& std::clamp(const _Tp&, const _Tp&, const _Tp&) [with _Tp = int]: Assertion '!(__hi < __lo)' failed.
[1]    117616 abort (core dumped)  rpcs3
```

Backtrace:
```
Thread 1 (Thread 0x7fffed00bc40 (LWP 102241) "rpcs3"):
#0  0x00007ffff44beef5 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff44a8862 in abort () at /usr/lib/libc.so.6
#2  0x00000000005ca82a in std::__replacement_assert(char const*, int, char const*, char const*) (__file=__file@entry=0x289fbe0 "/usr/include/c++/10.2.0/bits/stl_algo.h", __line=__line@entry=3677, __function=__function@entry=0x289fb88 "constexpr const _Tp& std::clamp(const _Tp&, const _Tp&, const _Tp&) [with _Tp = int]", __condition=__condition@entry=0x289fd02 "!(__hi < __lo)") at /usr/include/c++/10.2.0/x86_64-pc-linux-gnu/bits/c++config.h:457
#3  0x0000000000f3fa81 in std::clamp<int>(int const&, int const&, int const&) (__hi=<optimized out>, __lo=<optimized out>, __val=<optimized out>) at /usr/include/c++/10.2.0/bits/stl_algo.h:3677
        available_geometry = {x1 = 3840, y1 = 0, x2 = <optimized out>, y2 = <optimized out>}
        pos = {xp = 5332, yp = 599}
#4  gs_frame::showEvent(QShowEvent*) (this=0x7fff3031c990, event=0x7fffffffd000) at /usr/src/debug/rpcs3/rpcs3/rpcs3qt/gs_frame.cpp:141
        available_geometry = {x1 = 3840, y1 = 0, x2 = <optimized out>, y2 = <optimized out>}
        pos = {xp = 5332, yp = 599}
#5  0x00007ffff51bcb95 in QWindow::event(QEvent*) () at /usr/lib/libQt5Gui.so.5
```

I think it is caused by these lines:
https://github.com/RPCS3/rpcs3/blob/266c4209c453e3cddd027eaf9be3eee2b0f672c8/rpcs3/rpcs3qt/gs_frame.cpp#L141
https://github.com/RPCS3/rpcs3/blob/266c4209c453e3cddd027eaf9be3eee2b0f672c8/rpcs3/rpcs3qt/gs_frame.cpp#L142
Before commit e557c962fbeb319dddf7652fde9f0bea235e469e this method worked well.

I don't know C++ or Qt, but it looks like it is because `available_geometry.left()` and `available_geometry.top()` is assumed to be zero and they are not added to `width()`/`height()` in third clamp argument, so my suggested solution (which may be totally wrong) is:
```C
	pos.setX(std::clamp(pos.x(), available_geometry.left(), available_geometry.left() + available_geometry.width() - frameGeometry().width()));
	pos.setY(std::clamp(pos.y(), available_geometry.top(), available_geometry.top() + available_geometry.height() - frameGeometry().height()));
```
But i don't know if it will work in cases where window is stretched to multiple monitors.

#### 1. Please attach RPCS3's log.
Not relevant

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
Not graphical issue

#### 3. Please attach screenshots of your problem.
Not relevant

#### 4. Please provide comparison with real PS3.
Not relevant

#### 5. Please provide your system configuration:
Not relevant except OS

* OS: Arch Linux latest, kernel 5.11.15
* CPU: AMD Ryzen 3950X
* GPU: AMD Radeon 5700XT
* Driver version: Mesa 21.0.2

**Comment by Megamouse** [comment]
The mentioned PR should fix the issue.
I have no idea why Qt would crash though.
Seems like some upstream bug. Setting the window position to some garbage value should not result in a crash imo

**Comment by new-sashok724** [comment]
It crashes in clamp function, not in Qt

**Comment by new-sashok724** [comment]
Also, i think it would still crash if window width/height + position is bigger than width/height of the single screen. Maybe use min/max, not clamp?
