### ISSUE TITLE
Resistance 2™ [BCES00226] jittery audio

### ISSUE THREAD

**Issue by MainTomato** [RPCS3/rpcs3#10450]
- **Quick summary**
Resistance 2 version 01.00 and later has jittery audio on the default settings and even with time stretching enabled on the first campaign cutscene. So bad to the point that you can't understand what the characters are saying.

- **RPCS3's log**
https://0.0g.gg/?d9a3c612b239662b#CyaRdBHkSJkpzC7kfzGW7uxs9EJvcp8GWWzHvATwMvXa
- system configuration:

    OS: Linux Mint 20.1 Cinnamon
    CPU: AMD Ryzen 5 3600 6-Core Processor × 6
    GPU: GeForce GTX 1080 Ti
    Driver version: 460.80
    RPCS3 Version: 0.0.16-1-dfbd63df Alpha (Flatpak, same result on appimage)

- **Please include**.
Posted this issue before but didn't provide enough information, now have provided a log file and system information. original here https://github.com/RPCS3/rpcs3/issues/8565 (Sorry for not giving enough information before, I'm new at posting issues.)

**Comment by digitaldude555** [comment]
Turn off spu loop detection.

**Comment by MainTomato** [comment]
@digitaldude555 Didn't fix.

**Comment by MainTomato** [comment]
Video: https://peertube.co.uk/videos/watch/26a0eb88-ae06-41cd-9a94-6d60a30fa930

**Comment by lainiwaku** [comment]
tested on windows and working great, you have no other audio choice to test  outside of that " Renderer: FAudio" ?

**Comment by MainTomato** [comment]
@lainiwaku I believe this Is a Linux (Ubuntu/Debian) only issue. Haven't tested on Arch or Windows.

**Comment by SolomonGrundyThanksForTheTurkey** [comment]
I have the same issue on windows 
Completely broken opening cutscene with intense audio jitter - using global settings. 
I7 10750H 
RTX 2070
16GB RAM

**Comment by nitroos-ai** [comment]
Retest with latest master.

**Comment by MainTomato** [comment]
> Retest with latest master.

Issue is still present.

**Comment by nitroos-ai** [comment]
I just tried the game with TSX and SPU Decoder: ASMJIT and it's working great. Although doesn't seem to work well with SPU Decoder: LLVM as it freezes the emulator when compiling graphics.

**Comment by Jonathan44062** [comment]
The issue is still present, it happen if you update or not the game, I tried both, the results are the same.

**Comment by MainTomato** [comment]
[untitled.webm](https://user-images.githubusercontent.com/57838286/197812825-9e280de6-8944-4d52-b7ce-fd7d78a7a455.webm)
This was recorded with 0.0.24-1-ee3e3667 Alpha

**Comment by crayt90** [comment]
This issue still persists on SteamDeck with RPCS3 0.0.25-1-8be4ac68 Alpha.

In-game works without issue, rarely under 25 fps, no audio-stutter.
But cutscene audio stutters.

As I'm no coder, I can't really help in resolving this issue besides testing.
Let me know if I should test something or you need better input, I might be able to deliver from my rig.

**Comment by Tha14** [comment]
Still experiencing severe stuttering in cutscenes.

OS: Windows 10 19042.867
CPU: AMD Ryzen 5 3600 6-Core Processor × 6
GPU: GeForce GTX 1660 Super OC
Driver version: 527.56
RPCS3 Version: 0.0.26-14688-0d2714a1

**Comment by Jonathan44062** [comment]
Can we close this? The issue with the cutscenes in Resistance 2 are fixed
https://drive.google.com/file/d/1ZZ5zL1T_afNbLSMzNZBOFIhLEN1cXmio/view?usp=sharing

**Comment by b800047** [comment]
just to confirm and leave this here, this issue is still present until a fix is made or discovered...especially the intro...

OS: Windows 11 Home 22H2 / 22621.2283
CPU: AMD Ryzen 7 2700 Eight-Core Processor
GPU: AMD Radeon RX 6600 XT
Driver version:	31.0.22011.1008 (i think that's what it is...)
RPCS3 version: 0.0.29-15680-8bd05871

im still trying to test different small settings to see what clicks to make the intro cutscene run smooth but no luck so far (llvm, audio, advance, etc.)

**Comment by alexconsole04** [comment]
I think it's safe to say this issue can be closed now, don't know why it hasn't been closed yet.
Cutscenes are perfectly fine, probably have been for a while now
[RPCS3.log.gz](https://github.com/user-attachments/files/19597653/RPCS3.log.gz)
