### ISSUE TITLE
[Regression] Verification failed in copy_image_to_buffer - God Mode [NPUB31140]

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#10620]
Master:

![image](https://user-images.githubusercontent.com/23019877/127238710-bcea35c6-3047-4392-bd50-0bfb549827ca.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6889168/RPCS3.log)

Last woking build:
0.0.17-12522
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6889150/RPCS3.log.gz)

First broken build:
0.0.17-12527 #10604
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6889158/RPCS3.log)

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/10628

**Comment by rtentser** [comment]
Can still reproduce with "The Last of Us" (BCES01585) when Resolution Scale is 100%. Not sure if it's the same bug, but the output similar:

> F SIG: Thread terminated due to fatal error: Verification failed
> (in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKTexture.cpp:111[:4], in function copy_image_to_buffer) (e=0x000001e7[487])

**Comment by Megamouse** [comment]
@kd-11  fixed
