### ISSUE TITLE
OBLIVION Softlock when changing settings during gameplay.

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#10812]
Oblivion fails to load after changing difficulty during gameplay.
Steps to reproduce: Push pause, go to options, then gameplay, and move the difficulty icon anywhere except for the exact same spot it was on. Attempt to back all the way out of the menus and click return. The message saving... will pop up and never progress. Audio continues as normal.
(Note: As long as you stay inside the menus the game will not freeze.)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7098465/RPCS3.log.gz)

**Comment by Gael2433** [comment]
Also happens in OBLIVION™ [BLES00163]

The game softlocks when exiting out of settings menu if the difficulty level has been altered.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7747805/RPCS3.log.gz)

RPCS3 v0.0.19-13106-18f59d3b Alpha
Microsoft Windows 10 Version 21H1
Intel Core i7-3770
16Gb DDR3 RAM
Nvidia Geforce GTX 1070 on driver 496.76.0.0

Video from media channel on rpcs3 discord:
https://discord.com/channels/272035812277878785/272875751773306881/922586972743143426

Alternatively here is the video in .mp4 format(4.45Mb)
https://user-images.githubusercontent.com/69867624/146829288-3d5e09ca-e867-405d-a76e-cea499bbc46a.mp4

**Comment by illusion0001** [comment]
Does this happen on real ps3

**Comment by Gael2433** [comment]
Highly doubt it, I have also noticed that the game auto saves but doesnt actually create a save file unless you manually save, but that doesnt softlock the game unlike trying to exit out of the menu after changing the difficulty slider.

**Comment by Gael2433** [comment]
Just checked on my PS3, it does not occur there, the "Saving..." prompt appears for a second or two before the game exits the menu.

**Comment by illusion0001** [comment]
Send Vidya

**Comment by Gael2433** [comment]
Got no way to record my ps3, stoopid HDCP

**Comment by Darkhost1999** [comment]
Just tried adjusting brightness during gameplay as well because it was dark and same issue

**Comment by Darkhost1999** [comment]
Fixed

**Comment by yontekh** [comment]
this issue still occurs for me in 0.0.20-13243-86919ec0 Alpha

**Comment by Darkhost1999** [comment]
Got a log?

**Comment by yontekh** [comment]
how do I make a log?

**Comment by yontekh** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7967457/RPCS3.log.gz)

**Comment by yontekh** [comment]
Darkhost1999, you stated that the problem was solved for you.
Can you tell me which firmware, and settings you are using?

**Comment by Darkhost1999** [comment]
Plain default settings without any changes on the latest 4.88 firmware that Sony provides

**Comment by Darkhost1999** [comment]
> Darkhost1999, you stated that you cant reproduce the problem anymore. Can you tell me which firmware, and settings you are using?

Any Luck?

**Comment by Asinin3** [comment]
@yontekh Still an issue for you with latest firmware and default emulator settings?

**Comment by Megamouse** [comment]
closing due to inactivity and reported fixed by other users

**Comment by Darkhost1999** [comment]
![image](https://user-images.githubusercontent.com/60384196/175188017-97c76c92-038c-4c88-9fcf-bc56782b24c1.png)

**Comment by Darkhost1999** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9077458/RPCS3.log.gz)
Can someone with permissions reopen this I think it's been too long for me to reopen

**Comment by Darkhost1999** [comment]
The information still needed for this is an actual error code. And potentially a regression test.
Although I'm quite certain that I've just gotten lucky by those times I was not able to replicate the issue. As even master will work normal sometimes. As if there's a sequence of events to get the settings changes to work and that sequence always changes.

**Comment by Darkhost1999** [comment]
I noticed a connection between saving your game and saving your config changes.
Changing your settings during the main menu can work. About 2/8 times it'll work.
Changing your settings mid gameplay if you save your game. Then go edit the settings and return from that about 7/8 times things will work.
Changing settings after playing for a while is more likely to work than the main menu at about 3/8 times.
The error codes when the game freezes always tends to be related to saving the game. When you fast travel to Bruma or visit Bruma it takes like 5 minutes to save your game there and performance tanks. I'm fairly certain there is something wrong with Oblivion and saving settings or gameplay even if there hasn't been any trouble loading savedata after a save actually succeeds.
