### ISSUE TITLE
[NPEB00435] Beyond Good and Evil HD: visual glitches

### ISSUE THREAD

**Issue by Linear524** [RPCS3/rpcs3#10960]
Beyond Good and Evil [NPEB00435] have some long standing issues with mipmapping on grass textures and invalid geometry occlusion (Zcull or Z-buffer bug ?). Many things was fixed by latest revisions and by WCB+RCB, but mipmapping and "see-through geometry" bugs still here with any configuration and settings applied...

Here is my screenshots:
![screenshot-2021_10_04_19_11_32](https://user-images.githubusercontent.com/84367301/135954040-a17bfbb3-e2cb-43c4-8800-4d11ed6589a0.jpg)
![screenshot-2021_10_04_19_11_38](https://user-images.githubusercontent.com/84367301/135954044-260f0d97-98bd-44bd-bcbb-ff6b6ed76021.jpg)
![screenshot-2021_10_04_19_12_36](https://user-images.githubusercontent.com/84367301/135954048-c23812be-e055-424e-a3e8-ba0da8b0f4f7.jpg)
![screenshot-2021_10_04_19_12_23](https://user-images.githubusercontent.com/84367301/135954051-ff409210-661d-4fe8-a74e-d34c8eb48044.jpg)
![screenshot-2021_10_04_19_12_05](https://user-images.githubusercontent.com/84367301/135954055-abb67259-f0e3-4ead-a57b-44be8d144e83.jpg)

My rig:
    SYS: Intel(R) Xeon(R) CPU E5-2690 v4 @ 3.20GHz | 14 Threads | 31.83 GiB RAM |
    SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 18362
    GPU: 'NVIDIA GeForce GTX 1080' running on driver 471.41.0.0
    SYS: Firmware version: 9.1.0

My settings:
WCB+RCB+WDB+RDB = ON
LLVM Recompilers.
Zcull Accuracy = Precise.
No external patches applied.
Everything else is set to Default.

Additional info:
This title is well know of its old and tricky engine and it is a pain in the ass on any emulated platform (GC, PS2, PS3, XBOX360) due to unusual mipmapping implementation and hardware vertex processing... It even have some W-buffer settings on PC port ! :P The only way I saw to emulate this game correctly with all features = use software renderer in PCSX2, but it's slow and native resolution of PS2 is too damn low.
RPCS3 only needs some mipmapping fixes for this title and Zcull tweak in order to being perfectly emulated. Maybe it suffer from some kind of texture cache issue as well...  (O_O)

Well, this game engine is weird, but the game itself is very good and too important to not being forgot through decades... 
Even PC port is broken and buggy under Windows 10.

**Comment by Linear524** [comment]
@DonelBueno
Can you show your RPCS3 config ?
I'm using 1080 via 471.41 drivers and have no idea why this mipmapping crap is happening on my side...

**Comment by DonelBueno** [comment]
[config_NPEB00435.txt](https://github.com/RPCS3/rpcs3/files/7446206/config_NPEB00435.txt)
Rename to .yml and see if that works for you.

**Comment by Linear524** [comment]
@DonelBueno
Tried your config, still the same result. Far grass is with broken mipmapping and texture corruption on some surfaces...
Funny thing - latest update broke skies texture :P ( PR #11080)

**Comment by DonelBueno** [comment]
Well, I don't know what is happening in your setup =/

The latest update didn't break anything here.

**Comment by Linear524** [comment]
GOT IT !  I've found what is wrong with yours and mine configurations - if I disable WCB = I getting exact same image as you do... But without WCB a lot of other important effects got screwed. For example - some faces are not shaded correctly and character eyes become black colored at far distance (another mipmap fail)...
So I believe there is some mipmapping error when WCB is enabled. Maybe some mip stage got inverted for those buggy textures or wrong dimension calculated...
Anyway, only KD-11 can help us here )))

**Comment by Linear524** [comment]
Little addition - I've double checked geometry issue (legs see-through stone) and it is not an emulator bug - it is ubisoft shanghai lammers bug = real PS3 has this issue due to porting studio dumb mistake in materials...
![PS3bug](https://user-images.githubusercontent.com/84367301/139796803-127a1e68-e734-4bd8-b5d7-517f92b0e5ec.jpg)

So now the only issue left here for sure is WCB mipmapping stage fail...

**Comment by LifeIsStrange** [comment]
Hi, just to say that I used the latest rpcs3  version and there is still the mipmapping issue...
By default not mimpaping issue but there are missing textures which cause glitches. Enabling WCB fixes the black missing textures but introduce mimpaping textures bugs on textures that are otherwise perfectly rendered without WCB.
It seems WCB introduce a side effect :/

If this was fixed the game would become perfectly playable, and this game is one of the best game ever !
Note that for some mimapped texture bug it disappear when the player become close to the texture.

**Comment by JimScript** [comment]
It seems like the LOD textures get mixed up with each load:
![NPUB30394_screenshot_2022_07_18_10_29_34](https://user-images.githubusercontent.com/66685584/179569407-78709d13-51dd-4b40-91f1-9317f356a329.png)
![NPUB30394_screenshot_2022_07_18_10_30_36](https://user-images.githubusercontent.com/66685584/179569420-f867d301-118d-4682-aeaa-320ce0cb0b11.png)
That lock symbol is apart of the UI textures, so maybe the other glitched textures are other textures somewhere they shouldn't be.

**Comment by JimScript** [comment]
This is without WCB:
![NPUB30394_screenshot_2022_07_19_23_55_42](https://user-images.githubusercontent.com/66685584/179917540-4d2f8a78-7db6-48ce-a263-4fbdcda1d595.png)
![NPUB30394_screenshot_2022_07_19_23_57_16](https://user-images.githubusercontent.com/66685584/179917566-ddde78ef-cadb-4e83-8ee5-c56b1542cd7b.png)
It seems that WCB doesn't cause the issue so much as remix it.

**Comment by Linear524** [comment]
Mipmapping bug is fixed by pull #12905 and with LOD bias set to -3 with WCB+RCB
I think real mip bug is still not resolved, but using this settings fixes overal scene rendering... So I closing this issue :)

**Comment by kd-11** [comment]
This is not fixed. I think https://github.com/RPCS3/rpcs3/pull/12905 caused some confusion - it is not meant to be used as a fix. It is a hack. That's why I moved it to debug. it also doesn't set lod bias it adds some offset to LOD bias which is configured by the game. So if this is somehow hiding bugs, then we have deeper issues elsewhere.

**Comment by Darkhost1999** [comment]
Indeed. Lod bias addend shouldn't fix anything. Maybe it assists in finding the real fix though?

**Comment by Triticum0** [comment]
I've had the same issue with Bulletstorm with getting hit with lighting causing similar issues with mipmaps #12899

**Comment by Linear524** [comment]
@Triticum0
Nope - your issue is not related to this current mipmapping bug. From what I see from your images - it is just broken MLAA shader function or maybe some depth texture resolving bug/ Z-bug ...

**Comment by Linear524** [comment]
Damn - another bug in this title discovered = framebuffer readback (or wrong memory address) is broken somewhere: when you capture images on Jade's camera - menu shows wrong/buggy images... This bug is possibly triggered by WCB function, but I', not sure...

**Comment by Fewnity** [comment]
Texture problem is still a problem at this day, even with Write color buffers enabled

**Comment by AniLeo** [comment]
Unless there's a new regression on recent builds within the v0.0.29 timeframe causing a new bug with similar symptoms, the original issue has long been fixed as I've already verified multiple times, ask for support on the Discord and Forums first to make sure you don't have a local issue going on

**Comment by craigsonoffergus** [comment]
I can verify the black texture bug, often showing in Jayde's eyes and Peyj's face. I have a brand new install of RPCS3 on my Steam Deck, installed from Emudeck. The only change I've made to the settings is to enable Write Color Buffers, as per instructions. That did not help. Is there any other info I can provide? My game looks exactly like the screenshots in the close #6160 thread.

**Comment by Fewnity** [comment]
Probably a regression I guess? Nobody was able to help me with this bug... And I noticed some audio problem on the game, I will probably open a new issue

**Comment by TryingToLove** [comment]
> Damn - another bug in this title discovered = framebuffer readback (or wrong memory address) is broken somewhere: when you capture images on Jade's camera - menu shows wrong/buggy images... This bug is possibly triggered by WCB function, but I', not sure...

Can confirm this is still an issue. Captured images on Jade’s camera register as empty black boxes for me.

**Comment by AniLeo** [comment]
I'm tired of reverifying the same issue, black photography bug claims without a log file and RSX capture won't be accepted and they were not even part of this ticket in the first place.

**Comment by TryingToLove** [comment]
> I'm tired of reverifying the same non-issue, black photography bug claims without a log file and RSX capture won't be accepted and they were not even part of this ticket in the first place.

“Non issue”….riiiiiiight. Try to solve instead of blaming the messenger.

**Comment by AniLeo** [comment]
Issue doesn't exist as far as we're concerned while using the wiki settings. No one on our side reproduces it and zero logs and RSX captures from anyone claiming otherwise. The only well known thing here is the lack of a proper bug report.

Maybe you should take a long look into the mirror and learn how to be a decent user instead of rambling about developers while not managing to do the bare minimum in a bug report.

**Comment by TryingToLove** [comment]
> Issue doesn't exist as far as we're concerned while using the wiki settings. No one on our side reproduces it and zero logs and RSX captures from anyone claiming otherwise. The only well known thing here is the lack of a proper bug report.
> 
> Maybe you should take a long look into the mirror and learn how to be a decent user instead of rambling about developers while not managing to do the bare minimum in a bug report.

Issue was reported and closed by you (see link), despite users saying your “Write Color Buffers” fix did not work. Ignoring the issue because others are getting it and you’re not is hardly a solution. Go ahead and censor/delete my message now.

https://github.com/RPCS3/rpcs3/issues/6160

**Comment by AniLeo** [comment]
Alright, still no logs or RSX capture after asking twice, cleaning up.

If you're not going to do the bare minimum in a bug report, you shouldn't be writing on GitHub tickets in the first place.

Subsequent bug reports for this bug will only be accepted with the aforementioned attachments. We're not here to guess root causes on issues we can't reproduce from leechers that are ready to complain at any time but never to provide the necessary debug information.

**Comment by TryingToLove** [comment]
> Alright, still no logs or RSX capture after asking twice, cleaning up.
> 
> If you're not going to do the bare minimum in a bug report, you shouldn't be writing on GitHub tickets in the first place.
> 
> Subsequent bug reports for this bug will only be accepted with the aforementioned attachments. We're not here to guess root causes on issues we can't reproduce from leechers that are ready to complain at any time but never to provide the necessary debug information.

If you haven’t fixed the issue in 5 years, when others in that thread/report already provided plenty of attached screenshots of the blank/black photo entries issue, I doubt there’s anything I can provide that you’ll really take seriously.

Best of luck…

**Comment by AniLeo** [comment]
Holy shit, are you retarded? Because you either can't read or your browser is rendering a completely different version of 6160 than the one we have on our repository. 

> Plenty of attached screenshots and info

The ONLY log and ONLY screenshot in #6160 of the black camera photo issue shows WCB disabled, so that's already a bad report.

The other user that mentioned the issue also said in reply they don't have the issue after enabling WCB, so the report was also wrong in the first place. 

Every other post is discussing other unrelated bugs, besides the two last ones that also provide no log or RSX capture.

Besides the fact that the only screenshot was provided without WCB, screenshots are completely useless to debug this issue, I can draw a black rectangle in my screenshot and that would provide exactly zero additional insight to the problem.

The mental gymnastics you do to refuse to upload debug information are fucking insane.

**Comment by TryingToLove** [comment]
> Holy shit, are you retarded? Because you either can't read or your browser is rendering a completely different version of 6160 than the one we have on our repository.
> 
> > Plenty of attached screenshots and info
> 
> The ONLY log and ONLY screenshot in #6160 of the black camera photo issue shows WCB disabled, so that's already a bad report.
> 
> The other user that mentioned the issue also said in reply they don't have the issue after enabling WCB, so the report was also wrong in the first place.
> 
> Every other post is discussing other unrelated bugs, besides the two last ones that also provide no log or RSX capture.
> 
> Besides the fact that the only screenshot was provided without WCB, screenshots are completely useless to debug this issue, I can draw a black rectangle in my screenshot and that would provide exactly zero additional insight to the problem.
> 
> The mental gymnastics you do to refuse to upload debug information are fucking insane.

First of all, there’s no need for cursing and rudeness. It’s unprofessional, especially for a Mod. I’ve been very polite to you.

Second of all, I’ve looked at the process of uploading RPCS3 debug info and it seems quite complicated. I would have assumed you’d been well aware of this issue anyway, on a fairly popular game. Very surprised if that’s not the case. In the 6160 report, the very last comment politely stated that they’d done the suggested WCB fix and were still getting the camera black boxes, asking for more help. Your response? To not reply to them and close the report instead.

If I was a dev, I’d not dismiss a graphical error as a “non issue”. If just one person was having problems, I’d want to investigate. That’s how you get your program better. But that’s just me. I’m sorry you find my questions so distasteful to you.

**Comment by AniLeo** [comment]
I think you're under the wrong impression I'm supposed to be polite to people that come in here to complain, ignore bug report guidelines, refuse to upload debug information and then proceed to accuse us of ignoring non-issues that we do not reproduce and that never had a proper bug report.

If you think that reading and following the step-by-step instructions made on how to make a bug report are too complicated, you shouldn't be on GitHub in the first place. This platform is for developers and users that want to contribute to improving the software they use. Not for voicing empty handed complaints.

**Comment by TryingToLove** [comment]
> I think you're under the wrong impression I'm supposed to be polite to people that come in here to complain, ignore bug report guidelines, refuse to upload debug information and then proceed to accuse us of ignoring non-issues that we do not reproduce and that never had a proper bug report.
> 
> If you think that reading and following the step-by-step instructions made on how to make a bug report are too complicated, you shouldn't be on GitHub in the first place. This platform is for developers and users that want to contribute to improving the software they use. Not for voicing empty handed complaints.

It says a lot that you view average folks who bring emulator issues to light as those who “complain”. We’re all just here to get in your way, apparently. That’s fine. Good eye opener for sure. We can’t all be techies or developers. Many of us are just everyday emulator users with issues. But now that I know you have no real intention of helping people like me, I’ll stay away from any RPCS3 discussion here. It’s gratifying that you don’t speak for all of Github because I’ve absolutely gotten helpful info here before.

**Comment by AniLeo** [comment]
Ah, fuck off you piece of shit. After hours you still refuse to upload a log or RSX capture, proceed to play the victim, strawman other imaginary people into the discussion and even have the gall to add "no real intention of helping people like me".

**Comment by TryingToLove** [comment]
> Ah, fuck off you piece of shit. After hours you still refuse to upload a log or RSX capture, proceed to play the victim, strawman other imaginary people into the discussion and even have the gall to add "no real intention of helping people like me".

Ok now you’re just being toxic and abusive. Shame on you. You shouldn’t even be allowed to be on GitHub, tbh, treating people like that…whether what I say annoys you or not. Try to have some class. As I’ve told you, the process of the debug report is a bit complicated for a noob/non-dev like myself. Chill out.

And just a reminder, all this started just cause I wrote a very short response to another user here saying I was having the same issue. You easily could have ignored that but I guess it’s just in your DNA to be a jerk.

**Comment by AniLeo** [comment]
Banned. Enough is enough, I've never seen someone so fucking obnoxious in years.

**Comment by digant73** [comment]
@Linear524, @JimScript, @craigsonoffergus is that still an issue?

**Comment by digant73** [comment]
please re-test on latest build. Hopefully some textures and reflections issues have been fixed by recent build 0.0.39-18790

**Comment by Fewnity** [comment]
> please re-test on latest build. Hopefully some textures and reflections issues have been fixed by recent build 0.0.39-18790

I still have issues with textures with the latest build on OpenGL and on Vullkan (cache cleared).
