### ISSUE TITLE
Final Fantasy XIII-2 - Shadows ignore alpha transparency with Vulkan renderer

### ISSUE THREAD

**Issue by lextra2** [RPCS3/rpcs3#11254]
Xbox 360 / PlayStation 3 / RPCS3 OpenGL (Correct)
![xbox](https://user-images.githubusercontent.com/20690384/145718808-05377be5-1c11-4147-a3aa-7405aaa250ff.png)

RPCS3 Vulkan (Incorrect)
![rpcs3](https://user-images.githubusercontent.com/20690384/145718813-ee6d5def-9755-44ea-8939-d921ce40c77b.png)

OpenGL works fine, but not an option due to abysmal performance.

Btw, the same incorrect rendering also happens in the Pc version.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7726915/RPCS3.log)
[RSX Capture](https://www.mediafire.com/file/4mdsyo1tsjx0l1o/rsx.7z/file)
[RenderDoc](https://www.mediafire.com/file/gln26qdcrkz0hfx/renderdoc.7z/file)

**Comment by lextra2** [comment]
Added files

**Comment by lextra2** [comment]
Fixed in rpcs3-v0.0.21-13380 if `Anti-Aliasing` is set to `Disabled`.
Probably fixed by either #11607 or #11665 (no time to test atm, sorry)

**Comment by RainbowCookie32** [comment]
If *disabling* anti-aliasing fixes it, then there's still an issue here.

**Comment by hoholee12** [comment]
The alpha ignoring also happens on Gran Turismo 5.
Performance regression happened in #11607, and alpha bug started in #11665.

**Comment by kd-11** [comment]
Is this still an issue?

**Comment by lextra2** [comment]
I'll let you know soon.

**Comment by lextra2** [comment]
@kd-11 
Fixed, thanks! (Anti-Aliasing on hair still does not work the way it does on a real PS3 though, but that is another issue)

![Fixed](https://user-images.githubusercontent.com/20690384/197434738-0ead36c9-729e-4058-a630-0e8832914826.PNG)
