### ISSUE TITLE
Silent Hill Downpour weird stutter that stops only after reloading the checkpoint

### ISSUE THREAD

**Issue by MaxBowie** [RPCS3/rpcs3#11426]
Hello!
I am having a weird stutter issue. After a new checkpoint, it runs jittery but runs smooth after I reload the same checkpoint through the game. 

After the Diner Ravine checkpoint (something like 25 mins from the beginning) the game runs pretty smooth, except for some occasional points. But after going through the next checkpoint, Dinner Sky Tram, the game becomes very stuttery (hopefully it is clearly visible on the video, in reality it is very bad and extremely jittery), but the frametime and framerate remains very stable.
But if I manually reload the same last Dinner Sky Tram checkpoint - the game will run almost perfectly smooth. Not sure if that's because of how the game works on real hardware or it happens due to an emulator.
https://www.youtube.com/watch?v=SzPL9WWLxAw
Following this issue since June. Nothing changed since then.
Maybe it is worth mentioning that there are plenty of places in the game where it stutters with smooth framerate and frametime. But all of them stop when I move further. But the one described above persists even when I move to the next checkpoint without reloading.

#### 0. Make sure you're running with settings as close to default as possible
Settings for the video are default except for 150% resolution scale and 512x512 Resolution Scale Threshold.
On totally default settings the behavior is exactly the same.
Also, nothing seems to affect the issue, like OpenGL, lower resolution, SPU decoder, Shader mode, etc.
With unlocker FPS the issue remains too. 

#### 5. Please provide your system configuration:
Windows 10
Ryzen 1700x
GTX 1060 6gb
Driver version 511.23
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7918461/RPCS3.log)
[BLUS3056520211022131326_08.zip](https://github.com/RPCS3/rpcs3/files/7918464/BLUS3056520211022131326_08.zip)

Save data attached. Load Diner Ravine and move to the next Dinner Sky Tram checkpoint. Notice stutter and reload Dinner Sky Tram checkpoint manually via the Load menu. Notice smooth gameplay.

**Comment by FlexBy420** [comment]
Is this still an issue?

**Comment by digant73** [comment]
@MaxBowie is that still an issue?

**Comment by Triticum0** [comment]
Seems to be fixed https://youtu.be/gyhRLXAwVog?t=1640&si=8_HRc0n-7k0gh5FC but might need to the test game myself

**Comment by digant73** [comment]
I would avoid to consider youtube video to close issues. I would ask the OP or any one facing an issue to test and confirm the issue is fixed

**Comment by Triticum0** [comment]
I agree but you not getting a response from the op

**Comment by edm0rales** [comment]
Not fixed, and i'm glad to know loading the checkpoint makes it better, i tried and its true

**Comment by Triticum0** [comment]
@digant73 should be reopen sorry
