### ISSUE TITLE
Bug: Error reading disc on Colin McRae: DiRT [BLES00095] on macOS

### ISSUE THREAD

**Issue by reece394** [RPCS3/rpcs3#11421]
## Details

When running Colin McRae: DiRT it frequently flashes E cellSysutil: “Error reading disc in the log Retrying, please wait..." on screen as well as spamming the log

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7914893/RPCS3.log)

#### 3. Please attach screenshots of your problem.
https://user-images.githubusercontent.com/31659691/150556445-08bc56fe-957a-45c9-ae57-58918ddf21f3.mp4

#### 4. Please provide comparison with real PS3.
Shouldn't produce that error on screen

#### 5. Please provide your system configuration:
*OS macOS 12.1 Monterey
*CPU Apple M1 Max 10 Core
*GPU Apple M1 Max 32 Core
*RAM/GPU Memory 32GB (Shared)
*Driver version 0.2.890

#### Please include anything else you deem to be important
Dump was verified with PS3-ISO-Builder and an IRD file with no missing files and no errors so the dump should be a valid one.

**Comment by reece394** [comment]
Flashing error on screen fixed with latest builds however log is still spammed with E cellSysutil: “Error reading disc in the log Retrying, please wait..."

**Comment by mavethee** [comment]
![CleanShot 2024-09-02 at 14 57 05@2x](https://github.com/user-attachments/assets/77546c87-65f8-4a14-9990-10d579749201)

Sadly still an issue.

```sh
E cellSysutil: “Error reading disc in the log Retrying, please wait..."
```

[Colin McRae DiRT™ [BLES00095].log](https://github.com/user-attachments/files/16837818/Colin.McRae.DiRT.BLES00095.log)

**Comment by mavethee** [comment]
Small update, it can actually load further with that errors still present.
Currently it just barely runs intros and stutters a lot with CPU temps sky rocketing 💀 
![CleanShot 2024-12-29 at 20 01 59@2x](https://github.com/user-attachments/assets/66e01155-f031-4af9-b6d4-cd5fe2feca51)
[DiRT.log](https://github.com/user-attachments/files/18270604/DiRT.log)

**Comment by reece394** [comment]
Log still produces the error on RPCS3 v0.0.40-18876-d46ddcee Alpha 
```E cellSysutil: Opening error message dialog with message: “Error reading disc Retrying, please wait...”```

[RPCS3.log](https://github.com/user-attachments/files/25749767/RPCS3.log)
