### ISSUE TITLE
Guilty gear xrd revelator blackscreen

### ISSUE THREAD

**Issue by sbawra** [RPCS3/rpcs3#11462]
When i open guilty gear xrd revelator the loading screen of rpcs3 appear but after that it just pure blackscreen
[RPCS3 LOG.zip](https://github.com/RPCS3/rpcs3/files/7965291/RPCS3.LOG.zip)

**Comment by RainbowCookie32** [comment]
Month old RPCS3 build, GPU drivers from 2020 and Windows 10 from like 2017.

Update RPCS3, your GPU drivers, and Windows, then move RPCS3 out of Program Files and see if the issue still happens.

**Comment by LuismaSP89** [comment]
I can confirm the issue, but this problem started 1,5-2 years ago:

https://forums.rpcs3.net/archive/index.php/thread-200704.html

It gives the error:

F {PPU[0x100000c] Thread (Session) [0x010c892c]} VM: Access violation reading location 0x3a5500b4 (unmapped memory) [type=u0]

**Comment by LuismaSP89** [comment]
Attached my Log, using the latest RPCS3 version, updated drivers, windows, etc.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7966621/RPCS3.log.gz)

Specs: 

GTX 970
i7 4790k
16 GB DDR3
Windows 11 pro

**Comment by Megamouse** [comment]
Try with the mentioned PR please

**Comment by LuismaSP89** [comment]
@Megamouse Sorry but how I can download a build from the PR in order to test? I don't know how to build that PR by myself.

Thank you so much.

**Comment by Darkhost1999** [comment]
https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3![Screenshot_20220131-162506_Firefox Beta.png](https://user-images.githubusercontent.com/60384196/151883351-0df3fc8d-c841-421b-92e7-89767a872990.png)

**Comment by Neirene** [comment]
I'm posting the current status here for safekeeping and reference. 

The game shows a black screen after launching

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/5244595/151885998-4cafa1fb-88c3-4617-bca5-050e3eb7cc2a.png">

Log Snippet:

```
S SPU: SPU Runtime: Built 98 functions.
U sys_prx TODO: _sys_prx_register_module(name=“cellProcessElf”, opt=*0xd0040ce0)
S PPU: LLVM: Loaded module v5-kusa-1z3Pyu8YVnnorJiQ2hfu1e-00001P-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsysmodule.sprx” (id=0x23000b00)
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x1, a2=0x1, a3=0xd0040a50)
E SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x2, a2=0xd0040a50, a3=0x0)
S PPU: LLVM: Loaded module v5-kusa-XCgQWMc1s99n1WTwrpWvw4-00001P-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libgcm_sys.sprx” (id=0x23000e00)
S PPU: LLVM: Loaded module v5-kusa-GsbjiwC5Sm3exFcR5udHpE-00001P-westmere.obj
S PPU: LLVM: Loaded module v5-kusa-gRWSbPdZHFQq5essKqQVjk-00001P-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsre.sprx” (id=0x23001100)
S PPU: LLVM: Loaded module v5-kusa-fLV79QqHgPi90UziTsWrHo-00001P-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libfs.sprx” (id=0x23001200)
U sys_prx TODO: _sys_prx_register_module(name=“_sysProcessElf”, opt=*0xd0040df0)
S PPU: LLVM: Loaded module v5-kusa-ZAhea3FFhakpfMa36ZvaNx-00001P-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/librtc.sprx” (id=0x23004b00)
S PPU: LLVM: Loaded module v5-kusa-UnNP3fZh95wiCGy3Q0csRy-00001P-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libresc.sprx” (id=0x23004f00)
U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0) x2
S PPU: LLVM: Loaded module v5-kusa-t1xTtC1PVoW6Jh636RxJVQ-00001P-westmere.obj
S PPU: LLVM: Loaded module v5-kusa-2wS6UCQGvL8KpqZwEg6HX7-00001P-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libnet.sprx” (id=0x2300a000)
S PPU: LLVM: Loaded module v5-kusa-jJoZ07PrzerYWWhZciLzhv-00001P-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libl10n.sprx” (id=0x2300a300)
E SYS: 'sceNpMatching2Term2' failed with 0x80022303 : SCE_NP_MATCHING2_ERROR_NOT_INITIALIZED [1]
U sceNp2 TODO: sceNpMatching2Init2(stackSize=0x0, priority=0, param=*0x0)
U sceNp2 TODO: sceNpMatching2RegisterRoomEventCallback(ctxId=1, cbFunc=*0x1bb67c0, cbFuncArg=*0x200fea80)
U sceNp2 TODO: sceNpMatching2RegisterRoomMessageCallback(ctxId=1, cbFunc=*0x1bb67d0, cbFuncArg=*0x200fea80)
U sceNp2 TODO: sceNpMatching2RegisterLobbyEventCallback(ctxId=1, cbFunc=*0x1bb67d8, cbFuncArg=*0x200fea80)
U sceNp2 TODO: sceNpMatching2RegisterLobbyMessageCallback(ctxId=1, cbFunc=*0x1bb67e0, cbFuncArg=*0x200fea80)
F {PPU[0x100000c] Thread (Session) [0x0103e98c]} VM: Access violation reading location 0xba6b52d4 (unmapped memory)
```

**Comment by Megamouse** [comment]
you always have to upload the log file.
The snippets are almost always useless.

**Comment by Neirene** [comment]
Fixed

**Comment by LuismaSP89** [comment]
Same here, the PR build doesn't solve the issue.

Log attached
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7982022/RPCS3.log.gz)
.

**Comment by emmetmorris** [comment]
Does the same on Mac build for me, but if I keep resetting the game it will boot maybe 1 in 10 or 1 in 20 times and run normally. On the times it just goes to black screen the error says 'Access violation reading location 0x97471e4 (unmapped memory)'

**Comment by rubbersoul65** [comment]
I'm having the same problem with unmapped memory playing Guilty Gear Xrd -Sign-
Here is my log 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8357134/RPCS3.log)

**Comment by Silanda** [comment]
By some miracle Revelator actually booted for me yesterday, but only once. I've tried setting PSN to simulated as stated in the other issue, but that doesn't seem to work for me.

By the way, aren't this and #9520 the same issue?

**Comment by RipleyTom** [comment]
please test with https://github.com/RPCS3/rpcs3/pull/11887

**Comment by emmetmorris** [comment]
> please test with #11887

Seems to fix the problem for me. Great.

**Comment by Silanda** [comment]
> please test with #11887

Tentatively that seems to have fixed it.
