### ISSUE TITLE
Uncharted 3 white glowing spots and stripes on the screen

### ISSUE THREAD

**Issue by hapii2** [RPCS3/rpcs3#11559]
White bright squares and stripes appear on the screen. What can i do? My PC:
* Windows 10
* AMD Ryzen 7 3700X 8-Core 3.60 GHz
* NVIDIA GeForce GTX 1060 6GB
* 16GB RAM
![unchartedbug1](https://user-images.githubusercontent.com/100093171/154861241-e43d59c0-8217-4ab0-a1f1-3fc87e9171fc.png)
![unchartedbug2](https://user-images.githubusercontent.com/100093171/154861252-13359b92-70bd-4040-ac56-a92daf259e0a.png)

I noticed someone has exactly the same problem in the video below:
https://www.youtube.com/watch?v=fwfaYjhoru0

**Comment by Darkhost1999** [comment]
> White bright squares and stripes appear on the screen. What can i do? https://www.youtube.com/watch?v=fwfaYjhoru0

Heyo that's my link you can try adding patches via -> manage -> game patches all of them except debug and dev menu and you'll be good enough to complete the game.
These are workarounds not fixes so issue is valid

**Comment by kd-11** [comment]
I believe some combination of accuracy settings fixes this. Try read color buffers + write color buffers + accurate xfloat for a start. Then add read depth buffer and write depth buffer as a followup.

**Comment by Darkhost1999** [comment]
for a start
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8665432/RPCS3.log)

https://user-images.githubusercontent.com/60384196/167738150-2e679dcf-3e86-4911-9f9e-9468db5ba379.mp4

as a followup.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8665474/RPCS3.log.gz)

https://user-images.githubusercontent.com/60384196/167738900-d35d90dc-5597-4439-b0fe-2ba55330c010.mp4

Sorry forgot about this

**Comment by Darkhost1999** [comment]
> Same,how to fix?

Manage -> game patches -> enable all except for debug and dev menus.
But is a workaround until the emulator doesn't need patches one day.

**Comment by JeevanathV** [comment]
Hey were you able to find a workaround for the issue? I was trying the same and have the same issue..

**Comment by YuriNator557** [comment]
The Enable GPU Lighting patch should fix it but I think the issue stems from improperly emulated SPU lighting

**Comment by PlazmaProductions** [comment]
Guys I have found your fix I had the exact same problem as you guys and basically all you have to do is update your game you can find out how to do this online as sometimes when you download the rom it gives you an outdated version so updating it fixes the glitches. After you do this make sure that the game has all the settings in the compatibility list and add the patches that were already talked about here. This should fix the problem.

**Comment by Darkhost1999** [comment]
Proper fixes involve not using patches so the github issue is still valid. We shouldn't have to hack a game to play it.
Although yes they just need to make sure they're using the patches applicable to their version of the game by ticking the "show only owned games" box in the patch manager.

**Comment by jacksonslash** [comment]
Well you don't need to use the patches to fix the white spots glitch thats just if you want extra performance so I would say its fixed

**Comment by PlazmaProductions** [comment]
Well you don't need to use the patches to fix the white spots glitch thats just for extra performance all you need to do is update the game and it fixes it so I would say its fixed

**Comment by Darkhost1999** [comment]
Do you have proof it's fixed for you?
A log?
And what hardware are you using?
The log will tell us what settings so others may possibly benefit from the fix as well.

**Comment by PlazmaProductions** [comment]
Yes I have proof however it is not a matter of settings it is a matter of whether or not your game is outdated you see when I downloaded my uncharted 3 rom it showed up as being version 1.00 so I needed to update the game using rusty-psn. You can find out how to do this from this link. [https://wiki.rpcs3.net/index.php?title=Help:Installing_Game_Updates#:~:text=Get%20your%20Game%20Serial%20(right,for%20updates%20or%20hit%20Enter%20.](url) That updated my game to the current version 1.19 which fixed the glowing white spots issue. However if you just don't use any patches at all then there will be still a few graphical glitches like you will see these weird white bar
s flashing around at the top. So if you want to fix all the graphical glitches you will need to at least disable MLAA from the patch list. Here is my log [RPCS3.log](https://github.com/RPCS3/rpcs3/files/9387253/RPCS3.log)

**Comment by PlazmaProductions** [comment]
I can send an image of it working if you want as well

**Comment by YuriNator557** [comment]
Your game is pirated, we aren't interested

**Comment by PlazmaProductions** [comment]
Ahh got ya sorry didn't realize you guys actually bought the game well it might be different for you then but I would recommend making sure that your game is updated before trying any changes as who know it might fix your problem

**Comment by PlazmaProductions** [comment]
Well for the guy who created the post in the first place it looks like he has the exact same version of the game as mine so for him it could fix the issue I don't know about anyone else

**Comment by Darkhost1999** [comment]
I wouldn't be surprised if most these messages are deleted.  I'd actually appreciate the cleanup too

**Comment by Trigston** [comment]
This is due to the "Disable SPU Post-processing" patch. If you read the notes, it says:

"Do not use this patch if you're not upscaling, it'll introduce white squared artifacts..."

So you have two options:
A) Disable the patch
B) Apply a tiny bit of upscaling

The reason upgrading worked is because it disables all the patches - so the issue disappears.

**Comment by MSuih** [comment]
Closing as this seems to be caused by patches. For this reason we'd prefer issue reports to be done without any enabled if possible

**Comment by Darkhost1999** [comment]
> Closing as this seems to be caused by patches. For this reason we'd prefer issue reports to be done without any enabled if possible 

It is solved by patches not caused by patches

**Comment by Darkhost1999** [comment]
Apparently their comment says it's also solved by upscaling but not resolved at 100% scale

**Comment by Darkhost1999** [comment]
> ![image](https://user-images.githubusercontent.com/60384196/185748220-9ae84ac6-1c6c-4b35-ba64-41f08199ca1c.png)
> [RPCS3.log](https://github.com/RPCS3/rpcs3/files/9387182/RPCS3.log)

No Patches to be found here used at all

**Comment by Darkhost1999** [comment]
![image](https://user-images.githubusercontent.com/60384196/227782420-1b80c35c-0d9a-4017-a650-0bd809616288.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11071863/RPCS3.log)
Modern information

**Comment by MSuih** [comment]
Okay, i misunderstood the reply

**Comment by davewuk** [comment]
As others have said, this issue seems to be fixed by using the patches. I don't have this issue at all if I a) use the recommended settings and b) use the patches provided. Upscaling seems to work fine too, I normally have it set to 150% for 1080p.

My current settings for UC3 are all default except:

- SPU Loop Detection ON (seems to help with stability for me at least)
- ZCULL Accuracy: Relaxed (as recommended on wiki)
- Write Colour Buffers: ON (as recommended on wiki)
- RSX Fifo Accuracy: Atomic (as recommended on wiki)
- Accurate RSX Reservation Access: ON (as recommended on wiki)

Patches are configured as follows:

![patch config](https://github.com/RPCS3/rpcs3/assets/55807111/a7ad7292-3207-4b6f-ae6d-0769f7f2f393)

The linked bug report above _is a completely separate issue_, but kd-11 asked me to test without patches hence the apparent similarity.

**Comment by Darkhost1999** [comment]
I know they're separate issues as you were talking about dynamic lighting.
Only made reference to the issue to explain the part you mentioned about playing without patches makes the game entirely unplayable.
This issue may make your issue incapable of determining whether your issue is present or not by taking up a huge portion of the screen and/or blocking any effects of dynamic lighting or shadows that may not be working.

ALL issues on github need reported with STOCK settings and NO patches.
This issue is valid for being an issue when NO patches are used. As said over and over again on this issue already. Just leave the tag alone. It was just a notification of awareness.

**Comment by Asinin3** [comment]
This was already fixed by https://github.com/RPCS3/rpcs3/pull/14647 Enable RSX Tiled Memory settings/follow settings on wiki.
