### ISSUE TITLE
Regression: Transparent rendering is stripy in LittleBigPlanet [NPUA80472]

### ISSUE THREAD

**Issue by metraberryy** [RPCS3/rpcs3#11818]
## Summary
Transparent objects render with stripes on them. Not sure how else to explain it

This issue appears in v0.0.20-13177-d6aa834b (https://github.com/RPCS3/rpcs3/pull/11373)

### Regression
![regression](https://user-images.githubusercontent.com/30480654/163504078-f6a6d71a-b0c2-47a3-a4c2-e2ca4a9a0c80.png)
https://drive.google.com/file/d/1spYkUDJCeP4dhS8ePw0M0TA_WmFNuf7u/view?usp=sharing

### Correct behaviour
![correct](https://user-images.githubusercontent.com/30480654/163509214-8a781f36-2794-46ef-a2c2-612d81606119.png)
https://drive.google.com/file/d/1UcuinjGQmLUYdQsuUKBaHZxwoKUvI_Vr/view?usp=sharing

## Reproduction
This effect is most noticeable on score bubbles, though the effect can be seen on the Pod windows, glass, or any other transparent objects
The screenshots are from the second level (first after the introduction level), 'First Steps'.

## System Specs
* Windows 10 10.0.19041
* Intel Core i7-9700K @ 3.60GHz
* NVIDIA GeForce GTX 1660 Ti
* Driver version 27.21.14.6089

**Comment by AniLeo** [comment]
That's interesting, because the new behaviour you describe is very similar to what happened on RDNA2 GPUs prior to the fix

**Comment by capriots** [comment]
Persona 4 Arena Ultimax has a very similar stripe pattern since that PR with MSAA on.

Before:
![NPUB31563_screenshot_2022_06_03_18_52_51](https://user-images.githubusercontent.com/29807355/171913343-109cfdb2-e554-4ea4-a6ac-aa188e892e9b.png)

After:
![NPUB31563_screenshot_2022_06_03_18_54_25](https://user-images.githubusercontent.com/29807355/171913446-114085d2-abad-40e5-b2b4-8b43a5610d12.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8834419/RPCS3.log.zip)
[RSX Capture](https://github.com/RPCS3/rpcs3/files/8834420/NPUB31563_20220603185432_capture.rrc.zip)
[RenderDoc](https://github.com/RPCS3/rpcs3/files/8834421/P4A.rdc.zip)

**Comment by kd-11** [comment]
Ok, this one is going to be annoying to fix. I'll think of something.
Fixing this game will just break Tales of Graces F again.

**Comment by kd-11** [comment]
This should be fixed now with the "hardware MSAA resolve" option.

**Comment by Triticum0** [comment]
It is not, it the same behavior that was in the screenshot for #15000 on the transparent surface

**Comment by Metraberryy** [comment]
the effect is definitely reduced, but not entirely gone

![image](https://github.com/RPCS3/rpcs3/assets/30480654/4d2b055c-5557-4753-b03a-b75f5cbd4130)
![image](https://github.com/RPCS3/rpcs3/assets/30480654/a7f404e0-a862-4b34-a3e3-99c4494e64d3)

**Comment by TorutheRedFox** [comment]
the uv resolving for software msaa resolve should be adjusted to fix this

**Comment by ItsLaguna** [comment]
Sadly Force MSAA Hardware Resolve murders performance, making the game unplayable (GPU at 100% usage, single digit fps).

I personally resorted to upscaling to 200% instead as a workaround for the issue, though some materials still show up lines like glass in the intro level (this also happens with Force MSAA Hardware Resolve) and if you have any DLC costume installed, the bubbles in the "My Content" section will be empty.

**Comment by TheGlitcher1705** [comment]
as metra said even if you want to take that performance hit it still doesn't fix the issue

**Comment by alexconsole04** [comment]
![Image](https://github.com/user-attachments/assets/c37fc904-eee3-41ab-ae2c-f9d76d61edc2)
I don't know if anyone has mentioned it before or anywhere else, but the broken transparency effect is also present on OpenGL.

**Comment by Sockdrawercoder** [comment]
I think either due to the most recent AMD drivers (as of 5/24/2025), or due to build 0.036-17966-3e674a89 Alpha, this issue has gotten worse. or it may be a different issue, i'm not really sure.

![Image](https://github.com/user-attachments/assets/57e0c507-9f34-4a3b-a1e4-18a0084fd837)

https://www.youtube.com/watch?v=pYm2G0yELcs

either way, these blue squares have shown up all over anything that isn't being anti-aliased.

**Comment by ItsLaguna** [comment]
> I think the most recent AMD drivers (as of 5/24/2025) have caused this issue to get worse? i'm not really sure.
> ive just got these blue squares have all over anything that isn't being anti-aliased.

Disable antialiasing, is not the same issue.

**Comment by jchabin** [comment]
Pointed this out on the other issue, but disabling anti-aliasing makes score bubbles render MORE correctly, mostly without the stripes or flickering (but with a new visual artifact).

<img width="490" height="491" alt="Image" src="https://github.com/user-attachments/assets/e048dd9c-1eb0-497a-ad09-81d9d2d06722" />
<img width="297" height="272" alt="Image" src="https://github.com/user-attachments/assets/d7eafd19-6c51-47de-b56c-0e3c3115d70f" />
<img width="1417" height="922" alt="Image" src="https://github.com/user-attachments/assets/7101f9d5-5de8-4bc0-9a04-4912ced47109" />

Personally, I prefer this to the stripes...?

**Comment by EngineMachiner** [comment]
Just wanted to show a comparison of the current state of transparency rendering in the game with the default config and a scaled config with 200% scale and CPU blit checked.

[https://www.youtube.com/watch?v=RPQseWBrQUA](https://www.youtube.com/watch?v=RPQseWBrQUA)

[RPCS3.log.gz](https://github.com/user-attachments/files/22703599/RPCS3.log.gz)
[RPCS3_Scaled.log.gz](https://github.com/user-attachments/files/22703600/RPCS3_Scaled.log.gz)

**Comment by kd-11** [comment]
I need new RSX captures of the pod scene for this. I don't have LBP1 but MSAA is behaving differently again on modern hardware and drivers in other games so this warrants a retest.
If the glitch is not obvious (stripes) point it out as a comment.

**Comment by alexconsole04** [comment]
[BCUS98148_20260111110537_capture.rrc.gz](https://github.com/user-attachments/files/24553671/BCUS98148_20260111110537_capture.rrc.gz)

Inside the Pod.

**Comment by kd-11** [comment]
This bug is hardware specific. It only appears on NVIDIA cards.

**Comment by kd-11** [comment]
This one needs SSAA to emulate MSAA. It's just a hardware specific thing that we have no control over. The way MSAA is implemented on desktop really makes it not so useful for accurate emulation.
It's not even a regression anymore, rolling back the offending fix causes graphics to break 10x worse with the current geforce drivers (tested on the DLSS4.5 beta driver). AMD remains largely unaffected though lowering the shading rate causes some flickering in other titles.

**Comment by kd-11** [comment]
Depends on https://github.com/RPCS3/rpcs3/issues/18030

**Comment by nulshift** [comment]
> This bug is hardware specific. It only appears on NVIDIA cards.

This bug is happening for me on an RX 6950 XT.

**Comment by digant73** [comment]
> > This bug is hardware specific. It only appears on NVIDIA cards.
> 
> This bug is happening for me on an RX 6950 XT.

attach a screenshot of the possible issue

**Comment by squelch41** [comment]
On an RX6600XT - is the same on my other machine with an RX6700XT

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/18f098eb-e771-4e7a-8858-a267cdcf6ae3" />

Config:

<img width="851" height="906" alt="Image" src="https://github.com/user-attachments/assets/4b840629-91c5-49f2-b8f7-f4c08ccb195b" />

<img width="850" height="908" alt="Image" src="https://github.com/user-attachments/assets/dfad1db5-687e-4029-bc71-d9c633f394fd" />

RCPSC3 0.0.039-18812-3585881a Alpha
Windows 11
AMD drivers 26.1.1

Running Strict Rendering Mode seems to fix, but tanks frame rate - ~20fps on the 6600XT and is unplayable. The 6700XT can do 26-30fps

**Comment by Sockdrawercoder** [comment]
If anyone's still dealing with broken MSAA in LBP1 on AMD cards (like the AMD Radeon RX 7600M XT), just download the newest chipset drivers (Version 8.01.20.513 as of writing this) and the issue should be mostly resolved. I'd also recommend turning on Force Hardware MSAA Resolve in the advanced settings of your config if you're still having trouble. It works your system harder, but it still looks ok. 

note - this is at least the case on my fully AMD based computer <:/

**Comment by squelch41** [comment]
Doesnt work for me on a 6700XT or 6600XT with current RPCS3 and up to date drivers

**Comment by jansimon2** [comment]
The pixelated graphics in LBP1 with AMD Hardware with Vulkan renderer are gone for me with latest drivers. I have a 7700x CPU and a 7900 XT GPU. I updated AMD Adrenalin to version 26.6.1 and Chipset Drivers to 8.05.04.516 on June 12, 2026. I updated using AMD Adrenalin.

Before that I had 26.1.1 and 8.03.25.247 and still had the issue. Maybe it's just the Chipset Drivers but I'm not really an expert on this.

**Comment by AniLeo** [comment]
Removed the off-topic comments, this ticket is for an NVIDIA bug. The AMD bug is a different ticket that was already closed as solved by the vendor.

**Comment by EngineMachiner** [comment]
This is still present on AMD on default settings though considering the title of issue. The latest driver did solve the Vulkan bloom issue. Were you referring to that ticket?
<img width="398" height="433" alt="Image" src="https://github.com/user-attachments/assets/fe3398d2-5402-4848-8558-061ee34b1ea3" />

**Comment by DerpyTurtle3** [comment]
This is only present on Nvidia cards?
