### ISSUE TITLE
Batman Arkham Asylum GOTY

### ISSUE THREAD

**Issue by git-tiger** [RPCS3/rpcs3#12009]
When in the Scarecrow nightmare stages, RPCS3 would hang. 
Using default settings, except "Write Depth Buffers".

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8693104/RPCS3.log)

* OS = Windows 10
* CPU =  AMD Ryzen 4800H
* GPU = Nvidia GTX1650Ti

**Comment by git-tiger** [comment]
I was wondering if 8GB ram was too small, as usage hit 100%, so added another 16GB.
Now, I got past the crash point in the game.

**Comment by git-tiger** [comment]
Now it is crashing again. Attached log
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8958895/RPCS3.log)

**Comment by Jonathan44062** [comment]
I got an RSX error just doing the Challenge Map, Shock and Awe (Normal or extreme) that arena you get an RSX error, even using RSX FIFO Atomic does fix the problem 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10160909/RPCS3.log.gz)

**Comment by Jonathan44062** [comment]
Still an issue
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11843509/RPCS3.log.gz)

**Comment by Zarch7** [comment]
I am facing the same issue now,the game works for a few minutes(if lucky then for a few hours)then randomly crashes giving me the error code of F {RSX [0x00f2f10]} VM: Access violation reading location 0x40400000 (unmapped memory). I have tried "Write Depth Buffers" and setting RSX FIFO Atomic but it doesn't help.
My laptop specs
Ryzen 5 5600h
rtx 3060
32GB ram
Windows 11

**Comment by FlexBy420** [comment]
Been playing the game for couple of hours by now and I did not get any crash. Seems like this issue was fixed at some point.

**Comment by digant73** [comment]
maybe another game that should be retested.
@FlexBy420, @Jonathan44062 could you retest it?

**Comment by niekvlessert** [comment]
Still have the issue overhere with an iMac M1, 16GB RAM. Tried Write Depth buffers as well.

**Comment by digant73** [comment]
@alexconsole04 still crashing on latest build?

**Comment by alexconsole04** [comment]
> [@alexconsole04](https://github.com/alexconsole04) still crashing on latest build?

I would need to dump and test again

**Comment by alexconsole04** [comment]
The game still crashes during 3rd scarecrow section.

[RPCS3.log.gz](https://github.com/user-attachments/files/22482728/RPCS3.log.gz)

**Comment by kd-11** [comment]
@alexconsole04 How reliable is the crash? 100%?

**Comment by alexconsole04** [comment]
> [@alexconsole04](https://github.com/alexconsole04) How reliable is the crash? 100%?

@kd-11 It's rather consistent, but happens at random times.
The base game almost always randomly crashes with a similar RSX violation crash. The buffers required for scarecrow sections from further testing did not help.

**Comment by digant73** [comment]
@alexconsole04 maybe this issue has been fixed on recent builds. Please retest if possible

**Comment by alexconsole04** [comment]
The game still crashes in 3rd scarecrow section shortly after.

[RPCS3.log.gz](https://github.com/user-attachments/files/25620167/RPCS3.log.gz)
