### ISSUE TITLE
A Boy and His Blob [NPUB31614] - Flickering/Corrupt/Swapped Textures on Vulkan

### ISSUE THREAD

**Issue by retroNUC** [RPCS3/rpcs3#12021]
### Summary
Textures in the game appear to be flickering/corrupt/swapped when being encountered for the first time on Vulkan. Most obvious on the title screens. Default settings, only just started using RPCS3. Game rendering fine when using OpenGL.

A Boy and His Blob [NPUB31614]
RPCS3 Version: 0.0.22-13600-2ba437b6 Alpha | master

### System Configuration
* OS - Windows 11 Pro 21H2
* CPU - 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
* GPU - Integrated Iris XE Graphics
* Driver - 30.0.101.1934 Beta

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8703841/RPCS3.log.gz)
[NPUB31614_20220516234757_capture.zip](https://github.com/RPCS3/rpcs3/files/8703844/NPUB31614_20220516234757_capture.zip)

![image](https://user-images.githubusercontent.com/71151161/168694893-b7e222ec-2a54-48f7-924d-8c8a1c48ef7c.png)

**Comment by retroNUC** [comment]
Tested on 0.0.22-13643 with included change. While the majority of texture corruption appears to be gone with this fix, especially with flickering on moving/animated sprites, some texture corruption and disappearing sprites still remain on Vulkan that do not occur on OpenGL.

![image](https://user-images.githubusercontent.com/71151161/170149295-707e2ea4-38cf-41f3-9eb2-95e665c3a2b8.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8766885/RPCS3.log.gz)

[NPUB31614_20220525003926_capture.zip](https://github.com/RPCS3/rpcs3/files/8766886/NPUB31614_20220525003926_capture.zip)

**Comment by kd-11** [comment]
Reopening.
Needs synchronization2 extensions to fix it properly.

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/14065 assuming no driver bugs on intel.

**Comment by retroNUC** [comment]
Unfortunately, issue is still occurring in latest nightly RPCS3 build (0.0.28-15229), with latest Intel drivers (101.4502). New logs/capture attached.

![image](https://github.com/RPCS3/rpcs3/assets/71151161/5cad7ad4-02bc-43d0-89b5-4c538abe9807)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11858308/RPCS3.log.gz)
[NPUB31614_20230624230902_capture.zip](https://github.com/RPCS3/rpcs3/files/11858310/NPUB31614_20230624230902_capture.zip)

**Comment by JohnLoveJoy** [comment]
> Try with #14101. Each driver and hardware seems to expect different setups and I just don't have Xe on hand.

I can't reproduce this one, either in the Master or in the specified PR. The game runs perfectly here.

![BBPS01Master](https://github.com/RPCS3/rpcs3/assets/31490343/45423955-3a74-4f2a-ba2e-67e12b573a62)

![BBPS0](https://github.com/RPCS3/rpcs3/assets/31490343/e12c0fc9-08a3-4c71-9f0a-6102e519ab24)


[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11907616/RPCS3.log.gz)

**Comment by retroNUC** [comment]
Corruption still occurs on my system in 0.0.28-15270, which includes the above PR.

![image](https://github.com/RPCS3/rpcs3/assets/71151161/19180408-1b41-401c-9418-1ef80b37d1ea)

[NPUB31614_20230630182850_capture.zip](https://github.com/RPCS3/rpcs3/files/11919140/NPUB31614_20230630182850_capture.zip)

**Comment by kd-11** [comment]
Reopening. However, we don't have access to any xe hardware, so I'll remove from my wq for now.

**Comment by retroNUC** [comment]
For clarification, I'm not running any dedicated Xe/Arc hardware, this is just Intel integrated graphics on an 11th Gen CPU (Core i7-1165G7).

They stopped calling their integrated graphics 'Xe' after this very small period so it wouldn't confuse people with their upcoming dedicated hardwareand went back to the 'UHD' moniker for 12/13th Gen, but I imagine you may be able to reproduce this on any modern (11th Gen onwards, non-F/KF) Intel CPU with any extra GPU hardware disabled.

**Comment by digant73** [comment]
@retroNUC is that still an issue?

**Comment by retroNUC** [comment]
Yes, this still appears to be an issue on latest RPCS3 with semi-recent Intel drivers (101.6795 - May 2025)

[NPUB31614_20251026192656_capture.rrc.gz](https://github.com/user-attachments/files/23152803/NPUB31614_20251026192656_capture.rrc.gz)
[RPCS3.log.gz](https://github.com/user-attachments/files/23152804/RPCS3.log.gz)

<img width="2581" height="1521" alt="Image" src="https://github.com/user-attachments/assets/737a144a-c1a2-4272-af18-1d6fde85bcce" />

**Comment by digant73** [comment]
please provide an update on this issue
