### ISSUE TITLE
RPCS3 Eternal Sonata, causing Driver Crash, after Crash cannot launch until reboot windows

### ISSUE THREAD

**Issue by chrcoluk** [RPCS3/rpcs3#12044]
Win 10 64bit
Nvidia 3080 FE 472.84 Drivers - not overclocked
RPCS3 3.0.0.22-13600-2ba437b6 Alpha

Basically the opening cutscene in the game cannot finish it crashes and not just the emulator but it seems its causing a driver crash/reset.  Card isnt overclocked.  No instability ever seen in normal PC games.

I am attaching the log.

In addition if try to relaunch after this happens, I cant launch at all until I reboot, after a few seconds a device disconnect sound and frozen emulator.

**Comment by chrcoluk** [comment]
[RPCS3-crash.zip](https://github.com/RPCS3/rpcs3/files/8742309/RPCS3-crash.zip)

**Comment by Asinin3** [comment]
Update gpu drivers

**Comment by chrcoluk** [comment]
Hi, the same problem with drivers 512.77

I did a bit more digging and found a post suggesting to set zcull to accurate setting for modern nvidia GPUs turing and newer, and this has seemed to fix it, I want to do more test runs of the opening scene (it lasts quite a while about 15 minutes), and if they all succeed I will close this report.

Probably should have just left everything on default :p.

**Comment by chrcoluk** [comment]
Driver crash again in a cut scene early game, so still not stable. Still on the latest Nvidia driver.

**Comment by kd-11** [comment]
Post the new log.

**Comment by chrcoluk** [comment]
Sorry dont think I have that log now, but I have what I think is good news.

I have since then changed two settings.

I disabled float 16 support as the tip said it causes problems on some gpus, and also disabled exclusive full screen mode as had observed all my issues were whilst in full screen.

I have had one crash since then, but it was a game freeze not an entire driver crash so I think that was unrelated.  I was able to relaunch without reboot as well on that one.

I currently have a log over 1 gig uncompressed, I can zip that up and send though if it helps to provide info about my system, if thats not good enough I can do more playing with those two options toggled back.

Thank you for all the work on this emulator, I think its amazing whats been achieved.

**Comment by kd-11** [comment]
Run vkdiag from here: https://github.com/13xforever/vkdiag/releases/tag/v1.1.14
And post a screenshot with the results. Whenever messing with fullscreen has any observable effects, it usually points to an issue with conflicting plugins.

**Comment by chrcoluk** [comment]
Hi I ran vkdiag last night which just moaned about the build of windows (on 1809 LTSC, still, need to get this on 21H2 at some point), I am in RPCS3 right now playing the game but will do the screenshot for you later today.

Also I appear to have made the game very stable now by dropping PPU decoder to interpreter static, SPU is still on LLVM.  SPU seems to have the far bigger performance hit so its still playable in terms of performance.  Not a single driver crash since the half floating point change.

**Comment by kd-11** [comment]
Closing due to inactivity. I have to assume the issue was resolved.

**Comment by chrcoluk** [comment]
Not resolved, I just play using the lower performance mode, not sure how it can get resolved with no dev attention. O_o
