### ISSUE TITLE
Flamethrower heavily drops FPS in Ratchet & Clank Future: Tools of Destruction

### ISSUE THREAD

**Issue by EvilPlayer1** [RPCS3/rpcs3#12058]
## Details

When using flamethrower, FPS heavily drops and log begins to spam error.

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8747947/RPCS3.log)
#### 3. Please attach screenshots of your problem.
![Screenshot 2022-05-21 19-12-22](https://user-images.githubusercontent.com/90133207/169660477-ff3676ec-2416-478a-93cf-0277c59a11c8.png)
![Screenshot 2022-05-21 19-12-28](https://user-images.githubusercontent.com/90133207/169660479-c487b60b-6186-4fa8-a20c-b33ed833fa1e.png)
#### 5. Please provide your system configuration:
* OS - Windows 11
* CPU - Intel Core i7-11700
* GPU - NVIDIA GeForce GTX 1660 SUPER
* Driver version - 512.77

**Comment by Asinin3** [comment]
Disabling logging wont make his errors go away it will only improve perf from less logging. LBP issue isn't that it is having cache misses and RSX errors like mad. It's log spam. This might have a lot of errors but they are actual errors and not just random things spamming the log.

**Comment by EvilPlayer1** [comment]
> Disabling logging wont make his errors go away it will only improve perf from less logging. LBP issue isn't that it is having cache misses and RSX errors like mad. It's log spam. This might have a lot of errors but they are actual errors and not just random things spamming the log.

yeah. I tried that and got +6 FPS

**Comment by kd-11** [comment]
Which error is spammed? I cannot tell from the log.

**Comment by JimScript** [comment]
"E RSX: Fault in uninterruptible code!" but it doesn't seem to spam that much, like using 38 ammo only produces 205 of these errors.

**Comment by Xcedf** [comment]
Just assuming, but in GoW3 when you hit blue stones with gauntlets, there are lots of refraction effects and slowdown maybe similar to this one.

**Comment by kd-11** [comment]
Retest. This should have been fixed by the GT5 improvements work.

**Comment by Jonathan44062** [comment]
Still an issue with the performance
https://github.com/RPCS3/rpcs3/assets/78843189/b7a9cbd2-ba2d-4c10-a0b6-da03b2b34663

**Comment by Valtekken** [comment]
+1 on this issue with the latest build. Using the flamethrower sends the fps down to 30/40 from a stable 60, under any circumstances.

**Comment by Valtekken** [comment]
I'll continue on this one from #15507 to avoid cluttering the list with stuff that could be talked about in its own space.

Just one question, do I need to clear all of the caches to test each build and see if the flamethrower issue has been fixed or mitigated? I just tried the latest build, but the issue persisted just as badly so I'm wondering whether I'm doing something wrong.

**Comment by kd-11** [comment]
From what I've seen, flamethrower wasn't really fixed. However, the reduced system load overall makes it so that it doesn't dip as badly as before, but still pretty awful (cuts fps in half).

**Comment by Valtekken** [comment]
> From what I've seen, flamethrower wasn't really fixed. However, the reduced system load overall makes it so that it doesn't dip as badly as before, but still pretty awful (cuts fps in half).

Man, I'm not even seeing that improvement. Still a complete tank from a stable (more or less) 60 to the low 20s/high 10s

**Comment by digant73** [comment]
is that still an issue?

**Comment by alexconsole04** [comment]
Yes its still an issue

**Comment by chroniceel93** [comment]
Out of interest (as I happen to be blitzing through the series), I was scanning through issues, and saw this one. 

Current PC is a linux system with a Ryzen 7 7700X, with a AMD RX 6700 XT, running the latest RPCS3 build (appimage) as of posting, using the vulkan backend.

I'm *technically* seeing a framerate dip, but only into the low 50's, when using the flamethrower.

<img width="2050" height="1172" alt="Image" src="https://github.com/user-attachments/assets/96e30a4b-565e-4b77-8df8-4c37253b9410" />

This doesn't mean things are resolved, but I figure it's an interesting data point regardless.

**Comment by kd-11** [comment]
The flame effect triggers a storm of flush requests forcing GPU stalls. I saw sustained load of over 40 hard sync events per frame which is incredibly high. When not using the flamethrower the count is around 0. We need to check what its trying to read back mid-draw so badly.

**Comment by Valtekken** [comment]
> The flame effect triggers a storm of flush requests forcing GPU stalls. I saw sustained load of over 40 hard sync events per frame which is incredibly high. When not using the flamethrower the count is around 0. We need to check what its trying to read back mid-draw so badly.

What kind of data are we looking for here? Is it trying to read an asset like a texture or an audio effect or something else?
