### ISSUE TITLE
rsx: Thread terminated due to fatal error: Verification failed

### ISSUE THREAD

**Issue by snnaakee** [RPCS3/rpcs3#12066]
Emulator is now throwing fatal error on the latest master build :
```
{RSX [0x054db3c]} SIG: Thread terminated due to fatal error: Verification failed 
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\VKGSRender.cpp:2789[:3], in function begin_conditional_rendering)
```

![image](https://user-images.githubusercontent.com/62524548/169705176-12bea67b-0167-4ae8-bf42-5036782dec60.png)

The crash occurs when using rpcs3-v0.0.22-13626-ec2d5298 from pull #12020 and ZCULL Accuracy is set to Precise (Slowest). 
ZCULL Accuracy to Approximate (Fast) prevents the emulator from crashing, but the game doesn't support it well (causes the game not to render beyond 10 meters or so).

The crash is completely gone when reverting back to rpcs3-v0.0.22-13604-5a581f46 (pull #12045).

#### Logs:
[5a581f46.log](https://github.com/RPCS3/rpcs3/files/8749800/5a581f46.log)
[ec2d5298 .log](https://github.com/RPCS3/rpcs3/files/8749835/ec2d5298.log)

#### System configuration:
* Windows 10
* i7-8700K CPU @ 3.70GHz
* GTX 970
* 16 Go RAM
* 512.77

edit:
[The fatal crash in video](https://youtu.be/YynVPNrrta0)

**Comment by snnaakee** [comment]
After further investigation, it led me to f0135a02

I started compiling from commit 850eef0c then the crash started to occur at f0135a02

Getting back to the head of master, then commenting the line at rpcs3/Emu/RSX/VK/VKGSRender.cpp:551 gets rid of the crash.
`backend_config.supports_hw_conditional_render = true;`

Also, I noticed the crash tends to happen when the CPU is under heavy load.

**Comment by Megamouse** [comment]
Does this also happen with openGL ?

**Comment by AniLeo** [comment]
The game on the logs is listed as Intro, can this be reproduce on something that is Ingame or Playable?

**Comment by snnaakee** [comment]
> Does this also happen with openGL ?

No it doesn't.



> The game on the logs is listed as Intro, can this be reproduced on something that is Ingame or Playable?

No, at least not on my computer.
I tried around 4-5 different games from 2007 (near the game on the logs) to 2011 (the most recent I have).

**Comment by snnaakee** [comment]
I recorded 3 videos, which I think is always good to take for reference.

No edit, ZCULL Accuracy to Precise (Slowest).
[Video 1: Crash](https://youtu.be/YynVPNrrta0)

With rpcs3/Emu/RSX/VK/VKGSRender.cpp:551 removed and ZCULL Accuracy to Precise (Slowest)
[Video 2: No crash](https://youtu.be/-DGy1_MCA1E)

No edit, but ZCULL Accuracy to Approximate (Fast) to avoid the fatal crash.
Will cause major graphical issues.
[Video 3: No edit](https://youtu.be/hC4ZMQXo_sE)

Logs for the test with ZCULL Accuracy to Approximate (Fast):
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8754600/RPCS3.log)

Tested on RPCS3 v0.0.22-13641-608f8235 Alpha | master

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/12071

**Comment by snnaakee** [comment]
Fatal crash is still happening with #12071

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8757246/RPCS3.log)

**Comment by kd-11** [comment]
Ok, should be fixed now.

**Comment by snnaakee** [comment]
> Ok, should be fixed now.

I can confirm the crash is gone.

Thank you !
Keep on keeping on !

**Comment by sinbadbd** [comment]
When game lunched then it showing error & freez the screen. Any solution about this? 

`F {RSX [0x0019588]} SIG: Thread terminated due to fatal error: Unknown register name: unk
(in file /private/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/VKCommonDecompiler.cpp:155[:3], in function get_varying_register_location) (errno=316=Unknown error: 316)
S SPU: New block compiled successfully x15`

**Comment by deadmeme5** [comment]
hi, i have the same problem now with Little Big Planet 3 patch 1.26 error is `F {RSX [0x0372ca0]} SIG: Thread terminated due to fatal error: Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\Common\surface_utils.h:481[:4], in function set_old_contents` 

here are the logs: 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9791749/RPCS3.log)
[TTY.log](https://github.com/RPCS3/rpcs3/files/9791750/TTY.log)

**Comment by LuismaSP89** [comment]
This keeps happening also to me on every game, latest build of rpcs3: 

F {RSX [0x0000000]} SIG: Thread terminated due to fatal error: Failed to compile vertex shader
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\VKProgramPipeline.cpp:29[:25], in function compile)

**Comment by ZachFett** [comment]
Getting this issue with Dead to Rights: Retribution, immediately after the legal screen fades away. I've tested both BLES00824 and BLUS30278, both have the same error at that same moment.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10502157/RPCS3.log)

**Comment by deadmeme5** [comment]
> Getting this issue with Dead to Rights: Retribution, immediately after the legal screen fades away. I've tested both BLES00824 and BLUS30278, both have the same error at that same moment.
> 
> [RPCS3.log](https://github.com/RPCS3/rpcs3/files/10502157/RPCS3.log)

change the SPU decoder and ppu decoder from LLVM recompiler to dynamic interpreters
try playing around with these most likely it will fix.

**Comment by kd-11** [comment]
Don't necro closed issues. Open new issues if you have a problem that requires investigation.
