### ISSUE TITLE
Shadow of the Colossus Flickering graphics and Pixelated Upscaling issue

### ISSUE THREAD

**Issue by Mrblubb** [RPCS3/rpcs3#12103]
## Quick summary
-Parts of geometry are flickering while moving camera/walking/running ingame. 
-When upscaling with/without patch image becomes pixelated.
(issue still occurs in latest as well as a week old builds)

## Details

Video Preview 1: https://www.veed.io/view/9b77af0d-943d-45da-9921-6b3990f9e05b?sharingWidget=true
Video Preview 2 : https://www.veed.io/view/75dea663-4786-4864-8df5-40d960b94c3d?sharingWidget=true

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8786675/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8786678/RPCS3.log.gz)

#### 3. Please attach screenshots of your problem.
Image Preview :
![vlcsnap-2022-05-27-18h00m58s786](https://user-images.githubusercontent.com/88938655/170699924-b54b897e-9703-48d7-b21b-6f4c1080a64d.png)
![vlcsnap-2022-05-27-18h02m11s058](https://user-images.githubusercontent.com/88938655/170699931-37816cca-7511-4d0e-a1fe-333f4b7931ae.png)

#### 5. Please provide your system configuration:
* OS Windows 10 21h1
* CPU FX 8350 4.4 ghz
* GPU GTX 1060 6gb
* Driver version 511.79

**Comment by YuriNator557** [comment]
The game uses MLAA, this is what will cause the game to become pixelated when upscaling
Issues relating to resolution scaling are not valid, it's a hack which isn't automatically compatible with every game

**Comment by Mrblubb** [comment]
This isn't only an issue regarding upscaling. Flickering graphics happens at native resolution without any patches at the default settings in the latest builds.

**Comment by YuriNator557** [comment]
Apologies,
If this is a graphical issue at native res then we'd need an RSX capture as well, also a Renderdoc capture if you can get one

**Comment by Mrblubb** [comment]
How do I provide that? I don't know the procedure well.

**Comment by YuriNator557** [comment]
Alt + C will generate an RSX capture and pause emulation, it will save to the 'captures' folder

**Comment by Mrblubb** [comment]
Thanks for the tip. Here's the RSX capture for the latest build:
https://we.tl/t-gkhhscUmeJ

**Comment by YuriNator557** [comment]
Can you upload it to somewhere more permanent, that link will expire in a week

**Comment by Mrblubb** [comment]
Here, done! https://drive.google.com/file/d/1gv1EPUDoLVMtIwdD_bC8ooB4GkOTYNYs/view?usp=sharing

**Comment by Mrblubb** [comment]
After more testing the graphics are fine in rpcs3-v0.0.17-12620-27c86422. No more flickering and pixelation.

**Comment by Darkhost1999** [comment]
> After more testing the graphics are fine in rpcs3-v0.0.17-12620-27c86422. No more flickering and pixelation.

Is this the last version that works successfully? Or what was the version where the issue started?

**Comment by Tarek2013** [comment]
Hi !
I've read that Asus fixed they Bios drivers coz the last before made shuttering with AMD cores and graphics.
So, did u tried to update your bios system ?

**Comment by no008080** [comment]
I ran across a similar issue. However, it seems to just be this one texture in front of the temple (as of the time of recording).

![unknown_2022 08 01-21 00](https://user-images.githubusercontent.com/97309764/182225693-c47024ce-51b8-4d4d-ab7f-a341a99e84bb.gif)
RSX capture: https://mega.nz/file/RGATAAIA#5XnXyqVFFgMdH2rnfRSdFxYcnAkT7-fy73Ek07bD4vY

**Comment by shinra-electric** [comment]
According to the OP this issue is fixed. 

However I can reproduce the flickering texture reported by no008080 on 0.0.27.15055.

**Comment by munkychon** [comment]
Was this ever fixed? Have there ever been any new suggestions about running this game optimally? I know the mlaa patch and 60fps patch are doing their jobs. I also understand that atoimic needs be selected in the advanced section. No matter how I tinker with these settings I get the flickering screen on the castle steps. The game runs so well though, I know I'm being picky. Just wondering if this was ever ironed out. I've even reproduced the error on the old version of RPCS3 mentioned by OP. On my system, the issue persists regardless of version number or settings applied. Thanks for listening. 


My Specs:
Ryzen 5 3600, 32gb Corsair RAM, sapphire pulse RX6600


![Image](https://github.com/user-attachments/assets/73f1baa4-ebd2-415e-857d-4985ec5b2ad8)

**Comment by Mrblubb** [comment]
Ok so the issue does still exist in every build. Back then when I played on that version that particular area was fixed so I continue playing but didn't played much due to stutters and ridiculous high CPU usage. But I think this is one of those issues that can't be fixed as a few other games also have this issues. Better wait for the PC version if Sony does a re-release like they're doing. All God of War games are getting a release on PC this year too. I think rpcs3 did what it could but now is PC port time.

**Comment by kd-11** [comment]
This one needs verification on PS3. Everything I'm seeing here looks like issues with the game itself.

**Comment by munkychon** [comment]
Anyone have a ps3 to test? Or maybe difference in versions? I'm using USA/Brazil version. Maybe results differ with PAL version?

**Comment by Mrblubb** [comment]
Running on latest build with default settings + 1080p native, Shaders Ultra, Precise CULL + Atomic FIFO.
I can confirm the issue has been completely fixed & it looks gorgeous and runs Butter Smooth. 
I've shared a video below as well. 
Thank you RPCS3 Team!!! Love you guys 🤗💖💖💖

![Image](https://github.com/user-attachments/assets/24029ead-5321-4211-afe6-0888edb8b01f)

Video : https://www.youtube.com/watch?v=ptgVPm6ORO0

**Comment by munkychon** [comment]
My potato is still running with an r5 3600 cpu, think I can push it with your settings? Also, thanks for the news and posting your settings.

**Comment by Mrblubb** [comment]
@munkychon Glad I could help. You can definitely try the 60fps patch & bump resolution to 4k I'm sure it can handle it well. Here I've beaten 3 bosses and not a single framedrop or stutter. Cpu usage is around 65% & Gpu around 25%. It runs way better than pcsx2 & probably the definitive way to play on PC. 
***Just one thing I noticed that when the camera is still and you see Wander's face from a distance it looks weirdly aliased. If that can be fixed, then I assume this thread can be safely closed.

**Comment by digant73** [comment]
@Mrblubb is that still an issue?

**Comment by Mrblubb** [comment]
> [@Mrblubb](https://github.com/Mrblubb) is that still an issue?

not at all. at least for my specs. there are no issues and it runs perfect. I cleared the game on it.

**Comment by munkychon** [comment]
Thanks for continually updating guys. On a side note, I now prefer playing this on pcsx at 180% overclock for 60fps. I also highly recommend sad origami's texture pack for a look that rivals or improves upon rpcs3 visuals. Try it out, this person must truly love the game as they retexured all assets to hd... Wow

**Comment by Mrblubb** [comment]
Ah..sure!! Thanks
