### ISSUE TITLE
0.0.24-14148 GOWA [NPUA80918] graphics issues

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#12670]
### Quick summary

Thanks for reading.
CPU AMD FX-6300 4 GB RAM Geforce GT 640 driver 470.129.06
Linux Ubuntu 20.04.5 64 bits.
An old cpu, but with the same cpu using previous versions not happen the bug.
Perhaps happening in others cpus too ?

GOWA not start if using
Accurate SPU Reservations: false

Need
Accurate SPU Reservations: true
Accurate RSX reservation access: false

In title screen and in stages happen graphics flickering.
That bugs never had happening.
Not happen if using ASMJIT.

Logs
Have an nice day.

![01 ASMJIT](https://user-images.githubusercontent.com/21184987/190843545-4962cc7d-2cd9-4d09-8bc2-6e8346c54301.jpg)

![02](https://user-images.githubusercontent.com/21184987/190843553-c82675ca-0683-4f24-9cdf-4f44f9e90161.jpg)

![03](https://user-images.githubusercontent.com/21184987/190843558-2802e258-ca4f-4eb4-98b0-c7115f653aac.jpg)

### Attach a log file

[RPCS3-GOW-ASMJIT.zip](https://github.com/RPCS3/rpcs3/files/9591078/RPCS3-GOW-ASMJIT.zip)

[RPCS3-GOWA-LLVM.zip](https://github.com/RPCS3/rpcs3/files/9591079/RPCS3-GOWA-LLVM.zip)

**Comment by mfdsrax2** [comment]
You need an RSX capture for graphic issues.

**Comment by Augusto7743** [comment]
Thanks for your reply with information above.
I will to do an RSX capture =)

**Comment by kd-11** [comment]
The most important piece of information here is the build where the problem started appearing. Not many people have the FX cpus anymore so it probably broke accidentally while something else was being worked on.

**Comment by Augusto7743** [comment]
Huge slowdown happen in other cpus too.
Edited the summary with the correct informations.

**Comment by kd-11** [comment]
This should have been fixed.

**Comment by Augusto7743** [comment]
Thanks very much for replying and your amazing job done in RSX code =)

Graphics issues and slowdown are still happening in current build.
The PRs breaking GOWA are from several previous builds. The coders not has noticed the issues and was as PR "completed".
If you read the PR topics has users saying about breaking anothers games and having better speed for others games.
Is an surprise for me GOWA graphics issues not had been reported.
Is as some users not want use current builds if are using an build working with good accurate emulation.
I try use update builds mainly for testing an report so contributing with the project.
I had tested 37 builds to figure what had breaked some games. Really is much time to do it. Some users not want to do it.

Hey kd-11 ... your github username icon is from what game ?

**Comment by solarmystic** [comment]
This could definitely a Linux only issue at least for the graphics portion, the game looks normal even on the latest builds on Windows using settings recommended by the game's wiki page. Game starts normally using LLVM for both SPU and PPU.

![image](https://user-images.githubusercontent.com/4345150/192938888-8522a930-d0b5-4143-b12b-a252128b0e29.png)

I cannot comment on the slowdown since i've not experienced any over the same builds, before or after the builds reported by this user.

Tested with a 12400F/2080TI machine on NVIDIA 516.94 drivers.

**Comment by elad335** [comment]
You can test with #12598 the slowdown issue.

**Comment by Augusto7743** [comment]
@solarmystic
I only has tested in Linux build.
LLVM and VM improvements has breaked GOWA only for cpu no tsx and AVX2 ?

@elad335
Using 0.0.24-14183 PR 12700.
PR 12700 has code was 12598 ? If yes both bugs not are fixed.

In PR 12700 have the information
Added a new setting controlling PPU usleep sleep time called "Usleep Time Addend" in game config. Known to improve performance in some situations in internal testing.

In game config file and GUI configuration not have any "Usleep Time Addend" setting.
That feature not is in current build ?

**Comment by elad335** [comment]
Just test it with no further config changes.

**Comment by Augusto7743** [comment]
In https://rpcs3.net/compatibility?b browsing not have PR 12598.
That PR was added in build ? Accessing
https://github.com/RPCS3/rpcs3/pull/12598
That PR is "draft". Not merged.

**Comment by elad335** [comment]
https://cirrus-ci.com/task/5858869300690944

**Comment by Augusto7743** [comment]
Thanks for replying and sharing the build link.

Choplifter HD [NPUB30619]
is having the same graphics issues related with GOWA
If using ASMJIT not any graphics bugs.
Tested in both master and your alpha build.
I need test if was breaked in 0.0.18-12773.

Using PR 12598 :

- Some games are loading more fast.
- Random crashed closing the emulator main window.

GOWA continue having both graphics and slowdown bugs.
However have an tiny better speed in some moments being related with PR 12598

LittleBigPlanet [NPUA80472]
Loading and gameplay is more fast

MOTORSTORM PACIFIC RIFT DEMO [NPUA70022]
Not more temporary freeze in gameplay

WipEout HD [NPUA80105]
gameplay now is smooth framerate

About
Usleep Time Addend: 0

If using another value does any errors ?

**Comment by Augusto7743** [comment]
Choplifter HD [NPUB30619] having the same graphic bug.
Not happen if using ASMJIT.
Also happening since 0.0.18-12773 10809 SPU LLVM Improvements
https://github.com/RPCS3/rpcs3/pull/10809

Please see the screenshot. Not is easy an screenshot showing all graphics issues. Flickering transparent triangles above of graphics exactly as in GOWA game title.

![screen](https://user-images.githubusercontent.com/21184987/193165042-6fa4a26a-09ea-47b6-82ef-595ebc77a8fb.jpg)

**Comment by Augusto7743** [comment]
I not understand if my bug topic is being ignored.
More of one year and not any user posting about it ... perhaps are bugs related only in Linux ?

Thus being I have done 2 video captures for showing the problems happening in GOWA and Choplifter too.
First started the game few times to create all SPUs and shaders thus avoiding performance problems.
Possibly have anothers games having graphics issues by the PRs below

[Testers Needed] SPU LLVM Improvements #10809
https://github.com/RPCS3/rpcs3/pull/10809

[Need test] vm locking refactoring #11904
https://github.com/RPCS3/rpcs3/pull/11904

The PR 11904 have done an huge slowdown in GOWA. Now the game is extremly slow almost all time even in menus and pausing.
Others games are running in 100 % emulation speed. However are using much more cpu than before of PR below.
I not have done an video capture of others games because are being emulated 100 %, but using much more cpu exactly when was added the PR below.
Possibly another PR only doing problems in Linux.
Please watch the video.

https://www.youtube.com/watch?v=c3lOWLFPAxo

From the begin to 1 minute is the build rpcs3-v0.0.18-12757-b30ac485_linux64 being the last build running correctly in Linux.
From 1:05 are problems from builds
Graphics issues = rpcs3-v0.0.18-12773-9e62ca56_linux64 ... ASMJIT not happen the graphics issues bug
Slowdown = rpcs3-v0.0.22-13536-5c1f79ab_linux64

Please see the video below

https://www.youtube.com/watch?v=eR5aXwz4Bd4


From begin to 40 seconds is using the build rpcs3-v0.0.18-12757-b30ac485_linux64.
After is using build rpcs3-v0.0.18-12773-9e62ca56_linux64.
Chopilfter only have graphics issues by #10809. The game issue happen in both GOWA and Choplifter.
The game have done few slowdowns in some moments.

I need create another bug report for Choplifter or continue using here ?

**Comment by Augusto7743** [comment]
Tested in recent rpcs3-v0.0.27-14980
The bug with graphics related with PR 10809 (SPU LLVM Improvements) was fixed.
Thanks !

Now only happening the slowdowns related with PR #11904 ( vm locking refactoring ).

**Comment by Asinin3** [comment]
Closing this, you already opened another issue for the slowdown
