### ISSUE TITLE
Outrun Online Arcade - Multiplayer menu displays black screen - Cannot return to main menu

### ISSUE THREAD

**Issue by Mufausa** [RPCS3/rpcs3#12764]
### Quick summary

When you go to Multiplayer mode (with RPCN connected) the game just displays a black screen and you cannot go back.

You can still hear the menu music but outside of that. You are forced to quit the game and restart it again.

![image](https://user-images.githubusercontent.com/10360004/194418713-19947f9f-7b63-4413-ab99-13f04ac55216.png)

![image](https://user-images.githubusercontent.com/10360004/194418769-3cedd0a8-3e2e-4fe2-a9a9-3ecb5b2d11a8.png)

### Details

As I mentioned above. The multiplayer lobby does not work - The game goes to a black screen and you can hear the menu music continuing to play. But outside of that. You cannot do anything and are forced to close the game on RPCS3.

### Attach a log file

U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E SYS: 'sys_rsx_context_attribute' failed with 0x80010002 : CELL_EINVAL [1]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPEB00073/USRDIR/pl_ps/projects/trc/trc.gpu” [1]
E SYS: 'sys_fs_lseek' failed with 0x8001002a : CELL_EBADF [1]
E SYS: 'sys_fs_lseek' failed with 0x8001002a : CELL_EBADF [2]
E SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPEB00073/USRDIR/pl_ps/projects/trc/trc_en.gpu” [1]
E SYS: 'sys_fs_lseek' failed with 0x8001002a : CELL_EBADF [3]
U sceNp TODO: sceNpCustomMenuActionSetActivation(array=*0xd0010270, options=0x0)
E SYS: 'sceNpCustomMenuActionSetActivation' failed with 0x80023b02 : SCE_NP_CUSTOM_MENU_ERROR_NOT_INITIALIZED [1]
U sceNp TODO: sceNpCustomMenuActionSetActivation(array=*0xd0010270, options=0x0)
E SYS: 'sceNpCustomMenuActionSetActivation' failed with 0x80023b02 : SCE_NP_CUSTOM_MENU_ERROR_NOT_INITIALIZED [2]
E SYS: 'sceNpBasicRegisterHandler' failed with 0x8002a662 : SCE_NP_BASIC_ERROR_NOT_INITIALIZED [1]
U sceNp TODO: sceNpCustomMenuRegisterActions(menu=*0xbaf5a8, handler=*0x664b70, userArg=*0xbaf570, options=0x0)
E SYS: 'sceNpCustomMenuRegisterActions' failed with 0x80023b02 : SCE_NP_CUSTOM_MENU_ERROR_NOT_INITIALIZED [1]
U cellGameExec TODO: cellGameGetBootGameInfo(type=*0xd0010b20, dirName=*0xd0010b28, execdata=*0xd0010b24)
E SYS: 'cellPadSetActDirect' failed with 0x80121102 : CELL_PAD_ERROR_INVALID_PARAMETER [1]
E SYS: 'cellPadSetActDirect' failed with 0x80121102 : CELL_PAD_ERROR_INVALID_PARAMETER [2]
E SYS: 'cellPadSetActDirect' failed with 0x80121102 : CELL_PAD_ERROR_INVALID_PARAMETER [3]
U sceNp TODO: sceNpBasicSetPresenceDetails(pres=*0xb9557c, options=0x2)
E SYS: 'sceNpBasicSetPresenceDetails' failed with 0x8002a662 : SCE_NP_BASIC_ERROR_NOT_INITIALIZED [1]
E SYS: 'cellSaveDataAutoLoad2' failed with 0x8002b401 : CELL_SAVEDATA_ERROR_CBRESULT [1]
U sceNp TODO: sceNpBasicSetPresenceDetails(pres=*0xb9557c, options=0x2)
E SYS: 'sceNpBasicSetPresenceDetails' failed with 0x8002a662 : SCE_NP_BASIC_ERROR_NOT_INITIALIZED [2]
E SYS: 'cellNetCtlNetStartDialogLoadAsync' failed with 0x80130101 : CELL_NET_CTL_ERROR_NOT_INITIALIZED [1]

### System configuration

- SYS: RPCS3 v0.0.24-14283-5c24009e Alpha | master
- SYS: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz | 12 Threads | 15.95 GiB RAM | TSC: 3.696GHz | AVX+ | FMA3 | TSX-FA disabled by default
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2022-10-17T16:26:42

**Comment by Mufausa** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9804270/RPCS3.log.gz)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9804271/RPCS3.log)


Log Files

**Comment by Knekospy** [comment]
I have also encountered this same issue and it still has yet to be fixed in the latest version.

**Comment by Mufausa** [comment]
Hopefully we'll get a dev to look into this

I'd love to play Outrun online again

**Comment by Knekospy** [comment]
I know you can't download it off PSN anymore if you don't already own it, but do the normal servers no longer work?

**Comment by Mufausa** [comment]
I have it on Xbox 360 but I am not sure if the servers are still live.

**Comment by Ninetime** [comment]
Is addressed by #15011

**Comment by Mufausa** [comment]
I can confirm. The black screen issue has now been address. I can get to the next screen as shown by @Ninetime 

However, lobbies still cannot be created as of this post. I know that is still being worked on.
