### ISSUE TITLE
XBlaze Games Seem to crash when closing the game.

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#13352]
### Quick summary

When stopping the application or closing the window the game crashes from a Dead FIFO commands.

### Details

When testing XBLAZE CODE: EMBRYO Trial Verison  [NPJB90613] and  XBlaze Lost: Memories Trial Verison [NPJB90776] The game seem to crash the emulator when stopping the application with this log output.

RSX [0x0000000]} SIG: Thread terminated due to fatal error: Dead FIFO commands queue state has been detected!
Try increasing "Driver Wake-Up Delay" setting or setting "RSX FIFO Accuracy" to "Atomic", both in Advanced settings. Called from
(in file ../rpcs3/Emu/RSX/RSXFIFO.cpp:647, in function run_FIFO) (errno=110=Connection timed out)
(in file ../rpcs3/Emu/RSX/RSXThread.cpp:3009, in function recover_fifo) (errno=110=Connection timed out)

I test with RSX FIFO Accuracy set to Atomic and Order and Atomic but it didn't change the out so not sure why it crashes.

### Attach a log file

[XBlaze Code: Embryo Trial Verison.log.gz](https://github.com/RPCS3/rpcs3/files/10609457/XBlaze.Code.Embryo.Trial.Verison.log.gz)
[XBlaze Lost: Memories Trial Verison.log.gz](https://github.com/RPCS3/rpcs3/files/10609459/XBlaze.Lost.Memories.Trial.Verison.log.gz)

### System configuration

  SYS: RPCS3 v0.0.26-14666-37b46df7 Alpha | master
  SYS: AMD Ryzen 5 2600 Six-Core Processor | 12 Threads | 15.57 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
  SYS: Operating system: POSIX, Name: Linux, Release: 5.15.89-1-MANJARO, Version: #1 SMP PREEMPT Wed Jan 18  20:37:11 UTC 2023
  SYS: Current Time: 2023-02- 4T19:08:17
  RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 3060 Ti' running on driver 525.85.5.0
  SYS: Firmware version: 4.89

### Other details

This doesn't affect the playability of the game so not really a pressing issue.

**Comment by Asinin3** [comment]
You set it to atomic, but didn't change the wakeup delay on Advanced tab like the error told you to. Use 150-250.

Closing as these issues are already being tracked, and should be fixed with settings.

**Comment by Triticum0** [comment]
Tested using Wakeup delay with 100/150/200/250 and The issue Still persists but thank you for the help.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12138399/RPCS3.log)
