### ISSUE TITLE
SOULCALIBUR Ⅱ HD ONLINE [NPUB31366] - Game crashes at start

### ISSUE THREAD

**Issue by Rex000** [RPCS3/rpcs3#13458]
### Quick summary

Crashes right at the beginning.

### Details

After installing the pkg the I ran it, it compiled the SPU cache then showed the Bandai Namco and Project Soul logos then crashed the whole emulator right after it.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10838118/RPCS3.log)

**Comment by Megamouse** [comment]
try libVdec lle

**Comment by Megamouse** [comment]
another crash is fixed in #13460

**Comment by Rex000** [comment]
Just tried, still crash

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10845029/RPCS3.log)

**Comment by Megamouse** [comment]
I don't know. works for me if you ignore the occasional HLE libVdec deadlock at the start.
The audio is horrible though....

**Comment by Ninetime** [comment]
> I don't know. works for me if you ignore the occasional HLE libVdec deadlock at the start. The audio is horrible though....

Disabling Audio Buffering cleared up the audio issues for me in this title.

**Comment by Rex000** [comment]
Seems like it's an issue with the intro movie. The moment that blue mist starts coming from the right side of the screen, the emulator crashes. If I skip the intro movie the game seems to run fine.

**Comment by Rex000** [comment]
Seems like it's an issue with the intro movie. The moment that blue mist starts coming from the right side of the screen, the emulator crashes. If I skip the intro movie the game seems to run fine. Don't know if this will be an issue with every movie though. Hopefully not.

**Comment by FlexBy420** [comment]
Is this still an issue?

**Comment by Rex000** [comment]
Yes

**Comment by Virtua64** [comment]
idk, this doesnt seem like an issue for anyone else.  His cpu is well below spec (4c / 4t, no AVX2) and maybe he should verify his pkg to see if it is corrupt.  Just booted the game 10 times, let the intro movie play a bit and it loaded and played correctly every time for me on a basic windows 10, ryzen 2700x system.

**Comment by digant73** [comment]
@Rex000 is that still an issue?

**Comment by Rex000** [comment]
It's still happening.
