### ISSUE TITLE
[Regression] LittleBigPlanet stuck on blank screen when loading levels

### ISSUE THREAD

**Issue by Zerron21** [RPCS3/rpcs3#13692]
### Quick summary

The game gets stuck on a blank white screen when loading a story level while the emulator is running without crashing.

### Details

LittleBigPlanet™ [NPUA80472] was capable of loading the story levels perfectly fine before the update but now the screen is stuck on the white transition screen and goes on for a seemingly infinite time without anything happening. The FPS counter is still active and controller inputs do nothing so closing the emulator is the only way to exit the screen. v0.0.27-14883-9ff6003d is affected aswell.

Here's a screenshot for reference.
![NPUA80472_screenshot_2023_04_18_15_46_49](https://user-images.githubusercontent.com/62805345/232814182-f75e46d2-1b47-4f2a-9ff5-a1f0e8101bd4.png)

### Build with regression

v0.0.27-14881-39d17a94

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11262586/RPCS3.log.gz) Regression in 0.0.27-14881-39d17a94

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11262621/RPCS3.log.gz) Functional in 0.0.27-14879-999caea0

### System configuration

OS: Windows 11 Home 2H22 Build 22621.1555
CPU: 12th Gen Intel(R) Core(TM) i7-12700H   2.30 GHz
GPU: NVIDIA GeForce RTX 3050 Ti Laptop GPU
GPU Driver: Game Ready 531.68
RAM: 16.0 GB

**Comment by solarmystic** [comment]
Probably also fixed by #13702

**Comment by Cederick** [comment]
Still broken as of right now. Even downloaded the latest version to retest.

https://github.com/RPCS3/rpcs3/issues/13694#issuecomment-1516569882

**Comment by solarmystic** [comment]
Working just fine over here with the latest version (0.0.27-14893) on Windows. Updated to 1.30.

![image](https://user-images.githubusercontent.com/4345150/233522372-c9186b2d-84e0-4e95-9b6c-e1ef085e5e7e.png)

Tested on a 12700KF/2080TI/W10 21H2 machine.

**Comment by Zerron21** [comment]
Version 0.0.27-14892 and onward fixed it for me
