### ISSUE TITLE
Adventure Time: Finn and Jake Investigations Demo Crashes when combine items [NPEB02234]

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#13706]
### Quick summary

EU version of the demo crashes when trying to combine 2 items.

### Details

When testing the European version of the demo, I have an issue where the game would crash when trying to combine 2 items. I tested the US version which didn't experience the issue and your pkg checker showed that the pkg was fine. So not sure why the problem occurred.

![NPUB31664_screenshot_2023_04_19_14_14_51](https://user-images.githubusercontent.com/71127352/233087551-37bccde4-4f67-4071-8a5a-761603de251a.png)

Crash error: VM: Access violation reading location 0xfffffff4 (unmapped memory)

### Attach a log file

[Adventure Time: Finn and Jake Investigations Demo.log.gz](https://github.com/RPCS3/rpcs3/files/11273468/Adventure.Time.Finn.and.Jake.Investigations.Demo.log.gz)
[Adventure Time: Finn and Jake Investigations (Demo) NPUB31664.log.gz](https://github.com/RPCS3/rpcs3/files/11273469/Adventure.Time.Finn.and.Jake.Investigations.Demo.NPUB31664.log.gz)

### System configuration

RPCS3 v0.0.27-14885-32bfb808 Alpha | master | FW 4.88 | 5.15.106-1-MANJARO
AMD Ryzen 5 2600 | 12 Threads | 15.95 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 3060 Ti (530.41)

**Comment by Triticum0** [comment]
Updating to version 1.02 seems to fix the issue you can close it if the fix is up to your standards.

**Comment by ChwaraeTeg** [comment]
I was able to reproduce the crash in v1.00 of NPEB02234 on RPCS3 v0.0.28-15346 with the same error: 
_VM: Access violation reading location 0xfffffff4 (unmapped memory)_

Log file: [RPCS3_NPEB02234.log.gz](https://github.com/RPCS3/rpcs3/files/12032637/RPCS3_NPEB02234.log.gz)

When trying to reproduce the error I found that you don't need to play all the way through to where the game first requires you to combine 2 items - the error can be reproduced as soon as you're through the opening cinematic and take control of the player: press Select, highlight the sword item in your inventory and press Square, highlight Jake in your inventory and press Square, then press Triangle to trigger the crash.

I tried the same version (v1.00 of NPEB02234) on a PS3 console and the game doesn't crash when doing the same steps.

**Comment by digant73** [comment]
it seems this issue has been reported as fixed. @Triticum0 can you confirm?

**Comment by Triticum0** [comment]
@digant73 When? I tested as of RPCS3 Version: 0.0.38-18263-3c401e7b Alpha | master and still crashes with default settings on version 1.00

**Comment by digant73** [comment]
you reported fixed with update 1.02

**Comment by Triticum0** [comment]
That fine, but as ChwaraeTeg the original release doesn't crash on hardware. I will add it to wiki and move it to playable on compatibility report. but this still should be looked at as could help other game in the future.

**Comment by ChwaraeTeg** [comment]
Issue is still present in RPCS3 v0.0.38-18310-3df0c8ca Alpha

Updated log: 
[RPCS3.log.gz](https://github.com/user-attachments/files/23416305/RPCS3.log.gz)
