### ISSUE TITLE
[NPJB00235]E.X. Troopers - Missing character textures color in VR room 

### ISSUE THREAD

**Issue by JumpingY** [RPCS3/rpcs3#13853]
### Quick summary

Missing character textures color in VR room.Some textures have colors.Everything is normal in the mission map

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11471746/RPCS3.log.gz)

### Attach capture files for visual issues

![QQ截图20230514185047](https://github.com/RPCS3/rpcs3/assets/54348327/4062522d-64e8-42ad-a03f-618725086f0d)
![QQ截图20230514185058](https://github.com/RPCS3/rpcs3/assets/54348327/e9d60783-d382-4c64-83e5-79ab5eba84bf)
![QQ截图20230514185204](https://github.com/RPCS3/rpcs3/assets/54348327/ad90f269-ad03-4cbe-9dc7-a0c0bd1a5b64)
![QQ截图20230514185135](https://github.com/RPCS3/rpcs3/assets/54348327/0facae57-4cfb-4175-a727-aa2ddf7006ca)

### System configuration

CPU:R7-3700X
GPU:GTX1660
GPU Driver Version:531.61

**Comment by coryetzel** [comment]
+1 Same here. 

![Rpcs3 Screenshot 2023 12 08 - 23 35 15 49](https://github.com/RPCS3/rpcs3/assets/81812967/19ba2f4d-d6fd-4264-adba-744a9cb0d2ab)

The following seem to have no effect on it:

- Write/Read color buffers.
- Legacy shader mode.
- Strict rendering mode.
- Selecting OpenGL.

**System configuration**
CPU: i5-6600k
GPU: GTX 1070
Driver Version: 546.29

**Comment by Kelbitron** [comment]
I can confirm this is still happening

I have tried the steps above to no luck as well before I stumbled upon this post.

- Changing to OpenGL and removing all cached shaders to redo them
- Turning on Color Buffers
- Turning AA off/on
- Attempting other shader modes

**System configuration**
CPU: i3-12100f
GPU: RTX 3060 12gb
Driver Version: 555.85

**Other details**
RPCS3 Version: v0.0.32-16611-feff2ba0 Alpha

**Comment by RobbedColek** [comment]
Can confirm this is still an issue - game is otherwise playable.

**System configuration**
CPU: Ryzen 9 5900X
GPU: GTX 1080
Driver Version: 572.61

**Other details**
RPCS3 Version: 0.0.37-18143-335ed8d9 Alpha | master

**Comment by digant73** [comment]
please re-test on latest build. Hopefully some textures and reflections issues have been fixed by recent build 0.0.39-18790

**Comment by JumpingY** [comment]
> please re-test on latest build. Hopefully some textures and reflections issues have been fixed by recent build 0.0.39-18790
Unfortunately, the issue persists until the latest version is tested

**Comment by FrankyBuster** [comment]
This still happens on latest, and sometimes it results in missing environment lighting

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/42c16d1a-a680-49f2-baca-667af8249752" />

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/7ca45af3-715a-481f-bfb0-771e3cf94194" />

**Comment by FrankyBuster** [comment]
Here are two renderdoc captures of the issue in places where it happens most consistently, maybe that could help looking into fixing it

[Challenge medal shop](https://drive.google.com/file/d/1ZFtIWKWIU6Tq9mDYvbHlNkF__9q7Se-1/view?usp=sharing)
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/acb869a8-b532-4c1e-a273-c61639d3d726" />

[VR mission](https://drive.google.com/file/d/1E_GqqFpOci0tkF0Zc61uD3yY1hSs0Nj6/view?usp=sharing)
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/54769120-4ec4-4956-ba27-bdfb0450a7c5" />

I'm running the game on an AMD Ryzen 5 5600G with iGPU (runs pretty well for the most part).

**Comment by LoweysLitsman** [comment]
I've just tested and **enabling Write Color Buffers seems to solve the issue** for me, @FrankyBuster could you help confirm?

Normally all I have to do is go inside the VR Room and back to the Lobby by about 2 to 3 for this to trigger.
I've now done it like +10 times in a row and it hasn't happened.
<details><summary>Video Example without Write Color Buffers </summary>
<p>

https://github.com/user-attachments/assets/8d0ff081-5928-40d1-9ebf-72713434c16f

</p>
</details> 


We'll be able to close the issue and I'll update the wiki if you or anyone else confirms this solves it.
If not, do you have any info on how to reproduce the issue consistently?

Win11 25H2, i9-13900K, RTX 3080 616.56
[エクストルーパーズ \[NPJB00235\].log.gz](https://github.com/user-attachments/files/31703492/NPJB00235.log.gz)

https://github.com/user-attachments/assets/d8987bee-eb26-498a-b982-e76df24866bc

**Comment by FrankyBuster** [comment]
> I've just tested and **enabling Write Color Buffers seems to solve the issue** for me, [@FrankyBuster](https://github.com/FrankyBuster) could you help confirm?

I can confirm that on latest it does seem to fix the issue with the environment lighting and materials breaking after going in and out of the VR room/VR missions, but it doesn't fix the pitch white characters in the medal exchange menu.
