### ISSUE TITLE
Flickering textures in Ratchet & Clank Future: Tools of Destruction

### ISSUE THREAD

**Issue by EvilPlayer1** [RPCS3/rpcs3#13907]
### Quick summary

One of the old bugs, when some textures are glitching/flickering.

### Details

https://github.com/RPCS3/rpcs3/assets/90133207/078fc066-db91-4d58-9a81-e83993b382b6

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11548394/RPCS3.log)

### Attach capture files for visual issues

https://drive.google.com/file/d/1dwCz524248hZ0mu263rop2d2w8yJRRg2/view?usp=sharing

### System configuration

OS: Windows 11
CPU: i7-11700
GPU: GeForce GTX 1660 SUPER
GPU driver version: 531.79

**Comment by kd-11** [comment]
I think a savefile is more useful for debugging this.
Also:
1. Try enabling "read color buffers" option in the advanced tab.
2. Try enabling "force high precision Z" in the debug tab or config.yml to force better Z range on NVIDIA cards.

**Comment by Jonathan44062** [comment]
Here's my save file
https://www.mediafire.com/file/so3dfamynfz9eo6/BCUS98127_SAVE_1.rar/file

I try both options and sadly it is the same.
1.- Read color Buffers
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11655480/RPCS3.log.gz)

2.- Force High Precision Z
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11655544/RPCS3.log.gz)

**Comment by digant73** [comment]
@Jonathan44062, @EvilPlayer1 is that still an issue?

**Comment by EvilPlayer1** [comment]
> [@Jonathan44062](https://github.com/Jonathan44062), [@EvilPlayer1](https://github.com/EvilPlayer1) is that still an issue?

yes

**Comment by digant73** [comment]
@EvilPlayer1 please provide an update. Many bugs have been fixed in latest months

**Comment by alexconsole04** [comment]
I tested recently and it still occurs.

**Comment by digant73** [comment]
> I tested recently and it still occurs.

maybe disabling vertex cache helps?

**Comment by Jonathan44062** [comment]
Using disable vertex cache and Emulate Special Depth Comparison does not help either, still an issue

**Comment by digant73** [comment]
this issue is possibly the same present on other Insomniac games (Resistance FOM and Resistance 3). In R3 it seems almost fixed by enabling `Emulate Special Depth Comparison` although that setting produces some artefacts in other places as reported on issue #18880.

### scene in R3 with the flickering issue:

https://github.com/user-attachments/assets/091847de-f0a8-4944-ad0d-fcf4abdd83ca


### scene in R3 with Emulate Special Depth Comparison. See the artifacts (flickering shadows) on trees on the right of the screen:

https://github.com/user-attachments/assets/35499500-1169-4ea1-a34a-c7ca1ab3a45a

**Comment by alexconsole04** [comment]
<img width="2560" height="1401" alt="Image" src="https://github.com/user-attachments/assets/ba9d77e9-d692-4bf9-88fb-c098335d3500" />
Recent PR does not fix this issue.
