### ISSUE TITLE
MX vs. ATV: Untamed Lighting Issue

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#14045]
### Quick summary

The game lighting is broken compared to the hardware

### Details

Rpcs3:
![NPUB90056_screenshot_2023_06_18_06_59_44](https://github.com/RPCS3/rpcs3/assets/71127352/91fb3027-6d90-4e40-b20c-a2978c795284)

Ps3:
https://youtu.be/Y_DgzWpAfNk?t=11076

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11780765/RPCS3.log.gz)

### Attach capture files for visual issues

https://drive.google.com/file/d/16_xXNWE2SwcDyzNiDxqzNX-OGVaBVlzX/view?usp=sharing

### System configuration

RPCS3 v0.0.27-14905-bb8e43f1 Alpha | master | FW 4.88 | 5.15.106-1-MANJARO
AMD Ryzen 5 2600 | 12 Threads | 15.95 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 3060 Ti (530.41)

**Comment by Asinin3** [comment]
Did you test settings e.g the write color buffers option, other buffer settings on advanced tab, strict mode etc and see if it helps?

**Comment by Triticum0** [comment]
Tested using that setting it made no difference

**Comment by Triticum0** [comment]
Retested and there was no change. Using other buffers + Cpu Blits
build (v0.0.30-15912-bc141831)

**Comment by Triticum0** [comment]
Retested and there was no change. Using all buffers
RPCS3 Version: 0.0.38-18261-3c1ebe9f Alpha | master

**Comment by Triticum0** [comment]
Also foliage shading also doesn't match hardware

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/5464c4c7-f467-4e5b-9cb6-66feb0f5e451" />

Hardware
https://www.youtube.com/watch?v=syhHZsP5siM

**Comment by digant73** [comment]
please re-test on latest build. Hopefully some textures and reflections issues have been fixed by recent build 0.0.39-18790

**Comment by Triticum0** [comment]
No change

**Comment by ShadowH69** [comment]
> No change

@Triticum0 any other issues remain with the game? since the new PR?

**Comment by Triticum0** [comment]
Fixed by #18627 but has regression on Kittery point character sprites 

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/f4cce609-7b00-4e9d-8063-9437db8d223c" />

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/172c76eb-1c4c-40da-809b-25549730e0ad" />

**Comment by digant73** [comment]
regressed by #18627 or another PR?

**Comment by Triticum0** [comment]
No, haven't found out what pr caused it yet

**Comment by Triticum0** [comment]
superseded by #18637
