### ISSUE TITLE
Dead or Alive 5: Last Round - Water wave effect broken

### ISSUE THREAD

**Issue by antoniodesousa** [RPCS3/rpcs3#14058]
### Quick summary

The water wave effect that appears in some stages is not rendering at all. It's specially visible in the beach stage.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11799003/RPCS3.log.gz)

### Attach capture files for visual issues

![002-min](https://github.com/RPCS3/rpcs3/assets/10920974/c38160d7-1d36-4f71-adeb-353df77bfe5a)

### System configuration

RPCS3 Version: 0.0.28-15215-073b723c Alpha | master | FW 4.90
CPU: Ryzen 6900HX
GPU: Radeon RX 6600m
RAM: 64GB
SSD: 2TB
OS: Windows 11 Pro 22H2

**Comment by FlexBy420** [comment]
Is this still an issue?

**Comment by antoniodesousa** [comment]
I just tested it using the latest release as of today RPCS3 Version: 0.0.33-17046-3e516df2. Still the same as before.

![FPS_ 30 75 _ Vulkan _ 0 0 33-17046 _ DEAD OR ALIVE 5 Last Round  BLJM61258  19_10_2024 21_08_48](https://github.com/user-attachments/assets/83872460-7eff-4077-a07b-9c4d4c3ae670)

**Comment by scju** [comment]
> I just tested it using the latest release as of today RPCS3 Version: 0.0.33-17046-3e516df2. Still the same as before.
> 
> ![FPS_ 30 75 _ Vulkan _ 0 0 33-17046 _ DEAD OR ALIVE 5 Last Round  BLJM61258  19_10_2024 21_08_48](https://github.com/user-attachments/assets/83872460-7eff-4077-a07b-9c4d4c3ae670)

Why do they have dark lines on their faces?

**Comment by mosin311aa** [comment]
> > I just tested it using the latest release as of today RPCS3 Version: 0.0.33-17046-3e516df2. Still the same as before.
> > ![FPS_ 30 75 _ Vulkan _ 0 0 33-17046 _ DEAD OR ALIVE 5 Last Round  BLJM61258  19_10_2024 21_08_48](https://github.com/user-attachments/assets/83872460-7eff-4077-a07b-9c4d4c3ae670)
> 
> Why do they have dark lines on their faces?

Some form of other rendering issue

**Comment by digant73** [comment]
is that still an issue?

**Comment by mosin311aa** [comment]
> is that still an issue?

I didnt experience this particular bug, however this still exists https://github.com/RPCS3/rpcs3/issues/14058#issuecomment-2626573979

**Comment by antoniodesousa** [comment]
Yes, still the same.

![Image](https://github.com/user-attachments/assets/ac0e211b-0801-451b-aef5-bcbee99526c5)

[RPCS3.log.gz](https://github.com/user-attachments/files/23136081/RPCS3.log.gz)

**Comment by FlexBy420** [comment]
Possibly fixed by #18224 Please retest.

**Comment by antoniodesousa** [comment]
Sadly, still the same. Everything renders fine except that there're no waves or movement at all. It's just plain flat. It seems fine in the distance though.

![Image](https://github.com/user-attachments/assets/76519e76-3d59-425a-89ad-2e6c7debc90e)
[RPCS3.log.gz](https://github.com/user-attachments/files/25698399/RPCS3.log.gz)

**Comment by digant73** [comment]
please try if the issue is fixed by latest build 0.0.41-19450

**Comment by antoniodesousa** [comment]
Still the same.

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/4534a6fb-8ecb-4a9a-a167-a7b33698e61d" />
