### ISSUE TITLE
[Regression] After Burner Climax - Crashing on menu (#13875)

### ISSUE THREAD

**Issue by andylowemedia** [RPCS3/rpcs3#14199]
### Quick summary

Running After Burner Climax on RPCS3 on an Apple M1 MAX. It was working fine and then after an update it crashes at the menu screen.

### Details

Running After Burner Climax on RPCS3 on an Apple M1 MAX. It was working fine and then after an update it crashes at the menu screen. I'm not aware of which build it was where it worked. This is the following output from the log console:

<details><summary><h3>Log Output</h3></summary>
<pre>
- SYS: RPCS3 v0.0.28-15353-a828c214 Alpha | master
- SYS: VirtualApple @ 2.50GHz | 10 Threads | 64.00 GiB RAM | TSC: 1.000GHz
- SYS: Operating system: macOS, Version: 13.4.1
- SYS: Current Time: 2023-07-14T17:32:51
- RSX: Found vulkan-compatible GPU: 'Apple M1 Max' running on driver 0.2.988
- SYS: Firmware version: 4.90
S PPU: Enabled: Non-Java Mode Fixup
E PPU: Can't build instruction VSL
E PPU: Can't build instruction VSR
- RSX: Found vulkan-compatible GPU: 'Apple M1 Max' running on driver 0.2.988
E RSX: Your GPU driver does not support some required MSAA features. MSAA will be disabled.
E RSX: Your GPU does not support double precision floats in shaders. Graphics may not render correctly.
E RSX: Your GPU does not support depth bounds testing. Graphics may not render correctly.
E RSX: Your GPU does not support wide lines. Graphics may not render correctly.
E RSX: Your GPU does not support framebuffer logical operations. Graphics may not render correctly.
E RSX: Apple GPUs are incompatible with the current implementation of asynchronous texture decoding.
S HID: DualShock 4 Controllers found: 1
S Input: The pad mode was changed to Single-threaded
S Input: DualShock 4 device 0 connected
S GUI: Boot successful.
S PPU: LLVM: Loaded module v6-kusa-tGrUK85GgkjarnCtdio3Hi-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-SJosc8dabnwYWRyg4hzy6K-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-YACwz9mp0LKby91qqMqnJf-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-rR58yW7wntyEUaaRnNRX64-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-Mng8QYJ17JLYV0LKWxuCFF-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-RLfdnuv9X6PmvCJeSHSfUz-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-SRsedLsWygvYbsrNETuLfT-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-jQFk54Zki7Jco12kN7gGU2-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-Yq4vk1XAffxYFdCsChacVe-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-6GGVLWxuAUsakv9y3Pk6AW-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-dKJ4djccYM3GhcYUd7CaAh-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-Ezhz0zW5z8c7fq1i9wXs3j-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-qUgYjxtm4XJ8vqC0doWYwW-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-hTte0ixgNY8NwQ2jmspw1W-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-Q1UAGNaSzv1kRE9gHMTmW0-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-maK74F7CYYPEvQVks4eAQp-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-fPV0TkFaMMytfLExV0ZiX9-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-gC6jTYZhHMArf7405QWw9E-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-mFJJxHZVmuuFxjx2hCp0Ns-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-5N5bYWKN3s78qcu5whxQFd-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-dLQReLYrbAUjVZvCdXFTJj-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-8RJYPuo0KycY4V3xoC2sgb-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-FKGhd4HMnv6iAeSsxQvumV-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-AW1pKNRuyE95HXAH4QJHzd-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-AtVqtVGWVgUQqkG3wfdvrG-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-kLbQZHXsHZwtH1AtCYMdzf-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-7aewFgCL3gA2fQ8ag56LYL-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-cxxhk3cpswg4NzCM0ZAaqo-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-CZMuza8guboFv9s5dniPMv-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-TbfjiqeCNzcW8zU7wP6ZaJ-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-WuNpLPkxoEvFPeJv4bEUdz-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-A23rUvfFfeP0AN0tgohbd4-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-S1ijgrg54SzXvfSm91Ux4V-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-5AFNHSmA6wSVkqtbJuMcYV-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-h3ngGPYsxrpbikYe9Lzp8m-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-j6TvkM4mqV3HwG2GgTSkvL-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-JzeWEng62G75JsXVYp00mG-00001G-westmere.obj
S SPU: SPU Runtime: Built the interpreter.
S SPU: SPU Runtime: Built 1248 functions.
U sys_prx TODO: _sys_prx_register_module(name=“cellProcessElf”, opt=*0xd0058ce0)
S PPU: LLVM: Loaded module v6-kusa-1z3Pyu8YVnnorJiQ2hfu1e-00001G-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsysmodule.sprx” (id=0x23000b00)
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x1, a2=0x1, a3=0xd0058a50)
E SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x2, a2=0xd0058a50, a3=0x0)
S PPU: LLVM: Loaded module v6-kusa-XCgQWMc1s99n1WTwrpWvw4-00001G-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libgcm_sys.sprx” (id=0x23000e00)
S PPU: LLVM: Loaded module v6-kusa-1Au1tg93M0j9aPxhbpVJAC-00001G-westmere.obj
S PPU: LLVM: Loaded module v6-kusa-5MR5UPWcNoRKHsUNJqHbKV-00001G-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsre.sprx” (id=0x23001100)
U sys_prx TODO: _sys_prx_register_module(name=“_sysProcessElf”, opt=*0xd0058df0)
S PPU: LLVM: Loaded module v6-kusa-ZAhea3FFhakpfMa36ZvaNx-00001G-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/librtc.sprx” (id=0x23002f00)
S PPU: LLVM: Loaded module v6-kusa-fLV79QqHgPi90UziTsWrHo-00001G-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libfs.sprx” (id=0x23003000)
S PPU: LLVM: Loaded module v6-kusa-UnNP3fZh95wiCGy3Q0csRy-00001G-westmere.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libresc.sprx” (id=0x23004600)
U cellNetCtl TODO: cellNetCtlAddHandler(handler=*0x4d7088, arg=*0x0, hid=*0x14ff950)
E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPEB00175/USRDIR/dev_hdd0/game/NPEB00175/USRDIR/rom/adx/voice.afs” [1]
E SYS: 'cellSaveDataFixedLoad2' failed with 0x8002b401 : CELL_SAVEDATA_ERROR_CBRESULT [1]
E SYS: 'cellMsgDialogAbort' failed with 0x8002b302 : CELL_MSGDIALOG_ERROR_DIALOG_NOT_OPENED [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPEB00175/USRDIR/dev_hdd0/game/NPEB00175/USRDIR/rom/adx/ABC_HIRO_LOOP.adx” [1]
E SYS: 'sys_ppu_thread_join' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: 'sys_ppu_thread_join' failed with 0x80010005 : CELL_ESRCH [2]
E SYS: 'sys_ppu_thread_join' failed with 0x80010005 : CELL_ESRCH [3]
E RSX: Format incompatibility detected, reporting failure to force data copy (VK_FORMAT=0x7C, GCM_FORMAT=0x83)
F {RSX [0x05166b0]} SIG: Thread terminated due to fatal error: Verification failed
(in file /private/var/folders/76/zy5ktkns50v6gt5g8r0sf6sc0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/VKTexture.cpp:64[:3], in function copy_image_to_buffer) (errno=316=Unknown error: 316)
</pre>
</details>

### Build with regression

v0.0.27-15033-e1744cea

### Attach two log files

Error
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12052281/RPCS3.log)
Working
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12052449/RPCS3.log)

**Comment by Asinin3** [comment]
I don't think you have actually tested this for regressions properly. You state that the build with regression is 15033, but that PR was just a change to the debugging tools. Have you actually confirmed which build breaks it? Use https://rpcs3.net/compatibility?b&p=5 Go to old builds and narrow down exactly what build causes the issue.

Don't go one build at a time, go back months at a time until you find where it starts to work again. Then go in-between where it worked and broke until you narrow down exactly what build caused the issue.

**Comment by andylowemedia** [comment]
Thanks for the comment, I did this however there are many skipped Mac builds between 0.0.27-15005 and 0.0.27-15033 and the two in between, builds 0.0.27-15008 and 0.0.27-15015, wouldn't even load a game list. Now I can't load any of the other builds as my setup if is Mac only, and when it was noted that the logs were needed for in game and so I supplied the best I could there. I did make it clear that this error was only on the Mac M1 Max. However if this means that the regression can not be found as you need to identity which build it was in between the available Mac builds then I understand.

**Comment by Asinin3** [comment]
If you've narrowed it down, thats good enough. "between 0.0.27-15008 and 0.0.27-15015," is good info. Before you only listed one build with nothing stating if t happened around that time, for all we knew it could've happened months prior.

If I had to make a guess, I would say its probably caused by https://github.com/RPCS3/rpcs3/pull/13875 . But it might be something else. Did you clear all caches etc when testing newer build?

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/13875 added the checks to catch this type of error. Previously it would have silently sent the incorrect dimensions to the hardware and caused some random device lost errors on NVIDIA.

**Comment by andylowemedia** [comment]
> If you've narrowed it down, thats good enough. "between 0.0.27-15008 and 0.0.27-15015," is good info. Before you only listed one build with nothing stating if t happened around that time, for all we knew it could've happened months prior.
> 
> If I had to make a guess, I would say its probably caused by #13875 . But it might be something else. Did you clear all caches etc when testing newer build?

Everytime I try a new build, I always cleared the caches. I even tend to that every time I update to the latest build as well.

**Comment by kd-11** [comment]
I'm unable to reproduce any crashing. What are you doing in the menus to trigger the crash?

**Comment by andylowemedia** [comment]
Nothing, it just happens as soon as the start menu happens, sometimes I can press start sometimes not. It just crashes. Always with the same error that I posted.

**Comment by andylowemedia** [comment]
One thing I have noticed is that in the logs:
" /private/var/folders/76/zy5ktkns50v6gt5g8r0sf6sc0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/VKTexture.cpp"
This file doesn't exist in my file system.

**Comment by kd-11** [comment]
> One thing I have noticed is that in the logs: " /private/var/folders/76/zy5ktkns50v6gt5g8r0sf6sc0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/VKTexture.cpp" This file doesn't exist in my file system.

It just means it existed on the cloud machine that compiled your build.

**Comment by Asinin3** [comment]
Working here on Windows atleast.

**Comment by Satan86** [comment]
Should be fixed by #14446

**Comment by andylowemedia** [comment]
Still doesn't work with the exact same error at the exact same time, as of testing build 0.0.29-15476. I had cleared all of the caches in the menu.

**Comment by andylowemedia** [comment]
Any progress with this?

**Comment by zardozerr** [comment]
Unfortunately as of the latest build, 0.0.34-17528-fe1fd862, this game still doesn't work.

It crashes trying to load a game after the title screen:
F {RSX [0x0065524]} SIG: Thread terminated due to fatal error: Verification failed (object: 0x0)
(in file /Users/runner/work/1/s/rpcs3/Emu/RSX/VK/VKTexture.cpp:63[:3], in function 'void vk::copy_image_to_buffer()') (errno=316=Unknown error: 316)

Machine is a mbp M1 Max, on latest Sequoia 15.3.1

**Comment by RussDCA** [comment]
Adding my voice to this.

Had RPCS3 installed on my M1 Mac mini (16gb) then _one day_ the game couldn't get past the menu screen. You can sit as long as you like on the initial "After Burner Climax - Press Start Button" screen. I don't game a lot, just kick back every now and then so I sat on this assuming it'd be re-fixed again at some point.

My steps are then to:

1. Press Start
2. Either load my save game or not, the outcome is the same
3. Game freezes

Tested a lot today on my a M4 Mac mini Pro (20 core with 64gb memory, Sequoia 15.4.1) and using 0.0.36-17947.

Like @andylowemedia, I went back over previous versions to narrow down where the game stopped running and after checking 20 or so versions, I ended up with this:

- rpcs3-v0.0.27-15005-8e15afb2_macos (After Burner **Working**)
- rpcs3-v0.0.27-15008-c70338a9_macos (No games listed in the UI)
- rpcs3-v0.0.27-15015-a1e19e1c_macos (No games listed in the UI)
- rpcs3-v0.0.27-15033-e1744cea_macos (After Burner **Not Working**)

There are many other builds in between these, but not for the Mac.

If you prepare yourself to hit buttons fast, you can:

1. Press Start
2. Either load a save or not
3. Reach the Aircraft select screen
4. Hear the sample "Select Aircraft"
5. And the screen locks here (screenshot)

But that's as far as I can get it.

<img width="1625" alt="Image" src="https://github.com/user-attachments/assets/c559dd6d-5005-455c-836a-b3e48f523fe8" />

**Comment by RussDCA** [comment]
A minor update. Just installed RPCS3 0.0.37-18022.

As previously mentioned, I don't game often so I've not tested any versions between my last comment and this one.

However, something's changed. The game is still crashing at the same point, but rather than a lock up, the window simply closes and I see the "RPCS3 has quit unexpectedly" window.

**Comment by marus70** [comment]
This issue remain in last release 18263.

Apple M4
32 GB RAM
Mac OS Sequoia 15.6.1

[RPCS3.log](https://github.com/user-attachments/files/23159731/RPCS3.log)
[RPCS3.log.gz](https://github.com/user-attachments/files/23159730/RPCS3.log.gz)

**Comment by digant73** [comment]
is that still an issue? please retest.

**Comment by andylowemedia** [comment]
I havent been able to test with any new for several months thanks to the LLVM. I keep getting crashes on the recompiler.

[crash.txt](https://github.com/user-attachments/files/25374156/crash.txt)

So can;t give you an answer

**Comment by RussDCA** [comment]
> is that still an issue? please retest.

Just installed 0.0.39-18794 (2026-02-15 19:04:56) on my Mac and I have a crash. No frozen screen like the screenshot above, the emu just bombs out and all windows close.

Second attempt, I hammered the Start and X buttons to see if I could somehow jump over/fool the issue (tried this in earlier versions too). I managed to hear "Select aircraft", but the crash happened again.

**Comment by andylowemedia** [comment]
I have managed to get my install of RPCS3 workign again. And I concur with @RussDCA i get the exact same issue. The only difference originally it would just hang, now it crashes and closes all windows. Happens everytime at approximatley the same place.

**Comment by marus70** [comment]
> > is that still an issue? please retest.
> 
> Just installed 0.0.39-18794 (2026-02-15 19:04:56) on my Mac and I have a crash. No frozen screen like the screenshot above, the emu just bombs out and all windows close.
> 
> Second attempt, I hammered the Start and X buttons to see if I could somehow jump over/fool the issue (tried this in earlier versions too). I managed to hear "Select aircraft", but the crash happened again.

Same here, a bit better now. I'm attaching the o.s. log after crash if needed.
Apple M4 Sequoia 15.7.3
rpcs3 18794 arm

[apple log.txt](https://github.com/user-attachments/files/25401445/apple.log.txt)

**Comment by andylowemedia** [comment]
Hi Just htought i would mention as  0.0.42-19922-0a85b394 Afterburner Climax is working on my Macbook Pro M1 MAX so i don;t know if it was an intentional fix or whether it was a side effect of something else, but thought I would mention it.

**Comment by RussDCA** [comment]
> Hi Just htought i would mention as 0.0.42-19922-0a85b394 Afterburner Climax is working on my Macbook Pro M1 MAX so i don;t know if it was an intentional fix or whether it was a side effect of something else, but thought I would mention it.

I think this has been prematurely closed with just the one report of the game now loading. Just tried myself and for me it's crashing even earlier now, right in the final stages of building the SPU cache. During this version 19923 popped up and still getting the same crash with the SPU build.

If I find time over the weekend, I'll kill all files and do a fresh install, but I'm not overly hopeful.

**Comment by marus70** [comment]
I can confirm 19922 ARM now working on my M4, not tried 19923.

**Comment by RussDCA** [comment]
Tested today on 19985 and I have success here.
