### ISSUE TITLE
DX12: 'SampleLevel': implicit truncation of vector type

### ISSUE THREAD

**Issue by B1ackDaemon** [RPCS3/rpcs3#1421]
Discovered in game Shoot Many Robots (NPUB30600)
http://www.emunewz.net/forum/showthread.php?tid=169135&pid=228969#pid228969

```
E {rsx::thread} Unimplemented TEX_SRB instruction: UPB
E {rsx::thread} FS build failed:D:\rpcs3\FragmentProgram.hlsl(80,9-79): warning X3206: 'SampleLevel': implicit truncation of vector type
D:\rpcs3\FragmentProgram.hlsl(81,9-89): warning X3206: 'SampleLevel': implicit truncation of vector type
```

**Comment by vlj** [comment]
can you share all FragmentProgramX.hlsl in bin/ folder after the error has been met ?

**Comment by B1ackDaemon** [comment]
@vlj, done http://rghost.ru/6JSLXJF7n

**Comment by tambry** [comment]
@B1ackDaemon Fixed by #1439?

**Comment by B1ackDaemon** [comment]
@tambry , still occurs on recent master build (PR #1447)
Log: http://rghost.ru/7xj8ppQbD

**Comment by tambry** [comment]
Probably the fault of the unimplemented UPB (Unpack Byte?) shader instruction in DX12, then.

**Comment by raven02** [comment]
UPB should be implemented here - https://github.com/RPCS3/rpcs3/pull/1764 .

Does it help?

**Comment by raven02** [comment]
In 0.0.0.9 , it cannot bootup even with libsre.sprx.elf

{PPU[0x4] Thread (main_thread) [0x00c5e8d0]} struct vm::access_violation thrown: Access violation reading address 0x10

**Comment by raven02** [comment]
I'm closing it and put it to 0.0.0.9 regression list.
