### ISSUE TITLE
Watch Dogs - Controller doesn't stop rumbling

### ISSUE THREAD

**Issue by Ordinary205** [RPCS3/rpcs3#14246]
### Quick summary

Using the controller while playing this game, seems to continuously non-stop vibrate.

### Details

This triggers the bug when driving vehicles, jumping over high obstacles, or getting near to explosives.
I'm not really sure if this only happens on XInput controllers.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12138110/RPCS3.log.gz)

### System configuration

AMD Ryzen 5900X 12-Core Processor | 24 Threads | 15.89 GiB RAM | RTX 3080 driver 536.67.0.0 | Windows 10 Pro 22H2

**Comment by Ordinary205** [comment]
The best way to fix this, is by reconnecting the controller or disabling the vibrations on the gamepad configuration.

**Comment by Megamouse** [comment]
Please test again

**Comment by SlyCooperReloadCoded** [comment]
Oh good there's an open issue for this.  Yes, this is still an issue as of 0.0.34-17438.

**Comment by digant73** [comment]
the issue is possibly fixed by #16963 recently merged. A retest is welcome

**Comment by Bobble80** [comment]
> the issue is possibly fixed by [#16963](https://github.com/RPCS3/rpcs3/pull/16963) recently merged. A retest is welcome

It didn’t fix the same constant vibration issue in both Amazing Spider-Man games unfortunately. It’s still present after yesterday’s update.

**Comment by digant73** [comment]
Please test if the attached `rpcs3.exe` is working and attach your `rpcs3.log`.
You can use, XInput, SDL, DS3 or Dualsense pad handlers.

[rpcs3.zip](https://github.com/user-attachments/files/22244493/rpcs3.zip)
