### ISSUE TITLE
Improve `--no-gui`

### ISSUE THREAD

**Issue by Anuskuss** [RPCS3/rpcs3#14255]
- [x] **Bug**: After selecting a game in *Tom Clancy's Splinter Cell Trilogy* you'll get notified that "This game saves data automatically at certain points. Do not switch off the power when the HDD access indicator is flashing." This notifications does not show up in NoGUI, thus softlocking the emulator.
- [x] **Bug**: NoGUI (or rather CLI launching) makes game intros lag massively. I don't know what else this affects but that's what I noticed right away. Doesn't happen when games are launched from the games list.
- [x] **Feature Request**: Speaking of games with internal launchers, when changing the main executable (e.g. from launcher to game or back), RPCS3 will spawn another window. This ruins the immersion (you'll see your desktop or whatever window is underneath for a split second) or worse yet, my DE sometimes thinks that my emulator launcher is frozen and ask me if I want to kill it. It would be better to just reuse the window.
- [ ] **Feature Request**: Another annoying thing about multi-title games is that it needs to (re)build the PPU/SPU cache everytime you change the main executable. It would be preferable to just build all caches of all (sub-) titles at the start of the game. There's already the *PPU LLVM Precompilation* option but that doesn't cover this case currently.
- [ ] **External bug**: Starting with GNOME 44, RPCS3 won't start games in fullscreen anymore. Fullscreen can be triggered manually though. This should probably be fixed in GNOME but it's a bug so I'll report it here for completeness sake.

**Comment by MrGrosNounours** [comment]
On Ubuntu, RPCS3 is crashing when i launch a game from a compilation in no-gui mode.

**Comment by AniLeo** [comment]
I can reproduce the full-screen bug on GNOME 44.3

**Comment by Anuskuss** [comment]
> 5. **External bug**: Starting with GNOME 44, RPCS3 won't start games in fullscreen anymore. Fullscreen can be triggered manually though. This should probably be fixed in GNOME but it's a bug so I'll report it here for completeness sake.

Found this in my log when trying to start a game (not fullscreen):
```
E RSX: Swapchain: Swapchain creation failed because dimensions cannot fit. Max = 1920, 1050, Requested = 1920, 1080
E RSX: Swapchain: Swapchain creation failed because dimensions cannot fit. Max = 1280, 690, Requested = 1920, 1050
```

**Comment by elad335** [comment]
Fixed?

**Comment by Anuskuss** [comment]
The first point seems to be fixed and the second might have been an issue on my end but I'm not entirly sure.
GNOME will still not start in fullscreen and is at v46.2 now so I don't think it will magically solve itself. It works in GNOME Wayland though.

**Comment by Megamouse** [comment]
I think none of the remaining issues presented here are related to the main issue.
And since random issue compilations like this don't get any traction, I'll close this.
Feel free to open new issues if necessary

**Comment by Anuskuss** [comment]
Well the 5th point is only semi fixed because it doesn't work in X11, although since Wayland is the future and since X11 support will probably get dropped at some point it'll "fix itself". I personally no longer boot into X11 so I don't care but I don't know maybe you guys do.
As for the 4th point, that's definitely still relevant so I'll create a separate issue for it.
