### ISSUE TITLE
[Regression] SOCOM CONFRONTATION Texture bug and sound bug

### ISSUE THREAD

**Issue by Sapelain** [RPCS3/rpcs3#14259]
### Quick summary

The Spectator mode problem was corrected but the image has color errors and sound is locked. Rather, it goes very badly. It may be that it is now unfriendly with the sound card (Sound Blaster Z) now.

### Details

![BCES00173_screenshot_2023_07_24_20_25_15](https://github.com/RPCS3/rpcs3/assets/126752527/1d5b4d83-581a-4523-9f12-a2951dcf0c0d)
![BCES00173_screenshot_2023_07_24_20_35_15](https://github.com/RPCS3/rpcs3/assets/126752527/ebbbfd74-5024-4cf4-95f2-166173fe7875)

### Build with regression

v0.0.28-15397-94bb75fb

### Attach two log files

https://mega.nz/file/yCBVlCwY#LYM0rpUDa3bGqd-F9VZw7g1CF7j-Fg2H5aFa2iMfFVQ

### System configuration

RPCS3 v0.0.28-15391-782344ee Alpha | master
Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz | 8 Threads | 15.94 GiB RAM | TSC: 3.500GHz | AVX+ | FMA3
GPU: 'AMD Radeon RX 580 2048SP' running on driver 2.0.270
Sound card: Sound Blaster Z
Operating system: Windows, Major: 10, Minor: 0, Build: 19045, Service Pack: none, Compatibility mode: 0

**Comment by AniLeo** [comment]
- RPCS3 version "RPCS3 v0.0.28-14239" doesn't exist
- Missing second log file from the last good version before the one that introduced the regression

**Comment by Sapelain** [comment]
Here is a reference to a previous case that was solved and without failures. Everything perfect
RPCS3 v0.0.28-15372-38a5313e
https://github.com/RPCS3/rpcs3/issues/14242

I will do a full log and Capture that I leave here :

RPCS3 v0.0.28-15397-94bb75fb

https://mega.nz/file/rPo0xCBD#bobn1jqtc7bM0PkZL4AIan_fvOSHIoR2u9SyK3T50oE
https://mega.nz/file/jXgQjQDb#CdFCgV2h-JCVzsIwqIIL5vGr1YQbKi1DGio6Ftp2YdQ

**Comment by AniLeo** [comment]
There's many builds between the 2 you mentioned. The build you flagged (v0.0.28-15397) could have not introduced the regression as it only changes sceNpTrophy code, so your report is still invalid.

**Comment by sebringers** [comment]
Users are still experiencing issues. since these are really old and overdue is it possible to receive a status update on this?
