### ISSUE TITLE
 Warhawk bug graphics 

### ISSUE THREAD

**Issue by Sapelain** [RPCS3/rpcs3#14365]
### Quick summary

The clouds blink into giant black squares. I leave a video of me and another person who passes the same to him

### Attach a log file

https://mega.nz/file/vKYnjBQB#oMWI9Fk2WlP6tLKBTSD0qeqY_aVuU9w6ZntC3ndFq6Y

### Attach capture files for visual issues

https://mega.nz/file/yfhAEQqa#dmYqYXbyFkiPXfutQNEngXhtA7eGiLaiIFPK7mc-I24
https://www.youtube.com/watch?v=MRXYqKTVDyM

### System configuration

RPCS3 v0.0.28-15395-bc40b61e Alpha | master
Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz | 8 Threads | 15.94 GiB RAM | TSC: 3.500GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 19045, Service Pack: none, Compatibility mode: 0
GPU: 'AMD Radeon RX 580 2048SP' running on driver 2.0.270 Driver: AMD 23.7.1

**Comment by AniLeo** [comment]
Missing RSX or RenderDoc capture file, uploaded file is not a frame capture

**Comment by Sapelain** [comment]
![1](https://github.com/RPCS3/rpcs3/assets/126752527/58bb6df1-36e5-40b7-bd51-4388db212b79)
![2](https://github.com/RPCS3/rpcs3/assets/126752527/1144d83b-0cd3-4412-ab9b-ddd35a341bf6)
![3](https://github.com/RPCS3/rpcs3/assets/126752527/fded31dd-9e3a-41f4-980f-0d41761c39d8)

**Comment by AniLeo** [comment]
Removed the random UI screenshots, that's not adding any information since all setting values are present in the log file

**Comment by Sapelain** [comment]
RenderDoc doesn't work for me.
This is the maximum I get.
![BCES00008_screenshot_2023_07_25_13_30_25](https://github.com/RPCS3/rpcs3/assets/126752527/e2a61230-cec8-4b31-a9fd-9249f3f6b915)
![BCES00008_screenshot_2023_07_25_13_30_52](https://github.com/RPCS3/rpcs3/assets/126752527/a6dd5028-125a-423e-9dd7-f8a88664d3eb)

**Comment by AniLeo** [comment]
As explained in the issue template, you don't have to use RenderDoc, RSX capture is easier from inside the emulator
Did you not read the template before writing into the fields?

**Comment by Sapelain** [comment]
I had not read it carefully, I will correct this and the other one that I have open.  I'm sorry.

**Comment by nathub** [comment]
I'd like to comment I am having the same issue.
If I can contribute data to help find the issue let me know.
Sorry I don't know common practices here, I found this thread via google. I can't find other reports of this yet.

I also can't tell if this is a new issue or not, I haven't played Warhawk in like 6 months. I don't remember this issue being there before but I can't be sure.

**Comment by Sapelain** [comment]
You can add your catch with the RSX. Do an RSX Capture with RPCS3 in the moment and put it on.

**Comment by TheOldManAndTheC** [comment]
I'm also having the same issue.  After narrowing down which builds have the issue, it seems that it was introduced in build 0.0.28-15304, which only modified a single MSAA shader as a fix for Gran Turismo headlights.  This build and all newer builds I tested have the same problem, while 0.0.28-15303 works fine.
The commit in question is here:
https://github.com/RPCS3/rpcs3/pull/14130/commits/5fbab4590b095dd5a91a59b637dd6ec5da0d0ae6
Hope this helps.

**Comment by Sapelain** [comment]
Typical. You fix a problem and you break several things along the way inadvertently

**Comment by stcbus** [comment]
I was seeing clouds starting as black in 0.0.27 on my Mac actually.

**Comment by Tha14** [comment]
@kd-11 Could you please have another look at this when you can? After the recent RPCN update warhawk players cannot use the older builds to play without the graphical artifacts.
https://github.com/RPCS3/rpcs3/commit/465c42170704e6f03d8f550b27635be6efb65103

**Comment by Tha14** [comment]
I've compiled the 0.0.27 version in which the problem does not exist yet and updated RPCN so you can use this until the problem is completely fixed in RPCS3 master:
https://github.com/Tha14/rpcs3/releases/tag/WARHAWK_0.27

**Comment by Noodlez1232** [comment]
Is there any way this can get some more visibility? I think a regression in a game is pretty important to revert, right?

**Comment by stcbus** [comment]
> Is there any way this can get some more visibility? I think a regression in a game is pretty important to revert, right?

I concur, please fix this.

**Comment by ZyriBlackwood** [comment]
> I've compiled the 0.0.27 version in which the problem does not exist yet and updated RPCN so you can use this until the problem is completely fixed in RPCS3 master: https://github.com/Tha14/rpcs3/releases/tag/WARHAWK_0.27

This link appears broken can you provide another?

**Comment by cmese** [comment]
Still has the same issue with the newest version of RPCS3. Clouds are black squares. Turning Read Color Buffers on in Advanced GPU removes the black squares but the clouds become erratic so the game is still unplayable. Any updates on this?

**Comment by Noodlez1232** [comment]
Still broken here. Can we please get a revert? It's so much more important that a game is unplayable than it is that Gran Turismo has more accurate headlights.

**Comment by stcbus** [comment]
THIS!

**Comment by kd-11** [comment]
This one went under the radar and I forgot about it. It's a simple fix, I'll push something in a few hours.

**Comment by kd-11** [comment]
It's fixed by https://github.com/RPCS3/rpcs3/pull/15743

**Comment by ManGuyNY** [comment]
I am still having this issue on the current build. 

**Log file:**
[RPCS3.log.gz](https://github.com/user-attachments/files/16423252/RPCS3.log.gz)

**RSX Capture:**
[BCUS98117_20240730025735_capture.rrc.gz](https://github.com/user-attachments/files/16423463/BCUS98117_20240730025735_capture.rrc.gz)

![Screenshot 2024-07-30 025802](https://github.com/user-attachments/assets/19e19b15-18aa-4262-b8a8-2dad1e3329de)
