### ISSUE TITLE
[Regression] Unable to boot games on Linux

### ISSUE THREAD

**Issue by cipherxof** [RPCS3/rpcs3#14409]
### Quick summary

After the update to qt6 I am no longer able to boot any games on Arch Linux.

https://github.com/RPCS3/rpcs3/pull/12471

### Details

![image](https://github.com/RPCS3/rpcs3/assets/5994581/35a270c3-45b2-41cf-98fb-d4af004c6055)

### Build with regression

v0.0.29-15420-ef12da77

### Attach two log files

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12234529/RPCS3.log)

### System configuration

RPCS3 v0.0.29-15420-ef12da77 Alpha | master
12th Gen Intel(R) Core(TM) i7-12700KF | 16 Threads | 31.16 GiB RAM | TSC: 3.610GHz | AVX-512+ | FMA3
Operating system: POSIX, Name: Linux, Release: 6.2.6-273-tkg-cfs, Version: #1 SMP PREEMPT_DYNAMIC TKG Wed, 15 Mar 2023 23:53:12 +0000
Qt version: Compiled against Qt 6.5.0 | Run-time uses Qt 6.5.0

**Comment by AniLeo** [comment]
Cannot reproduce

![image](https://github.com/RPCS3/rpcs3/assets/10283761/c0d0c4f5-d8ed-430e-ac65-3554a6b6d481)

Linux 6.4.7
Manjaro 23.0.0
X11
GNOME 44.3
Mutter

**Comment by MastaG** [comment]
Are you running on Wayland and using a dedicated GPU?
(E.g. not the primary one)

**Comment by justunscored** [comment]
CPU AMD Ryzen 9 7900X 12-Core Processor
GPU rtx 3070
OS: Arch Linux
Kernel: 6.4.7-arch1-3

I am experiencing similar issues on Arch Linux as well, build 15417 is fine but after 15419 Call Of Duty: Ghosts crashes, firmware installs complete but then rpcs3 crashes there as well, and when exiting any game it crashes. 
My other games seem to be fine.

**Comment by MastaG** [comment]
Try running rpcs3 with: QT_QPA_PLATFORM=xcb

**Comment by BigTreezZ** [comment]
I am getting this exact error on Arch Linux as well, except it's when I close any game. I can boot and run games with no issue, but this error will always pop up when closing a game, crashing RPCS3 entirely.

- SYS: RPCS3 v0.0.29-15443-dea24c90 Alpha | master
- SYS: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz | 12 Threads | 15.49 GiB RAM | TSC: 3.192GHz | AVX+ | FMA3 | TSX
- SYS: Operating system: POSIX, Name: Linux, Release: 6.4.8-lqx1-1-lqx, Version: #1 ZEN SMP PREEMPT Thu, 03 Aug 2023 20:20:21 +0000
- SYS: Current Time: 2023-08-05T13:52:14
- RSX: Found Vulkan-compatible GPU: 'NVIDIA GeForce GTX 1650' running on driver 535.86.5.0
- SYS: Firmware version: 4.89

I uploaded a log below (it's a manually compressed RPCS3.log file. The .log.gz file wasn't working, and the .log file was 32mb, surpassing the 25mb upload limit.)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12267139/RPCS3.zip)

**Comment by AdadG** [comment]
Same here on Ubuntu 22.04.3 LTS. MGS4 can't start due to this, for example.

**Comment by Techbane** [comment]
Same issue on Mint 21.1. It triggers either on attempting to run a game or install a firmware, seemingly triggered by the "compiling PPU modules" process. I can't get it to produce a log, but it keeps spamming this over and over in the terminal until crashing with a segfault:

> RPCS3: Pad Thread: SIG: Thread terminated due to fatal error: futex_waitv is not supported (Linux kernel is too old)
(in file /tmp/cirrus-ci-build/rpcs3/util/atomic.cpp:883, in function wait) (errno=38=Function not implemented)
RPCS3: RSX [0x0000000]: SIG: Thread terminated due to fatal error: futex_waitv is not supported (Linux kernel is too old)
(in file /tmp/cirrus-ci-build/rpcs3/util/atomic.cpp:883, in function wait) (errno=38=Function not implemented)

It actually had been a while since I updated my kernel so I went and did that, to no avail. As mentioned by @justunscored reverting to 15417-9b3a878c fixes it.

**Comment by AniLeo** [comment]
Not the same issue. What you're having is #14422. We will bump our minimal kernel requirement if no other solution is found.

**Comment by AniLeo** [comment]
Needs retest on latest build for the issue specifically reported in this issue, not the outdated kernel one.

**Comment by justunscored** [comment]
The latest build seems to have fixed it for me, My game is able to boot now and can now create firmware cache.

**Comment by AdadG** [comment]
The problem persists for me, I can't install the firmware nor start MGS4. Issues that don't exist in the pre-update to Qt6 (v0.0.28-15417-9b3a878c_linux64).
I have the kernel and Ubuntu updated.

**Comment by BigTreezZ** [comment]
The issue I had before (error message after closing a game) still persists for me as well. 

Arch Linux 6.4.10-lqx1-1-lqx
KDE Plasma 5.27.7
X11

**Comment by AniLeo** [comment]
> The problem persists for me, I can't install the firmware nor start MGS4. Issues that don't exist in the pre-update to Qt6 (v0.0.28-15417-9b3a878c_linux64).
> I have the kernel and Ubuntu updated.

Need log file to update the issue so it can be reopened

**Comment by justunscored** [comment]
Okay so I realized why mine was working... 

I only really use X11 but In a attempt to see if it was just X11 not launching games when both were broken, i had switched to wayland but it didn't fix the issue and both were crashing upon launching the same game and creating firmware cache and I forgot to switch back to X11 after trying to see if wayland would fix the issue

 and that's why it was fixed for me at that time. Issue still persists on X11 but not wayland.

**Comment by justunscored** [comment]
Okay so I realized why mine was working...

I only really use X11 but In a attempt to see if it was just X11 not launching games when both were broken, i had switched to wayland but it didn't fix the issue and both were crashing upon launching the same game and creating firmware cache and I forgot to switch back to X11 after trying to see if wayland would fix the issue

and that's why it was fixed for me at that time. Issue still persists on X11 but not wayland.

**Comment by therealbungus** [comment]
This is also happening to me, preventing the system menu from booting. Error happens at the very end of compiling modules, or when closing out of a game. Same exact error popup in the original issue post.


Arch 6.4.10-zen2-1-zen
KDE Plasma 5.27.7, X11
Nvidia GTX 1080Ti
Intel i5-10600k

**Comment by Parotaku** [comment]
Hello
I don't know if it's the same problem as others but I can't boot any games anymore on Linux Mint (Victoria 21.2 Cinnamon) either. The emu says it's running but not rendering window is created...

- SYS: RPCS3 v0.0.29-1-01a05502 Alpha | master | local_build
- SYS: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz | 12 Threads | 15.51 GiB RAM | TSC: 3.300GHz | AVX+ | FMA3
- SYS: Operating system: POSIX, Name: Linux, Release: 5.15.0-79-generic, Version: #86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023
- SYS: Current Time: 2023-08-16T21:09:55
- RSX: Found Vulkan-compatible GPU: 'NVIDIA GeForce RTX 2070 SUPER' running on driver 525.125.6.0
- RSX: Found Vulkan-compatible GPU: 'llvmpipe (LLVM 15.0.7, 256 bits)' running on driver 0.0.1
- SYS: Firmware version: 4.90

All threads terminate like this: 

F {Progress Dialog Server} SIG: Thread terminated due to fatal error: Address duplication in atomic_wait::list
(in file /run/build/rpcs3/rpcs3/util/atomic.cpp:943[:6], in function wait)
F {Performance Sensor} SIG: Thread terminated due to fatal error: Address duplication in atomic_wait::list
(in file /run/build/rpcs3/rpcs3/util/atomic.cpp:943[:6], in function wait)
S PPU: Enabled: Non-Java Mode Fixup
F {PPU Syscall Usage Thread} SIG: Thread terminated due to fatal error: Address duplication in atomic_wait::list
(in file /run/build/rpcs3/rpcs3/util/atomic.cpp:943[:6], in function wait)
...etc...

**Comment by Nekotekina** [comment]
Should be fixed now.

**Comment by BigTreezZ** [comment]
If the latest version (RPCS3 v0.0.29-15487-384c807d Alpha) was supposed to fix it, it didn't, at least for me. I still get the message saying "Segfault executing location 00007f604c022fd0 at 00007f604c022fd0. Thread: Main Thread." as soon as I close any game I'm playing.

In addition, Red Dead Redemption GOTY (BLES01294) has completely stopped booting for me, and instantly gives me the error "Segfault executing location 00007f539c1b1fd0 at 00007f539c1b1fd0. Thread: Main Thread." (slightly different error). It is the only game where I encounter the behavior others have experienced, whereas I normally only get an error message when I close a game I'm currently running. Keep in mind this could have already been happening since I first commented on this issue, but only now did I try booting that game specifically.

I attached a log for the RDR GOTY crash below.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12363930/RPCS3.log)

**Comment by AniLeo** [comment]
This is not related to the futex_waitv regression (that has been fixed) as I already said above, do not mix issues as it confuses developers

**Comment by AdadG** [comment]
The issue persist on the last version (v0.0.29-15487-384c807d), I can't even install the firmware yet.

**Comment by therealbungus** [comment]
Issue is still persisting after latest update. After updating, I cleared my spu and ppu caches, then tried creating them again, crashes with the same segfault error as in OP. Only game I have in RPCS3 is Skate 3 (BLUS30464). Log attached below.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12366794/RPCS3.log)

**Comment by cipherxof** [comment]
I'm no longer having trouble booting as of the latest master build :man_shrugging:

**Comment by BigTreezZ** [comment]
Fully working for me now as well (RPCS3 v0.0.29-15497-454cb697 Alpha). Red Dead Redemption boots up again, and no more error messages after closing any game. Thank you!

**Comment by AdadG** [comment]
The issue has been resolved for me as well in the latest version (at the time of writing: v0.0.29-15497-454cb69). I can finally install the firmware and start MGS4.
Thanks.

**Comment by justunscored** [comment]
The issue is fixed for real this time. This time I am actually on X11 rather then Wayland.

**Comment by therealbungus** [comment]
Issue already closed, but I can confirm that this issue has been fixed. Thank you so much to everyone who has worked on this project ❤️
