### ISSUE TITLE
ratchet and clank nexus random freeze

### ISSUE THREAD

**Issue by A-w-x** [RPCS3/rpcs3#14424]
### Quick summary

the game freezes randomly

### Attach a log file

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12262233/RPCS3.zip)

### System configuration

ryzen 6800u
32gb ram
arch linux
mesa git
rpcs3 latest appimage

**Comment by A-w-x** [comment]
i think that helped but crashing with the same error #14425

**Comment by A-w-x** [comment]
no freeze in 3hrs after the canary patch and the crash seems fixed with #14436

should this be closed even if the patch is unofficial?

**Comment by Jonathan44062** [comment]
It has to be open, the canary fix freezes patches are only a temporary solution until the real fix arrives (The PR fixes all R&C Games with the freezes issues)

**Comment by kostakis** [comment]
Even with the MR being merged my R&C tools of destruction still get random freezes and everything needs restart.

**Comment by dcon03** [comment]
> Can this be closed yet ???

Unless it's been officially resolved, no.

**Comment by ScottNash042** [comment]
> > Can this be closed yet ???
> 
> Unless it's been officially resolved, no.

well hopefully the original OP will answer it

**Comment by A-w-x** [comment]
still using the patches, is this supposed to be fixed?

**Comment by Jonathan44062** [comment]
@A-w-x No, workarounds are not allowed, this needs to be fixed without the patches, users from discord has reporting freezes, the issue is not fixed yet

**Comment by TheGentlemen29** [comment]
It freezes each time I start the level. 

[RPCS3.log](https://github.com/user-attachments/files/29664099/RPCS3.log)
