### ISSUE TITLE
[Regression] All Pro Football 2k8 - Crowd shadows (#13077)

### ISSUE THREAD

**Issue by RP32WEC** [RPCS3/rpcs3#14608]
### Quick summary

Crowd shadows flickering

### Details

Works as expected in 14483 but not with build 14488.

### Build with regression

v0.0.25-14488-04fb8655

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12504601/RPCS3.log.gz)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12504602/RPCS3.log.gz)

### Attach capture files for visual issues

![Untitled-6](https://github.com/RPCS3/rpcs3/assets/94249324/9a904fcc-b815-4614-965d-bacdb4a28639)
![Untitled-5](https://github.com/RPCS3/rpcs3/assets/94249324/8655ca71-9ae6-47a6-b040-1b3c7fee9de6)

**Comment by AniLeo** [comment]
Linking PR that introduced the regression: #13077

**Comment by kd-11** [comment]
This was fixed at some point. It renders correctly now, even better than the before image since distant crowds have correct shadowing and lighting.

**Comment by RP32WEC** [comment]
I've updated to the latest version and the issue is still there.

**Comment by kd-11** [comment]
> I've updated to the latest version and the issue is still there.

Please provide a log and maybe a screenshot as well in case I'm looking at the wrong thing.

**Comment by RP32WEC** [comment]
> > I've updated to the latest version and the issue is still there.
> 
> Please provide a log and maybe a screenshot as well in case I'm looking at the wrong thing.

Both are provided above which show the issue I that I'm referring to.

**Comment by RP32WEC** [comment]
> > I've updated to the latest version and the issue is still there.
> 
> Please provide a log and maybe a screenshot as well in case I'm looking at the wrong thing.

Both are provided above which show the issue that I'm referring to.
