### ISSUE TITLE
[Regression] Updating to #14603 doesnt let the game boot

### ISSUE THREAD

**Issue by ReLyf47** [RPCS3/rpcs3#14605]
### Quick summary

After updating to #14603 booting any game would just result in the PPU Compiling stage being stuck forever

### Details

on #14603 
![image](https://media.discordapp.net/attachments/277227681836302338/1147489894038503434/image.png)
Booting a game will be stuck on 118/119 module 148/148 forever.
same happened to this guy on the [discord channel.](https://discord.com/channels/272035812277878785/277227681836302338/1147487793556230225)

while on any build before #14603 (Ex. #14595 or #14589)
![image](https://cdn.discordapp.com/attachments/277227681836302338/1147490550820376636/image.png)
PPU modules get past the stuck and can progress to 120/120 Module 324/324

![image](https://cdn.discordapp.com/attachments/277227681836302338/1147491966687379517/image.png)
and the game also boots.
said guy with the same issue fixed it with downgrading to #14589 
[Here's the message they sent.](https://discord.com/channels/272035812277878785/277227681836302338/1147492028557578251)

This testing was done with the cache folder nuked (no old cache is leftover)

(ps: i hope i did the report correctly)

### Build with regression

rpcs3-v0.0.29-15581-11006dac

### Attach two log files

Using #14595 :
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12503905/RPCS3.log.gz)

Using #14603 :
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12503893/RPCS3.log.gz)

**Comment by Darkhost1999** [comment]
It's related to what I was mentioning here
https://github.com/RPCS3/rpcs3/pull/14595#issuecomment-1703296760
Just was trying and didn't think it affected regular game boots. There is a new PR out that testing soon.

**Comment by elad335** [comment]
Retest.

**Comment by ReLyf47** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12504103/RPCS3.log.gz)
still borked on the intreperter

**Comment by elad335** [comment]
Retest.

**Comment by Darkhost1999** [comment]
What I mentioned is resolved and yea I see SPU is building cache while PPU is building cache. Looks clean, isn't freezing, and is compiling.

**Comment by autofire372** [comment]
I am still getting hangs at the end of PPU compilation in Lego Star Wars: The Complete Saga as well as the XMB.

I am using build 15608.
