### ISSUE TITLE
MLB The Show 16 artifacting

### ISSUE THREAD

**Issue by kingtag1999** [RPCS3/rpcs3#14731]
### Quick summary

MLB The Show 16 has artifacting and black bars popping up in RTTS, both in-game and in the menu.
Windows 11 OS

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12883758/RPCS3.log)

### Attach capture files for visual issues

https://www.dropbox.com/scl/fi/kybkm3d8ffee9q7wr3zkp/BCUS01089_20231012094345_capture.7z?rlkey=zhonarf57w9buv69nwwi2i35y&dl=0

### System configuration

Windows 11 OS
NVidia 1660 Ti

**Comment by digant73** [comment]
@kingtag1999 is that still an issue?

**Comment by helenclarko** [comment]
<img width="2392" height="1341" alt="Image" src="https://github.com/user-attachments/assets/316dad2b-06ab-4d66-8a94-04c320b52f1e" />

Characters with white face:

<img width="765" height="1025" alt="Image" src="https://github.com/user-attachments/assets/8f584811-5b92-48ec-859f-065233204c1d" />

Crowd overlaying field:

<img width="2347" height="1317" alt="Image" src="https://github.com/user-attachments/assets/f363bd0f-5111-459b-8dd7-3e672cd41440" />

MLB The Show 16 Log

[MLB16.log](https://github.com/user-attachments/files/23870384/MLB16.log)

I've been following this one for awhile let me add as much information as possible.

**System Configuration**

Processor: AMD Ryzen 7 5700X3D
GPU: NVIDIA GeForce RTX 5070
Windows 11 OS

**RPCS3 Configuration**
RPCS3 Version: 0.0.38-18432-6dd37cb2 Alpha | master
SPU XFloat Accuracy: Approximate XFloat
SPU Block Size: Safe
Renderer: Vulkan
Write Color Buffers: Enabled
RSX FIFO Accuracy: Atomic

**Comment by helenclarko** [comment]
@digant73 I'm happy to get you whatever you need.

**Comment by digant73** [comment]
please re-test on latest build. Hopefully some textures and reflections issues have been fixed by recent build 0.0.39-18790

**Comment by michael-rutledge** [comment]
I updated to 0.0.39-18794 this morning, and am still seeing these issues (bad billboards and missing facial textures for created players). I recorded some video for extra visual context: https://www.youtube.com/watch?v=galb-oAXi9k

I know I'm on not on the same exact game (I am on MLB 13 The Show), but I am hopeful that due to the same engine being used under the hood, fixing one of the installments should fix the others.

**Comment by Virtua64** [comment]
For the record,  the issue with the graphical abnormalities such as the barriers blocking the view and other on field random abnormalities affect **_all_** MLB The Show titles starting with MLB 11.  So MLB 11 - MLB 16 The Show are all affected by this glitch that make the games unplayable in most stadiums.  Apparently it has something to do with the rendering of the crowd.   I have no idea if this is a RSX or SPU issue but I tried every RPCS3 setting known to mankind for the last 5 years and I could not "fix" it.

**Comment by michael-rutledge** [comment]
I am not very graphics-savvy but **this feels to me like broken vertex data in shaders.**

It looks to me like the crowd gets rendered via multiple shaders/cameras (don't know the accurate term here) placed in world space around the stadium. Seemingly random selections of those shaders/cameras become broken as the camera moves around. When they become broken, the section of the crowd that is now broken disappears from where they should be and instead get rendered somewhere also random, **almost as if world space gets mixed up with object space or vice versa.**

When that crowd section becomes _not_ broken again, they render correctly back where they should. You can see this as I move the camera around in [my earlier example video](https://www.youtube.com/watch?v=galb-oAXi9k), especially around [3 minutes in](https://youtu.be/galb-oAXi9k?si=gq1FkxozoxMAbdqz&t=180). You can also see in that timestamp that there is a **decent amount of stuff rendered on what appears to be an XY axis of sorts, congregating on the pitcher's mound.**

Due to a quirk in how baseball stadiums are typically laid out in real life, the least amount of crowd is typically visible in-game while facing away from home plate towards the center field wall, where the [batter's eye](https://en.wikipedia.org/wiki/Batter%27s_eye) is. This means **the problem is technically least severe when using the default batting camera**, such as in the first screenshot in this thread. I can say from personal experience though that the problem gets way worse when facing home plate, such as when fielding in _Road to the Show_ mode or when using a behind-the-mound pitching camera.

**Comment by michael-rutledge** [comment]
**Got some RenderDoc data for the face texture issue:**

Here is a capture from the _Edit Player_ screen for a custom created player. Notice that the character is rendered properly, along with a normal map for facial details in the top right image under "Inputs." There is also a general face texture tucked away in the inputs as well.

<img width="2559" height="1389" alt="Image" src="https://github.com/user-attachments/assets/678905f0-701e-4257-a925-4ddec13c0f12" />

When a custom character is rendered in an actual game, this map and texture are shown as empty/black: 

<img width="2556" height="1117" alt="Image" src="https://github.com/user-attachments/assets/ad56c435-03e4-4de5-9841-c689f63d0b32" />

**I have no idea how this data gets lost, but it does and that's what causes that particular bug.**

**Comment by michael-rutledge** [comment]
I know this is my third uninterrupted comment here, so I will try to keep it brief, but here is my summary of the root problems:

* **Black and white faces:** caused by normal map and texture maps for characters' faces getting filled with uninitialized or garbage memory during on-field gameplay; _Edit Player_ and _Create Player_ screens are fine (see my last comment)
* **Crowd glitches:** caused by bad data filling the `gl_Position` field of crowd billboard vertices:

<img width="1770" height="1202" alt="Image" src="https://github.com/user-attachments/assets/8c1a9653-3ab8-4755-a515-3b4e96c7ca29" />

---

I go into greater detail in this new video: https://www.youtube.com/watch?v=BLQVGDHReZE

Perhaps this is enough information to remove the _Need Information_ tag?

**Comment by kd-11** [comment]
Does the issue happen when shader compiler is set to "legacy single threaded"? Also try setting shader precision to low though modern nvidia cards do not behave the same as PS3 when it comes to some conversions.
As for the bad vertex data - GIGO. If we're pulling in garbage then the emulated shader will put out garbage. The fact that the first 3 verts have the exact same value is not looking good and is extremely unusual for geometry, which hints at trash being located where the game said vertex data would be.
Forcing shaders to run inline can sometimes help if the game is reusing calculations done at load time to render later on since skipped shaders tend to just mean uninitialized memory.

**Comment by Triticum0** [comment]
Only test mlb 11 but crowd issue does occur with shader precision set to low and legacy single threaded shader compiler

**Comment by michael-rutledge** [comment]
+1 on MLB 13. Just tried myself (with deleted shader cache and all) and identical issues persist.

**Comment by nabawi29** [comment]
I hope this will be fix in the future. MLB THE SHOW 16 will feed pc gamers for centuries

**Comment by digant73** [comment]
please an update on this issue after many bugfixes on the last months

**Comment by sbaum23** [comment]
I still see these issues (faces and crowd glitches) on MLB 16 with version `0.0.41-19596-a7d90852`.

**Comment by shinimasu20** [comment]
can confirm the same issues on version `0.0.42-19725-2f403459`

**Comment by Biostalker** [comment]
Suddenly the white face bug is gone in 16. better in 10 too.  Just dropping info

**Comment by ShadowH69** [comment]
> Suddenly the white face bug is gone in 16. better in 10 too. Just dropping info

and the crowd on the field issue?

**Comment by Biostalker** [comment]
Sadlly, they still on tourettes, but I have noticed leaving hot zones on can mitigate the issue a bit

**Comment by ShadowH69** [comment]
> Sadlly, they still on tourettes, but I have noticed leaving hot zones on can mitigate the issue a bit

if you can could you provide screenshots of the issue resolved for interest sake

**Comment by Biostalker** [comment]
https://imgur.com/hRvDchZ  Sorry had errands to run.

**Comment by Biostalker** [comment]
https://imgur.com/hRvDchZ CAC in 16
I wanted to do some more testing in-game.  The Show 08 had been my daily-driver since it had zero major graphical errors.  It still has CAC black face(white in 16).

It appears now that the Show 10 has zero graphical errors and no white face either.  Playing full games in Yankee stadium, No issues. Playing RTTS feels nice.  Yeah.  This is seriously running nice now. 2-3 hours in-game.  Multiple MLB stadiums tested watching all the replays .   Everything seems to be fully functional.


The show 16 CAC seems to be fixed but the crowd is still  janky.  Just wanted to leave a lay of the land from a hopeless cubs fan.  Might have to check 11-15.  Will edit in anything relevant.

**Comment by saghm** [comment]
I was able to play a full season of Show 10 over a few weeks recently. The only graphical issues I had were occasionally the lighting being a bit too bright or something when starting a game, but it would fix by just quitting the current game and restarting it (not even restarting the emulator, just literally the current ballgame). From what I've been able to find from manually testing, everything from 11 onwards has the weird issues with the crowd being on the field and everything (for at least some stadiums).

**Comment by Virtua64** [comment]
> I was able to play a full season of Show 10 over a few weeks recently. The only graphical issues I had were occasionally the lighting being a bit too bright or something when starting a game, but it would fix by just quitting the current game and restarting it (not even restarting the emulator, just literally the current ballgame). 

The game benefits with WCB enabled. In fact, all MLB shows need it enabled iirc.

>From what I've been able to find from manually testing, everything from 11 onwards has the weird issues with the crowd being on the field and everything (for at least some stadiums).

Yeah, from  years 11 - 16, the games are broken with that crowd glitch in almost every stadium.  Its a shame this was never looked at by the devs.  Its a great series that is still mostly unplayable after all these years because of this one stupid glitch...
