### ISSUE TITLE
Segfault reading location, Emu Thread Name: 'Network Thread'.

### ISSUE THREAD

**Issue by Fabxx** [RPCS3/rpcs3#14787]
### Quick summary

This segmentation fault can happen at random times with different games, so far i've experienced this with:

Splinter cell Double Agent
Saints Row 2
Call of duty: Ghosts
Call of Duty Black Ops 1
God of war Collection
VSH/XMB (after reconstructing database and rebooting)

Most of the times happens when trying to load something that requires rpcs3 to restart to open another menu and such.

This segfault causes the entire emulator to freeze, not even being possible to close it.

Networking is totally disabled in the emulator.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13199003/RPCS3.log)

this log was generated at the time SC:DA crashed.

### System configuration

CPU: Intel core i7-10700

GPU: RTX 3060 v2 OC 12GB

RAM: HyperX DDR4 2.9Ghz

OS: Linux (Debian 12 Bookworm)

**Comment by Fabxx** [comment]
I did some more tests and added a few more games that are affected. If you want to easily reproduce this, you can use the emulated XMB as described above if you don't have any of the games listed above.

**Comment by elad335** [comment]
Retest on master

**Comment by Fabxx** [comment]
issue has been fixed

**Comment by Shoegzer** [comment]
Please reopen this.  I just tested with COD Black Ops 2 (which was freezing along with the other titles on the above list) and unfortunately it's still freezing.  

[RPCS3 Log](https://www.sendspace.com/file/78iu9q)

Note: Log file was too large to attach here as it took a while to test before the issue occurred.

**Comment by Fabxx** [comment]
> Please reopen this.  I just tested with COD Black Ops 2 (which was freezing along with the other titles on the above list) and unfortunately it's still freezing.  
> 
> [RPCS3 Log](https://www.sendspace.com/file/78iu9q)
> 
> Note: Log file was too large to attach here as it took a while to test before the issue occurred. 

In my testing neither ghosts or BO 2 freezed, are you sure you've updated the build?

**Comment by Shoegzer** [comment]
Yes. Tested on commit cee6d03033fe43ee3875d6196d6d3697144d51b0.

**Comment by RipleyTom** [comment]
> Please reopen this. I just tested with COD Black Ops 2 (which was freezing along with the other titles on the above list) and unfortunately it's still freezing.
> 
> [RPCS3 Log](https://www.sendspace.com/file/78iu9q)
> 
> Note: Log file was too large to attach here as it took a while to test before the issue occurred.

First, can't download the log, this host is absolute cancer.
Second, does it segfault in Network Thread? Otherwise it's not relevant to this issue.

**Comment by Shoegzer** [comment]
Okay, try [this one](https://file.io/FnE0TlDzh03t).

Anyway, bad assumption on my part. There's something seemingly network-related in this log, though perhaps unrelated to the Network Thread segfault:

`
·E 0:02:15.402509 {PPU[0x1000000] Thread (main_thread) [HLE:0x02fb29a4, LR:0x008dd214]} SYS: 'cellNetCtlGetInfo' failed with 0x80130108 : CELL_NET_CTL_ERROR_NOT_CONNECTED [1]`

There is another issue report for that though, so I suppose this one can stay closed if it's really unrelated.  That said, other testers that are finding these titles aren't freezing should test for longer - they still freeze.
