### ISSUE TITLE
PPU: MFVSCR exception

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#1480]
MFVSCR instruction missing 
`
F {PPU[0x70000000] Thread (main_thread) [0x0025e2cc]} class std::logic_error thrown: MFVSCR instruction at 0x25e2cc (NPEA00007)
`

**List of games affected:**
- NPEA00007
- NPEA00008
- NPEA00011
- NPEA00041
- NPEB00833
- NPEB01037
- NPEB01283

**Comment by tambry** [comment]
@MyaniPT It ain't implemented on PPU Interpreter 2, but it should be fine on Interpreter 1.

**Comment by MyaniPT** [comment]
Gotcha, with PPU Interpreter 1 it opens the GSFrame and goes (there's already an issue about it so I won't prolong myself)

`
{PPU Thread[0xc9] (HDD Game setup)[0x002f57d8]} HLE: Last function: cellHddGameCheck (0x9117df20)
{PPU Thread[0xc9] (HDD Game setup)[0x002f57d8]} Exception: invalid map<K, T> key
Please report this to the developers.
`

**Comment by tambry** [comment]
It also happens on GTA V.

**Comment by supergatto** [comment]
PPU Interpreter 1 was broken by @Nekotekina merge
And show this:
`
{PPU[0x120] Thread ([RAGE] Dependency) [0x00a40ed4]} class std::runtime_error thrown: MFVSCR
(in file C:\rpcs3\rpcs3\Emu\Cell\PPUInterpreter.cpp:182)
{PPU[0x6] Thread (main_thread) [0x00a42bf8]} class std::runtime_error thrown: MFVSCR
(in file C:\rpcs3\rpcs3\Emu\Cell\PPUInterpreter.cpp:182)
`
Original posts: http://www.emunewz.net/forum/showthread.php?tid=156673&pid=231118#pid231118

**Comment by Nekotekina** [comment]
Precise interpreter has been removed with a TODO to restore it. If someone wishes to do it, it shouldn't be hard to restore all instructions using SAT flag (and MFVSCR as well) and put them into ppu_interpreter_precise "namespace" (actually a struct). It's just cannot be copied blindly from the history, it needs accurate porting. I didn't do it myself because most games don't use MFVSCR and I don't care about GTA V.

**Comment by AniLeo** [comment]
Also happens on: 
- NPEA00007
- NPEA00008
(Will fill in more games when I find them)

**Comment by MarioSonic2987** [comment]
Max Payne 3 [NPEB-01037] in https://github.com/RPCS3/rpcs3/commit/74fec275c71eaa4118bdca3eee3068c31f99c8be
```
{PPU[0x70] Thread ([RAGE] netThreadPool 1) [0x00b6bb34]} class std::runtime_error thrown: MFVSCR
(in file C:\rpcs3\rpcs3\Emu\Cell\PPUInterpreter.cpp:272)
```

**Comment by AniLeo** [comment]
Updated with current known list of affected games

**Comment by raven02** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/2289 . Tested with Tori-Emaki

**Comment by AniLeo** [comment]
It's still not implemented but not crashing games anymore and already added to the roadmap so those listed above should be good to progress a little further
