### ISSUE TITLE
James Cameron's Avatar: The Game - Flicker textures

### ISSUE THREAD

**Issue by Jonathan44062** [RPCS3/rpcs3#14833]
### Quick summary

In some moments of the game, using a gun or the RDA, the walls starts flickering 
I tried some settings and don't fix the issue

### Details

https://github.com/RPCS3/rpcs3/assets/78843189/f3b1ca07-25a7-4855-b712-1273bbb4c6b6

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13405361/RPCS3.log.gz)

### Attach capture files for visual issues

Is hard to catch the right moment, since the flicker is fast to get the right capture 

### System configuration

Windows 10 22H2
Intel Core i7-8700
15.93 GiB RAM
GPU: NVIDIA GeForce GTX 1070 Ti (546.17)

### Other details

I can share my save files to test better
https://www.mediafire.com/file/cbajvdhavyqwkv5/Avatar_the_Game_Save_files.rar/file

**Comment by zombie167** [comment]
Please check the option "Allow Host GPU Labels"

**Comment by digant73** [comment]
@Jonathan44062 in the same period (Nov 2023) of your report, other users reported flickering issues apparently present at default game resolution (720p). Maybe it can be useful to check if the issue is not present at different resolutions (e.g. 1080p)

**Comment by Darkhost1999** [comment]
> Maybe it can be useful to check if the issue is not present at different resolutions (e.g. 1080p)

Even if true this will not satisfy the issue ticket or resolve it.
All games must work correctly at standard resolution and only games that officially support 1080p must be able to support someday in the future a 1080p mode. But the only true goal for resolution is all 1280x720p standard game resolutions work.

**Comment by digant73** [comment]
I know. it was requested just to have a clear picture of the bug for main developers. Many reported bugs (strangely in the same period; e.g. maybe due to a possible common regression?) possibly related to a single possible fix

**Comment by kd-11** [comment]
This one needs a gfxrecon capture from someone with a RTX30 card since it happens for a single frame.

**Comment by digant73** [comment]
@Jonathan44062 maybe fixed now?

**Comment by Jonathan44062** [comment]
Still broken, even tested with the new setting of Z-fighting, no changes
