### ISSUE TITLE
Steam Deck OLED unable to boot game from gamemode(gamescope)

### ISSUE THREAD

**Issue by KrisCris** [RPCS3/rpcs3#14917]
### Quick summary

Might be something similar to this https://github.com/RPCS3/rpcs3/issues/14628, but I am not sure.

With the same boot drive, I can only reproduce this issue on my OLED Steam Deck, not on the OG. Whenever I try to boot a game from the Steam Deck game mode, this error happens. But in desktop mode it was fine.

<img width="1341" alt="Screenshot 2023-12-20 at 6 45 20 PM" src="https://github.com/RPCS3/rpcs3/assets/38860226/d7d91b31-185b-4dbe-aa2c-3a88ef73d5b3">

### Details

I am using the .appimage version.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13726297/RPCS3.log)

### System configuration

Steam Deck OLED

**Comment by MSuih** [comment]
From what I recall from various conversations:

* Gamescope people blamed this on our old Vulkan library. We update it recently but it didn't solve the issue.
* They'd want us to stop shipping our own Vulkan library and rely on system provided one, but we can't do that as we support Ubuntu LTS and those have ancient Vulkan deps.
* The library itself should mostly be just a compatibility layer between RPCS3 and drivers so we're a bit puzzled as to why it causes this issue. Maybe gamescope hooks into the library and thus expects it to work in very specific manner.

**Comment by solari21** [comment]
Same issue here in Steam OS gaming mode with appimage format of RPCS3

**Comment by Originalimoc** [comment]
What is this doing? Maybe some clue? https://github.com/FrogTheFrog/com.moonlight_stream.Moonlight/blob/master/gamescope/VkLayer_FROG_gamescope_wsi.x86_64.json

**Comment by ds8k** [comment]
Also experiencing this

**Comment by xRassyx** [comment]
Just got my deck OLED and launching games with it in game mode is busted for me too. Same error. Any news on how to fix this???!

**Comment by xRassyx** [comment]
So after speaking to a friend of mine on the discord, He's discovered a workaround to where Rpcs3 works in game mode of the steam deck. Downgrading to version v0.0.28-15245 is the best option for the moment. I give full credit to k6stor of the discord for this workaround!

**Comment by k6storama** [comment]
well I'm not saying it's a workaround, it's just the last build that doesn't crash inside the gamescope for me.

**Comment by Originalimoc** [comment]
Isn't there a flatpak build? Use that

**Comment by Mrlinkwii** [comment]
flatpak isnt supported and is a third party build @Originalimoc

**Comment by Originalimoc** [comment]
But does it work?
And, Or is it built by flathub?

**Comment by xRassyx** [comment]
Use that build of rpcs3 and you should be fine :)

**Comment by JoshuaSenouf** [comment]
> So after speaking to a friend of mine on the discord, He's discovered a workaround to where Rpcs3 works in game mode of the steam deck. Downgrading to version v0.0.28-15245 is the best option for the moment. I give full credit to k6stor of the discord for this workaround!

From my testing, you can actually go as far as [0.0.28-15417](https://github.com/RPCS3/rpcs3-binaries-linux/releases/download/build-9b3a878c189e4e688b6025de0d0ff659116dcade/rpcs3-v0.0.28-15417-9b3a878c_linux64.AppImage), i.e. the last build for 0.0.28.

The moment you start using [0.0.29-15419](https://github.com/RPCS3/rpcs3-binaries-linux/releases/download/build-6cd5a7eab960608cc38652c7d9f7900d52b122da/rpcs3-v0.0.29-15419-6cd5a7ea_linux64.AppImage), i.e. the first build for 0.0.29, we encounter the issue.

**Comment by k6storama** [comment]
This issue can be circumvented by adding `LD_LIBRARY_PATH=/usr/lib:/usr/local/lib %command%` in the Steam launching options, which will force RPCS3 to use system libraries instead of the ones included in the AppImage.

**Comment by JosephBoseph** [comment]
> This issue can be circumvented by adding `LD_LIBRARY_PATH=/usr/lib:/usr/local/lib %command%` in the Steam launching options for RPCS3, which will force RPCS3 to use system libraries instead of the ones included in the AppImage.

Had this issue too and this solution worked! Thank you

**Comment by AniLeo** [comment]
Can you test with the PR that I just opened? I have the LCD model, not the OLED, so I can't test.

Build: https://artprodsu6weu.artifacts.visualstudio.com/Ad52971ce-2651-462c-a71a-8019f393a0cf/3598951b-4d39-4fad-ad3b-ff2386a649de/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL25la290ZWtpbmEvcHJvamVjdElkLzM1OTg5NTFiLTRkMzktNGZhZC1hZDNiLWZmMjM4NmE2NDlkZS9idWlsZElkLzEwMDg0L2FydGlmYWN0TmFtZS9SUENTMytmb3IrTGludXgrKGNsYW5nKQ2/content?format=zip

**Comment by AniLeo** [comment]
Fixed by #15273

**Comment by casasfernando** [comment]
@AniLeo while the vulkan library error is not present anymore in gamemode (gamescope) and RPCS3 is starting up correctly, still doesn't work as expected. I'm using AppImage 16203 (latest at the moment) and the game starts to load, I can see the PPU loading progress bars screen screen but it freezes there. I can hear the game sound and music in the background so emulation is still running, but screen remains stuck in the initial PPU loading screen.
In desktop mode the problem is not present and everything works as expected.
Since the vulkan library error is indeed solved I think I will open a new issue for this.
I'm on a Steam Deck OLED with the latest updates (Steam OS 3.5.17) and firmware.

Thanks

**Comment by casasfernando** [comment]
> 
> I had this issue as well very briefly, disabling `Start games in fullscreen mode` fixed it but I couldn't replicate the issue after re-enabling it so I was hesitant on opening an issue.

Thanks @rawdatafeel !
This was it, in my case I was using the `--fullscreen` CLI parameter when launching the emulator from a helper script I'm using to be able to use ISO files for the games, so the problem was happening regardless the status of `Start games in fullscreen mode`.
I removed the CLI parameter and left `Start games in fullscreen mode` enabled, and the issue went away.

**Comment by pyromancer5** [comment]
am having this problem steam deck rpcs3 app image stuck on shader game mode
i saw a post saying i need to have vulkan icd loader installed how can i install that
on desktop it work fine but in game mode its stuck and freez on shader compile
