### ISSUE TITLE
[Regression] MGS4 Grey Screen bug

### ISSUE THREAD

**Issue by Krythulu** [RPCS3/rpcs3#15112]
### Quick summary

In previous build of RPCS3, after dropping down in a section of the rubble building in MGS4 after meeting the weapons launderer. The screen will go grey and the player is unable to move besides entering a closet or bin. This isn't a problem in a previous build of the game

### Details

In MGS4, after meeting Drebin we are introduced to a section of the game where there's a collapsing building. Snake has to go through this building in order to progress and as the player progresses, there is a section where they have to slide down some rubble

Where the player is before the bug
![NPUB31633_screenshot_2024_01_27_19_15_48](https://github.com/RPCS3/rpcs3/assets/94866697/2611d728-b6db-4954-b0d5-190f25a0727b)

However if the player is playing on build 0.0.30-15998 instead of sliding down and progressing they are met with a grey screen
![NPUB31633_screenshot_2024_01_27_19_15_54](https://github.com/RPCS3/rpcs3/assets/94866697/4facb567-9987-4a51-92bb-e9269f381266)

Intended result as seen on build 0.0.30-15996
![NPUB31633_screenshot_2024_01_27_19_18_21](https://github.com/RPCS3/rpcs3/assets/94866697/e0cb1b0c-5577-4b46-8a0a-0046b9a8b449)

### Build with regression

0.0.30-15998

### Attach two log files

Log of the build with regression
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14073484/RPCS3.log.gz)

Log of the build that works
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14073494/RPCS3.log.gz)

### Attach capture files for visual issues

https://www.dropbox.com/scl/fi/158j9nesdy112i7lvhvvr/NPUB31633_20240127193802_capture.rrc.gz?rlkey=m066kljuvmtp0nil4enref4ip&dl=0

### System configuration

Operating System: Windows 10 Pro 22H2
CPU: Ryzen 5 5600x 6-Core Processor, 3701 Mhz, 6 Core(s), 12 Logical Processor(s)
GPU: AMD Radeon Rx 6750 XT 12gb

**Comment by Slickbait** [comment]
same CPU, Windows 11 23H2 and an RX 6700 XT, although on the Liquid fight the game gets stuck on a black screen and I die

**Comment by RipleyTom** [comment]
Can you try with https://github.com/RPCS3/rpcs3/pull/13897 ? https://artprodsu6weu.artifacts.visualstudio.com/Ad52971ce-2651-462c-a71a-8019f393a0cf/3598951b-4d39-4fad-ad3b-ff2386a649de/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL25la290ZWtpbmEvcHJvamVjdElkLzM1OTg5NTFiLTRkMzktNGZhZC1hZDNiLWZmMjM4NmE2NDlkZS9idWlsZElkLzk2NDMvYXJ0aWZhY3ROYW1lL1JQQ1MzK2ZvcitXaW5kb3dz0/content?format=zip

**Comment by Krythulu** [comment]
> Can you try with #13897 ?
> 
> https://artprodsu6weu.artifacts.visualstudio.com/Ad52971ce-2651-462c-a71a-8019f393a0cf/3598951b-4d39-4fad-ad3b-ff2386a649de/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL25la290ZWtpbmEvcHJvamVjdElkLzM1OTg5NTFiLTRkMzktNGZhZC1hZDNiLWZmMjM4NmE2NDlkZS9idWlsZElkLzk2NDMvYXJ0aWZhY3ROYW1lL1JQQ1MzK2ZvcitXaW5kb3dz0/content?format=zip

The build you sent appears to have fixed the issue. Thanks

**Comment by AniLeo** [comment]
The issue is not solved because the PR is not merged.

**Comment by h4rpooon** [comment]
I am also experiencing this issue.

**Comment by sloggas** [comment]
happening to me too

**Comment by chrismagic14** [comment]
Same Issue with 0.0.30-16026

**Comment by seanmiles** [comment]
Also having this issue with 0.0.30-16026

**Comment by ThisIsSet-L** [comment]
Similar issues on Linux  0.0.30-16015-c3c73c7e Alpha | master | local_build

Sorry for poor recording, was done with RPCS3 in-game
https://github.com/RPCS3/rpcs3/assets/31947915/1d3095c1-e75d-4570-acb6-f76516a60844

**Comment by ThisIsSet-L** [comment]
There are also further issues, after title sequence "Solid Snake", when in South America, climbing up the mountain side. Tall grass turns you and all enemies invisible, and you are constantly being "bumped" into and shot at.

**Comment by skalmanjr** [comment]
Did a roll instead of falling down on the wall and had no issues progressing.

**Comment by Asinin3** [comment]
Guys how hard is it to read? https://github.com/RPCS3/rpcs3/pull/13897 is confirmed to fix the issue but the build hasn't merged yet. You can either use that PR build, or use a build before this issue started to occur until its merged..

Leave this issue open until its merged.

**Comment by Asinin3** [comment]
Closing as linked PR merged.

**Comment by mezinr** [comment]
is it fixed, still happening to me. haven't rolled over the slide.

**Comment by westjgames** [comment]
> is it fixed, still happening to me. haven't rolled over the slide.

Can you provide your build id?

**Comment by cowboy-mode** [comment]
New to all of this and experiencing the same issue here. Can someone give a step by step process of how to use #13897 to solve this issue. I am not familiar with how to use PRs and add them to RPCS3 for fixes.

**Comment by ItsLaguna** [comment]
> New to all of this and experiencing the same issue here. Can someone give a step by step process of how to use #13897 to solve this issue. I am not familiar with how to use PRs and add them to RPCS3 for fixes.

Just update the emulator, the issue has been fixed since the PR has been merged already.

**Comment by cowboy-mode** [comment]
Thanks for the feedback. I thought to do that. Had the emulator updated this morning but issue is still occurring. I just powered through by rolling off ledges so its not too big of an issue. More so its the invisible character models and crashing.

**Comment by Forutieru** [comment]
Build : 0.0.30-16067 I tried and still got the grey screen and after rebooting the game all my saves have been corrupted :/

**Comment by ItsLaguna** [comment]
> Build : 0.0.30-16067 I tried and still got the grey screen and after rebooting the game all my saves have been corrupted :/ Edit: I restarted rpcs3 and my saves works again but i still can't go past that point without getting the grey screen... Edit 2: i changed SPU XFLOAT Acurracy to Accurate Xfloat and changed in the advanced tab RSX FIFO to Atomic. I managed to pass normaly but Accurate Xfloat ask a lot on the CPU so i switched back after saving just after the next cutscene.

I just beat the whole game on 0.0.30-16079 without issues, at this point it's likely an issue with your settings or your dump. Better ask for help in the Discord than posting here.

**Comment by fiskoner** [comment]
Same issue happening on 0.0.35-17571-583ec5d8 Alpha
Changing SPU XFloat Accuracy from Relaxed to Approximate resolved an issue
CPU: Ryzen 7 7800x3d
Patches: canary patch only,
