### ISSUE TITLE
NASCAR Unleashed [BLUS30806] movies are miscolored

### ISSUE THREAD

**Issue by CookiePLMonster** [RPCS3/rpcs3#15247]
### Quick summary

NASCAR Unleashed's intro movies are randomly flickering between the correct and broken colors. Switching between fullscreen/windowed can fix (or break) the colors, but it's not behaving 100% consistently in either mode.

### Details

How it looks when the colors are correct:
![image](https://github.com/RPCS3/rpcs3/assets/7947461/822dedc3-5795-4f7a-8617-dcd521d79deb)

When they are off:
![image](https://github.com/RPCS3/rpcs3/assets/7947461/571d5174-3829-4bfb-aef5-8f3b30e111c7)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14410125/RPCS3.log.gz)

### System configuration

Windows 10 Pro 22H2
12th Gen Intel(R) Core(TM) i9-12900K
31.80 GiB RAM
NVIDIA GeForce GTX 1070 running on driver 546.1.0.0

### Other details

Strict Rendering Mode does **NOT** resolve the issue.

**Comment by Megamouse** [comment]
I'm fairly sure we had this issue before, because I remember the intro and also the random color changes.
I just don't remember what fixed it last time.

**Comment by digant73** [comment]
@CookiePLMonster is that still an issue?

**Comment by CookiePLMonster** [comment]
> [@CookiePLMonster](https://github.com/CookiePLMonster) is that still an issue?

Yes it is.

**Comment by digant73** [comment]
please re-test on latest build. Hopefully some textures and reflections issues have been fixed by recent build 0.0.39-18790

**Comment by CookiePLMonster** [comment]
Still broken.

<img width="1920" height="1032" alt="Image" src="https://github.com/user-attachments/assets/d17358ba-65b3-484a-a2df-a04a7b19e08b" />

**Comment by CookiePLMonster** [comment]
I tried again on 0.0.40-19145 **after clearing all caches for the game**, and the issue doesn't seem to be happening anymore:

<img width="1920" height="1032" alt="Image" src="https://github.com/user-attachments/assets/e6c8a6b0-181a-4ffd-9c39-f560869f32e2" />

Tried with Async compiler, and with Async + interpreter.
