### ISSUE TITLE
[Regression] Multi-context support pull request breaks inFamous [BCUS98119]

### ISSUE THREAD

**Issue by 5kft** [RPCS3/rpcs3#15445]
### Quick summary

This change (https://github.com/RPCS3/rpcs3/pull/15421) has broken the rendering of explosions in InFamous (the screen flashes and shows dark flashing geometric patterns), and also has impacted the rendering of the HUD/minimap and target reticle as well.

Other rendering in the game seems fine, it's just shots/explosions and the HUD/reticle that are broken now.

### Details

I upgraded to the latest build that includes this pull request: https://github.com/RPCS3/rpcs3/pull/15421, and rendering of explosions in InFamous is completely broken.  Reverted to the previous build of RPCS3 that does not include this pull request, and rendering behavior is correct again.

Example screen cap during explosion (just a frame grab, during the explosion it just shows random/flashing full-screen geometric patterns):
![infamous-broken-explosions (pull 15421)](https://github.com/RPCS3/rpcs3/assets/38135790/8c7f23a1-0245-4325-8842-c23d1bb186e9)

HUD and minimap (and targeting reticle) are no longer fully rendered:
![infamous-hud-problems (pull 15421)](https://github.com/RPCS3/rpcs3/assets/38135790/dd88a265-04e9-4da9-8230-ad2c2b108e50)

### Build with regression

v0.0.31-16323-d6f6752a

### Attach two log files

[RPCS3-build-v0.0.31-16319-0231902a-good.log.gz](https://github.com/RPCS3/rpcs3/files/14967645/RPCS3-build-v0.0.31-16319-0231902a-good.log.gz)
[RPCS3-build-v0.0.31-16323-d6f6752a-(pull-15421)-bad.log.gz](https://github.com/RPCS3/rpcs3/files/14967646/RPCS3-build-v0.0.31-16323-d6f6752a-.pull-15421.-bad.log.gz)

### Attach capture files for visual issues

(I tried making an RSX capture but it is difficult pausing and catching the explosions - I included a screen capture above instead)

**Comment by JimScript** [comment]
For some reason, the UI is fully functional when you're standing on top of Zeke's TV.

**Comment by kd-11** [comment]
Hmm, I'm pretty sure this is a pushbuf issue, but need to verify.

**Comment by kd-11** [comment]
I was wrong, I broke vertex textures.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/15453

**Comment by JimScript** [comment]
I downloaded the update and I'm still getting the same vertex explosions and HUD flickering as I was before.

**Comment by Jack54guythecoder** [comment]
I am trying to make an RSX Capture of Infamous, because if you press L3 a couple of times, it somewhat fixes the HUD.
Could I upload an RSX capture for kd-11 to debug?

**Comment by 5kft** [comment]
Indeed, I'm sad to say that build v0.0.31-16338 does _not_ fix the problem - same issue occurs as originally reported...

**Comment by Raptr12** [comment]
This same issue is happening with InFamous 2:

- The reticle is absent, making aiming difficult.
- The minimap fails to display, hindering navigation and orientation.
- There are discrepancies observed in the karma level system, affecting gameplay dynamics.
- Utilizing R2 abilities triggers visual glitches, where the effects and particles manifest as black geometric shapes, reminiscent of the issues experienced in InFamous 1.

**Comment by Jack54guythecoder** [comment]
![image](https://github.com/RPCS3/rpcs3/assets/152041128/306e4750-ccc1-4ee6-8a1f-cc8cf1724d7d)
In this moment, it somehow fixes and glitches out

**Comment by kd-11** [comment]
Looks like the fix only solved the problem for code veronica which is weird. i guess the changes caused multiple unrelated regressions.
I'm not sure how to proceed since this game is notoriously annoying to debug and everyone has different luck reproducing the issue, so I'll do a code analysis to determine the cause.

**Comment by DMoguri** [comment]
Can't wait 'til you break code veronica again lmao

**Comment by Raptr12** [comment]
I was trying previous rpcs3 builds and the build 16299 runs Infamous 1 and 2 without any of this glitches.

**Comment by 5kft** [comment]
Thanks so much @kd-11 - hugely appreciated!

**Comment by Raptr12** [comment]
![image](https://github.com/RPCS3/rpcs3/assets/102325799/31f960a4-ca8e-4030-92f2-39a6df751de8)
Thanks @kd-11
