### ISSUE TITLE
[BLUS30718] Excessive / Ineffective shader caching in The Tomb Raider Trilogy

### ISSUE THREAD

**Issue by RecklessGlue540** [RPCS3/rpcs3#15851]
### Quick summary

Ran Anniversary for quite a few hours, one of the biggest problems I noticed is that shader caching seems to happen very frequently and in the same areas over and over again, kinda ruining the experience.
Playing through the whole Croft Manor level resulted in more than 10.000 shaders being compiled, and it even keeps on going after rebooting the game and going through the same areas.
Because of this, the shader preloading step at the start is also pretty slow, due to this absurd amount of pipeline objects.
It is kind of concerning imo because these games seem so primitive when it comes to their graphics.

I only tested Anniversary in depth, but I think it's safe to assume Legend and Underworld behave the same in this case.
The games play fine otherwise. No issues even at 60 fps. For the record, this particular issue happens even with the default / completely stock settings, which is what the log below contains.

### Details

Some footage here:
https://streamable.com/a90t8s

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/16411440/RPCS3.log.gz)

### System configuration

Operating System: Windows 11 Home, 23H2, OS Build: 22631.3958
CPU: Ryzen 7 5700G with Vega 8 integrated graphics
GPU: Radeon RX 6700 10gb running on 24.7.1 drivers
RAM: 16gb DDR4 3600mhz
RPCS3 Build: v0.0.32-16717-02aac2c5 Alpha | master

**Comment by 3Edu** [comment]
I can confirm that TR Legends has the same issue but with flashing white textures when compiling shaders.

So far, the only way that i found to "fix it" is using Shader Mode on Legacy (Single Threaded) but in return, you get stutters everytime a shader are compiled so not ideal solution.

It would be great a fix for this since the PC ports are not so great with lack of proper gamepad/UI support and some missing shaders effects.

**Comment by kd-11** [comment]
We have a problem with caching.
For example this snippet:
```
·! 0:17:38.094236 {RSX [0x01b7910]} RSX: Add program (vp id = 638, fp id = 8140)
·! 0:17:38.095019 {RSX [0x01b7b24]} RSX: Add program (vp id = 638, fp id = 8140)
·S 0:17:38.095095 {RSX.W6} RSX: Program compiled successfully
·S 0:17:38.096204 {RSX.W1} RSX: Program compiled successfully
·S 0:17:38.101365 {RSX.W2} RSX: Program compiled successfully
·! 0:17:38.390752 {RSX [0x00bf540]} RSX: Add program (vp id = 638, fp id = 8150)
·S 0:17:38.392109 {RSX.W3} RSX: Program compiled successfully
·! 0:17:38.400417 {RSX [0x00bf774]} RSX: Add program (vp id = 638, fp id = 8150)
·S 0:17:38.402539 {RSX.W4} RSX: Program compiled successfully
·! 0:17:38.590975 {RSX [0x006d2a0]} RSX: Add program (vp id = 638, fp id = 8150)
·S 0:17:38.595372 {RSX.W5} RSX: Program compiled successfully
·! 0:17:38.838688 {RSX [0x00dfd18]} RSX: Add program (vp id = 4151, fp id = 8290)
·! 0:17:38.843289 {RSX [0x00e02e4]} RSX: Add program (vp id = 4151, fp id = 8290)
```
It's just recompiling the same shader over and over again. This means possibly a difference in pipeline state is the cause, that needs to be looked at. This issue existed before and was fixed using an analyzer pass, that just needs to be improved to cover such scenarios.

**Comment by digant73** [comment]
maybe this bug has been fixed by #16568 recently merged on master branch. It should be better to re-test now

**Comment by 3Edu** [comment]
> maybe this bug has been fixed by [#16568](https://github.com/RPCS3/rpcs3/pull/16568) recently merged on master branch. It should be better to re-test now

Did a quick test and the problem remains on current version. 

**Footage:** 
https://streamable.com/jdu8yp

**LOG:**
[RPCS3.log](https://github.com/user-attachments/files/18478416/RPCS3.log)

**Comment by digant73** [comment]
did you try also a second run? just to be sure the cache was eventually filled in in case it was empty on the first run

**Comment by 3Edu** [comment]
> did you try also a second run? just to be sure the cache was eventually filled in in case it was empty on the first run. Verify also that `Disable On-Disk Shader Cache` on `Advanced` tab is not enabled

Yes, here some footage of the 3rd run:

https://streamable.com/nxr3eb

I also did as you mentioned, but the results were similar. 

Here's some footage with a empty shader cache, Disable On-Disk Shader Cache (enabled) **+ Shader mode (GPU Tab) on Legacy**. Massive stutterings when flashlight is on but no flashing textures, maybe it's something related to async shaders.

Footage:
https://streamable.com/78ovo6

**Comment by fpsdemon** [comment]
BLES01195's Tomb Raider: Underworld has the same issue I think. And if you modify Resolution Scale setting to above 100%, screen flashes reappear. If Resolution Scale set to 150% (1080p) it looks normal at first, but sooner or later screen flashing return when new shader compiled or some time has passed. If set to 300% (2160p), screen flashes immediately.

TRU (Resolution scale 3x) (Flashing warning)
[https://streamable.com/56obhu](https://streamable.com/56obhu)

Finally, if game is running at fullscreen, some time later screen flashes again with 720p too. And RPCS3's log says this:
`E 0:42:11.683184 {RSX [0x019620c]} RSX: Possible data corruption on frame context storage detected`
Log: [RPCS3.log.gz](https://github.com/user-attachments/files/18551749/RPCS3.log.gz)

**Comment by kd-11** [comment]
Unfortunately looks like the shaders are coming from some sort of JIT, as if the game is being run under some type of emulator or wrapper. They're extremely long and have a lot of variation. Some are like 6k instructions long just to do a basic effect, clearly this is coming from some dynamic runtime. Performance is also really bad on lower end cards because of this. There are some dupes getting rebuilt but those are really from just different state such as different renderpass configs.

This kind of thing shouldn't be a big deal once the interpreter is fixed up to be more usable, it should be the setting in use in such cases. That said, I'm still seeing some white flashes in async+interpreter mode despite there being no such glitches in legacy mode and pure interpreter mode.

**Comment by kd-11** [comment]
Hybrid mode no longer flickers. Just switch to asyc + interpreter for shader compiler and you should be fine. If you don't wish to wait for shaders to compile, disable the shader cache in advanced tab. It's the only consistent way to play the trilogy. Tested with croft manor and the experience was fine.

**Comment by kamikazilucas** [comment]
its still giving me glitches whenever it compiles

**Comment by Jonathan44062** [comment]
Needs to be re-open, the cracking shaders is still an issue

**Comment by audiowylde2345** [comment]
I have to put it on legacy single threaded to get it to stop it's still stutters a little bit but it's the only way to stop the unbearable flickering

**Comment by audiowylde2345** [comment]
I can confirm legend is the same thing.

**Comment by GuilhermeBSilva2002** [comment]
this still needs attention!! makes no sense why async + interpreter is the suggested shader mode on the wiki, it has major glitches with weird blinking colors in-game even when stationary, async recompiler multi threaded has flickering textures when compiling and single threaded has stuttering
