### ISSUE TITLE
Medals are not displayed in Wipeout HD/Fury

### ISSUE THREAD

**Issue by lsvy97** [RPCS3/rpcs3#15921]
### Quick summary

The medals are not displayed at the end of the race in in Wipeout HD/Fury. But they're supposed to be here.
![no medal 1](https://github.com/user-attachments/assets/2ca60a1e-89af-4b5e-b9a1-f4e2a0a49d8b)

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/16570382/RPCS3.log.gz)

### System configuration

Operating System
	Майкрософт Windows 11 Pro для рабочих станций 64-bit
CPU
	AMD Ryzen 5 5600	37 °C
	Vermeer 7nm Technology
RAM
	16,0ГБ Dual-Channel DDR4 @ 1197MHz (17-17-17-39)
Motherboard
	ASRock A520M Pro4 (AM4)	38 °C
Graphics
	SyncMaster (1280x1024@60Hz)
	8176MB ATI AMD Radeon RX 7600 (Gigabyte)
Storage
	931GB Seagate ST1000DM003-1ER162 (SATA )	29 °C
	931GB Samsung SSD 980 1TB (Unknown (SSD))
Optical Drives
	No optical disk drives detected
Audio
	AMD High Definition Audio Device

**Comment by ChaCheeChoo** [comment]
Same issue also applies to the Online Rank medals, both on the online main menu and post-race.

**Comment by b1scu1t** [comment]
It looks like this issue has been resolved as of RPCS3 Version: 0.0.36-17727-6511e0f3 Alpha | master.

![Image](https://github.com/user-attachments/assets/1963fef4-b271-4c65-b67a-6013cd4b9998)

As expected, the medal shows up in the in-game and on the results screen!

**Comment by lsvy97** [comment]
No, the issue still persists, even on the latest version

![Image](https://github.com/user-attachments/assets/22c9b0ae-8102-4a96-8416-864f2f023382)
