### ISSUE TITLE
[Bug] [macOS] [Arm] LLVM compiler crashes on complicated games

### ISSUE THREAD

**Issue by meh7an** [RPCS3/rpcs3#16002]
### Quick summary

By loading heavy PS3 games on an Apple Sillicon mac, the app crashes on crash when compiling a large number of SPU blocks

### Details

By loading a heavy game with a lot of SPU blocks, the game will crash with this fatal error:

```
F {PPU[0x1000000] main_thread} SIG: Thread terminated due to fatal error: Verification failed (object: 0x0)
(in file /Users/mehran/Documents/Projects/rpcs3/RPCS3-Arm-Build-Script/rpcs3/rpcs3/util/types.hpp:942[:102], in function decltype(auto) ensure(T &&, const_str, std::source_location) [T = bool]) (errno=2=No such file or directory)
```

Sometimes the SPU compilation continues a bit, but not further. The FPS counter keeps working until closing the game, which freezes the app:

```
E SIG: Thread [PPU[0x1000000] main_thread] is too sleepy. Waiting for it 21306.083µs already!
E SIG: Thread [PPU[0x1000000] main_thread] is too sleepy. Waiting for it 41302.500µs already!
...
E SIG: Thread [PPU[0x1000000] main_thread] is too sleepy. Waiting for it 5169650.750µs already!
E SIG: Thread [PPU[0x1000000] main_thread] is too sleepy. Waiting for it 10373992.625µs already!
```

And it can only be closed through Force Quit menu.

### Attach a log file

<details>
    <summary>The launch log</summary>

```
- SYS: RPCS3 v0.0.32-16873-e5b03d9c Alpha | master | local_build
- SYS: Apple M3 Max (10P+4E) | 14 Threads | 36.00 GiB RAM | TSC: 0.024GHz | FMA3
- SYS: Operating system: macOS, Version: 14.5.0
- SYS: Current Time: 2024-08-26T18:11:29
- RSX: Found Vulkan-compatible GPU: 'Apple M3 Max' running on driver 0.2.994
- SYS: Firmware version: 4.90
E PAT: Skipping patch data entry: [ be32, 0x00460434, 0x388000013 ] (key: PPU-c5d2fd31933f88313956774b84346d242979eba6, location: line 10142, column 6, file: /Users/mehran/Library/Application Support/rpcs3/patches/patch.yml) yaml-cpp: error at line 10143, column 27: bad conversion
E PAT: Skipping invalid patch node Disable Fisheye: (key: PPU-c5d2fd31933f88313956774b84346d242979eba6, location: line 10170, column 4, file: /Users/mehran/Library/Application Support/rpcs3/patches/patch.yml)
E PAT: Skipping patch data entry: [ be32, 0x00460434, 0x388000013 ] (key: PPU-8fd7b704255420d0e9a6b337b6d1bcaae39ff569, location: line 10142, column 6, file: /Users/mehran/Library/Application Support/rpcs3/patches/patch.yml) yaml-cpp: error at line 10143, column 27: bad conversion
E PAT: Skipping invalid patch node Disable Fisheye: (key: PPU-8fd7b704255420d0e9a6b337b6d1bcaae39ff569, location: line 10199, column 4, file: /Users/mehran/Library/Application Support/rpcs3/patches/patch.yml)
S SYS: Updates found at /dev_hdd0/game/BCUS98174/
E PAT: Skipping patch data entry: [ be32, 0x00460434, 0x388000013 ] (key: PPU-c5d2fd31933f88313956774b84346d242979eba6, location: line 10142, column 6, file: /Users/mehran/Library/Application Support/rpcs3/patches/patch.yml) yaml-cpp: error at line 10143, column 27: bad conversion
E PAT: Skipping invalid patch node Disable Fisheye: (key: PPU-c5d2fd31933f88313956774b84346d242979eba6, location: line 10170, column 4, file: /Users/mehran/Library/Application Support/rpcs3/patches/patch.yml)
E PAT: Skipping patch data entry: [ be32, 0x00460434, 0x388000013 ] (key: PPU-8fd7b704255420d0e9a6b337b6d1bcaae39ff569, location: line 10142, column 6, file: /Users/mehran/Library/Application Support/rpcs3/patches/patch.yml) yaml-cpp: error at line 10143, column 27: bad conversion
E PAT: Skipping invalid patch node Disable Fisheye: (key: PPU-8fd7b704255420d0e9a6b337b6d1bcaae39ff569, location: line 10199, column 4, file: /Users/mehran/Library/Application Support/rpcs3/patches/patch.yml)
S PAT: Applied patch (hash='PPU-120fb71f7352d62521c639b0e99f960018c10a56', description='Bug Fix: University Nailbomb Softlock Fix', author='illusion, ZEROx', patch_version='1.0', file_version='1.2') (<- 18)
S PAT: Applied patch (hash='PPU-120fb71f7352d62521c639b0e99f960018c10a56', description='Disable SSAO', author='JohnHolmesII, ZEROx, illusion, Juhn', patch_version='1.1', file_version='1.2') (<- 1)
S PAT: Applied patch (hash='PPU-120fb71f7352d62521c639b0e99f960018c10a56', description='Disable Motion Blur', author='JohnHolmesII, ZEROx, illusion, Juhn', patch_version='1.0', file_version='1.2') (<- 1)
S PAT: Applied patch (hash='PPU-120fb71f7352d62521c639b0e99f960018c10a56', description='Bug Fix: Infected Severed Head Crash', author='illusion, ZEROx', patch_version='1.0', file_version='1.2') (<- 6)
S PAT: Applied patch (hash='PPU-120fb71f7352d62521c639b0e99f960018c10a56', description='Disable in-built MLAA', author='Whatcookie, illusion, ZEROx', patch_version='4.0', file_version='1.2') (<- 67)
S PAT: Applied patch (hash='PPU-120fb71f7352d62521c639b0e99f960018c10a56', description='21:9 Aspect Ratio', author='illusion', patch_version='1.0', file_version='1.2') (<- 3)
S PAT: Applied patch (hash='PPU-120fb71f7352d62521c639b0e99f960018c10a56', description='WCB/WDB Performance fix', author='ZEROx', patch_version='1.0', file_version='1.2') (<- 10)
S PAT: Applied patch (hash='PPU-120fb71f7352d62521c639b0e99f960018c10a56', description='Disable Mesh trimming', author='JohnHolmesII, ZEROx, illusion, Juhn', patch_version='1.0', file_version='1.2') (<- 1)
S PAT: Applied patch (hash='PPU-120fb71f7352d62521c639b0e99f960018c10a56', description='Enable GPU Lighting', author='JohnHolmesII, ZEROx, illusion, Juhn', patch_version='2.0', file_version='1.2') (<- 126)
S PAT: Applied patch (hash='PPU-120fb71f7352d62521c639b0e99f960018c10a56', description='Unlock FPS', author='illusion', patch_version='1.0', file_version='1.2') (<- 1)
S PAT: Applied patch (hash='PPU-120fb71f7352d62521c639b0e99f960018c10a56', description='Depth border fix', author='JohnHolmesII, ZEROx, illusion, Juhn', patch_version='1.0', file_version='1.2') (<- 1)
S PAT: Applied patch (hash='PPU-120fb71f7352d62521c639b0e99f960018c10a56', description='Disable Depth of Field', author='JohnHolmesII, ZEROx, illusion, Juhn', patch_version='1.0', file_version='1.2') (<- 1)
S PAT: Applied patch (hash='PPU-120fb71f7352d62521c639b0e99f960018c10a56', description='Speedboost', author='ZEROx, illusion', patch_version='1.0', file_version='1.2') (<- 1)
S PAT: Applied patch (hash='PPU-120fb71f7352d62521c639b0e99f960018c10a56', description='Disable Bloom', author='JohnHolmesII, ZEROx, illusion, Juhn', patch_version='1.0', file_version='1.2') (<- 3)
S ppu_loader: PPU executable hash: PPU-120fb71f7352d62521c639b0e99f960018c10a56 (<- 240)
S PPU: Found valid roaming SPU code at 0xf4df80..0xf4f000 (guessed_ls_addr=0x4000, GUID=0xf4df80..0xf4f000)
S SPU: Found 4 SPU function(s)
S PPU: Found valid roaming SPU code at 0xf4f000..0xf64a00 (guessed_ls_addr=0x4000, GUID=0xf4f000..0xf64a00)
S SPU: Found 23 SPU function(s)
S PPU: Found valid roaming SPU code at 0xf64a00..0xf69500 (guessed_ls_addr=0x4000, GUID=0xf64a00..0xf69500)
S SPU: Found 28 SPU function(s)
S PPU: Found valid roaming SPU code at 0xf69500..0xf6ce00 (guessed_ls_addr=0x4000, GUID=0xf69500..0xf6ce00)
S SPU: Found 21 SPU function(s)
S PPU: Found valid roaming SPU code at 0xf80800..0xf90400 (guessed_ls_addr=0x4000, GUID=0xf80800..0xf90400)
S SPU: Found 39 SPU function(s)
S PPU: Found valid roaming SPU code at 0xf90400..0xf9cb00 (guessed_ls_addr=0x4000, GUID=0xf90400..0xf9cb00)
S SPU: Found 30 SPU function(s)
S PPU: Found valid roaming SPU code at 0xf9cb00..0xf9d580 (guessed_ls_addr=0x4000, GUID=0xf9cb00..0xf9d580)
S SPU: Found 3 SPU function(s)
S PPU: Found valid roaming SPU code at 0xf9d580..0xfbf680 (guessed_ls_addr=0x4000, GUID=0xf9d580..0xffffffff)
S SPU: Found 197 SPU function(s)
S PPU: Found valid roaming SPU code at 0xfc4700..0xfc5980 (guessed_ls_addr=0x4000, GUID=0xfc4700..0xfc5980)
S SPU: Found 8 SPU function(s)
S PPU: Found valid roaming SPU code at 0xfc7100..0xfcc000 (guessed_ls_addr=0x4000, GUID=0xfc7100..0xfcc000)
S SPU: Found 10 SPU function(s)
S PPU: Found valid roaming SPU code at 0xfcc000..0xfcdf80 (guessed_ls_addr=0x4000, GUID=0xfcc000..0xfcdf80)
S SPU: Found 2 SPU function(s)
S PPU: Found valid roaming SPU code at 0xfe7880..0xff4f80 (guessed_ls_addr=0x4000, GUID=0xfe7880..0xff4f80)
S SPU: Found 40 SPU function(s)
S PPU: Found valid roaming SPU code at 0xff4f80..0xff5200 (guessed_ls_addr=0x4000, GUID=0xff4f80..0xff5200)
S SPU: Found 1 SPU function(s)
S PPU: Found valid roaming SPU code at 0xff8380..0xff8f80 (guessed_ls_addr=0x4000, GUID=0xff8380..0xff8f80)
S SPU: Found 2 SPU function(s)
S PPU: Found valid roaming SPU code at 0xfffc00..0x1000680 (guessed_ls_addr=0x4000, GUID=0xfffc00..0x1000680)
S SPU: Found 1 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1008980..0x1009600 (guessed_ls_addr=0x4000, GUID=0x1008980..0x1009600)
S SPU: Found 3 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1019100..0x101a200 (guessed_ls_addr=0x4000, GUID=0x1019100..0x101a200)
S SPU: Found 2 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1034400..0x1036000 (guessed_ls_addr=0x4000, GUID=0x1034400..0x1036000)
S SPU: Found 4 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1036000..0x103cb00 (guessed_ls_addr=0x4000, GUID=0x1036000..0x103cb00)
S SPU: Found 12 SPU function(s)
S PPU: Found valid roaming SPU code at 0x103cb00..0x1042000 (guessed_ls_addr=0x4000, GUID=0x103cb00..0x1042000)
S SPU: Found 9 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1042000..0x1043a00 (guessed_ls_addr=0x4000, GUID=0x1042000..0x1043a00)
S SPU: Found 2 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1043a00..0x1054700 (guessed_ls_addr=0x4000, GUID=0x1043a00..0x1054700)
S SPU: Found 15 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1054700..0x1059d00 (guessed_ls_addr=0x4000, GUID=0x1054700..0x1059d00)
S SPU: Found 10 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1059d00..0x106a800 (guessed_ls_addr=0x4000, GUID=0x1059d00..0x106a800)
S SPU: Found 49 SPU function(s)
S PPU: Found valid roaming SPU code at 0x106a800..0x106bf80 (guessed_ls_addr=0x4000, GUID=0x106a800..0x106bf80)
S SPU: Found 9 SPU function(s)
S PPU: Found valid roaming SPU code at 0x106bf80..0x106f600 (guessed_ls_addr=0x4000, GUID=0x106bf80..0x106f600)
S SPU: Found 9 SPU function(s)
S PPU: Found valid roaming SPU code at 0x106f600..0x1071d00 (guessed_ls_addr=0x4000, GUID=0x106f600..0x1071d00)
S SPU: Found 1 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1071d00..0x1072980 (guessed_ls_addr=0x4000, GUID=0x1071d00..0x1072980)
S SPU: Found 1 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1072980..0x1073e00 (guessed_ls_addr=0x4000, GUID=0x1072980..0x1073e00)
S SPU: Found 3 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1073e00..0x1077600 (guessed_ls_addr=0x4000, GUID=0x1073e00..0x1077600)
S SPU: Found 9 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1077600..0x1078c80 (guessed_ls_addr=0x4000, GUID=0x1077600..0x1078c80)
S SPU: Found 4 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1078c80..0x1087900 (guessed_ls_addr=0x4000, GUID=0x1078c80..0x1087900)
S SPU: Found 65 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1087900..0x109ad00 (guessed_ls_addr=0x4000, GUID=0x1087900..0x109ad00)
S SPU: Found 98 SPU function(s)
S PPU: Found valid roaming SPU code at 0x109ad00..0x109fb80 (guessed_ls_addr=0x4000, GUID=0x109ad00..0x109fb80)
S SPU: Found 26 SPU function(s)
S PPU: Found valid roaming SPU code at 0x10b5b00..0x10be880 (guessed_ls_addr=0x4000, GUID=0x10b5b00..0x10be880)
S SPU: Found 30 SPU function(s)
S PPU: Found valid roaming SPU code at 0x10be880..0x10c5880 (guessed_ls_addr=0x4000, GUID=0x10be880..0x10c5880)
S SPU: Found 21 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1102c80..0x1105e00 (guessed_ls_addr=0x4000, GUID=0x1102c80..0x1105e00)
S SPU: Found 15 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1105e00..0x1113800 (guessed_ls_addr=0x4000, GUID=0x1105e00..0x1113800)
S SPU: Found 65 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1113800..0x1121200 (guessed_ls_addr=0x4000, GUID=0x1113800..0x1121200)
S SPU: Found 48 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1121200..0x1124180 (guessed_ls_addr=0x4000, GUID=0x1121200..0x1124180)
S SPU: Found 20 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1124180..0x1130e00 (guessed_ls_addr=0x4000, GUID=0x1124180..0x1130e00)
S SPU: Found 44 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1130e00..0x1132700 (guessed_ls_addr=0x4000, GUID=0x1130e00..0x1132700)
S SPU: Found 10 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1132700..0x1134a00 (guessed_ls_addr=0x4000, GUID=0x1132700..0x1134a00)
S SPU: Found 3 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1135880..0x1138180 (guessed_ls_addr=0x4000, GUID=0x1135880..0x1138180)
S SPU: Found 5 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1138180..0x1140500 (guessed_ls_addr=0x4000, GUID=0x1138180..0x1140500)
S SPU: Found 15 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1140500..0x114a000 (guessed_ls_addr=0x4000, GUID=0x1140500..0x114a000)
S SPU: Found 13 SPU function(s)
S PPU: Found valid roaming SPU code at 0x114a000..0x114cc00 (guessed_ls_addr=0x4000, GUID=0x114a000..0x114cc00)
S SPU: Found 10 SPU function(s)
S PPU: Found valid roaming SPU code at 0x114cc00..0x114d900 (guessed_ls_addr=0x0, GUID=0x114cc00..0x114d900)
S SPU: Found 1 SPU function(s)
S PPU: Found valid roaming SPU code at 0x114d900..0x1153980 (guessed_ls_addr=0x0, GUID=0x114d900..0x1153980)
S SPU: Found 14 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1153980..0x1153d80 (guessed_ls_addr=0x0, GUID=0x1153980..0x1153d80)
S PPU: Found valid roaming SPU code at 0x1153d80..0x1154e00 (guessed_ls_addr=0x0, GUID=0x1153d80..0x1154e00)
S SPU: Found 1 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1154e00..0x1156a00 (guessed_ls_addr=0x0, GUID=0x1154e00..0x1156a00)
S SPU: Found 4 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1156a00..0x1158600 (guessed_ls_addr=0x0, GUID=0x1156a00..0x1158600)
S SPU: Found 4 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1158600..0x1159480 (guessed_ls_addr=0x0, GUID=0x1158600..0x1159480)
S PPU: Found valid roaming SPU code at 0x1159480..0x1159c00 (guessed_ls_addr=0x0, GUID=0x1159480..0x1159c00)
S SPU: Found 6 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1159c00..0x115fd00 (guessed_ls_addr=0x0, GUID=0x1159c00..0x115fd00)
S SPU: Found 30 SPU function(s)
S PPU: Found valid roaming SPU code at 0x115fd00..0x1163b80 (guessed_ls_addr=0x0, GUID=0x115fd00..0x1163b80)
S SPU: Found 8 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1163b80..0x1164600 (guessed_ls_addr=0x0, GUID=0x1163b80..0x1164600)
S SPU: Found 2 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1164600..0x1165a80 (guessed_ls_addr=0x0, GUID=0x1164600..0x1165a80)
S SPU: Found 1 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1165a80..0x1186a00 (guessed_ls_addr=0x0, GUID=0x1165a80..0x1186a00)
S SPU: Found 124 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1186a00..0x11af080 (guessed_ls_addr=0x3000, GUID=0x1186a00..0x11af080)
S SPU: Found 182 SPU function(s)
S PPU: Found valid roaming SPU code at 0x11af080..0x11b4e80 (guessed_ls_addr=0x4000, GUID=0x11af080..0x11b4e80)
S SPU: Found 24 SPU function(s)
S PPU: Found valid roaming SPU code at 0x11b4e80..0x11c9d00 (guessed_ls_addr=0x4000, GUID=0x11b4e80..0x11c9d00)
S SPU: Found 100 SPU function(s)
S PPU: Found valid roaming SPU code at 0x11c9d00..0x11ebc80 (guessed_ls_addr=0x4000, GUID=0x11c9d00..0x11ebc80)
S SPU: Found 184 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1209380..0x1222800 (guessed_ls_addr=0x4000, GUID=0x1209380..0x1222800)
S SPU: Found 103 SPU function(s)
S PPU: Found valid roaming SPU code at 0x1222800..0x122bc00 (guessed_ls_addr=0x0, GUID=0x1222800..0x122bc00)
S SPU: Found 32 SPU function(s)
S PPU: Enabled: Non-Java Mode Fixup
- RSX: Found Vulkan-compatible GPU: 'Apple M3 Max' running on driver 0.2.994
E RSX: Your GPU driver does not support some required MSAA features. MSAA will be disabled.
E RSX: Your GPU does not support double precision floats in shaders. Graphics may not render correctly.
E RSX: Your GPU does not support depth bounds testing. Graphics may not render correctly.
E RSX: Your GPU does not support wide lines. Graphics may not render correctly.
E RSX: Your GPU does not support framebuffer logical operations. Graphics may not render correctly.
E RSX: Apple GPUs are incompatible with the current implementation of asynchronous texture decoding.
S Input: The pad mode was changed to Single-threaded
S GUI: Boot successful.
S PPU: LLVM: Compiled module v6-kusa-GvEKa7d4ZjyC7rJt4fLEVu-00001G-apple-m1.obj
S PPU: LLVM: Compiled module v6-kusa-cJMoykFdr3r4Wk7Y0a7oA8-00001G-apple-m1.obj
S PPU: LLVM: Compiled module v6-kusa-1q8t9QtVGWpmXerwfQ98vb-00001G-apple-m1.obj
S PPU: LLVM: Compiled module v6-kusa-KkvPA1Lx0x0MFUaig5e2ZJ-00001G-apple-m1.obj
S PPU: LLVM: Compiled module v6-kusa-CfS1YfN8kknj7zC8oqjjMZ-00001G-apple-m1.obj
S PPU: LLVM: Compiled module v6-kusa-b5vANTz5ZWr5XWQ3Lt3kAm-00001G-apple-m1.obj
S PPU: LLVM: Compiled module v6-kusa-h6b4MjWuMHG85JhKZE7crb-00001G-apple-m1.obj
S PPU: LLVM: Compiled module v6-kusa-iY3QowsSFCA8WvsVQGKS0K-00001G-apple-m1.obj
S PPU: LLVM: Compiled module v6-kusa-t71RCLH3jzMLk0HdxgGhVA-00001G-apple-m1.obj
...
S PPU: LLVM: Compiled module v6-kusa-KaFr2zGnq4ZQNT1Esjk6jJ-00001G-apple-m1.obj
S PPU: LLVM: Compiled module v6-kusa-eQYyM5RXhsqrWKqpYonxbZ-00001G-apple-m1.obj
S PPU: LLVM: Compiled module v6-kusa-dK7At6P36xyRh2fb5TYffo-00001G-apple-m1.obj
S PPU: LLVM: Compiled module v6-kusa-KYzvuc9tJ5zfWPrHXfv99o-00001G-apple-m1.obj
S PPU: LLVM: Compiled module v6-kusa-G3WsQkoLX8NEHbVKKfknG4-00001G-apple-m1.obj
S PPU: LLVM: Compiled module v6-kusa-5Wr6o0Wxke8ghH2WWnioxW-00001G-apple-m1.obj
S PPU: LLVM: Compiled module v6-kusa-QoMQU3T8kSAH4cQhoT1x9Y-00001G-apple-m1.obj
S PPU: LLVM: Compiled module v6-kusa-NMpbKtiTnTL9hAHxo5J4n5-0004Xj-apple-m1.obj
S PPU: LLVM: Loaded module v6-kusa-UAxtfWCozPHiv30yoG2Ucd-0004Xj-apple-m1.obj
S SPU: SPU Runtime: Built the interpreter.
U SPU TODO: [__spu-0x04428-FJJah41gZmG9WRtxSuf16Ndf0nPi:0x04500] Unmatched spu_rsqrte(c) found in FMA
U SPU TODO: [__spu-0x04520-fx48rRHj7bSEAnznrwb35FegNTrG:0x045cc] Unmatched spu_re(b) found in FMA
U SPU TODO: [__spu-0x04520-fx48rRHj7bSEAnznrwb35FegNTrG:0x047f0] Unmatched spu_rsqrte(c) found in FMA
U SPU TODO: [__spu-0x04520-fx48rRHj7bSEAnznrwb35FegNTrG:0x048b8] Unmatched spu_rsqrte(c) found in FMA
S SPU: New SPU block compiled successfully (size=18)
S SPU: New SPU block compiled successfully (size=15)
S SPU: New SPU block compiled successfully (size=6)
S SPU: New SPU block compiled successfully (size=44)
S SPU: New SPU block compiled successfully (size=2)
S SPU: New SPU block compiled successfully (size=12)
U SPU TODO: [__spu-0x08118-PJn0LwrTrAogoQy8K16oJ7kWzUQv:0x08254] Unmatched spu_re(b) found in FMA
S SPU: New SPU block compiled successfully (size=26)
S SPU: New SPU block compiled successfully (size=1)
U SPU TODO: [__spu-0x082b8-kPgXfJqb1LgG3NdSocoGXUayhpPr:0x08358] Unmatched spu_rsqrte(c) found in FMA
U SPU TODO: [__spu-0x082b8-kPgXfJqb1LgG3NdSocoGXUayhpPr:0x08370] Unmatched spu_re(b) found in FMA
U SPU TODO: [__spu-0x082b8-kPgXfJqb1LgG3NdSocoGXUayhpPr:0x0849c] Unmatched spu_re(b) found in FMA
S SPU: New SPU block compiled successfully (size=62)
S SPU: New SPU block compiled successfully (size=76)
S SPU: New SPU block compiled successfully (size=62)
U SPU TODO: [__spu-0x0f9c8-tM8QkXm20duC2L45qu4ZCGSJNWC3:0x0fdd0] Unmatched spu_re(b) found in FMA
U SPU TODO: [__spu-0x085b8-L6U1YNtRiWdrcik2Vo7zm1PZ0C4E:0x088c0] Unmatched spu_re(b) found in FMA
U SPU TODO: [__spu-0x085b8-L6U1YNtRiWdrcik2Vo7zm1PZ0C4E:0x08758] Unmatched spu_re(b) found in FMA
U SPU TODO: [__spu-0x085b8-L6U1YNtRiWdrcik2Vo7zm1PZ0C4E:0x08bb8] Unmatched spu_re(b) found in FMA
S SPU: New SPU block compiled successfully (size=83)
S SPU: New SPU block compiled successfully (size=99)
S SPU: New SPU block compiled successfully (size=9)
S SPU: New SPU block compiled successfully (size=86)
S SPU: New SPU block compiled successfully (size=35)
S SPU: New SPU block compiled successfully (size=100)
S SPU: New SPU block compiled successfully (size=104)
S SPU: New SPU block compiled successfully (size=13)
S SPU: New SPU block compiled successfully (size=119)
S SPU: New SPU block compiled successfully (size=182)

.....

S SPU: New SPU block compiled successfully (size=14)
S SPU: New SPU block compiled successfully (size=9)
S SPU: New SPU block compiled successfully (size=72)
S SPU: New SPU block compiled successfully (size=10)
S SPU: New SPU block compiled successfully (size=62)
S SPU: New SPU block compiled successfully (size=4)
S SPU: New SPU block compiled successfully (size=38)
S SPU: New SPU block compiled successfully (size=61)
S SPU: New SPU block compiled successfully (size=261)
S SPU: New SPU block compiled successfully (size=11)
S SPU: New SPU block compiled successfully (size=1)
S SPU: New SPU block compiled successfully (size=433)
S SPU: New SPU block compiled successfully (size=14)
S SPU: New SPU block compiled successfully (size=10)
S SPU: New SPU block compiled successfully (size=6)
S SPU: New SPU block compiled successfully (size=82)
S SPU: New SPU block compiled successfully (size=40)
S SPU: New SPU block compiled successfully (size=11)
S SPU: New SPU block compiled successfully (size=198)
S SPU: New SPU block compiled successfully (size=2)
F {SPU Worker 1} SIG: Thread terminated due to fatal error: Verification failed (object: 0x0)
(in file /Users/mehran/Documents/Projects/rpcs3/RPCS3-Arm-Build-Script/rpcs3/rpcs3/util/types.hpp:942[:102], in function decltype(auto) ensure(T &&, const_str, std::source_location) [T = bool]) (errno=13=Permission denied)
S SPU: New SPU block compiled successfully (size=142)
S SPU: New SPU block compiled successfully (size=14)
S SPU: New SPU block compiled successfully (size=1)
S SPU: New SPU block compiled successfully (size=62)
S SPU: New SPU block compiled successfully (size=96)
S SPU: New SPU block compiled successfully (size=11)
S SPU: New SPU block compiled successfully (size=96)
S SPU: New SPU block compiled successfully (size=210)
S SPU: New SPU block compiled successfully (size=1)
S SPU: New SPU block compiled successfully (size=38)
S SPU: New SPU block compiled successfully (size=110)
S SPU: New SPU block compiled successfully (size=22)
S SPU: New SPU block compiled successfully (size=96)

.....

S SPU: New SPU block compiled successfully (size=11)
S SPU: New SPU block compiled successfully (size=58)
S SPU: New SPU block compiled successfully (size=71)
S SPU: New SPU block compiled successfully (size=30)
S SPU: New SPU block compiled successfully (size=4) x2
S SPU: New SPU block compiled successfully (size=57)
S SPU: New SPU block compiled successfully (size=61)
S SPU: New SPU block compiled successfully (size=2)
S SPU: New SPU block compiled successfully (size=18)
S SPU: New SPU block compiled successfully (size=14)
S SPU: New SPU block compiled successfully (size=20)
S SPU: New SPU block compiled successfully (size=70)
S SPU: New SPU block compiled successfully (size=30)
S SPU: New SPU block compiled successfully (size=38)
S SPU: New SPU block compiled successfully (size=6) x2
S SPU: New SPU block compiled successfully (size=4)
S SPU: New SPU block compiled successfully (size=88)
U SPU TODO: [__spu-0x04df8-P7pe5mV49KeWc7a57JH6jJg0VkvZ:0x04f50] Unmatched spu_re(b) found in FMA
S SPU: New SPU block compiled successfully (size=31)
S SPU: New SPU block compiled successfully (size=2)
S SPU: New SPU block compiled successfully (size=14)
S SPU: New SPU block compiled successfully (size=74)
E SIG: Thread [PPU[0x1000000] main_thread] is too sleepy. Waiting for it 21306.083µs already!
E SIG: Thread [PPU[0x1000000] main_thread] is too sleepy. Waiting for it 41302.500µs already!
E SIG: Thread [PPU[0x1000000] main_thread] is too sleepy. Waiting for it 81403.125µs already!
E SIG: Thread [PPU[0x1000000] main_thread] is too sleepy. Waiting for it 162098.542µs already!
E SIG: Thread [PPU[0x1000000] main_thread] is too sleepy. Waiting for it 322626.042µs already!
E SIG: Thread [PPU[0x1000000] main_thread] is too sleepy. Waiting for it 643859.833µs already!
E SIG: Thread [PPU[0x1000000] main_thread] is too sleepy. Waiting for it 1286014.375µs already!
E SIG: Thread [PPU[0x1000000] main_thread] is too sleepy. Waiting for it 2595768.792µs already!
E SIG: Thread [PPU[0x1000000] main_thread] is too sleepy. Waiting for it 5169650.750µs already!
E SIG: Thread [PPU[0x1000000] main_thread] is too sleepy. Waiting for it 10373992.625µs already!
E SIG: Thread [PPU[0x1000000] main_thread] is too sleepy. Waiting for it 20789432.125µs already!
E SIG: Thread [PPU[0x1000000] main_thread] is too sleepy. Waiting for it 41603212.333µs already!
E SIG: Thread [PPU[0x1000000] main_thread] is too sleepy. Waiting for it 83256908.667µs already!
E SIG: Thread [PPU[0x1000000] main_thread] is too sleepy. Waiting for it 166723724.292µs already!
```

</details>

### System configuration

Apple M3 Max 36GB Sonoma 14.5

**Comment by meh7an** [comment]
One reason I found that reproduces this issue, is enabling the "Skip intro" patch of GoW3. Without it, the game can run correctly for me.
<details>
    <summary> "Skip intro":</summary>

    Games: *gow3_103_title
    Author: "illusion, ZEROx"
    Notes: *gow3_skipintro_notes
    Patch Version: 2.0
    Patch:
      - [ byte, 0x00588e50, 0x01 ]       # Skip SCEA logos
      - [ be32, 0x002712b4, 0x4816ce9d ] # bl 0x003de150
      - [ be32, 0x003de150, 0x7d4802a6 ] # mfspr r10,LR
      - [ be32, 0x003de154, 0x3d200055 ] # lis r9,0x55
      - [ be32, 0x003de158, 0x8009fcc5 ] # lwz r0,-0x33b(r9)
      - [ be32, 0x003de15c, 0x3d206f00 ] # lis r9,0x6f00
      - [ be32, 0x003de160, 0x7f804800 ] # cmpw cr7,r0,r9
      - [ be32, 0x003de164, 0x419e001c ] # beq cr7,0x003de180
      - [ be32, 0x003de168, 0x3d206e67 ] # lis r9,0x6e67
      - [ be32, 0x003de16c, 0x39294372 ] # addi r9,r9,0x4372
      - [ be32, 0x003de170, 0x7f804800 ] # cmpw cr7,r0,r9
      - [ be32, 0x003de174, 0x419e000c ] # beq cr7,0x003de180
      - [ be32, 0x003de178, 0x801b0f5c ] # lwz r0,0xf5c(r27) // original
      - [ be32, 0x003de17c, 0x4800000c ] # b 0x003de188
      - [ be32, 0x003de180, 0x394a0020 ] # addi r10,r10,0x20 // branch to skip video function
      - [ be32, 0x003de184, 0x7d4803a6 ] # mtspr LR,r10
      - [ be32, 0x003de188, 0x4e800020 ] # blr
  </details>

**Comment by squidbus** [comment]
Not sure if it's directly related since I get a hard crash to desktop on this, but since you mentioned game patches, applying the [Sonic 06 graphics fix canary patches](https://wiki.rpcs3.net/index.php?title=Sonic_The_Hedgehog#Special_Notes) is also crashing for me. Works fine with x86_64 builds.

**Comment by kd-11** [comment]
Do any patches work? I'll try and find some patch to unlock fps.

**Comment by meh7an** [comment]
Most of the patches work on GoW3, even from the two submitted skip intro patches, one works.
From my tests, GoW Ascension and TLoU don't work even without patches. GoW Col1&2 work either ways. It's just so random.
Sometimes when happens, the SPU compilation finishes in a snap just showing the error.

**Comment by shinra-electric** [comment]
Patches work on Demon’s Souls (60fps and skip intros)

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/16011 fixes this, though I'm not sure if it negatively affects the x86 version of the app for macos. Please test if the rosetta version is still working ok.

**Comment by squidbus** [comment]
Not seeing the `Verification failed` crash anymore with that PR, although I am seeing games reach the end of compilation, and the log says that the compile completed, but the game is just stuck on the compiling screen with the full progress bar. This is with a fresh cache directory.

**Comment by shinra-electric** [comment]
With PR 16011 I can consistently build the cache for the first time and get in-game using 8 threads. 

However, when booting for a second time with an existing cache, one of the SPU threads will segfault. The thread number and locations are usually different.

```
F {SPU Worker 6} SYS: 
Segfault writing location 00000003002ccec0 at 0000000100efbc3c.
Emu Thread Name: 'SPU Worker 6'.

F {SPU Worker 6} SIG: Thread terminated due to fatal error: Segfault writing location 00000003002ccec0 at 0000000100efbc3c.
Emu Thread Name: 'SPU Worker 6'.
```

**Comment by kd-11** [comment]
The segfault is likely another case of MAP_JIT getting in the way. I'll try to reproduce.

**Comment by kd-11** [comment]
It is now fixed correctly. Multiple threads were calling mmap at the same time and getting back the same pointer.

**Comment by kd-11** [comment]
And I just got it again. I hate this OS.

**Comment by kd-11** [comment]
I've disabled parallel JIT memory allocation on MacOS. That should solve the crashes.

**Comment by squidbus** [comment]
Not seeing any SPU compile crashes anymore with thread count maxed out although I'm still seeing games hang on the compile screen at first boot with a fresh cache folder, then it works if I try again. Have some of this error in the log if it's related:
```
F {PPUW.23.0} SIG: Thread terminated due to fatal error: Verification failed (object: 0x0)
(in file rpcs3/rpcs3/util/vm_native.cpp:348[:3], in function void utils::memory_decommit(void *, usz)) (errno=2=No such file or directory)
```

**Comment by kd-11** [comment]
I'm not able to replicate this one, though it is ilkely related. Let's track it in a separate ticket.

**Comment by shinra-electric** [comment]
The latest commit disabling parallel JIT memory allocation seems to have resolved the issue. 

On lots of games I can load successfully whether it's first boot or using the cache. I haven't had any cases of the thread terminating. 

(I did notice a consistent stall with Ratchet & Clank, but there were no obvious error messages in the log and I assume it's a separate issue).

**Comment by Nekotekina** [comment]
Can MacOS overcommit memory like Linux does? If so, it could be solved more efficiently without mutex.

**Comment by kd-11** [comment]
> Can macOS overcommit memory like Linux does? If so, it could be solved more efficiently without mutex.

Yes, overcommit works. There were segfaults reported in games with too many blocks though, so I rolled that back.

**Comment by kd-11** [comment]
Btw, BSD also supports overcommit but we have it disabled. We may need to get more testing done on the other non-windows OSes other than linux.

**Comment by kd-11** [comment]
Maybe, though the same games worked ok on linux. MacOS is a lot more sensitive to memory management errors. If you get even one flag wrong it will throw errors.

**Comment by kd-11** [comment]
Something else I didn't think of at the time, but overcommit on macOS seems to default to something other than the "1" setting. Likely defaults to "2" so some cases are going to be rejected by the kernel. We can probably get this to work with some experimentation. I'll circle back around to it, I just needed to get the crashes out of the way to get testing underway.
