### ISSUE TITLE
[Mega Issue] Savestates

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#16216]
Here you can report issues with savestates, rant and complain about savestates.

**Comment by Darkhost1999** [comment]
Just Cause 2, VM: ConcSPUCellSpursKernel2 access violation writing location, on savestate load - kernel logged
[RPCS3.log](https://github.com/user-attachments/files/17460276/RPCS3.log)

**Comment by Foxeylady** [comment]
Hi. I've had trouble with savestates. The saving and loading seem to be fine until the moment when the game is supposed to open. But then there's only a split second of sound before it dies completely and nothing happens. So I'm guessing it's broken.

Other times, the save state actually loads, but then the game has no sound and it gets stuck on the next loading screen. 

Here are logs for both SS: Nr. 1 is the one that doesn't load and Nr. 2 the one that loads. 

[Save State 1 (Load).txt](https://github.com/user-attachments/files/17562473/Save.State.1.Load.txt)
[Save State 1 (Save).txt](https://github.com/user-attachments/files/17562477/Save.State.1.Save.txt)
[Save State 2 (Load).txt](https://github.com/user-attachments/files/17562478/Save.State.2.Load.txt)
[Save State 2 (Save).txt](https://github.com/user-attachments/files/17562479/Save.State.2.Save.txt)

**Comment by elad335** [comment]
@Foxeylady Can you upload the full logs? that is, RPCS3.log.gz?

To upload RPCS3's log, run your game first, then completely close RPCS3 and drag & drop the RPCS3.log.gz file into GitHub. The file may have a zip or rar icon. If you don't see the .log.gz file, or if RPCS3 crashed, look for the uncompressed log file instead. It will be named RPCS3.log, or show up as just RPCS3 with a notepad icon. Do not reopen RPCS3 before uploading as that will clear the log.

**Comment by Foxeylady** [comment]
I copied the entire logs into those files, I did it manually in order to separate them, So nothing should be missing in them, but I can also upload the full logs, if that's preferable.

**Comment by elad335** [comment]
@Foxeylady what you have copied from the *User Interface* is a brief of what the log *file* contains, it is not the full log. I have corrected my instructions on how to obtain the log file.

**Comment by Foxeylady** [comment]
Ah ok, then I'll upload the other thing

**Comment by Foxeylady** [comment]
Ok so it doesn't let me upload the gz file for some reason, so I just upload the text document. This contains the logs for both, the save and the load part. 

[RPCS3.log](https://github.com/user-attachments/files/17576955/RPCS3.log)

**Comment by MasterChief747** [comment]
One save state issue is Sonic the Hedgehog 2006. There is a graphical patch that fixes the graphics in this game. When you create a save state and load it, it seems the graphical patch doesn't get applied to the save state because the graphics are messed up again. Thank you!

**Comment by Chaoswizard98** [comment]
I've never had any issues creating save states, however when I boot a save state, I can only do so 3 times before RPCS3 freezes on the 4th attempt. Where the UI normally pops up to choose a save you wish to load, it doesn't do so on the 4th attempt and the game freezes causing the need to end the process and re-boot RPCS3 entirely.

1. Boot savestate (works fine)
2. Boot savestate again (works fine)
3. Boot savestate a third time (works fine)
4. Boot savestate a fourth time and the system freezes.

Rebooting RPCS3 after the third attempt, though a minor inconvenience, fixes the issue for another 3 loads.

**Comment by dudesh34** [comment]
hi,
Is it possible for you or megamouse to fix save state while using "guncon 3" setting? "megamouse" fixed save state with psmove setting yesterday.
thank you.

**Comment by Mithran573** [comment]
Whenever I try running savestates on Bakugan Battle Brawlers it keeps getting stuck on the "Processing Modules" part.

**Comment by durand237640** [comment]
Durand

**Comment by Dirka-ot-Bublika** [comment]
Hello everyone! There was a problem with most of the sounds disappearing after Savestate in Demon Souls in the elevator in front of Old King Allant. 
I am writing through a translator, so I apologize for the possible distortion of the text.
Thank you in advance for your help!

[RPCS3.log](https://github.com/user-attachments/files/21026112/RPCS3.log)

**Comment by hexad** [comment]
Hello. This may be a stupid question.
Do you think it could be possible to make a savestate, without having to reload the game and rebuilt the SPU cache, etc?

**Comment by elad335** [comment]
SPU issues have been fixed which have been the majority here, remaining issues should be scattered in new issues with detailed reports.

**Comment by MasterChief747** [comment]
This issue hasn't been fixed because Sonic 2006 still crashes when doing a savestate. It says "the ps3 application has likely crashed. You can close it". Then after I close it, I try boot last save state and nothing happens. I quit the app and when I try to reopen it it says another instance is running. Then I have to force close it from the task manager. Will there be a fix to the save state crash? Will there be a fix so that the graphics patch for this game can be applied when doing a save state because it wouldn't get applied in previous versions of this program. Thank you!
________________________________

**Comment by MasterChief747** [comment]
This issue hasn't been fixed because Sonic 2006 still crashes when doing a savestate. It says "the ps3 application has likely crashed. You can close it". Then after I close it, I try boot last save state and nothing happens. I quit the app and when I try to reopen it it says another instance is running. Then I have to force close it from the task manager. Will there be a fix to the save state crash? Will there be a fix so that the graphics patch for this game can be applied when doing a save state because it wouldn't get applied in previous versions of this program. Thank you!
