### ISSUE TITLE
BCES00609: InFamous - Vulkan Error "Device Lost"

### ISSUE THREAD

**Issue by VladOFF92** [RPCS3/rpcs3#16349]
### Quick summary

Greetings!
After first try to play InFamous I took "VK_Error: Device Lost" trouble.

### Details

I'm using Vulkan renderer as usual and games looking and working good ordinary (God of War 3, Demon's Souls etc.). But InFamous crashes every time when I try to boot this game. When I change render to OpenGL, game starts and plays without this error, but looks worse and many microfreezes appear. How can I play InFamous just with Vulkan without this bug?
![Безымянный](https://github.com/user-attachments/assets/75d4c1ec-8365-45c4-8010-d47f7f3c7b5b)

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/17895456/RPCS3.log)

### System configuration

Windows 10 Pro
Intel Xeon E5-2690 v4
Asus Strix GTX 970
32 Gb RAM
SSD 480 Gb (only for emulators and games)

**Comment by Jonathan44062** [comment]
That error message is related to this: https://github.com/RPCS3/rpcs3/issues/15289
So please report your issue there

**Comment by digant73** [comment]
I also have this issue in particular with some Infomniac's games (frequently present in R1 and R3, not present in R2). At the beginning, I thought it was due to my old GPU gtx 970 (4GB) so I decided to make some testing on a recent rtx 4060 (8GB). The issue is present also on the rtx 4060. Tested on latest and also on old nvidia drivers.

Some questions to main developers:
* does it make sense to test on an amd gpu (in case the issue is on nvidia drivers)? If the issue will be present also on that gpu, could it be enough to assume the issue is on rpcs3 or maybe it could be on another layer (e.g. vulkan)? If the issue could be in vulkan, is it possible to post a guide (e.g. on a FAQ page instead of an issue thread) on how to collect info that could be shared to main developers to address the issue?
* the fact that the issue is present on some games in particular and not present at all on other AAA games (such as KZ3, KZ2 etc...) could it be related to some features used by the games that maybe could be reported by some already existing tools integrated on rpcs3 and compared with the features of the games not affected by the issue?

**Comment by digant73** [comment]
@VladOFF92 still having the issue? if so try if the attached `rpcs3.exe` fixes it (make a backup of your current exe and replace it with  the attached one).

[rpcs3.zip](https://github.com/user-attachments/files/20014949/rpcs3.zip)

**Comment by digant73** [comment]
@VladOFF92 this issue should be probably fixed now. Please update to latest version and let us know or close the ticket if fixed

**Comment by digant73** [comment]
tested the demo and pretty much sure the issue has been fixed by the recent fix on descriptors indexing. Same GPU here. No more device-lost after the merged fix

**Comment by digant73** [comment]
as previously reported without any reply from the user, this issue has been fixed by #17149 and this ticket could be closed. Fully tested on same GTX 970 and recent RTX 4060

**Comment by VladOFF92** [comment]
Finally, tried same versions of game (firmwares and regions). My results:
Versions for 3.60 Rogero (USA and EU) is still crashing randomly with "Device lost" error.
Version for 3.55 Cobra (EU) works really good. I finished some plot missions and sidequests, and game is still doesn't crashing. Have some troubles only with sound and graphical artifacts (broken shadows and smoke), but this things can be fixed by Canary Patches.
I don't know that's a difference between this versions of game, but I think it's something like a solution of my trouble.
TY for all, dudes, and sorry for silence.

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/16004a55-e17b-423c-9b0b-6650cf1be0d2" />
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/a622a25f-ccc8-4411-bfb4-a589e6b6596e" />
