### ISSUE TITLE
Unknown command GETLLAR, this error is only on OpenGL.

### ISSUE THREAD

**Issue by supergatto** [RPCS3/rpcs3#1678]
Reference logs: 
http://www.emunewz.net/forum/showthread.php?tid=156673&pid=231191#pid231191
http://www.emunewz.net/forum/showthread.php?tid=167799&pid=231072#pid231072
http://www.emunewz.net/forum/showthread.php?tid=174442

**Comment by raven02** [comment]
I'm closing this as it should be fixed

**Comment by supergatto** [comment]
Hi, this isn't fixed.
Read my log:
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/312290/RPCS3.zip)
I am using latest build: rpcs3-ReleaseLLVM-caf58941.zip

**Comment by raven02** [comment]
Please open another one and specific which game is still hitting this error.
