### ISSUE TITLE
RSX: Discrepancies between Asynchronous and Synchronous Memory Manager

### ISSUE THREAD

**Issue by MarioSonic2987** [RPCS3/rpcs3#16800]
Here's a list of games that break (graphical issues or crashes) when using Asynchronous or Synchronous Memory Manager.

### Asynchronous Memory Manager

- [ ] Split/Second - Improves lighting and some effects, but it makes the image look too blury. Enabling **_Allow Host GPU labels_** fixes it, but green/red artifacts sometimes appear.

### Synchronous Memory Manager

Note that Synchronous Memory Manager is the same as having the **_Disable Asynchronous Memory Manager_** setting enabled, in Advanced tab.

- [ ] Saints Row: The Third - Water shakes when you're close to it.

### Logs

<details>
 <summary>Saints Row: The Third</summary>

[Log SRTT Sync MM](https://github.com/user-attachments/files/19054588/RPCS3.log.SRTT.Sync.gz)
[Log SRTT Async MM](https://github.com/user-attachments/files/19054635/RPCS3.log.SRTT.Async.gz)

</details>

**Comment by digant73** [comment]
@MarioSonic2987 add to the list also #16845

**Comment by MarioSonic2987** [comment]
@digant73 Your build provided here (#16809) doesn't break Saints Row: The Third (water works fine) and Kingdom Hearts II Final Mix (no slowdowns when Roxas attacks).

In Split/Second, green/red artifacts no longer appear when using **Allow Host GPU labels**.
![Image](https://github.com/user-attachments/assets/e6aa044d-5109-4daf-abd5-26b98a569d70)

**Comment by MarioSonic2987** [comment]
Enabling Allow Host GPU labels fixes shaking water in Saints Row: The Third with Synchronous Memory Manager, but it breaks distant water reflections.
![Image](https://github.com/user-attachments/assets/5397d652-40f9-496e-a198-fe5baf5300b9)

Disabling Read Color Buffers fixes it.
![Image](https://github.com/user-attachments/assets/f91b4b71-cc66-4968-a963-2ddd4ad4726c)

**Comment by digant73** [comment]
@MarioSonic2987 please add to the list also #16794

**Comment by kd-11** [comment]
Any games here that actually crash with the setting in default state?

**Comment by digant73** [comment]
the following code replacing line 48 in `MM.cpp` seems to fix the reported games. There is only only condition that hit performance for `Need for Speed Most Wanted` (see inline comments on the code)

```
		// Basically an unlock op. Flush if any overlap is detected
		for (const auto& block : g_deferred_mprotect_queue)
		{
			if (block.overlaps(start, end))
			{
				if (prot == utils::protection::no)      // avoids some performance drop (about 2-3 fps) on "Need for Speed Most Wanted"
					mm_flush_mprotect_queue_internal(); // fixes "Split Second"

				utils::memory_protect(ptr, length, prot); // fixes "Motorsport Pacific Rift"
				return;
			}
		}

		// condition "g_deferred_mprotect_queue.empty() && prot == utils::protection::ro" fixes missing letters on "littlebigplanet" withou any performance drop in other games
		// condition "g_deferred_mprotect_queue.empty() && prot == utils::protection::no" fixes flashing video and red referee on intro video (not in gameplay) "Rock Band" and "MME 2k14" respectively
		//
		// NOTE: Unfortunately the condition "prot == utils::protection::no" results in destroying any benefit on performance increase in games such as "Need for Speed Most Wanted"
		//
		if (prot == utils::protection::rw || prot == utils::protection::wx || (g_deferred_mprotect_queue.empty() && (prot == utils::protection::ro || prot == utils::protection::no))) // changed code
		//if (prot == utils::protection::rw || prot == utils::protection::wx) // original code

```

**Comment by kd-11** [comment]
> the following code replacing line 48 in `MM.cpp` seems to fix the reported games. There is only only condition that hit performance for `Need for Speed Most Wanted` (see inline comments on the code)
> 
> ```
> 		// Basically an unlock op. Flush if any overlap is detected
> 		for (const auto& block : g_deferred_mprotect_queue)
> 		{
> 			if (block.overlaps(start, end))
> 			{
> 				if (prot == utils::protection::no)      // avoids some performance drop (about 2-3 fps) on "Need for Speed Most Wanted"
> 					mm_flush_mprotect_queue_internal(); // fixes "Split Second"
> 
> 				utils::memory_protect(ptr, length, prot); // fixes "Motorsport Pacific Rift"
> 				return;
> 			}
> 		}
> 
> 		// condition "g_deferred_mprotect_queue.empty() && prot == utils::protection::ro" fixes missing letters on "littlebigplanet" withou any performance drop in other games
> 		// condition "g_deferred_mprotect_queue.empty() && prot == utils::protection::no" fixes flashing video and red referee on intro video (not in gameplay) "Rock Band" and "MME 2k14" respectively
> 		//
> 		// NOTE: Unfortunately the condition "prot == utils::protection::no" results in destroying any benefit on performance increase in games such as "Need for Speed Most Wanted"
> 		//
> 		if (prot == utils::protection::rw || prot == utils::protection::wx || (g_deferred_mprotect_queue.empty() && (prot == utils::protection::ro || prot == utils::protection::no))) // changed code
> 		//if (prot == utils::protection::rw || prot == utils::protection::wx) // original code
> ```

Yea, this isn't right, it just removes the benefit of having asynchronous MM in the first place. I'm missing something else here, but so far all the games are just random visual flicker which is bad for debugging since there are no code events I can hook into. It's much easier if a game hangs or crashes since I can pause execution and debug.
I'll come around to this once I fix the active regression caused by recent changes.

**Comment by digant73** [comment]
With the current code (not my changes) I also verified that `Pacific Rift` was the only game having no issue if using `Recompiler ASMJIT` or . Just in case Async MM should be managed in the same way across all `SPU Decoder` settings

**Comment by Bobble80** [comment]
> Any games here that actually crash with the setting in default state?


I enabled the “Disable Asynchronous Memory Manager” option in the debug menu and it only fixed the missing text in the menu screens and options menus in Splatterhouse. I tested the game again, and the rendering issue is still there when in game.
And I’m not sure if by enabling “Disable Asynchronous Memory Manager” causes the game to crash, as it did during the opening cutscene. But the game can be prone to crashing anyway.

https://github.com/RPCS3/rpcs3/issues/16873

https://github.com/RPCS3/rpcs3/issues/13254

**Comment by Bobble80** [comment]
> > > Any games here that actually crash with the setting in default state?
> > 
> > 
> > I enabled the “Disable Asynchronous Memory Manager” option in the debug menu and it only fixed the missing text in the menu screens and options menus in Splatterhouse. I tested the game again, and the rendering issue is still there when in game. And I’m not sure if by enabling “Disable Asynchronous Memory Manager” causes the game to crash, as it did during the opening cutscene. But the game can be prone to crashing anyway.
> > [#16873](https://github.com/RPCS3/rpcs3/issues/16873)
> > [#13254](https://github.com/RPCS3/rpcs3/issues/13254)
> 
> kd-11 asked to test with Asynchronous Memory Manager enabled (responsible for the issues reported on the games listed on this bug report) just to provide logs in case you get a freeze or crash (that will help him more on the troubleshooting). So you should test disabling `Disable Asynchronous Memory Manager` on `Debug` tab

Asynchronous Memory Manager Is enabled by default right? I did go into the debug tab and enable the ‘Disable Asynchronous Memory Manager’ option and run Splatterhouse again. Then the missing text issue in the menus and settings menus was fixed. But the game crashed during the opening cutscene. 
The game does crash sometimes during the opening cutscene though even with the default RPCS3 settings without having ‘Disable Asynchronous Memory Manager’ setting enabled. 

Do I still need to upload a log?

**Comment by digant73** [comment]
@Bobble80 yes thanks. Possibly for both Async MM enabled (default) and disabled (from `Debug` tab)

**Comment by Bobble80** [comment]
> [@Bobble80](https://github.com/Bobble80) yes thanks. Possibly for both Async MM enabled (default) and disabled (from `Debug` tab)

Ok, I’ve ran Splatterhouse again with default settings and then async mem manager disabled from the debug menu. 
I just ran it for the first few minutes past the opening cutscene but couldn’t get the game to crash. A lot of times it crashes during the opening cutscene and has done for months now. 

The flickering graphics / rendering issue is still present though with default settings and also with AMM disabled. But I noticed that when I ran the game again after originally trying to fix the missing text in the menus by disabling AMM from the debug menu yesterday, now the missing menus text seems to be visible again on default settings. 

Anyway, I gathered the logs, not sure if they’re any use to you. And also captured another short video clip of the flickering graphics issue.

**Comment by kd-11** [comment]
Testing needed with https://github.com/RPCS3/rpcs3/pull/17249

**Comment by ghost** [comment]
Do all these games still suffer from these issues or have some been fixed by now?

**Comment by Bobble80** [comment]
> Do all these games still suffer from these issues or have some been fixed by now?

Splatterhouse is still broken. It has the flickering graphics issue still on the floor of the opening level.

https://github.com/RPCS3/rpcs3/issues/16873

And the other issue here with the text not showing up in the menu screens. Same thing happens in Alice: Madness Returns with the missing text in the menu screens too.

**Comment by digant73** [comment]
yes, this is for sure one hot issue still open and probably affecting more games than the ones reported

**Comment by wxvu** [comment]
Asynchronous Memory Manager causes a significant reduction in performance in Armored Core V & Armored Core Verdict Day.
No apparent visual or gameplay issues with Synchronous enabled.

``Disable Asynchronous Memory Manager = false`` vs. ``Disable Asynchronous Memory Manager = true``

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/c5691025-e74b-43ad-a753-26ff3658031b" />

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/40dc6089-5f29-4d35-a541-65de7cad9d24" />

**Comment by alexconsole04** [comment]
Tested with LBP2 and LBP3, still broken.

**Comment by user18081972** [comment]
In Eternal Sonata, when 'Force CPU Blit Emulation' is turned on (which is usually recommended in the discord, and by end users who finished the game on RPCS3, because it fixes the crashing issues in this game). However 'Force CPU Blit Emulation' causes missing geometry.
Changing "Disable Asynchronous Memory Manager" to true fixes the missing geometry.

Here is an example of the issue with the missing geometry (ignore the bad performance, its because i recorded on a shitty laptop, the issue also occurs on my 3080 at fullspeed)
https://github.com/user-attachments/assets/e5ff2c29-217c-4070-b3d6-78d8fc218802

**Comment by kd-11** [comment]
We do not recommend using developer debug features for end users.

**Comment by kd-11** [comment]
How many of these games are correctly fixed when using Host GPU labels? I found some like LBP2 aren't even self-tripping, it's just a simple case of RSX lying about having some data available when we haven't even sent it to the host GPU yet.
Obviously CPU blit is incompatible with async MM, though this can be trivially worked around using a forced sync barrier in blit code.

**Comment by kd-11** [comment]
I'm pushing a fix for partial MM flush on blit engine access. That should close a few of these as well.

**Comment by digant73** [comment]
motorstorm and split second are not fixed by Host GPU Labels. The other games need feedback by other users.
The issue on motorstorm is not present with ASMJIT or even using 60 fps patch (in case it can be useful)

**Comment by digant73** [comment]
> I'm pushing a fix for partial MM flush on blit engine access. That should close a few of these as well.

ok waiting for it

**Comment by kd-11** [comment]
Test https://github.com/RPCS3/rpcs3/pull/18137

If the base PR doesn't fix it, try using host GPU labels. The implementation on NV is shaky but could still improve things a bit. I'll have to come up with a proper deferred jobs system for NV cards at a later time.

**Comment by digant73** [comment]
Motorstom not fixed even with Host GPU Labels. I was remembering wrong with Split Second. It was fixed by Host GPU Labels, so it is still fixed by that option even on your PR

**Comment by alexconsole04** [comment]
Appears to be fixed. 

<img width="2560" height="1392" alt="Image" src="https://github.com/user-attachments/assets/b684ecc4-f2a8-485f-ae9a-afd037ef9e5b" />

<img width="2560" height="1392" alt="Image" src="https://github.com/user-attachments/assets/420fd3c0-c553-4b7f-a40f-3dcbc4fed5e4" />

[LBP2](https://github.com/user-attachments/files/24995793/RPCS3.log.gz)

[LBP3](https://github.com/user-attachments/files/24995786/RPCS3.log.gz)

**Comment by digant73** [comment]
@alexconsole04 could you please test if also #16809 and #16835 are fixed?

**Comment by alexconsole04** [comment]
<img width="2560" height="1392" alt="Image" src="https://github.com/user-attachments/assets/978bae5f-29e3-4248-b618-2aa976957fd6" />

To add, the PR before new one I couldn't get this issue replicated. Very likely it's been fixed in an earlier build but I cannot say for certain that's the case

**Comment by digant73** [comment]
@Bobble80 verify if current build is fixing the issue on missing text on Splatterhouse. This kind of issue has been reported as fixed for LBP 2 & 3 and Borderland 2. Try first without Host GPU Label and if not fixed try with that option enabled. Let us know the result

**Comment by Bobble80** [comment]
> [@Bobble80](https://github.com/Bobble80) verify if current build is fixing the issue on missing text on Splatterhouse. This kind of issue has been reported as fixed for LBP 2 & 3 and Borderland 2. Try first without Host GPU Label and if not fixed try with that option enabled. Let us know the result

I actually tested Splatterhouse randomly last week before this new update was pushed, and the missing text issue seemed to be fixed. The game itself is still a mess on RPCS3 though, with the flickering graphics on the opening level and game crashing during the opening cutscene. 

I just tried it again now after this new update and the missing text in the settings menus seems to be back again. 
But RPCS3 has been in a terrible state for me over the last few months ever since I opened a bug report at the start of December. 
https://github.com/RPCS3/rpcs3/issues/17804#issuecomment-3624120615

There wasn’t anyone to help with the issue or investigate what might be happening. And I’m still getting the same problems months later, it’s just super unstable for me now and a fresh install doesn’t help. I give up with it at this point.

**Comment by digant73** [comment]
> > [@Bobble80](https://github.com/Bobble80) verify if current build is fixing the issue on missing text on Splatterhouse. This kind of issue has been reported as fixed for LBP 2 & 3 and Borderland 2. Try first without Host GPU Label and if not fixed try with that option enabled. Let us know the result
> 
> I actually tested Splatterhouse randomly last week before this new update was pushed, and the missing text issue seemed to be fixed. The game itself is still a mess on RPCS3 though, with the flickering graphics on the opening level and game crashing during the opening cutscene.
> 
> I just tried it again now after this new update and the missing text in the settings menus seems to be back again. But RPCS3 has been in a terrible state for me over the last few months ever since I opened a bug report at the start of December. [#17804 (comment)](https://github.com/RPCS3/rpcs3/issues/17804#issuecomment-3624120615)
> 
> There wasn’t anyone to help with the issue or investigate what might be happening. And I’m still getting the same problems months later, it’s just super unstable for me now and a fresh install doesn’t help. I give up with it at this point.

Did you test also with option `Allow Host GPU Labels`? that fixed the missing text on Borderlands 2.

**Comment by kd-11** [comment]
Needs a retest with https://github.com/RPCS3/rpcs3/pull/19383
Some of the bugs like the Split/Second one were fixed some time ago with the blit engine overhaul PR.

**Comment by digant73** [comment]
@MarioSonic2987 please mark MotorStorm Pacific Rift as fixed by #19383

**Comment by wxvu** [comment]
> Asynchronous Memory Manager causes a significant reduction in performance in Armored Core V & Armored Core Verdict Day. No apparent visual or gameplay issues with Synchronous enabled.
> 

Performance gap has closed between the two, but the frametimes are still screwy.

`Disable Asynchronous Memory Manager = false` vs. `Disable Asynchronous Memory Manager = true`

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/f7cdef25-4f7e-4c30-976e-ff7edcf5d9e4" />

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/38ac4118-741d-4930-8b10-2a37d5a6262f" />
