### ISSUE TITLE
Medals are not displayed in Wipeout HD/Fury

### ISSUE THREAD

**Issue by lsvy97** [RPCS3/rpcs3#17300]
### Quick summary

The medals are not displayed at the end of the race in in Wipeout HD/Fury. But they're supposed to be here.

![Image](https://github.com/user-attachments/assets/d484afca-1637-4941-ae88-f5bfbe85ae06)

### Attach a log file

[WipEout HD Fury \[BCES00664\].log.gz](https://github.com/user-attachments/files/20692549/WipEout.HD.Fury.BCES00664.log.gz)

### System configuration

Operating System
	Microsoft Windows 11 Pro for Workstations 64-bit
CPU
	AMD Ryzen 5 5600
	Vermeer 7nm Technology
RAM
	16,0GB Dual-Channel DDR4 @ 1596MHz (16-18-18-36)
Motherboard
	ASRock A520M Pro4 (AM4
Graphics
	AF24H1 (1920x1080@144Hz)
	8176 MB ATI AMD Radeon RX 7600 (Gigabyte)
Storage
	931GB Seagate ST1000DM003-1ER162 (SATA)
	931GB Samsung SSD 980 1TB (SSD)
Audio
	AMD High Definition Audio Device

**Comment by woj1993** [comment]
Can you check with shader model Legacy?

**Comment by lsvy97** [comment]
> Can you check with shader model Legacy?

Tried with Legacy, the medal is still missing

**Comment by b1scu1t** [comment]
<img width="1920" height="1056" alt="Image" src="https://github.com/user-attachments/assets/6f2f5312-21ba-4641-871f-c915cf0d19ac" />

The medals are shown again as of version 0.0.38.18177. To be honest, I am not sure which version the medals started re-appearing/disappearing.
```

                    ....,,:;+ccllll    -----------------------------
      ...,,+:;  cllllllllllllllllll    OS: Windows 10 IoT Enterprise LTSC x86_64
,cclllllllllll  lllllllllllllllllll    Host: Precision 7530
llllllllllllll  lllllllllllllllllll    Kernel: WIN32_NT 10.0.19044.6218 (21H2)
llllllllllllll  lllllllllllllllllll    Uptime: 5 days, 18 hours, 1 min
llllllllllllll  lllllllllllllllllll    
llllllllllllll  lllllllllllllllllll    Shell: Windows PowerShell 5.1.19041.6216
llllllllllllll  lllllllllllllllllll    Display (LGD0540): 1920x1080 in 16", 60 Hz [Built-in]
                                       
llllllllllllll  lllllllllllllllllll    
llllllllllllll  lllllllllllllllllll    
llllllllllllll  lllllllllllllllllll    
llllllllllllll  lllllllllllllllllll    
llllllllllllll  lllllllllllllllllll   
`'ccllllllllll  lllllllllllllllllll    
       `' \*::  :ccllllllllllllllll    
                       ````''*::cll    CPU: Intel(R) Core(TM) i7-8850H (12) @ 4.30 GHz
                                 ``    GPU 1: Intel(R) UHD Graphics 630 (128.00 MiB) [Integrated]
                                       GPU 2: NVIDIA Quadro P2000 (3.91 GiB) [Discrete]
                                       Memory: 14.79 GiB / 31.76 GiB (47%)

```

Here's my custom config
```
Core:
  PPU Decoder: Recompiler (LLVM)
  PPU Threads: 2
  PPU Debug: false
  PPU Calling History: false
  Save LLVM logs: false
  Use LLVM CPU: ""
  Max LLVM Compile Threads: 0
  PPU LLVM Greedy Mode: false
  LLVM Precompilation: true
  Thread Scheduler Mode: Operating System
  Set DAZ and FTZ: false
  SPU Decoder: Recompiler (LLVM)
  SPU Reservation Busy Waiting Percentage 1: 100
  SPU Reservation Busy Waiting Enabled: false
  SPU GETLLAR Busy Waiting Percentage: 100
  Disable SPU GETLLAR Spin Optimization: false
  SPU Debug: false
  MFC Debug: false
  Preferred SPU Threads: 0
  SPU delay penalty: 3
  SPU loop detection: true
  Max SPURS Threads: 6
  SPU Block Size: Safe
  Accurate SPU DMA: false
  Accurate SPU Reservations: true
  Accurate Cache Line Stores: false
  Accurate RSX reservation access: false
  RSX FIFO Accuracy: Atomic
  SPU Verification: true
  SPU Cache: true
  SPU Profiler: false
  MFC Commands Shuffling Limit: 0
  MFC Commands Timeout: 0
  MFC Commands Shuffling In Steps: false
  Enable TSX: Disabled
  XFloat Accuracy: Relaxed
  Accurate PPU 128-byte Reservation Op Max Length: 0
  Stub PPU Traps: 0
  Precise SPU Verification: false
  PPU LLVM Java Mode Handling: true
  Use Accurate DFMA: true
  PPU Set Saturation Bit: false
  PPU Accurate Non-Java Mode: false
  PPU Fixup Vector NaN Values: false
  PPU Accurate Vector NaN Values: false
  PPU Set FPCC Bits: false
  Debug Console Mode: false
  Hook static functions: false
  Libraries Control:
    []
  HLE lwmutex: false
  SPU LLVM Lower Bound: 0
  SPU LLVM Upper Bound: 18446744073709551615
  TSX Transaction First Limit: 800
  TSX Transaction Second Limit: 2000
  Clocks scale: 100
  SPU Wake-Up Delay: 0
  SPU Wake-Up Delay Thread Mask: 63
  Max CPU Preempt Count: 0
  Allow RSX CPU Preemptions: true
  Sleep Timers Accuracy: Usleep Only
  Usleep Time Addend: 0
  Performance Report Threshold: 500
  Enable Performance Report: false
  Assume External Debugger: false
VFS:
  Enable /host_root/: false
  Initialize Directories: true
  Limit disk cache size: false
  Disk cache maximum size (MB): 5120
  Empty /dev_hdd0/tmp/: true
Video:
  Renderer: Vulkan
  Resolution: 1280x720
  Aspect ratio: 16:9
  Frame limit: Auto
  Second Frame Limit: 0
  MSAA: Auto
  Shader Mode: Async Shader Recompiler
  Shader Precision: Low
  Write Color Buffers: true
  Write Depth Buffer: false
  Read Color Buffers: false
  Read Depth Buffer: false
  Handle RSX Memory Tiling: false
  Log shader programs: false
  VSync: true
  Debug output: false
  Debug overlay: false
  Renderdoc Compatibility Mode: false
  Use GPU texture scaling: false
  Stretch To Display Area: false
  Force High Precision Z buffer: false
  Strict Rendering Mode: false
  Disable ZCull Occlusion Queries: false
  Disable Video Output: false
  Disable Vertex Cache: false
  Disable FIFO Reordering: false
  Enable Frame Skip: false
  Force CPU Blit: false
  Disable On-Disk Shader Cache: false
  Disable Vulkan Memory Allocator: false
  Use full RGB output range: true
  Strict Texture Flushing: false
  Multithreaded RSX: false
  Relaxed ZCULL Sync: true
  Force Hardware MSAA Resolve: false
  3D Display Mode: Disabled
  Debug Program Analyser: false
  Accurate ZCULL stats: false
  Consecutive Frames To Draw: 1
  Consecutive Frames To Skip: 1
  Resolution Scale: 150
  Anisotropic Filter Override: 0
  Texture LOD Bias Addend: 0
  Minimum Scalable Dimension: 515
  Shader Compiler Threads: 0
  Driver Recovery Timeout: 1000000
  Driver Wake-Up Delay: 80
  Vblank Rate: 60
  Vblank NTSC Fixup: false
  DECR memory layout: false
  Allow Host GPU Labels: false
  Disable MSL Fast Math: false
  Disable Asynchronous Memory Manager: false
  Output Scaling Mode: Bilinear
  Vulkan:
    Adapter: Quadro P2000
    Force FIFO present mode: false
    Force primitive restart flag: false
    Exclusive Fullscreen Mode: Automatic
    Asynchronous Texture Streaming 2: true
    FidelityFX CAS Sharpening Intensity: 75
    Asynchronous Queue Scheduler: Safe
    VRAM allocation limit (MB): 65536
  Performance Overlay:
    Enabled: false
    Enable Framerate Graph: false
    Enable Frametime Graph: false
    Framerate datapoints: 50
    Frametime datapoints: 170
    Detail level: Medium
    Framerate graph detail level: All
    Frametime graph detail level: All
    Metrics update interval (ms): 350
    Font size (px): 10
    Position: Top Left
    Font: n023055ms.ttf
    Horizontal Margin (px): 50
    Vertical Margin (px): 50
    Center Horizontally: false
    Center Vertically: false
    Opacity (%): 70
    Body Color (hex): "#FFE138FF"
    Body Background (hex): "#002339FF"
    Title Color (hex): "#F26C24FF"
    Title Background (hex): "#00000000"
  Shader Loading Dialog:
    Allow custom background: true
    Darkening effect strength: 30
    Blur effect strength: 0
Audio:
  Renderer: Cubeb
  Audio Provider: CellAudio
  RSXAudio Avport: HDMI 0
  Dump to file: false
  Convert to 16 bit: false
  Audio Format: Stereo
  Audio Formats: 0
  Audio Channel Layout: Automatic
  Audio Device: "@@@default@@@"
  Master Volume: 100
  Enable Buffering: true
  Desired Audio Buffer Duration: 120
  Enable Time Stretching: false
  Disable Sampling Skip: false
  Time Stretching Threshold: 75
  Microphone Type: "Null"
  Microphone Devices: "@@@@@@@@@@@@"
  Music Handler: Qt
Input/Output:
  Keyboard: "Null"
  Mouse: Basic
  Camera: "Null"
  Camera type: Unknown
  Camera flip: None
  Camera ID: Default
  Move: "Null"
  Buzz emulated controller: "Null"
  Turntable emulated controller: "Null"
  GHLtar emulated controller: "Null"
  Pad handler mode: Single-threaded
  Keep pads connected: false
  Pad handler sleep (microseconds): 1000
  Background input enabled: true
  Show move cursor: false
  Paint move spheres: false
  Allow move hue set by game: false
  Lock overlay input to player one: false
  Emulated Midi devices: Keyboardßßß@@@Keyboardßßß@@@Keyboardßßß@@@
  Load SDL GameController Mappings: true
  IO Debug overlay: false
  Fake Move Rotation Cone: 10
  Fake Move Rotation Cone (Vertical): 10
System:
  License Area: SCEA
  Language: English (US)
  Keyboard Type: English keyboard (US standard)
  Enter button assignment: Enter with cross
  Console time offset (s): 0
  System Name: RPCS3-189
  PSID high: 0
  PSID low: 0
  HDD Model Name: ""
  HDD Serial Number: ""
  Process ARGV: {}
Net:
  Internet enabled: Disconnected
  IP address: 0.0.0.0
  Bind address: 0.0.0.0
  DNS address: 9.9.9.9
  IP swap list: "wipeout2048.muis.online.scee.com=185.194.142.4&&wipeout2048.online.scee.com=185.194.142.4"
  UPNP Enabled: true
  PSN status: Disconnected
  PSN Country: us
Savestate:
  Start Paused: false
  Suspend Emulation Savestate Mode: false
  Compatible Savestate Mode: false
  Inspection Mode Savestates: false
  Save Disc Game Data: false
Miscellaneous:
  Automatically start games after boot: true
  Exit RPCS3 when process finishes: false
  Pause emulation on RPCS3 focus loss: true
  Start games in fullscreen mode: false
  Prevent display sleep while running games: true
  Show trophy popups: true
  Show RPCN popups: true
  Show shader compilation hint: true
  Show PPU compilation hint: true
  Show autosave/autoload hint: false
  Show pressure intensity toggle hint: true
  Show analog limiter toggle hint: true
  Show mouse and keyboard toggle hint: true
  Use native user interface: true
  GDB Server: 127.0.0.1:2345
  Silence All Logs: false
  Window Title Format: "FPS: %F | %R | %V | %T [%t]"
  Pause Emulation During Home Menu: false
Log: {}
```

[config_BCES00664.yml](https://github.com/user-attachments/files/22708686/config_BCES00664.yml)

**Comment by digant73** [comment]
is that still an issue? as far as I see, the issue has been recently reported as fixed by @b1scu1t

**Comment by digant73** [comment]
this issue has been reported as fixed by another user in this thread and can be closed (also no more activity from the OT)

**Comment by thalmos** [comment]
I'm still not seeing the medals displayed. I tested current version 0.0.40 on a Steam Deck/SteamOS and on a Windows desktop with a RX 6800XT using the default config except enabled `Write color buffers`.  I also tested with b1scu1t's config but I was not able to get it working.

Both me and the original reporter are using AMD GPUs whereas the working report has NVIDIA GPU so there might be a difference there. If anyone else owns this game please check.

**Comment by RRR0b1n** [comment]
No medals here either, using an AMD GPU (7800 XTX)
