### ISSUE TITLE
[Regression] Visual Studio 17.14 introduces a compiler regression causing no audio on games on libadec HLE mode

### ISSUE THREAD

**Issue by PuffaloBuffalo** [RPCS3/rpcs3#17326]
### Quick summary

At the title screen for Peace Walker, if you wait, a cut-scene will play. This cut-scene no longer plays audio. The character dialogues before mission no longer play audio either.

### Details

In the previous version, these scenes played audio normally. I also notice audio pops on transition/loading screens

### Build with regression

0.0.37-18023

### Attach two log files

[RPCS3.log](https://github.com/user-attachments/files/20848659/RPCS3.log)

[RPCS3.log](https://github.com/user-attachments/files/20848666/RPCS3.log)

### System configuration

CPU - intel core i5-10400f @ 2.90GHz
GPU - AMD Radeon RX 6600 XT
Driver- AMD Adrenaline 25.6.1
Emulator on SSD, game on HDD

**Comment by elad335** [comment]
Hmm, have you tried it with savedata moved out? perhaps the new build made old savedata incompatible for this game.

**Comment by antoniodesousa** [comment]
Same for me. Deleting the savedata changes nothing. This PR is the culprit of the regression https://github.com/RPCS3/rpcs3/pull/17322

**Comment by ok-potato** [comment]
Similar issues occur on a fresh install of Demon's Souls with the mentioned build. Downgrading to 0.0.37-18022 solved it for me.

**Comment by extome9000** [comment]
> Similar issues occur on a fresh install of Demon's Souls with the mentioned build. Downgrading to 0.0.37-18022 solved it for me.

I can confirm the same thing. I reverted to 0.0.37-18022 and the audio was back to normal.

**Comment by elad335** [comment]
Test with #17330

**Comment by PuffaloBuffalo** [comment]
The issue is still present in 0.0.37-18024

**Comment by ok-potato** [comment]
> Test with [#17330](https://github.com/RPCS3/rpcs3/pull/17330)

Issue persists with this build as well.

**Comment by asome0verlord** [comment]
hi unsure if a noob like myself has any imput here but i am having the same issue i think, the main menu cutsceen has a small pop then no audio at all soon as the konmi logo plays, the first cutsceen has no sound for a handfull of effects like the rain and some impact sounds, but the voices and footsteps still play "normaly" 

this wasnt the case until after i updated RPCS3 :/ guess for the time being ill just play on xbox lol

**Comment by ok-potato** [comment]
> hi unsure if a noob like myself has any imput here but i am having the same issue i think, the main menu cutsceen has a small pop then no audio at all soon as the konmi logo plays, the first cutsceen has no sound for a handfull of effects like the rain and some impact sounds, but the voices and footsteps still play "normaly"
> 
> this wasnt the case until after i updated RPCS3 :/ guess for the time being ill just play on xbox lol

In case the latest build hasn't already fixed the problem, you can follow [this guide](https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3) to go back to the last working version.

**Comment by PuffaloBuffalo** [comment]
Regression is still present in 0.0.37-18055

**Comment by Starjadian** [comment]
I downgraded to 0.0.37-18005 and the sound is back to normal now.

**Comment by AniLeo** [comment]
I resetted CI caches and triggered a new build on #17336
Please test that build to see if it changes anything

**Comment by antoniodesousa** [comment]
> I resetted CI caches and triggered a new build on https://github.com/RPCS3/rpcs3/pull/17336
Please test that build to see if it changes anything

It made no difference for me.

**Comment by AniLeo** [comment]
Next build to try: #17341

**Comment by antoniodesousa** [comment]
> Next build to try: https://github.com/RPCS3/rpcs3/pull/17341

Just tested it and it's still broken for me :(

**Comment by AniLeo** [comment]
What I can see is that on the date of when this bug started, the CI environment updated MSBuild from 17.13 to 17.14

https://github.com/actions/runner-images/commit/59edccfddefb3e16e726d2e0477d9b5824d3aec2#diff-94a5744228c87bd66a08d2120ec5f9c3837e11985b58259b6c63c63330051293L255

I don't see a way to specify a different version, and windows-2022 is also using the same up-to-date version of VS2022 (17.14)

Whoever tested a local build with working audio, did you use VS2022 17.14 when building?

I think the bug is caused by this: https://github.com/actions/runner-images/issues/12470

**Comment by AniLeo** [comment]
I pushed a new commit to test on https://github.com/RPCS3/rpcs3/pull/17341, whenever it builds please test again

Also, please confirm that the clang build is not affected even on master, only the msvc one is

**Comment by antoniodesousa** [comment]
> Whoever tested a local build with working audio, did you use VS2022 17.14 when building?

@digant73

**Comment by antoniodesousa** [comment]
> I pushed a new commit to test on https://github.com/RPCS3/rpcs3/pull/17341, whenever it builds please test again

Still broken... I guess that we should wait for MS to release the fix for VS2022 17.14.

> Also, please confirm that the clang build is not affected even on master, only the msvc one is

clang build works fine even on latest master.

**Comment by digant73** [comment]
> > Whoever tested a local build with working audio, did you use VS2022 17.14 when building?
> 
> [@digant73](https://github.com/digant73)

I'm on VS2022 17.13.6

**Comment by digant73** [comment]
VS2022 updated to 17.14.7 and issue on audio is now present (in RELEASE mode).
In DEBUG mode the issue is not present

**Comment by elad335** [comment]
Test #17344 please.

**Comment by digant73** [comment]
> Test [#17344](https://github.com/RPCS3/rpcs3/pull/17344) please.

it seems working

**Comment by antoniodesousa** [comment]
> Test https://github.com/RPCS3/rpcs3/pull/17344 please.

Tekken 6 still no audio during movies and no background music.
Tekken 5 DR same as Tekken 6.
Time Crisis 4 same as Tekken 6.

**Comment by capriots** [comment]
It only happens when _both_ libatxdec and libadec are HLE'd. If one of them is LLE'd, this issue doesn't occur.

xmm6 isn't properly restored in ppu_thread::fast_call(), which is holding one of the operands for the condition of this if statement:
https://github.com/RPCS3/rpcs3/blob/20c9dcd2d6dbac8d2c1a4b1aab88d995ed6dc72e/rpcs3/Emu/Cell/Modules/cellAtracXdec.cpp#L519-L530

I would actually recommend to LLE libadec by default on Windows until this is fixed because this has the potential to produce very unpleasant audio.

**Comment by antoniodesousa** [comment]
> It only happens when both libatxdec and libadec are HLE'd. If one of them is LLE'd, this issue doesn't occur.

This DOES NOT FIX the audio issue for me in several games... please, read my comment above.
I'm on Windows 11 24H2 btw.

**Comment by AniLeo** [comment]
> > It only happens when both libatxdec and libadec are HLE'd. If one of them is LLE'd, this issue doesn't occur.
> 
> This DOES NOT FIX the audio issue for me in several games... please, read my comment above. I'm on Windows 11 24H2 btw.

There's no comment of you testing LLE of these libraries, the tests you posted were on other changes. Enabling LLE of libraries is done through rpcs3 settings.

**Comment by antoniodesousa** [comment]
> There's no comment of you testing LLE of these libraries, the tests you posted were on other changes. Enabling LLE of libraries is done through rpcs3 settings.

There you go. The log is from Tekken 5 DR but the other games that I mentioned above have the same issue.

![Image](https://github.com/user-attachments/assets/56aa48b7-8ce8-454f-be44-7a368315cb8b)

[RPCS3.log.gz](https://github.com/user-attachments/files/20986025/RPCS3.log.gz)

**Comment by oltolm** [comment]
You didn't LLE `libatxdec`.

**Comment by antoniodesousa** [comment]
> It only happens when both libatxdec and libadec are HLE'd. If one of them is LLE'd, this issue doesn't occur.

@oltolm only one should fix the issue supposedly. 

> You didn't LLE libatxdec.

I tried both before and it didn't work either.
I also tried libvdec like someone else advice it but same result.

Update:
hmm enabling only `libatxdec` seems to fix the audio issues...

**Comment by kcounv** [comment]
Until current Build 0.0.37-18070 , every version after 0.0.37-18022 having audio problem during matches of game NPJB00512 MOBILE SUIT GUNDAM: EXTREME vs. FULL BOOST

**Comment by alexbal29** [comment]
> VS2022 updated to 17.14.7 and issue on audio is now present (in RELEASE mode). In DEBUG mode the issue is not present

Can you check if audio is still broken on 17.14.8

**Comment by alexbal29** [comment]
@AniLeo issue fixed on 17.14.9,

<img width="1290" height="2796" alt="Image" src="https://github.com/user-attachments/assets/a5590016-4c62-4d02-931e-fff0ea1e666b" />

**Comment by alexbal29** [comment]
@digant73 Can you verify 17.14.9 fix the audio on rpcs3 

<img width="1290" height="2796" alt="Image" src="https://github.com/user-attachments/assets/18479584-a200-4ea1-bae2-177e9bd1a964" />

**Comment by alexbal29** [comment]
@AniLeo The bug is fixed on 17.14.9 but need to wait for it to be on github action runner image  

<img width="1290" height="2796" alt="Image" src="https://github.com/user-attachments/assets/12c81e6b-2c49-4b93-80b4-d80a63aa6732" />

**Comment by AniLeo** [comment]
I cleaned the msvc caches again and opened a new PR to test a clean build on windows-2025 20250720.1.0 which allegedly has VS 17.14.9

#17396

Can someone check if the issue persists with that PR?

**Comment by alexbal29** [comment]
> I cleaned the msvc caches again and opened a new PR to test a clean build on windows-2025 20250720.1.0 which allegedly has VS 17.14.9

The runner use 17.14.36310.24 who is VS 17.14.9 

<img width="1290" height="2796" alt="Image" src="https://github.com/user-attachments/assets/c465527e-5ec0-4fdf-bac2-b5a2a71726d6" />

**Comment by capriots** [comment]
Doesn't fix it unfortunately. Tried to compile it locally as well with the same result.
No idea if this is related, but enabling AVX2 or AVX512 for PPUThread.cpp actually makes msvc crash during compilation.
Could you try disabling Enhanced Instruction Set for PPUThread.cpp? Maybe that works around the issue. I don't have any more time to test right now

**Comment by alexbal29** [comment]
> I cleaned the msvc caches again and opened a new PR to test a clean build on windows-2025 20250720.1.0 which allegedly has VS 17.14.9
> 
> [#17396](https://github.com/RPCS3/rpcs3/pull/17396)
> 
> Can someone check if the issue persists with that PR?

It does not fix the audio bug  

https://github.com/user-attachments/assets/55123151-bf03-45da-97d3-cbd3b9d8763c

**Comment by alexbal29** [comment]
> Doesn't fix it unfortunately. Tried to compile it locally as well with the same result. No idea if this is related, but enabling AVX2 or AVX512 for PPUThread.cpp actually makes msvc crash during compilation. Could you try disabling Enhanced Instruction Set for PPUThread.cpp? Maybe that works around the issue. I don't have any more time to test right now

LLE libatxdec fix the audio issue tested on peace walker.

**Comment by antoniodesousa** [comment]
>I cleaned the msvc caches again and opened a new PR to test a clean build on windows-2025 20250720.1.0 which allegedly has VS 17.14.9
>
>https://github.com/RPCS3/rpcs3/pull/17396
>
>Can someone check if the issue persists with that PR?

I just tested it and the audio is still broken on 17.4.9.

Although the CI/CD is using the latest VS image 17.4.9, the MSBuild version is still the same as last week.

```
MSBuild version 17.14.14+a129329f1 for .NET Framework

** Visual Studio 2022 Developer Command Prompt v17.14.9
** Copyright (c) 2025 Microsoft Corporation
```

Last week:

```
MSBuild version 17.14.14+a129329f1 for .NET Framework

** Visual Studio 2022 Developer Command Prompt v17.14.8
** Copyright (c) 2025 Microsoft Corporation
```

**Comment by AniLeo** [comment]
@antoniodesousa But that's the msbuild for C#, not C++

**Comment by antoniodesousa** [comment]
hmm then I don't know why it's still broken. I guess they didn't actually fix the issue.
I think that it would be better if they had rollback to VS 17.13 instead of waiting another month for a possible "fix".

**Comment by AniLeo** [comment]
I think I'll just disable Windows builds at this point and wait until the clang-cl build is ready. No one wants to deal with msvc anymore.

**Comment by woj1993** [comment]
@AniLeo Is there any reason we can't switch to clang-cl build for windows until it is fixed?

**Comment by Asinin3** [comment]
> @AniLeo Is there any reason we can't switch to clang-cl build for windows until it is fixed?

https://x.com/rpcs3/status/1946069205704433834

**Comment by AniLeo** [comment]
https://developercommunity.visualstudio.com/t/SIMD-Code-optimization-bug/10945478/

**Comment by AniLeo** [comment]
Can someone on Windows please verify? You'll have to compile locally with that version and try to repro the bugs already discussed, as the version is not on CI yet

**Comment by capriots** [comment]
Never mind, I had PPU Decoder set to interpreter. Sorry about that ^^"

**Comment by AniLeo** [comment]
The ticket is not on the changelog. So I wouldn't expect anything to change.

**Comment by digant73** [comment]
already tested. The bug is still present

**Comment by kunit1** [comment]
It says the VS fix is not released yet. Is there a pre-release version that contains it?

**Comment by ghost** [comment]
> It says the VS fix is not released yet. Is there a pre-release version that contains it?

The only pre-release version of Visual Studio available is Visual Studio 2026 Insiders

<img width="1290" height="2796" alt="Image" src="https://github.com/user-attachments/assets/a5d0873f-6df4-4d8c-bdb3-971078c08ae9" />

**Comment by AniLeo** [comment]
Can you test #17515?

**Comment by woj1993** [comment]
I tested tutorial of Demon's Souls and it seems that sound is working more correctly. I heard some cracking but I guess it was my PC slowing down or something. Except for cracking, sound seems to work properly as there are no missing sounds, dialogue, effects etc.

**Comment by antoniodesousa** [comment]
Tested:

Demon's Soul
Lollipop Chainsaw
Tekken 6
Tekken 5: Dark Resurrection
Time Crisis 4
Time Crisis: Razing Storm
Mobile Suit Gundam: Extreme VS Full Boost

All audio issues seem to be fixed!
