### ISSUE TITLE
Enabling UPNP freezes when launching games

### ISSUE THREAD

**Issue by phonicswright** [RPCS3/rpcs3#17561]
### Quick summary

Enabling UPNP prevents 

### Details

I've tried with two games (Modnation Racers BCUS98167 and Skate 3 BLUS30464) and have the same issue in both. I have set up custom configs for each game to work with custom servers. Enabling UPNP for either of these games with otherwise default settings causes the program not to respond and prevents either game from launching. I have tested letting it sit for a half hour, and the program was still frozen. Disabling UPNP prevents this issue.

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/22752505/RPCS3.log)

### System configuration

Windows 11
i7-13700F
RTX 4060 with driver Ver. 32.0.15.8142

**Comment by RipleyTom** [comment]
Probably fixed by https://github.com/RPCS3/rpcs3/pull/18254. Reopen if that's not the case.

**Comment by ForgottenIce** [comment]
@RipleyTom I still have this issue on version 0.0.40-19407

This is how the end of the log looks after the freeze, right after opening a game:
```
·! 0:24:56.384046 ppu_loader: ** Imported module 'sys_crashdump' (ver=0x1, attr=0x9, 0x0, 0x0) [0xc23d94]
·! 0:24:56.384049 ppu_loader: **** sys_crashdump import: [sys_crash_dump_set_user_log_area] (0xb20f87b3) -> 0xc226f4
·! 0:24:56.384975 SYS: Cache: C:/Users/Simon/scoop/apps/rpcs3/current/cache/BCES00850/ppu-L5jh4VaPTErbzoY8LoTdoUtZn3RV-EBOOT.BIN/
·S 0:24:56.385088 PPU: Enabled: Non-Java Mode Fixup
·S 0:24:56.385094 PPU: Enabled: VNAN Fixup
·! 0:24:56.389493 UPNP_CFG: Loading UPNP config. Path: C:/Users/Simon/scoop/apps/rpcs3/current/config/upnp.yml
·! 0:24:56.391946 UPNP: Saved UPNP(http://192.168.0.1:49154/IGDdevicedesc1.xml) enabled
·! 0:24:56.391969 IPv6_layer: is_ipv6_supported(): disabled cause: force-disabled through config
·! 0:24:56.820494 {Performance Sensor} PERF: CPU Usage: Total: 4.3%, Cores: 9.4%, 0.0%, 6.3%, 6.3%, 0.0%, 0.0%, 6.3%, 9.4%, 6.3%, 25.0%, 9.4%, 9.4%, 0.0%, 3.1%, 0.0%, 0.0%, RAM Usage: 12611MB (Peak: 12611MB)
·! 0:25:06.820898 {Performance Sensor} PERF: CPU Usage: Total: 0.4%, Cores: 9.4%, 0.0%, 6.2%, 0.0%, 6.2%, 0.0%, 0.0%, 0.0%, 12.5%, 12.5%, 0.0%, 25.0%, 0.0%, 6.2%, 0.0%, 0.0%, RAM Usage: 12628MB (Peak: 12628MB)
·! 0:25:16.820983 {Performance Sensor} PERF: CPU Usage: Total: 0.0%, Cores: 9.2%, 3.0%, 15.5%, 3.0%, 6.1%, 3.0%, 0.0%, 0.0%, 9.2%, 12.4%, 12.4%, 18.6%, 0.0%, 0.0%, 3.0%, 0.0%, RAM Usage: 12620MB (Peak: 12628MB)
```

**Comment by carlmylo** [comment]
Confirming that it's happening here too.

[[Video]](https://youtu.be/0_7i4qXISMU)

[[Log]](https://github.com/user-attachments/files/28849901/Rock.Band.3.BLES00986.log.gz)

**Comment by ItsLaguna** [comment]
This seems to still be a thing but without the crashes, at least on my end.

Having "Enable UPnP" enabled in the config of a game delays the booting of said game by ~8 seconds, disabling it fixes it. Pinging @RipleyTom to let them know in case this is not supposed to happen.

**Comment by RipleyTom** [comment]
That's because RPCS3 is waiting to find your UPNP enabled router...
If you don't have a router with UPNP enabled...don't enable UPNP?

**Comment by ItsLaguna** [comment]
> That's because RPCS3 is waiting to find your UPNP enabled router... If you don't have a router with UPNP enabled...don't enable UPNP?

But I have UPnP enabled on my router lol I'll see if it's something else on my end, if not I'll just disable it and forget about it.
