### ISSUE TITLE
[Regression] Hyperdimension Neptunia and Trinity Universe Artifacting Issues on Vulkan with AMD GPU

### ISSUE THREAD

**Issue by Monsterman07** [RPCS3/rpcs3#17592]
### Quick summary

A new issue has appeared in these games is that there's some weird artifacting in the games if you use Vulkan with an AMD GPU.

### Details

https://github.com/user-attachments/assets/3d635431-1fca-4298-8a72-68fdddac8643

https://github.com/user-attachments/assets/7bb5444c-2608-4e30-a369-3a59f9bc1b57

This issue does not happen if I use an Nvidia GPU on Vulkan or use OpenGL

### Build with regression

0.0.38-18236-a5b5ac1e

### Attach two log files

Build with regression:

[RPCS3.log.gz](https://github.com/user-attachments/files/22957252/RPCS3.log.gz) (Hyperdimension Neptunia)

[RPCS3.log.gz](https://github.com/user-attachments/files/22957520/RPCS3.log.gz) (Trinity Universe)

Working build:

[RPCS3.log.gz](https://github.com/user-attachments/files/22957274/RPCS3.log.gz) (Hyperdimension Neptunia) 

[RPCS3.log.gz](https://github.com/user-attachments/files/22957571/RPCS3.log.gz) (Trinity Universe)

### Attach capture files for visual issues

[BLES01178_20251016220105_capture.rrc.gz](https://github.com/user-attachments/files/22957345/BLES01178_20251016220105_capture.rrc.gz)  (Hyperdimension Neptunia)

[BLUS30535_20251016223611_capture.rrc.gz](https://github.com/user-attachments/files/22957838/BLUS30535_20251016223611_capture.rrc.gz) (Trinity Universe)

### System configuration

OS: Windows 11
CPU: Ryzen 7 5800X3D
GPUs: RX 7900 GRE on AMD Adrenaline driver version 25.9.1 and GTX 1650 on Game Ready driver 560.94
RAM: 32GBs of DDR4 3200mhz

### Other details

Turning off anti-aliasing does not fix the issue and will actually make it even worse

**Comment by kd-11** [comment]
@Monsterman07 The ticket is marked regression but you did not mention the first build that broke it. Is it just the same vulkan regression from earlier this week? Or was it already broken?

**Comment by antoniodesousa** [comment]
From the logs:

RPCS3 v0.0.38-18185-9e49b910 -> Working https://github.com/RPCS3/rpcs3/pull/17540
RPCS3 v0.0.38-18236-a5b5ac1e -> Regression https://github.com/RPCS3/rpcs3/pull/17580

But I'm pretty sure the culprit is https://github.com/RPCS3/rpcs3/pull/17427

**Comment by Monsterman07** [comment]
> [@Monsterman07](https://github.com/Monsterman07) The ticket is marked regression but you did not mention the first build that broke it. Is it just the same vulkan regression from earlier this week? Or was it already broken?

It's the one I listed in "Build with regression".
Edit: Considering the build is right after that Vulkan merge and the issue is related to Vulkan. I'm pretty sure it's related to that regression.

**Comment by kd-11** [comment]
Check if https://github.com/RPCS3/rpcs3/pull/17594 fixes it

**Comment by Monsterman07** [comment]
> Check if [#17594](https://github.com/RPCS3/rpcs3/pull/17594) fixes it

I'm trying to build the fork to test it, but I'm having many issues with it

**Comment by kunit1** [comment]
@Monsterman07 Just grab the build from the PR. You don't need to build it yourself

**Comment by Darkhost1999** [comment]
You can also just type #17594 into rpcs3 discord #botspam and the bot will provide you with the download links

**Comment by Monsterman07** [comment]
> You can also just type [#17594](https://github.com/RPCS3/rpcs3/pull/17594) into rpcs3 discord #botspam and the bot will provide you with the download links

Oooooooh I never knew that lol. Thank you guys

**Comment by Monsterman07** [comment]
@kd-11 I finally tested the #17594 build and it doesn't fix the issue

**Comment by antoniodesousa** [comment]
I just tested Trinity Universe on my PC and I didn't find any issues on Vulkan using the latest build from this PR https://github.com/RPCS3/rpcs3/pull/17594

## System Information
CPU: **AMD Ryzen 9 6900HX with Radeon Graphics**        
OS Platform: **Windows**
OS Version: **24H2**
Manufacturer: **ATI Technologies Inc.**
GPU Model: **AMD Radeon RX 6600M**
Driver: **4.0.0 Core Profile Context 25.8.1.250723**
Shader: **4.60**

## Screenshots
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/9e921a12-07ea-4a40-927d-d878b16b200c" />
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/dad07834-2a2d-47e2-b2e1-2d43006cbeb1" />
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/324737dc-a9d2-4266-9750-d6428bfe4191" />
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/616eadcf-6be9-483f-9866-fc28efce8caa" />
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/10d30b02-b537-4172-9b9a-76992aec67a8" />
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/d87233c7-ee0d-456a-9e40-71be7d8d0e6e" />

## Log file
[RPCS3.log.gz](https://github.com/user-attachments/files/22979693/RPCS3.log.gz)

**Comment by kd-11** [comment]
@Monsterman07 Attach log file. Also since the PR is merged, you can just use the main release now.

**Comment by Monsterman07** [comment]
@kd-11 Okay here's the log for the PR build

[RPCS3.log.gz](https://github.com/user-attachments/files/22990232/RPCS3.log.gz)

**Comment by digant73** [comment]
@antoniodesousa, @Monsterman07 please can you confirm / double check this issue is fixed on current build (it was possibly fixed by #17594) and eventually close this ticket?

**Comment by antoniodesousa** [comment]
I didn't have any issues with the game before that commit, and still no issues with that commit.

**Comment by kd-11** [comment]
@Monsterman07 Please retest with AMD driver 25.11.1 - several other regressions related to rpcs3 are fixed in that release.

**Comment by Monsterman07** [comment]
@kd-11 The issue still remains even with the newest update of RPCS3 and the newest AMD driver. I tested Neptunia on my RX 6650 XT a week earlier and that one had no issues. Perhaps this is an issue specifically with RDNA3 GPUs?

[RPCS3.log.gz](https://github.com/user-attachments/files/23587007/RPCS3.log.gz)

[BLES01178_20251117173235_capture.rrc.gz](https://github.com/user-attachments/files/23586881/BLES01178_20251117173235_capture.rrc.gz)

**Comment by AniLeo** [comment]
No need to ask for random updates on driver bugs that we are tracking. This needs to be retested with driver 26.3.1 when it's out.

**Comment by kd-11** [comment]
> Perhaps this is an issue specifically with RDNA3 GPUs?

Possibly. We can send more traces to AMD if the issue is still present with the next driver.

**Comment by Monsterman07** [comment]
> Possibly. We can send more traces to AMD if the issue is still present with the next driver.

The artifacting issues are fixed with 26.3.1 and the newest RPCS3 version for me (0.0.40-19187-f463c128)
