### ISSUE TITLE
GL/Vulkan: One Piece: Pirate Warriors graphical issues

### ISSUE THREAD

**Issue by MarioSonic2987** [RPCS3/rpcs3#2262]
As of 0.0.16-12374:

- [x] Broken depth of field (blur) in cutscenes. - Fixed in #10733 
<details>
<summary>Old comment</summary>

**DX12** - Freezes in title screen with:
```
·F {rsx::thread} class std::runtime_error thrown: HRESULT = La instancia de dispositivo de GPU se ha suspendido. Use GetDeviceRemovedReason para averiguar cuál es la acción adecuada.
(in file C:\rpcs3\rpcs3\Emu\RSX\D3D12\D3D12RenderTargetSets.cpp:279)
```
**OGL**:
![](http://i.imgur.com/JIUno5a.png)
**Vulkan**:
![](http://i.imgur.com/eCbrMZc.png)

Crashes in same moment as in these pictures.

Outputs in all backends:
```
·E {rsx::thread} RSX: Unimplemented sca_opcode BRB
·E {rsx::thread} RSX: Unimplemented sca_opcode BRB
```
[Shaderlog DX12](https://drive.google.com/open?id=0B9LymxJkpT48WDRLM2FNMTJrYzQ)
[Shaderlog OpenGL](https://drive.google.com/open?id=0B9LymxJkpT48VzFSenl0WUgxS0E)
[Shaderlog Vulkan](https://drive.google.com/open?id=0B9LymxJkpT48QVdIYlZPNlhZVm8)
[RenderDoc Vulkan (Title screen & Main menu)](https://drive.google.com/open?id=0B9LymxJkpT48SG1EZlJSR1FPWDg)
</details>

**Comment by SakataGintokiYT** [comment]
@AniLeo 

Crash by sysnet issue on the line 425 'recvfrom'
After disabling this feature, the game starts normally without crash.

`W {PPU[0x1000000] Thread (main_thread) [0x00812824]} libnet: recvfrom(s=0, buf=*0x0, len=0, flags=0x80, addr=*0xd001f684, paddrlen=*0xd001f670)
`
```
Fatal error
Unhandled Win32 exception 0xC0000005.
Segfault reading location 0000000000000000 at 000000000021ef9f.
Instruction address: 000000000021ef9f.
Function address: 000000000021eec0 (base+0x20eec0).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

```

**Comment by kd-11** [comment]
Please retest with https://github.com/RPCS3/rpcs3/pull/2426

**Comment by MarioSonic2987** [comment]
![](http://i.imgur.com/SJEdudz.png)
With #2426, it's the same in Vulkan. I think this problem is somewhere.

[Shaderlog Vulkan](https://drive.google.com/open?id=0B9LymxJkpT48YVhnc0c3OWNuUWM)
[RenderDoc Vulkan](https://drive.google.com/open?id=0B9LymxJkpT48a1djSlpSNGw0UTA)

**Comment by SakataGintokiYT** [comment]
@kd-11 
**[OpenGL-RenderDoc](https://mega.nz/#!MBBD0LKY!DPjIHN2Q7BdNV8ooKTz9J0VlkiyieQLqH0BZbhng15c)**
**[Shaderlog:](https://mega.nz/#!lZgxxaqB!RRwyszNPNXKsCnpqoQRzt57BE1p1FZyOes70MsKOUp4)**

**Comment by Zangetsu38** [comment]
menu bugger and ingame strange blur 
![Uploading Capture d'écran 2017-02-26 01.18.08.png…]()
![capture d ecran 2017-02-26 01 18 27](https://cloud.githubusercontent.com/assets/5261759/23335982/e603912a-fbc1-11e6-8cb3-dbcb11e9d21b.png)
![capture d ecran 2017-02-26 01 20 57](https://cloud.githubusercontent.com/assets/5261759/23335981/e6004290-fbc1-11e6-9ec9-0cced2afae0e.png)

**Comment by MarioSonic2987** [comment]
Hits this (same as Skate 2):
`E {rsx::thread} RSX: Surface color buffer: Unsupported surface color format (0xd)`

On BRB side, it's the same in VK and GL.

In DX12, outputs:

```
·F 0:03:07.672151 {rsx::thread} class std::runtime_error thrown: HRESULT = La instancia de dispositivo de GPU se ha suspendido. Use GetDeviceRemovedReason para averiguar cu⬠es la acci󮠡decuada.
(in file C:\rpcs3\rpcs3\Emu\RSX\D3D12\D3D12RenderTargetSets.cpp:279)
```
[Shaderlog DX12](https://drive.google.com/open?id=0B9LymxJkpT48QjJ4Wm1mMzE2NzQ)

**Comment by MarioSonic2987** [comment]
With #2482, lighting effects are improved.
![](http://i.imgur.com/QTUhbcY.png)
![](http://i.imgur.com/TiaBX67.png)

**Comment by SakataGintokiYT** [comment]
**OpenGL**
<img src="http://www.fotoszok.pl/upload/85e13470.png" alt="Fotoszok.pl" />
#2962

**Comment by MarioSonic2987** [comment]
With jarves' build (https://ci.appveyor.com/project/jarveson/rpcs3/build/0.0.3-154), fixes water in title screen.
![image](https://user-images.githubusercontent.com/20027681/29449229-3721ec80-83fa-11e7-9d22-9721fad843c2.png)

**Comment by MarioSonic2987** [comment]
Tested with https://github.com/RPCS3/rpcs3/commit/cde29aba646752ab042be031dc468dac961b02f8:
![image](https://user-images.githubusercontent.com/20027681/30025645-c2728272-9179-11e7-9bd5-bee5964866ab.png)

**Comment by Asinin3** [comment]
@MarioSonic2987 I think this was fixed with: 9c70d2acbfca19009fe56501454bade3932f5637

**Comment by MarioSonic2987** [comment]
@Asinin3 Only fixed a portion of broken geometry.

**Comment by AniLeo** [comment]
Retested but latest build driver crashes Vulkan on AMD, reported to kd-11

**Comment by MarioSonic2987** [comment]
With PR #3488, has water effects, but with a white texture:

![image](https://user-images.githubusercontent.com/20027681/30771323-643844f0-a045-11e7-824e-77795c34e335.png)

**Comment by MarioSonic2987** [comment]
With #3744, lighting effects are improved (look at Luffy).
![image](https://user-images.githubusercontent.com/20027681/33022249-ce881488-ce04-11e7-8a35-b9bdbaacdb59.png)
![image](https://user-images.githubusercontent.com/20027681/33022145-75f7804c-ce04-11e7-97d1-06de416db7a4.png)

**Comment by MarioSonic2987** [comment]
Tested in https://github.com/RPCS3/rpcs3/commit/f24491de84fd5c0edb73ad876d9b1c3cef5da1f6:

![image](https://user-images.githubusercontent.com/20027681/34202844-4abc4c5a-e579-11e7-8ca5-fc98d133d063.png)
[Log OpenGL](https://github.com/RPCS3/rpcs3/files/1575157/Log.OPPW.20-12-17.GL.gz)
[Shaderlog OpenGL](https://drive.google.com/open?id=187BUyD1K0co1HPLVuwI22bGQE-s-jYjz)
[RenderDoc OpenGL](https://drive.google.com/open?id=16qFUKck9trMe2IpaJqcXou8-vwd1zd9Q)

**Comment by MarioSonic2987** [comment]
With #4312, gamma is fixed.
![image](https://user-images.githubusercontent.com/20027681/37874436-783835da-302f-11e8-8093-6d1bed46c337.png)

**Comment by hcorion** [comment]
Was this fixed in #4356

**Comment by MarioSonic2987** [comment]
With #4902, fixes black and misplaced textures in levels.
![image](https://user-images.githubusercontent.com/20027681/43047476-f8de07c2-8dd7-11e8-94de-fe9dad5605cd.png)

**Comment by reaper185** [comment]
exploding vertices also happens in Dynasty Warriors Gundam Reborn #4632

**Comment by MarioSonic2987** [comment]
This screenshot catches more graphical issues:

- [ ] Exploding vertices
- [ ] Screen flickering (epileptic colors)
- [ ] Broken effects (smoke)

![image](https://user-images.githubusercontent.com/20027681/44718156-74cf0580-aabf-11e8-96dd-404c62a21d1a.png)
[RenderDoc (OpenGL)](https://drive.google.com/open?id=1K_Gaq1JTQdEEO_nbVm6R8yu7_903vQik)

**Comment by MarioSonic2987** [comment]
With #5436, fixes broken and missing effects, although the water effects are still not perfect.
![image](https://user-images.githubusercontent.com/20027681/50394046-d431df00-075a-11e9-90d8-2f9ff9290145.png)

**Comment by kd-11** [comment]
Needs an update.

**Comment by MarioSonic2987** [comment]
There's still broken effects in water and flickering colors during cutscenes.
<details>
<summary>Images</summary>

![image](https://user-images.githubusercontent.com/20027681/63326279-3237b600-c32c-11e9-9f92-ae2514c29168.png)
![image](https://user-images.githubusercontent.com/20027681/63326336-51cede80-c32c-11e9-8b93-6ccb407d1546.png)
</details>

[RenderDoc VK](https://drive.google.com/open?id=1b3VxNth5JC2Gy-AI3-ueYdmoZfGZGrmd)
[RSX Captures](https://drive.google.com/open?id=1beNARWp61aC_qbKyx0FZaEfnHRgPT2uG)

**Comment by benderscruffy** [comment]
still broken effects in water and flickering colors during cutscenes.
![one](https://user-images.githubusercontent.com/2696404/74077716-0389d500-4a5d-11ea-93eb-9e0c0269b014.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4173661/RPCS3.log.gz)

**Comment by elad335** [comment]
Retest with #7846

**Comment by MarioSonic2987** [comment]
Nothing changed with PR #7846. Same glitches as before.
![image](https://user-images.githubusercontent.com/20027681/77534643-51d22680-6e99-11ea-8480-967cab2298cd.png)

**Comment by kd-11** [comment]
Attach recent RSX capture of broken water effects. The format has changed recently.

**Comment by Kyon-irk** [comment]
Nothing changed
![1](https://user-images.githubusercontent.com/36105011/81470267-8f59fb80-921c-11ea-9c54-550854e9359a.png)

**Comment by Emulator-Team-2** [comment]
@kd-11 
RSX Capture:
-(Broken water effects.)

**Link:** [RSX-Capture-(Build-0.0.10-10346)](https://drive.google.com/open?id=1xOdlnv7dS4RxsYdAsX4SLC-wk7snyLmO)

**Comment by Emulator-Team-2** [comment]
RSX Capture and screenshot for remaining glitches.

<details> 
<summary>(Black texture / Missing Blur)</summary>

**RPCS3:** ![1](https://user-images.githubusercontent.com/38318848/82139362-8aea9f80-9827-11ea-9ae1-9599add6407b.png)

**PS3:** ![2](https://user-images.githubusercontent.com/38318848/82139395-b79eb700-9827-11ea-9b01-d8dbeb094f08.png)

</details>

RSX Capture:
**Link:** [RSX-Capture-(Build-0.0.10-10395)](https://drive.google.com/open?id=1k-GgV8lkSUhGV89B79kIGp4gbrk2mZ0N)

-------------------------------------------------------------------------------------------------------
<details> 
<summary>(Flickering colors / Missing Blur)</summary>

**RPCS3:** ![3](https://user-images.githubusercontent.com/38318848/82139510-8e325b00-9828-11ea-8863-dfcc8bca038a.png)

**PS3:** ![4](https://user-images.githubusercontent.com/38318848/82139518-97bbc300-9828-11ea-92c1-fc23dcf9abbc.png)

</details>

RSX Capture:
**Link:** [RSX-Capture-(Build-0.0.10-10395)](https://drive.google.com/open?id=1ryW2mzVL_UnHCJcEJoDWom0oPHvlaX8S)

**Comment by kd-11** [comment]
Flickering and other glitches are solved by https://github.com/RPCS3/rpcs3/pull/10733
However, the background remains black during the intro sequence instead of blue. I can fix this in a one-line fix but hardware tests have refuted my hypothesis so I will not commit the hack.

**Comment by MarioSonic2987** [comment]
It remains this black background in the initial cutscene. It should be blue.
![image](https://user-images.githubusercontent.com/20027681/130227784-4905548e-b209-4441-84df-d3c2a9e56a80.png)

**Comment by Emulator-Team-2** [comment]
## Update:

-Still an issue, tested with the latest master build: (0.0.23-14031).

**Screenshots:**

<details> 
<summary>(PS3/RPCS3 Comparisons)</summary>

**PS3:**
![1](https://user-images.githubusercontent.com/38318848/183310602-63c85549-9705-4f1c-a69e-88827a0b8575.png)
**RPCS3:**
![2](https://user-images.githubusercontent.com/38318848/183310607-98ce6e79-d2a6-4db8-a59c-5b9a08d2ff2a.png)

</details>

##

**(RenderDoc/RSX Capture)**
Link:
[rdc capture-vk - Deleted.]
[rsx capture - Deleted.]

##

**System configuration:**
* OS: Windows 10 64-bit
* CPU: Intel i7-10700
* Memory: 16GB RAM
* GPU: GTX 1660
* Driver version: 512.95.0.0

**Comment by Emulator-Team-2** [comment]
Still an issue, tested with the latest master build: (rpcs3-v0.0.30-15912).

**Comment by digant73** [comment]
is the black texture still an issue?

**Comment by ghost** [comment]
Issue still present?

**Comment by MarioSonic2987** [comment]
It's still present.
<img width="1282" height="752" alt="Image" src="https://github.com/user-attachments/assets/126ad62b-3e69-43dc-bb63-0d196c7f0ff3" />

[Log](https://github.com/user-attachments/files/23290571/RPCS3.log.gz)
[RSX Capture](https://github.com/user-attachments/files/23290592/NPUB30836_20251102143238_capture.rrc.gz)

**Comment by digant73** [comment]
please re-test on latest build. Hopefully some textures and reflections issues have been fixed by recent build 0.0.39-18790

**Comment by MarioSonic2987** [comment]
No change with 0.0.39-18790:
<img width="1282" height="752" alt="Image" src="https://github.com/user-attachments/assets/66cc7460-d684-4490-a525-4f98968f3fed" />

**Comment by Louidjy09** [comment]
Hey, so I have Graphical problems with Pirate Warrior. 
Specs:
CPU: AMD Ryzen 5 2600
GPU: Nvidia RTX 2080
16GB of ram
Game is on HDD
Using Vulkan


pretty much every character in game as basically all of their assets constantly showing.

<img width="2188" height="1439" alt="Image" src="https://github.com/user-attachments/assets/21f0c0cc-9297-430c-9a4f-9fd2c280c1a5" />

<img width="463" height="675" alt="Image" src="https://github.com/user-attachments/assets/5029710c-de45-4ed8-a382-0a385067da04" />

**Comment by MarioSonic2987** [comment]
Edit: Now fixed.

<details>
 <summary>Original comment</summary>
Can reproduce. PR #18395 caused this regression.

**Last working build:**
<img width="1282" height="752" alt="Image" src="https://github.com/user-attachments/assets/84c2e4ed-42b0-49a6-8e88-881577f5f4d6" />

**Broken build:**
<img width="1282" height="752" alt="Image" src="https://github.com/user-attachments/assets/0ebeb090-12fe-412f-8c76-762730a5e92d" />

[Log (Working)](https://github.com/user-attachments/files/26342547/RPCS3.log.gz)
[Log (Broken)](https://github.com/user-attachments/files/26342597/RPCS3.log.gz)

</details

**Comment by rleonever** [comment]
Can someone test again now that tons of rsx fixes just arrived?

**Comment by MarioSonic2987** [comment]
@rleonever It's still present.
<img width="1282" height="752" alt="Image" src="https://github.com/user-attachments/assets/b0dd2c04-8f23-450d-88a7-aaa1ff9fd281" />

**Comment by MarioSonic2987** [comment]
Applying [the hack posted in issue 12262](https://github.com/RPCS3/rpcs3/issues/12262#issuecomment-5209461551) fixes the black background.
<img width="1282" height="752" alt="Image" src="https://github.com/user-attachments/assets/57e2ff12-8ed3-4844-b3ff-fca841ca39b6" />

**Comment by LupinIIINiceGuy** [comment]
> Applying [the hack posted in issue 12262](https://github.com/RPCS3/rpcs3/issues/12262#issuecomment-5209461551) fixes the black background. <img alt="Image" width="1282" height="752" src="https://private-user-images.githubusercontent.com/20027681/637866694-57e2ff12-8ed3-4844-b3ff-fca841ca39b6.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3OTAyMjY3MTQsIm5iZiI6MTc5MDIyNjQxNCwicGF0aCI6Ii8yMDAyNzY4MS82Mzc4NjY2OTQtNTdlMmZmMTItOGVkMy00ODQ0LWIzZmYtZmNhODQxY2EzOWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwOTI0VDA1MDY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNDZhNmJiNzFlNmJlZjhkNGIwNmJkMWMzNTA1ZTllMGIxZmI1ZDVjYWI2NTJhOWQ0NGJhMzQyMDczMWFkNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.sWvNfgqgqlEJw7w2BDom_E9r1mKWGpw4ymiYLF2pOkQ">

How do you apply this hack?
