### ISSUE TITLE
data install issue:  Dai-2-Ji Super Robot Taisen OG and Gundam Breaker 2

### ISSUE THREAD

**Issue by RainKikyou** [RPCS3/rpcs3#2532]
Installation of Dai-2-Ji Super Robot Taisen OG and Gundam Breaker 2 will be a random problem

`F {rsx::thread} class std::runtime_error thrown: Invalid RSX method 0x4 (arg=0x0)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:34)`

`F {rsx::thread} class std::runtime_error thrown: rsx::thread::ReadIO32(addr=0x1f000000): RSXIO memory not mapped
(in file C:\rpcs3\rpcs3\Emu\RSX\RSXThread.cpp:1073)`

`F {PPU[0x1000001] Thread () [0x00a0b128]} class std::runtime_error thrown: Locking failed (lwmutex=*0x23414358, owner=0x1000000)
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\sys_lwmutex_.cpp:160)`

`F {PPU[0x1000000] Thread (main_thread) [0x00a0b1a8]} class std::runtime_error thrown: Locking failed (lwmutex=*0x23414358, owner=0xfffffffc)
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\sys_lwcond_.cpp:258)`

`F {rsx::thread} class std::runtime_error thrown: Invalid RSX method 0x8 (arg=0x41710)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:34)`

`F {PPU[0x1000012] Thread (GameDataInstall) [0x00c3db28]} class std::runtime_error thrown: Locking failed (lwmutex=*0xd01c75d0, owner=0x100000a)
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\sys_lwmutex_.cpp:160)`

Dai-2-Ji Super Robot Taisen OG good luck,  can intro, like the following video but there will be crash problems
https://www.youtube.com/watch?v=hh50Wapxqzs
![qq 20170314175533](https://cloud.githubusercontent.com/assets/20301499/23895117/a8943094-08df-11e7-8537-075da31a8486.jpg)

**Comment by raven02** [comment]
This game actually has two major issues.

1. The game data install will try to write under the same name as itself which is BLJS10355 instead of something like BLJS10355_GAMEDATA .This renders the game unable to boot up to install game data but resort to rename the original title to something else to prevent name collision.

2. During data installation , it will randomly failed due to lock mutex failed .

F {PPU[0x1000001] Thread () [0x00a0b128]} class std::runtime_error thrown: Locking failed (lwmutex=*0x23414358, owner=0x1000000) (in file C:\rpcs3\rpcs3\Emu\Cell\Modules\sys_lwmutex_.cpp:160)

**Comment by chenjirong82** [comment]
点点滴滴

**Comment by chenjirong82** [comment]
How to solve the  installation  of  data?       How  long will it take to solve this problem?

**Comment by AniLeo** [comment]
Is this still an issue

**Comment by chenjirong82** [comment]
yes,this is an issue....

2017-07-20 9:27 GMT-07:00 Ani <notifications@github.com>:

**Comment by khanh-dtp-vn** [comment]
Any good news, everyone?

**Comment by chenjirong82** [comment]
No good news..  we will wait for the end of this year.

2017-08-29 18:14 GMT-07:00 khanh-dtp-vn <notifications@github.com>:

**Comment by AniLeo** [comment]
Try retesting

**Comment by khanh-dtp-vn** [comment]
@AniLeo what does that mean :) ?!

**Comment by AniLeo** [comment]
Means the issue hasn't been updated in 6 months and needs retesting. There have been many changes to the emulator.

**Comment by khanh-dtp-vn** [comment]
I retested 2 days ago, it's still the same!

**Comment by Megamouse** [comment]
please retest

**Comment by chenjirong82** [comment]
me  too.the  game   still   is  not   work   I  have to delete game data folder every times.

**Comment by raven02** [comment]
Issue still exists in latest build

**Comment by Realmantik** [comment]
Locking problem with `sys_lwcond_.cpp` must be fixed. At least for me it is fixed in Heavy Fire: Afghanistan.

**Comment by jokoputera** [comment]
Try latest build, let see how is it going...

**Comment by khanh-it** [comment]
@jokoputera I can confirm that "Dai-2-Ji Super Robot Taisen OG  [BLJS10133] " is OK now (latest build).
But the problem with "Super Robot Wars OG The Moon Dwellers BLJS10335" is still persist.
https://github.com/RPCS3/rpcs3/issues/6588

```
E {SPU Worker 5} SPU: [0x06aa0] SPU Analyser failed, 138 vs 276
E {PPU[0x1000000] Thread (main_thread) [0x01353d8c]} SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
E {PPU[0x1000000] Thread (main_thread) [0x0130ff0c]} SYS: '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
E {PPU[0x1000005] Thread (GameThread) [0x00ad4428]} SYS: 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [1]
E {PPU[0x1000005] Thread (GameThread) [0x00ad503c]} SYS: 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
E {PPU[0x1000005] Thread (GameThread) [0x0130ff0c]} SYS: '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
E {PPU[0x1000005] Thread (GameThread) [0x013054ec]} SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000005] Thread (GameThread) [0x013054ec]} SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000005] Thread (GameThread) [0x013054ec]} SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E {PPU[0x1000006] Thread (fios mediathread 2) [0x013d2090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/Dat/Window/WindowToolData/Texture/otehon_waku_01.dds” [1]
E {PPU[0x1000006] Thread (fios mediathread 2) [0x013d2000]} SYS: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/Dat/Map/Seqence/SeqUnit” [1]
```

**Comment by tarkungZZ** [comment]
3 years they still didn't fix it.

**Comment by elad335** [comment]
Wjays reported here is fixed, I mean, we dont even HLE sys_lwcond/mutex anymore.
This issue should be closed, more issues should be reported in more github issues.

**Comment by tarkungZZ** [comment]
> Whats reported here is fixed, I mean, we dont even HLE sys_lwcond/mutex anymore.
> This issue should be closed, anymore game issues should be reported in more github issues.

my issue is "Dai-2-Ji Super Robot Taisen OG [BLJS10133]" will randomly failed when install data into HDD  “/dev_bdvd/PS3_GAME/USRDIR/Dat/Map/Seqence/SeqUnit” like comment above the problem is after close rpcs3 and next time I run the game it show me an error so I have to delete all game file and re-install data everytime.

**Comment by elad335** [comment]
NEW ISSUE

**Comment by tarkungZZ** [comment]
> @jokoputera I can confirm that "Dai-2-Ji Super Robot Taisen OG [BLJS10133] " is OK now (latest build).
> But the problem with "Super Robot Wars OG The Moon Dwellers BLJS10335" is still persist.
> #6588
> 
> ```
> E {SPU Worker 5} SPU: [0x06aa0] SPU Analyser failed, 138 vs 276
> E {PPU[0x1000000] Thread (main_thread) [0x01353d8c]} SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
> E {PPU[0x1000000] Thread (main_thread) [0x0130ff0c]} SYS: '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
> E {PPU[0x1000005] Thread (GameThread) [0x00ad4428]} SYS: 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [1]
> E {PPU[0x1000005] Thread (GameThread) [0x00ad503c]} SYS: 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
> E {PPU[0x1000005] Thread (GameThread) [0x0130ff0c]} SYS: '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
> E {PPU[0x1000005] Thread (GameThread) [0x013054ec]} SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
> E {PPU[0x1000005] Thread (GameThread) [0x013054ec]} SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
> E {PPU[0x1000005] Thread (GameThread) [0x013054ec]} SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
> E {PPU[0x1000006] Thread (fios mediathread 2) [0x013d2090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/Dat/Window/WindowToolData/Texture/otehon_waku_01.dds” [1]
> E {PPU[0x1000006] Thread (fios mediathread 2) [0x013d2000]} SYS: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/Dat/Map/Seqence/SeqUnit” [1]
> ```

I still have this install data issue for Dai-2-Ji Super Robot Taisen OG [BLJS10133] with lastest rpcs3 build what build did you use back then.

**Comment by elad335** [comment]
Closing, this issue is a mess. Mixed with random errors which has been fixed or workarounded whilst also contains newer and different problems, for newer problems open new issues.
