### ISSUE TITLE
GL: Deadly Premonition: DC - minimap overflows out of boundary

### ISSUE THREAD

**Issue by ghost** [RPCS3/rpcs3#2573]
In Deadly Premonition: The Director's Cut the minimap image overflows out of the boundary set by the edges of the minimap as you can see below. 
![rpcs3_2017-03-22_15-46-02](https://cloud.githubusercontent.com/assets/12888227/24223038/052298ce-0f1a-11e7-8007-8d1748039b66.png)

This is what it should look like
![firefox_2017-03-22_16-10-18](https://cloud.githubusercontent.com/assets/12888227/24223071/2352d110-0f1a-11e7-9d81-b8051d81152a.png)

Log file: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/863065/RPCS3.zip)

**Comment by kd-11** [comment]
Should be fixed by https://github.com/RPCS3/rpcs3/pull/2582

**Comment by darkredflame** [comment]
Issue still persists. Just to give some clarification on what is happening, this seems to be a function of how the game is handling the map. When you press select, the map will move from the minimap and take up the screen in a similar fashion as in my image above. However the map will be transparent and it will be offset to the right a bit, and this is the expected behavior.

![image](https://cloud.githubusercontent.com/assets/12888227/24289418/d7c92482-1046-11e7-860b-7d79dc5557cb.png)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/867473/RPCS3.zip)

**Comment by kd-11** [comment]
So the game works fine if you don't bring up the map?

**Comment by darkredflame** [comment]
Nah, the top image in the first post, or the last image in my last post are examples of what the game looks like when you **haven't** brought up the map yet with the select button. 

This is what the game looks like when you bring up the map (using the select button) in the emulator.
![rpcs3_2017-03-25_06-45-47](https://cloud.githubusercontent.com/assets/12888227/24322305/b343553e-1126-11e7-8bad-8e61b60806c6.jpg)

This is what is supposed to happen when you bring up the map in the game.
![image](https://cloud.githubusercontent.com/assets/12888227/24322310/c6840a3a-1126-11e7-8ad5-e64604399969.png)

For some reason, the emulator is making the map bigger in both cases, when you don't have the map brought up (the image with the map being fully opaque and not staying in the minimap area) and when you have the map brought up (the image with the map being transparent, but taking up more of the screen than it's supposed to.)

**Comment by kd-11** [comment]
Still an issue?

**Comment by digitaldude555** [comment]
Yes. @kd-11

**Comment by digitaldude555** [comment]
![screenshot 581](https://user-images.githubusercontent.com/26138653/47942228-dd8c9100-def9-11e8-9c8b-852f830a8128.png)

Still an issue one year later.

**Comment by digitaldude555** [comment]
![Screenshot (3743)](https://user-images.githubusercontent.com/26138653/61474305-0de56400-a991-11e9-968a-d6e8728d68da.png)
![Screenshot (3744)](https://user-images.githubusercontent.com/26138653/61474306-0de56400-a991-11e9-9df2-58c44b519465.png)
