### ISSUE TITLE
GL: Demon's Souls - write color buffers issue 

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#2688]
When warping from Nexus to Plananx Archstone, the screen goes black as if "Write Color Buffers" option was not checked in setings.

[RPCS3.log.txt](https://github.com/RPCS3/rpcs3/files/921788/RPCS3.log.txt)
https://youtu.be/j184JTz18fE

**Comment by kd-11** [comment]
Last I tested, this was a timing bug. Every once in a while, it'll proceed further with proper brightness rendering at a lower resolution than before.

**Comment by ArtyomAN** [comment]
_> Every once in a while, it'll proceed further with proper brightness rendering at a lower resolution than before._

I encounter with this problem every time at this moment of the game. I use 10/10 brightness in game settings (overwise I can see literally nothing), and set 720p resolution in the emulator.

**Comment by francis-roux-serret** [comment]
It also happens with me when using the first archstone in the tutorial : when I arrive into next zone, I only got the hud and black display : the game works (I see the stamina going down when I run and I can read signs when I find them) but I see nothing. As the game does not save progress in the tutorial I'm stuck in the first part of it forever !!!

**Comment by isshininu** [comment]
Yeah, it still persist.

**Comment by isshininu** [comment]
This bug no more reproduceable with these settings: OpenGL, Recimpiler + ASMJIT.
Is it was fixed in latest builds? Perhaps.

**Comment by ArtyomAN** [comment]
Yesterday I checked out the latest build. The problem is still there but there is some improvment. Now I can barely see my character on black background (see screenshot 1) and event see a source of light (see screenshot 2). :-)

![demonsouls_learning1](https://user-images.githubusercontent.com/27104345/29006735-7fdf8748-7afe-11e7-96fe-bdadd1d7d80e.jpg)
![demonsouls_learning2](https://user-images.githubusercontent.com/27104345/29006734-7fdeb700-7afe-11e7-8134-e45d08c07488.jpg)

Moreover, now I can quit the game normally and reload it again, after this action the problem is not detected. So this is actual only after moving from 1st tutorial location to the 2nd one.

**Comment by isshininu** [comment]
>I can quit the game normally and reload it again,

I guess it always works here.

**Comment by C0rn3j** [comment]
@isshininu @ArtyomAN 

Are you guys on Arch Linux using the AUR build?

**Comment by Asinin3** [comment]
@C0rn3j They're both clearly using windows seven with that user interface.

**Comment by C0rn3j** [comment]
@Asinin3 I completely missed that for some reason, nvm then.

**Comment by rafael-57** [comment]
Isn't this fixed?

**Comment by Asinin3** [comment]
It got fixed but then kd had to revert some changes from jarveson's PR which was incompatible with his code. I think it's still broken but not 100% sure.

**Comment by AniLeo** [comment]
Is this still a bug? @isshininu

**Comment by isshininu** [comment]
let me try with latest build

**Comment by ImGonaRot** [comment]
I'm using 0.0.4-6390 with Recompiler (LLVM)/(ASMJIT), and OpenGL.
Still can't see the character at start area. See only black and the menus.

**Comment by AniLeo** [comment]
That's why tooltip says it's required for Demon's Souls..
