### ISSUE TITLE
Saint Seiya Brave Soldiers [BLES01936]

### ISSUE THREAD

**Issue by marsselluo** [RPCS3/rpcs3#3170]
The game has a glitch when it uses the big bang attack, part of the screen turns white. The problem appears in vulkan and OGL renderers. The game runs most of the time at 30FPS with just a some sttutering. Sorry for my english.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1203549/RPCS3.zip)

![ssbs](https://user-images.githubusercontent.com/30375393/29008038-23af2f54-7ae6-11e7-92b4-f460e4cf84e2.png)

**Comment by kd-11** [comment]
Retest with current master. Might have been fixed.

**Comment by marsselluo** [comment]
unfortunately it didn't fix, the problem still exist on OGL and Vulkan.

**Comment by kd-11** [comment]
Retest

**Comment by marsselluo** [comment]
it didn`t fixed.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1322302/RPCS3.log.gz)

**Comment by Cereal-Killa** [comment]
Game is running excellent scaled up to 300%, very playable to me, the major issues are:

1. Choppy audio, specially on intro scene
2. Blurred background graphics on some of the menus
3. Apparently the bloom effect is broken on the characters.

Other than that it's running @ 30fps and has not crashed a single time!

![rpcs3_2017-10-24_15-55-38](https://user-images.githubusercontent.com/25939765/31961047-683b918c-b8d8-11e7-861d-03384beeebb9.jpg)
![rpcs3_2017-10-24_15-59-34](https://user-images.githubusercontent.com/25939765/31961048-687148ea-b8d8-11e7-9109-ccc2449716ce.jpg)
![rpcs3_2017-10-24_16-00-13](https://user-images.githubusercontent.com/25939765/31961050-689a4bbe-b8d8-11e7-8907-8eb5329c03e4.jpg)
![rpcs3_2017-10-24_16-00-26](https://user-images.githubusercontent.com/25939765/31961051-68c24fce-b8d8-11e7-9db1-7d988f0722fb.jpg)
![rpcs3_2017-10-24_16-02-03](https://user-images.githubusercontent.com/25939765/31961054-68ee9eb2-b8d8-11e7-9dbf-042559fa55b0.jpg)
![rpcs3_2017-10-24_16-00-35](https://user-images.githubusercontent.com/25939765/31961057-6916d45e-b8d8-11e7-912a-8945c01471d5.jpg)

**Comment by Cereal-Killa** [comment]
Log:

[Log.txt](https://github.com/RPCS3/rpcs3/files/1412043/Log.txt)

**Comment by Cereal-Killa** [comment]
![rpcs3_2017-10-29_09-08-27](https://user-images.githubusercontent.com/25939765/32142942-37da069a-bc89-11e7-970c-62e714b55e9c.png)

Just confirmed that the graphics look fine running on OpenGL, unfortunately it's slow and and freezes a lot which doesn't happen with Vulkan.

**Comment by AniLeo** [comment]
Retest to see if the initial issue has been fixed

**Comment by marsselluo** [comment]
It didn't fix
![sem titulo](https://user-images.githubusercontent.com/30375393/35362632-40941218-014d-11e8-97ab-8a9900bd29df.jpg)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1662027/RPCS3.log.gz)

**Comment by marsselluo** [comment]
With the latest build, the white screen problem has been fixed in OGL and Vulkan. Great job.

**Comment by MarioSonic2987** [comment]
Yes. I confirm that it's fixed, but there's a quarter of the screen, hiding Seiya.

**Before**:
![image](https://user-images.githubusercontent.com/20027681/37363778-15497a18-26f9-11e8-98be-e82afec50246.png)

**After**:
![image](https://user-images.githubusercontent.com/20027681/37364133-ee5a67e0-26f9-11e8-9212-a479a2c64a69.png)

**Comment by marsselluo** [comment]
On my there's any square, the screen is totally clean
![sem titulo](https://user-images.githubusercontent.com/30375393/37364582-b21702a4-26d9-11e8-9aaa-99e90994a7ef.jpg)

**Comment by Cereal-Killa** [comment]
Clear your shader cache and try again, big bang looks fine here.
I'm still getting blurred menu graphics in Vulkan though.

**Comment by MarioSonic2987** [comment]
![image](https://user-images.githubusercontent.com/20027681/37368279-13eca34a-2706-11e8-8a8e-36b408bb81c2.png)
I did it early, but it's still the same.

**Comment by Cereal-Killa** [comment]
What about OpenGL

**Comment by MarioSonic2987** [comment]
![image](https://user-images.githubusercontent.com/20027681/37368666-320f12b2-2707-11e8-8681-70ba81aed2a3.png)
Same, but there's no particle effects in the square.

**Comment by Cereal-Killa** [comment]
Strange, I have a GTX 770, driver version 390.77.

**Comment by MarioSonic2987** [comment]
I have 391.01.

**Comment by Cereal-Killa** [comment]
I would expect the same results on all newer nVidia cards, try cleaning and updating your drivers.

https://www.wagnardsoft.com/content/display-driver-uninstaller-ddu-v17084-released

**Comment by MarioSonic2987** [comment]
382.05
![image](https://user-images.githubusercontent.com/20027681/37369622-f102de04-2709-11e8-8330-c0288514b89f.png)

**Comment by kd-11** [comment]
Res scaling?

**Comment by MarioSonic2987** [comment]
I used Strict Rendering Mode, therefore, there isn't resolution scaling.

**Comment by Asinin3** [comment]
I have seen a very similar issue in Armored Core Previously where the top left corner would render correctly, also seen it in Jurassic Park Episode 1 and a couple others.

**Comment by MarioSonic2987** [comment]
With #5427, fixes broken depth on special attack effects:
![image](https://user-images.githubusercontent.com/20027681/50834328-085cf080-1354-11e9-9548-c4497f10cf74.png)

**Comment by kd-11** [comment]
Should be correctly fixed by https://github.com/RPCS3/rpcs3/pull/5937

**Comment by MarioSonic2987** [comment]
Still looks correctly with #5937.

Resolution Scale at 100%: 
![image](https://user-images.githubusercontent.com/20027681/57367827-0a13b500-718a-11e9-92e3-2d327e2e5cfe.png)
Resolution Scale at 300%: 
![image](https://user-images.githubusercontent.com/20027681/57367912-3af3ea00-718a-11e9-98eb-0736b7558362.png)

**Comment by AniLeo** [comment]
Closing as fixed
