### ISSUE TITLE
Regressions caused by #3200

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#3243]
#3200 is now merged and this is an issue tracker for any tickets arising from that.

Known issues and workarounds
- [x] Increased first time stutter - try openGL and roll back if all else fails while the shader pipeline is replaced with new code. It will be improved soon.
- [ ] Missing graphics using intel drivers on windows. This isn't really new, but warrants investigation
- [X] Broken immediate indexed render - A fix has already been submitted #3241 
- [x] Sometimes the shader cache may be corrupted if the emulator crashes when writing shaders to disk. Will be resolved soon with validity checks. Delete the shader cache if the emulator crashes when loading the shaders from disk.
- [x] Increased emulator startup time due to shaders loading. - Will be optimized in the near future. For now, you may delete the cache if loading is taking too long, or use openGL which has much faster loading times.
- [x] Toggling fullscreen may result in a crash or hang

**Comment by danilaml** [comment]
My screen blanks for a second and the game goes white when I try to play After Burner Neo Climax
(Win10 x64, R9 290). Happens after the stage is loaded in the "take off from the carrier" cut-scene.

This is then outputted to the log:
```
F {rsx::thread} class std::runtime_error thrown: Assertion failed! Result is FFFFFFFCh
(in file Emu\RSX\VK\VKGSRender.cpp:1523)
```
Here is the full log attached:
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1229678/RPCS3.zip)

Was fine before merge.
Here is the log with shader cache deleted (i.e. clean run):
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1229681/RPCS3.zip)

**Comment by kd-11** [comment]
That error means the driver encountered an error it could not recover from and was reset. What gpu is it? You can run the game with strict mode and debug output enabled to see if the validation layer catches anything before the crash. If it does it will be helpful.

**Comment by kd-11** [comment]
That error means the driver encountered an error it could not recover from and was reset. What gpu is it? You can run the game with strict mode and debug output enabled to see if the validation layer catches anything before the crash. If it does it will be helpful.

**Comment by danilaml** [comment]
@kd-11 I've listed my GPU in the original comment. It's AMD R9 290 4GB.
 Also, I've already run it using Strict Rendering Mode (and GPU texture scaling, though it shouldn't matter for Vulkan). Before the merge I had no problems with this game. I've completed a few levels just before compiling the new rpcs3 version.

Tested the OpenGL renderer: works OK, although slower.
Changed back to Vulkan and it didn't crash. Not sure what happened there, but the crash was reliably reproducible earlier.
Welp, I retried after that and sure got the crash again:
```
F {rsx::thread} class std::runtime_error thrown: Assertion failed! Result is FFFFFFFCh
(in file Emu\RSX\VK\VKGSRender.cpp:1523)
```

**Comment by kd-11** [comment]
I suggested strict to keep the khronos validation layers 'debug output' option from generating too much spam. Its the debug output I was asking for. The reason is that if I have to contact amd about it they will ask for it. I do have that game somewhere but I cant test it myself at the moment.

**Comment by danilaml** [comment]
@kd-11 I can't seem to find the option to enable debug output in the settings. Was it removed in Qt GUI rework?

**Comment by AniLeo** [comment]
config.yml, it's hidden on Debug tab
You can enable debug tab on GuiSettings

**Comment by kd-11** [comment]
The debug tab is hidden by default. Edit the config file in GuiConfigs to enable it.

**Comment by danilaml** [comment]
@kd-11 here is the log with Debug Outputted enabled (edited config manually):
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1229748/RPCS3.zip)

**Comment by Renusek** [comment]
Yakuza Ishin (BLJM61149 and NPJB90690 for the demo version) has flickering right now (almost every second)

![unknown](https://user-images.githubusercontent.com/4978744/29404727-17d5dcf6-833c-11e7-9bea-5319055057f7.png)

**Comment by kd-11** [comment]
@danilaml I have tested the NPUB version of the game with crimson 17.7.2 and wasnt able to make it crash. I've tried all the 3 starting fighters and it works fine. However, it did freeze when I resized to fullscreen and then windowed again. Does the crash happen when you resize the window? From the log, the validation layer did not catch anything making it difficult to track down the issue.

**Comment by kd-11** [comment]
@Renusek Is it also broken with openGL? Also, need some more info on your hardware setup.

**Comment by mamoulianfh** [comment]
BLJS10053 - Tales of Vesperia JPN - Vulkan only regression - The game freezes during main intro (this was caused already by pull #3083 , but after pull #3200 the game freezes after skipping intro as well, which was not the case before. 

In OpenGL game works with same problems as reported in game compatibility thread, but is faster for me as before.

Logs fof Vulkan, OpenGL (both strict rendering) and OpenGL without strict rendering as well:

[RPCS3_0.0.3_5743_Vulkan.zip](https://github.com/RPCS3/rpcs3/files/1230959/RPCS3_0.0.3_5743_Vulkan.zip)
[RPCS3_0.0.3_5743_OGL.zip](https://github.com/RPCS3/rpcs3/files/1230961/RPCS3_0.0.3_5743_OGL.zip)
[RPCS3_0.0.3_5743_OGL_NoStrict.zip](https://github.com/RPCS3/rpcs3/files/1230962/RPCS3_0.0.3_5743_OGL_NoStrict.zip)

**Comment by GeniusMage** [comment]
Tales of Graces f (BLES01617) requires to delete the cache before starting the game, otherwise it will only show a black screen.

**Comment by danilaml** [comment]
@kd-11 it happens about 50% of the time for me. If I open Radeon settings at the same time/just after the driver crash, they crash too. I'm currently on 17.1.1, I'll update my drivers and see if it helps (doubt it). Btw, I have a bunch of LiveKernelEvent's and atidxx64.dll crash reports in windows event log.

**Comment by kd-11** [comment]
There's a pretty serious possible bug I've discovered in the AMD driver actually when investigating the fullscreen crash. I have a fix for that but yea, try updating the driver for now.

**Comment by Illynir** [comment]
@GeniusMage Same problem here on Tales of Graces F.

**Comment by Blacksama** [comment]
There are post in the other thread, certainly not sure where the issues are supposed to go. Sorry about that.

https://github.com/RPCS3/rpcs3/pull/3200

**Comment by SakataGintokiYT** [comment]
@Blacksama 
What driver version you have installed ?

**Comment by kd-11** [comment]
I tested it myself and saw nothing of the sort. Might be a driver issue as it only affects one user

**Comment by SakataGintokiYT** [comment]
@kd-11 
Gtx 650 ti with driver 378.66 
With Vulkan i have texture flickering in every game.
But works good on 382.53 and on newest driver.

**Comment by kd-11** [comment]
Yea. I suspected that since I didn't see other complaints on discord.

**Comment by Blacksama** [comment]
Yea I am on 376.xx OK last time I updated my graphic driver to the latest release, I started getting black screens in every game like a screen saver had activated and had to reboot my machine for it to work again, I will l try a 380.xx again tonight (*shivers*). Thanks for your answer.

**Comment by isshininu** [comment]
Silent Hill: Downpour now cause RPCS3 to crash immediately.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1236321/RPCS3.zip)

**Comment by C0rn3j** [comment]
@kd-11 
> Sometimes the shader cache may be corrupted if the emulator crashes when writing shaders to disk. Will be resolved soon with validity checks. Delete the shader cache if the emulator crashes when loading the shaders from disk.

Can this possibly be the cause of this?

https://github.com/RPCS3/rpcs3/issues/3239

**Comment by Wehavecookies56** [comment]
Rayman 3 HD now displays a black screen after the opening movie plays. Sound and inputs still work, Tested both OpenGL and Vulkan

**Comment by Kubokoo** [comment]
In NieR - Replicant turning on/off "Write color buffer" does't give effect like it used to (game only works for few seconds like it used to before this commit)
[https://www.youtube.com/watch?v=Yv4F20i3M9I](before (gamplay recorded by Arkru))

[https://www.youtube.com/edit?o=U&video_id=YKyv-iuhCXM](now)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1237295/RPCS3.zip)

**Comment by kd-11** [comment]
@danilaml I have managed to recreate the amd crash reliably after reinstalling my drivers. No idea why it didn't crash before. Updating the khronos validation layers also now shows some parts of the spec have changed and the emulator needs to adapt.

**Comment by danilaml** [comment]
@kd-11 thanks! So it's an emulator issue then (I was waiting on updating my drivers until 17.8.1 goes out of beta, since the installer for the current latest driver apparently lacks the fonts for my language and I'm not sure what I'm selecting xD)?

**Comment by kamer1337** [comment]
unreal engine 3 games crash the emulator (program stopped working message) on vulkan 

Tony hawk's Pro Skater 5    -- on loading screen before ingame
Tony hawk's Pro Skater HD -- crash on blackscreen

i have only these 2 with UE3

**Comment by kd-11** [comment]
Program stopped working crash box is important so try and copy the text. I can confirm it doesn't happen on every UE3 title.

**Comment by kamer1337** [comment]
well i meant this error it doesnt contains any info
![s](https://user-images.githubusercontent.com/18437274/29741637-5e62190a-8a71-11e7-9321-e81e414aee32.PNG)

after pressing Debug in visual studio:
`Unhandled exception at 0x000000005735EE68 (nvoglv64.dll) in rpcs3.exe: Fatal program exit requested.`

**Comment by kd-11** [comment]
Thats 'as expected' - Nvidia's present engine doesnt like the asynchronous submit method used. It'll hopefully be fixed without impacting performance too much. I am curious as to what the max and min number of swapchain images are - dump vulkaninfo output `vulkaninfo > vulkaninfo.txt` and I'll take a look.

**Comment by kamer1337** [comment]
[vulkaninfo.txt](https://github.com/RPCS3/rpcs3/files/1253899/vulkaninfo.txt)

**Comment by kd-11** [comment]
Looks like vulkaninfo only captures basic info about the swapchain - however, the dump does highlight something different about the nv driver here - The present engine is bound by the vblank window (only FIFO and FIFO_RELAXED are available). I'll try and recreate the condition since I only have FIFO and IMMEDIATE. Might help cleanly resolve all the pending issues with presentKHR dying on us.

**Comment by kamer1337** [comment]
looks like disabling strict rendering mode resolves the issue but now strings are not visible

**Comment by kd-11** [comment]
Interesting. I know why UE3 crashes nvidia then.

**Comment by Blacksama** [comment]
KD after this PR this error pops up at random during Persona 5 animated Movies, in most cases the Movie can be skipped but in the ending Movie which is damn long by the way it always crash.
The error is not present in the revision right before 3200 (3235), also tried the very last revision (3381) and is the same error.  This error is repeatable it always crash at the ending Movie. Hopefully you can help me again thank you. 

<img width="354" alt="error rpcs3" src="https://user-images.githubusercontent.com/30393444/30010940-42f11958-90f9-11e7-926c-965ecb4fc84d.png">

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1273625/RPCS3.zip)

**Comment by jjsat** [comment]
After the PR there is a crash in some UE3 games in the intro section. It crashes on a null pointer exception on the line `m_fence.destroy();` in `gl::texture_cache::cached_texture_cache::destroy()` (actually glDeleteSync crashes because it is called with a 0 value). I guess there should be a check to m_fence.is_empty() before calling destroy() - at least this fixes the crash - but I am not sure, it might go wrong somwhere else.

This happens with
- Singularity after the first intro screen
- Bioshock 2 after the Intro movies
- Batman Arkham Asylum Demo after the intro logos
- Alien Breed Impact Demo before showing anything

**Comment by kd-11** [comment]
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glDeleteSync.xhtml
`glDeleteSync will silently ignore a sync value of zero.` so, yes, thats a driver bug

Some of the other issues listed here are fixed in current master
- AfterBurner Climax no longer crashes on start using AMD (Crimson 17.9.1)
- Nvidia flickering was fixed by a driver update although changes to memory management should also fix this from the emulator itself as well
- UE3 nvidia issues - Needs retesting by affected users

**Comment by kamer1337** [comment]
i have still crashes in ue3 games with strict rendering mode

**Comment by Blacksama** [comment]
KD using last revision 3488 Persona 5 no longer crashes on the long ending sequence, on top of that there is a noticeable increase in performance in the animated scenes much less stuttering. Impressive work as usual.

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/3651 Fixes some rare issues introduced by this PR, relating to broken graphics. I suspect the wierd floaty trail bug in afterburner might also be fixed but I havent tested.

**Comment by danilaml** [comment]
@kd-11 ABC glitch is still there:
![image](https://user-images.githubusercontent.com/2046350/31998228-b0f4870c-b997-11e7-92a1-e7026c47d912.png)

Happens with strict mode enabled too:
![image](https://user-images.githubusercontent.com/2046350/31998335-14ecd408-b998-11e7-92f6-a05e5f484263.png)

Though the frequent driver crashes during lift off cut scene appear to be gone now.

**Comment by kd-11** [comment]
The glitches reported in here are all either fixed or reasonably improved in current master.
