### ISSUE TITLE
RSX: Call of Duty 3 - Unknown blend eq 0xffff

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#3357]
Tested by https://github.com/RPCS3/rpcs3/commit/64a6fbe39ff089d0155a36aeb0d3c6360d223ad9

While attemp to ingame it throws fatal error "Unknown blend eq 0xffff"

```
F {rsx::thread} class std::runtime_error thrown: Unknown blend eq 0xffff
(in file Emu\RSX\gcm_enums.cpp:733)
```

**[LOG](https://mega.nz/#!6NEXBTbR!X82qM4kOhbEQvEkamPtxGSEqSI6_V-0EYIxFhacx36Q)**

**Comment by chrisrowley14** [comment]
Seems to be the same issue on Call Of Duty Modern Warfare 2

```
F {rsx::thread} class std::runtime_error thrown: Unknown blend eq 0x0
(in file Emu\RSX\gcm_enums.cpp:733)
```

**Comment by kd-11** [comment]
Retest, may have been fixed with recent builds.

**Comment by WetNips** [comment]
Tested on latest release build bc27f5f

As above, while attempting to load the first level from cutscene the game 
> throws fatal error "Unknown blend eq 0xffff"

No change on this behavior, tested with ASMJIT and SPU LLVM.

> F {RSX [0x0549b48]} RSX: class std::runtime_error thrown: Unknown blend eq 0xffff
(in file c:\projects\rpcs3\rpcs3\emu\rsx\gcm_enums.cpp:733)
E {cellAudio Thread} cellAudio: Audio backend stopped unexpectedly, likely due to a buffer underrun

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2753470/RPCS3.log.gz)

**Comment by Realmantik** [comment]
Issue still exists
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3142555/RPCS3.log.gz)

**Comment by QuaiGoner** [comment]
Confirm, still crashing

**Comment by Xcedf** [comment]
By disabling line 733 in gcm_enums and line 283 in VKGSRender.cpp i was able to get ingame, but it constantly compiling shaders, over 50k for less than a minute
![12](https://user-images.githubusercontent.com/7060586/58041984-23c9da80-7b42-11e9-87ad-8ab1d6ed6744.jpg)

**Comment by luxox8** [comment]
![0101](https://user-images.githubusercontent.com/25025914/60151389-8a2dc280-97aa-11e9-94cb-08fc9c596ee6.JPG)
Problem persist in versio 0.0.6-8275. At least now I can hear audio and voices.
Can someone share a build with the changes specificated by Xcedf in the previous post?

**Comment by toccata10** [comment]
Same kind of error on Virtua Tennis 3 [BLUS30021]
```
F {RSX [0x000525c]} RSX: St13runtime_error thrown: Unknown blend eq 0x0
(in file ../rpcs3/Emu/RSX/gcm_enums.cpp:734)
```

**Comment by Xcedf** [comment]
Tried to disable these lines again but on newer build there's no longer an infinite shder compilation, and games works just fine

**Comment by dyno0** [comment]
> Tried to disable these lines again but on newer build there's no longer an infinite shder compilation, and games works just fine

How do you exactly do that? @Xcedf

**Comment by Xcedf** [comment]
@dyno0 
file gcm_enums.cpp line 723:
fmt::throw_exception("Unknown blend eq 0x%x" HERE, in);
comment out or remove
file VKGSRender.cpp lines 190 and 191:
default:
			fmt::throw_exception("Unknown blend op: 0x%x" HERE, static_cast<u32>(op));
Same comment out or remove

**Comment by dyno0** [comment]
I get that, but did you get the source, commented the code and made your own build, or you did it on a master build and just modify it? @Xcedf

**Comment by RainbowCookie32** [comment]
You need to get the source and build it with the changes

**Comment by elad335** [comment]
Fixed by #7780.

**Comment by suberg** [comment]
Issue still exists

![Capture](https://user-images.githubusercontent.com/18160956/170734486-e921d427-047b-4f4b-9e42-62b73db5b8d2.PNG)

[Log.zip](https://github.com/RPCS3/rpcs3/files/8787859/Log.zip)

**Comment by Blackbird88** [comment]
Can confirm this bug still happens.
[Log.zip](https://github.com/RPCS3/rpcs3/files/9038595/Log.zip)

**Comment by RareMv** [comment]
As of 0.0.23-14001 - this still persists.

Game hangs when the 1st mission starts.

Game is marked as "Playable" in RPCS3. Clearly not playable, haha.

**Comment by itsTyrion** [comment]
Confirmed, still an issue, please reopen. Also had 2 random RSX FIFO desyncs earlier. 
And random red/blue glitches. Please reopen

**Comment by kd-11** [comment]
You should try using fifo atomic or "atomic and ordered" in the advanced tab.

**Comment by elad335** [comment]
Also has the error message actually remained the same? iirc the specific error shouldn't happen anymore and it's relevant even if it's a different error at the same spot.

**Comment by Darkhost1999** [comment]
Looks to be the same error to me at the same function.

Before
> F {rsx::thread} class std::runtime_error thrown: Unknown blend eq 0xffff
(in file Emu\RSX\gcm_enums.cpp:733)
LOG
![733.png](https://user-images.githubusercontent.com/60384196/190637532-04bf7a05-4277-46d2-b602-7e5cf4125b22.png)

After
F {RSX [0x0564a30]} SIG: Thread terminated due to fatal error: Unknown blend eq 0xffff
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\gcm_enums.cpp:959[:22], in function to_blend_equation)
![959.png](https://user-images.githubusercontent.com/60384196/190637600-bed8a46d-741d-4b4a-9013-66bd62234b28.png)

**Comment by itsTyrion** [comment]
> Also has the error message actually remained the same? iirc the specific error shouldn't happen anymore and it's relevant even if it's a different error at the same spot.

```F {RSX [0x0564a30]} SIG: Thread terminated due to fatal error: Unknown blend eq 0xffff
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\gcm_enums.cpp:959[:22], in function to_blend_equation)
```

**Comment by itsTyrion** [comment]
> You should try using fifo atomic or "atomic and ordered" in the advanced tab.

Already had that thought but I want to see if I can maybe pinpoint it to a config change so I can add a sensible wiki entry, just takes some time because CoD 3 has a damn unskippable cutscene when you load a save -_-
