### ISSUE TITLE
Vulkan causing AMD driver crashing and BSOD in certain areas in Demon's Souls.

### ISSUE THREAD

**Issue by Justizia** [RPCS3/rpcs3#3482]
It only happens in certain areas. For example, I can play the tutorial until I reach a specific intersection, and I can load the Nexus, but I crash in the loading screen to Boletarian Palace. I am using the latest drivers (17.9.2) and I tried using a build from before the recent merge and ran into the same issue.

`F {rsx::thread} class std::runtime_error thrown: Assertion failed! Result is FFFFFFFCh (in file c:\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:564) F {PPU[0x1000005] Thread (HighGraphics) [0x009e1c8c]} class std::runtime_error thrown: Assertion failed! Result is FFFFFFFCh (in file c:\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:564)`

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1323364/RPCS3.log.gz)
[Pre-MergeRPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1323372/Pre-MergeRPCS3.log.gz)

**Comment by heribertofilho** [comment]
Same as #3484 and is being tracked in #3458 , kd-11 is already fixing this error.

**Comment by Asinin3** [comment]
@heribertofilho #3484 is tracking a regression from the merge, the OP had the same issue pre-merge. Justizia is also not using strict rendering mode.

**Comment by AniLeo** [comment]
Duplicate of #3474

**Comment by AniLeo** [comment]
Similar issue was fixed today, test with latest kd-11 PR

**Comment by Asinin3** [comment]
test

**Comment by Asinin3** [comment]
Comment from Justizia:
"Still happens with the rsx: More Fixes PR."

He is unable to comment here due to a restriction on this repo not allowing new accounts to comment or something.

**Comment by AniLeo** [comment]
Try again

**Comment by Justizia** [comment]
Error still persists with the rsx: More Fixes PR. Crashes in the same area and spits out the same error.

**Comment by Justizia** [comment]
I installed the Vulkan SDK and enabled Debug Output and Strict Rendering. Here's a new log with the error while using 6262.

[DebugRPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1326158/DebugRPCS3.log.gz)

**Comment by AniLeo** [comment]
Unfortunately only validation error there is 

```
·E 0:03:44.445879 {rsx::thread} RSX: ERROR: [Image] Code 165722113 : vkCreateImage parameter, pCreateInfo->initialLayout, must be VK_IMAGE_LAYOUT_UNDEFINED or VK_IMAGE_LAYOUT_PREINITIALIZED. The spec valid usage text states 'initialLayout must be a valid VkImageLayout value' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageCreateInfo-initialLayout-parameter)
```

Which is fixed by #3488 and is almost certainly unrelated to this issue

**Comment by rhythmthief** [comment]
I have been struggling with this issue since before the Vertex Rewrite

**Comment by Nezarn** [comment]
This issue is the same as #2201 since OP has RX480, and issue still exists, its a bit shame rpcs3 is nvidia biased too, since their driver bug already has a workaround, amd has issue for more than a year already, still no fix for crash.

Also multiple games are affected, it affects Project Diva Dreamy Theater too.

**Comment by kd-11** [comment]
Like I said before, bsod is a driver bug. And rpcs3 is not nvidia biased. Nvidia users end up with very crashy builds because I use AMD hardware. If it crashes without validation errors its on the driver vendor or khronos to update the spec.

**Comment by Nezarn** [comment]
@kd-11 if its a driver issue, how come mesa(radv) has the same issue ? (and mesa\radv != windows driver), so basically rpcs3 has an issue, not the drivers. (and I don't think amd devs and mesa devs make the same bug in driver)

**Comment by kd-11** [comment]
BSOD only happens on windows. Vulkan error FFFFFFFC is a different issue that has been mostly resolved. BSOD should not happen at all - thats for AMD to solve. It doesnt matter how broken rpcs3 is, a userland process should not kill the kernel. As for radv exiting with device lost error when running DeS - I am unable to reproduce on my system. Need more users with the same setup to encounter the same issue so that it is easily reproducible.

**Comment by Nezarn** [comment]
@kd-11 if you have project diva F, you can always reproduce this issue in Black Rock Shooter song. Btw BSOD doesn't happen anymore, just driver crashes with device lost. (and both windows and linux crashes at the same place, linux crashes so hard that X session becomes completely locked, can't even change to terminal)

Gonna try and find a place in DeS to reproduce this 100%

**Comment by henriquenj** [comment]
I side with @kd-11 on this matter: crashing kernels is not an userland problem. What RPCS3 might do is just to avoid the crashing condition altogether, however it'd be just a workaround. The real bug is on the driver.

When your X session crashes, can you still ssh into the computer? That should tell you if the kernel is alright.

**Comment by rhythmthief** [comment]
@henriquenj it's possible to ssh into the machine, and while it appears to be up and running for the most part, attempting a reboot leads to a complete freeze (ssh cuts off for good, the old frame is still stuck on the screen, nothing happens).

**Comment by henriquenj** [comment]
Likely some program is holding up the reboot process. I suggest you to take a look at `/var/log/messages` when this happens, however I have no clue what to look for.

**Comment by rhythmthief** [comment]
Fixed by #3618

**Comment by Justizia** [comment]
I can confirm that the problem has been fixed. Kudos to kd11 and everyone else who works on the emulator.
