### ISSUE TITLE
Not enough available space message with precompiled versions

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#3506]
When using the AppImages on Linux, I have this message with several games:
ERROR: not enough available space (terminate application).
If I compile the same version, it works (this error doesn't show up).
![space-pb](https://user-images.githubusercontent.com/7478580/30882008-fcb0387c-a307-11e7-8fcc-a08c6d615203.jpg)
[RPCS3.log-NotEnoughSpace.gz](https://github.com/RPCS3/rpcs3/files/1334848/RPCS3.log-NotEnoughSpace.gz)
Game tested: BLUS31588 (guilty gear revelator). Happens also on pixeljunk shooter (npua80253)

**Comment by zekesonxx** [comment]
I'm getting the same error with Journey (NPUA80275), it wants 694526012 KB, and considering that's almost 700GB I suspect it's an error.

Using `rpcs3-v0.0.3-2017-10-02-81b3e7e-8244_linux64.AppImage`, log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1360855/RPCS3.log.gz).

Going to try compiling rpcs3 myself and see if that fixes the error.

**Comment by zekesonxx** [comment]
Update: compiled rpcs3 manually, and Journey runs fine (well, not fine, but it gets long past that error message).

**Comment by hcorion** [comment]
This is most likely a clang bug, the AppImages are compiled with Clang, and when compiling with clang 5.0 on Arch Linux I also run into this bug.

**Comment by Enverex** [comment]
Just confirming the same as hcorion; this happens for me with the AppImage from the 9th on Arch (image is from trying to load Skate 3).

![image](https://user-images.githubusercontent.com/958670/31495285-eca873ec-af4e-11e7-9d33-6b8d2bc081bb.png)

**Comment by VelocityRa** [comment]
Getting this on Windows too.
![image](https://user-images.githubusercontent.com/6632271/32869927-3266eda2-ca82-11e7-9509-0da4a1f7c0b1.png)

Game is Sly 2: Band of Thieves, with fast interpreter.

**Comment by videah** [comment]
I get this issue when I try to boot Skate 3, but only if there's a save file present. If I clear the save, it'll boot just fine until I next try to boot it.
![image](https://user-images.githubusercontent.com/4761786/32985855-de1128e4-ccbb-11e7-8c40-15a050c92481.png)

**Comment by himaboo** [comment]
i have the same error in ea sports active 2 
[https://ibb.co/kMoXFR](url)
how can i fix this

**Comment by Subarasheese** [comment]
I am getting a similar problem on FIFA Street (2012) NPUB30651.

Clean install, no saves used.

"There is not enough available space in the HDD. To play the game, at least 658 KB more space is required. Exit the game and obtain the necessary space. "


![image](https://user-images.githubusercontent.com/35178075/34921631-12ab58c0-f964-11e7-8972-f214d0bbb2b9.png)

**Comment by Shoegzer** [comment]
Getting the same thing here after completing a level or dying in Resogun.

**Comment by Bielecki** [comment]
Same here on Fifa Street. Any update?
![](https://i.imgur.com/HYAJtEP.png)
i7-7700K, GTX 1070, 16 GB RAM, Windows 10 x64

**Comment by HorrorTroll** [comment]
![image](https://user-images.githubusercontent.com/24840279/35797869-a9c51864-0a93-11e8-9b61-72e0c2eb4500.png)

Same here on Sonic & SEGA All-Star Racing!

**Comment by Nikorasu95** [comment]
This bug even happens on builds provided on the RPCS3 website.

**Comment by Psycho-Hedgie** [comment]
v.0.0.5-6905 Windows
Lolipop Chainsaw still gives me that error

**Comment by reecespieces** [comment]
v.0.0.5-6980 Windows (latest release at time of writing. Binaries downloaded from the RPCS3 website)

Lolipop Chainsaw is still giving me that error

**Comment by Asinin3** [comment]
Fifa Street doesn't give the hdd space error anymore.
![rpcs3_2018-07-11_1606](https://user-images.githubusercontent.com/15137035/42559682-55c1bb20-84e4-11e8-8ad7-96dd5f1599cb.jpg)

**Comment by JustinSpedding** [comment]
I stopped seeing that error with Lollipop Chainsaw. I am using version 7087.

**Comment by Nikorasu95** [comment]
@JustinSpedding What are your settings? Because i'm using 7089 and i'm still getting that error.

**Comment by JustinSpedding** [comment]
@Nikorasu95 

LOLLIPOP CHAINSAW [BLES01525] (different serial number than yours)
rpcs3-v0.0.5-7087-c5dcef52
Linux Mint 19 x64
PPU: LLVM recompiler
SPU: ASMJIT recompiler
Renderer: Vulkan
Resolution: 1280x720

**Comment by Nikorasu95** [comment]
I tried your settings and I'm getting the error on Windows 10 Version 1803 (OS Build 17134.165)
Specs: 
CPU: i7 8700K
GPU: GTX 1080 Time
RAM: 16 GB DDR4
SSD boot drive: Samsung 960 Pro m.2 1TB
HDD: 6 TB Western Digital Back (RPCS3 installed here)
HDD: 12 TB Seagate barrecuda pro

**Comment by AVissie** [comment]
![rpcs3 - tales of symphonia - dawn of the new world error](https://user-images.githubusercontent.com/42137509/43707836-47be1188-9969-11e8-9671-c94251900a64.jpg)
Tales of Symphonia Dawn of a New World [NPUB31194]
RPCS3 version: 7138

**Comment by notwarhol** [comment]
<img width="641" alt="2018-09-27 22_05_08-fps_ 60 00 _ opengl _ 0 0 5-7404 _ lollipop chainsaw bles01525" src="https://user-images.githubusercontent.com/4278385/46184048-c4147b80-c2a1-11e8-8ecf-b59626be2364.png">
Using Windows build v0.0.5-7404-72ba062b_win64 with firmware 4.81 and I am still getting this issue. 

log
https://pastebin.com/raw/x4wHDysi

**Comment by Psycho-Hedgie** [comment]
Just wanna update on confirming that Lolipop Chainsaw nows works for me. I no longer get this message. I did absolutely nothing different. Just fixed itself in an update sometime around a late October.

**Comment by notwarhol** [comment]
> Just wanna update on confirming that Lolipop Chainsaw nows works for me. I no longer get this message. I did absolutely nothing different. Just fixed itself in an update sometime around late October.

Can you give any more details on the build/config? I'm still getting this in the current Win release
<img width="641" alt="2018-11-15 13_41_41-fps_ 59 97 _ vulkan _ 0 0 5-7498 _ lollipop chainsaw bles01525" src="https://user-images.githubusercontent.com/4278385/48574093-49003680-e8dc-11e8-983e-5ef6d7a8b9c5.png">

**Comment by notwarhol** [comment]
@Syko7956

**Comment by Kravickas** [comment]
This should be fixed, maybe some old cache or something ?

**Comment by notwarhol** [comment]
With v0.0.6-7796-982b2ab8_win64 i can get to the title screen, so it looks to be good!

**Comment by reecespieces** [comment]
![Capture](https://user-images.githubusercontent.com/15993751/54558467-308c4f80-4994-11e9-83c8-5c5262bbfd84.PNG)


Still having this problem on latest version. 



Using a 6TB HDD with over 2TB of free space.

**Comment by KBouder** [comment]
I have the same issue with Lollipop Chainsaw.. Here's a screenshot
![image](https://user-images.githubusercontent.com/11525691/55298727-399e0780-53fd-11e9-8470-e624864d51e0.png)
Now the weird thing is when I did the math, this came back to 1.32 TB of space required. The drive that RPCS3 is running off of has 2.67 TB of free space. I'm wondering if it's an issue with games that run on the Unreal Engine 3. Just a theory though. I would love to see this game be playable again, since it was in very good shape about a year ago.

**Comment by EvanHuxley** [comment]
Experienced this issue as well yet moving my files from my HDD to windows boot SSD resolved it.

**Comment by bloodydom666** [comment]
there is workaround in windows make vhd about 80-500GB and move rpcs3 there

**Comment by Artins90** [comment]
Also getting this on a 4TB HDD, it's annoying.

**Comment by elad335** [comment]
Test #7674, probably won't fix all of it though.

**Comment by Artins90** [comment]
The error is still there for BLUS30917 (Lollipop Chainsaw):
<img width="962" alt="Capture" src="https://user-images.githubusercontent.com/28777957/75762082-69a30880-5d3a-11ea-8235-3953fdb5943e.PNG">

**Comment by jakesterdog123** [comment]
@Artins90 can also confirm this for that title with a 4tb hdd

**Comment by everstraywolf** [comment]
confirm for BLUS30917 (Lollipop Chainsaw) with a 4tb hdd to

**Comment by revenz** [comment]
confirmed I get this with Lollipop Chainsaw if RPCS3 is on a 4TB hdd.  If i put it on a 500GB drive, the problem goes away.  
But this workaround isnt that friendly as any installed PKGs have to be on the smaller drive.

**Comment by reecespieces** [comment]
I'm not having this issue with Lolipop Chainsaw anymore. Still using the same 6TB HDD. Not quite sure which update fixed it for me.

**Comment by revenz** [comment]
I'm on the very latest version (RPCS3 just autoupdated yesterday when I posted that).

**Comment by Artins90** [comment]
> I'm not having this issue with Lolipop Chainsaw anymore. Still using the same 6TB HDD. Not quite sure which update fixed it for me.

Still not working on a 4TB HDD, I cleared all the caches before booting the game:
<img width="1765" alt="Capture" src="https://user-images.githubusercontent.com/28777957/82748870-84b76e80-9da5-11ea-9f8b-6ca14afef306.PNG">

What settings are you using?

**Comment by P3rf3ctXZer0** [comment]
I am unable to run lolipop chainsaw which was the only reason I grabbed this emulator.

**Comment by reecespieces** [comment]
@Artins90 

Just the default settings with Vulkan and VSync.

**Comment by rpgfan4life** [comment]
Not working for me too.

Windows 10
CPU: Intel Core i7 10700
GPU: NVIDIA GeForce GTX 1660
RAM: 64bit
Storage: D drive, E drive each 6TB, more than enough space

After trying to install a patched version of Tales of Symphonia: Dawn of the New World PSN (NPUB31194) this error has been starting to happen. Even if I uninstall it and reinstall it the problem still occurs. Even if uninstall it and just install Tales of Symphonia Chronicles (NPUB50101) the error still stays indefinitely. Where can I access all the HDD game memory space and delete them or, even better, is there a proper solution for this? Much thanks!

**Comment by elad335** [comment]
Test with #8799

**Comment by Artins90** [comment]
Lollipop Chainsaw finally works on my 4TB HDD, thank you for fixing this
<img width="1281" alt="Capture" src="https://user-images.githubusercontent.com/28777957/93647455-bfa27980-fa08-11ea-8d48-db5ae34d7ad0.PNG">

**Comment by elad335** [comment]
Still an issue?

**Comment by P3rf3ctXZer0** [comment]
I have not had time to test will test now.

**Comment by P3rf3ctXZer0** [comment]
Using test environment rpcs3-v0.0.12-11088-8307f82f_win64

**Comment by P3rf3ctXZer0** [comment]
![E4EdbiT 1](https://user-images.githubusercontent.com/10351221/97136903-67a31500-1722-11eb-8cbc-b2213921afb5.jpeg)
It seems to be working 👍
