### ISSUE TITLE
PPU: FCMPO inaccuracies

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#3516]
Currently FCMPO is just falling back to FCMPU.

Whenever [11] is compared, it returns 00001000 on getFPSCR(), which is the correct value for FCMPU. 
However, on a real PS3, this value is A0081000 on FCMPO. Since we fall back to FCMPU, we're obtaining the wrong value here when using FCMPU.

Everything else besides that scenario is accurate.

**Comment by hcorion** [comment]
After doing some research the issue is that the NaN exceptions are not implemented. If you look at 
https://github.com/RPCS3/rpcs3/blob/adf119e960cc455d526de650bc53901fc1755a40/rpcs3/Emu/Cell/PPUTranslator.cpp#L4141-L4153
you can see the NaN exception calls are commented out (and if you do uncomment it, it doesn't compile).

Perhaps this could be added to the roadmap?

**Comment by dio-gh** [comment]
Needs updating / retesting.

**Comment by elad335** [comment]
Interpreter's bug has been fixed.

**Comment by dio-gh** [comment]
So it's still an issue on the recompiler? Would make sense to keep the ticket open then I guess.

**Comment by elad335** [comment]
Nope, they are both on the same state now.

**Comment by dio-gh** [comment]
Closable then. :tada:

**Comment by elad335** [comment]
I meant only this.
> Note: On Interpreters on RPCS3, the sample always returns 00000000 on getFPSCR(). Something is wrong there as well.

**Comment by AniLeo** [comment]
The issue still persists since FCMPO and FCMPU are still implemented by exactly the same code

**Comment by ghost** [comment]
This should be investigated, who knows whats being broken because of this

**Comment by digant73** [comment]
maybe this is another bug that could be analyzed and fixed by @elad335, as he did recently with a similar bug fixed by #17690?

**Comment by elad335** [comment]
Long story short, there is no practical different between FCMPU and FCMPO for generic applications. Which is why PS3 applications work even though the implementation is identical. The difference lies in how they raise floating point exceptions, not known application read floating point exceptions.

**Comment by ghost** [comment]
@elad335 I see, so it’s not necessarily needed then

**Comment by rleonever** [comment]
> Long story short, there is no practical different between FCMPU and FCMPO for generic applications. Which is why PS3 applications work even though the implementation is identical. The difference lies in how they raise floating point exceptions, not known application read floating point exceptions.

@elad335 can you confirm is this can be closed or there is still something missing?
