### ISSUE TITLE
Exit when process finishes, Issue with launchers

### ISSUE THREAD

**Issue by marcussacana** [RPCS3/rpcs3#3778]
![https://a.pomf.space/ounkqvgghlwv.png](https://a.pomf.space/ounkqvgghlwv.png)

When a game have a laucher like the Shadow of The Colossus [BCES-01097], the "Exit when finishes" is triggered in the wrong time and close the RPCS3 without run the main executable.

I think the log isn't needed, but is here, just in the case:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1500511/RPCS3.log.gz)

**Comment by Asinin3** [comment]
This was fixed three days ago when https://github.com/RPCS3/rpcs3/pull/3688 was merged, did you update?

**Comment by marcussacana** [comment]
Ohh srry, here:
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/1500741/RPCS3.log.zip)

That issue isn't about a crash? 
My case is the game with a "launcher" who run a secondary elf,
I'm not sure, but looks the problem is the event is waiting the end of the eboot.bin execution,
the BCES-01097 have 2 games in one, if you select one, looks the eboot process end and start the execution of the selected game .elf, before the emulation resume in the called  elf, the "Exit on end" is triggered and close the emulator.
I'm saying i'm not sure because I'm not a c++ dev, i can't debug to see the true problem, srry.

It's this build: https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-7014/artifacts

**Comment by Nekotekina** [comment]
Must be fixed in #3775

**Comment by marcussacana** [comment]
Not fixed yet...
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/1502288/RPCS3.log.zip)

**Comment by Nekotekina** [comment]
Try new build

**Comment by marcussacana** [comment]
Nothing...
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/1502874/RPCS3.log.zip)

**Comment by Asinin3** [comment]
I tried it and it worked for me, completely fixed 👍 

@marcussacana Your latest log is from master? it doesn't say that it's from the PR build here: https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-7022/artifacts

**Comment by marcussacana** [comment]
Oops, it's working, I was a long time without sleep at that time, it seems that was my mistake, sorry and thanks guys.
