### ISSUE TITLE
Regressions caused by #3772

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#3821]
This is a tracker for any regressions introduced by https://github.com/RPCS3/rpcs3/pull/3772

**Comment by GeniusMage** [comment]
Reposting this here, since it hasn't changed:

**Tales of Vesperia**

![bandicam 2017-11-23 14-30-21-974](https://user-images.githubusercontent.com/27543170/33175333-b97ffc64-d05b-11e7-9a4b-dfadd8056708.png)
![bandicam 2017-11-23 14-34-23-321](https://user-images.githubusercontent.com/27543170/33175395-fb4840ac-d05b-11e7-849a-bd8ec86ccc1f.png)
Sky texture no longer works in main menu and world map

**Comment by PTKickass** [comment]
Regression in Jak and Daxter Collection (BCUS98281), game no longer boots.
![captura de ecra 556](https://user-images.githubusercontent.com/20132880/33498366-f900015e-d6c8-11e7-8c42-a64fa7f3eee1.png)

**Comment by Marthgun** [comment]
I'm not sure if this is a regression, it's pretty much the same as it was for the early commits on #3772 

Tales of Graces f [BLES01617]

Skits are working beautifully, but the transparency lines aren't just affected the in-game cutscenes and the end-of-battle pose screen, it's affecting every part now.  SO CLOSE!!!

![togf_intro](https://user-images.githubusercontent.com/15056246/33498458-04f70f84-d697-11e7-993f-3d389c6563a3.PNG)


![togf_world](https://user-images.githubusercontent.com/15056246/33498466-07cd2414-d697-11e7-9f17-d464d1443ab4.PNG)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1522624/RPCS3.log.gz)

**Comment by zekesonxx** [comment]
Wipeout HD (NPUA80105)'s menu has some serious graphical regressions

[![it is a wipeout](https://img.youtube.com/vi/UcNnkLVqFBE/0.jpg)](https://www.youtube.com/watch?v=UcNnkLVqFBE)

**Comment by FabTheZen** [comment]
Introduced ugly frameskip in Skate 3, that makes the game much less playable https://gfycat.com/BigPoshIrishwaterspaniel

**Comment by FibYar** [comment]
P5. Manga-style insertions breaked.
![20171202131225_1](https://user-images.githubusercontent.com/12131583/33514392-49979654-d764-11e7-803f-b295ea27852e.jpg)

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/3827

**Comment by PTKickass** [comment]
Retested with #3827 and the Jak and Daxter collection still refuses to boot.

Actually, correcting my previous report, the build that introduced the problem was actually #3820 and not #3772. I followed the link on the official Discord for reporting regressions, but didn't check the build properly.

Anyway, attaching a .log file and a screenshot of the game's state in any case.
![captura de ecra 561](https://user-images.githubusercontent.com/20132880/33516057-e1e08714-d763-11e7-94cd-023723f36a2c.png)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/1523831/RPCS3.log)

**Comment by GeniusMage** [comment]
#3827 fixes the sky in Vesperia (and the other new things).

**Comment by kd-11** [comment]
@PTKickass In that case its better to open a separate issue for that since the commits are by a different contributor.

**Comment by M220** [comment]
Hi
Thanks for your beautiful work!
There is a regression in Persona 5 that wasn't there until commit 3772 : 
 Before : 
![untitled 2](https://user-images.githubusercontent.com/26696487/33517725-76b673dc-d79e-11e7-9065-8966fd42c1d6.png)
Now : 
![untitled](https://user-images.githubusercontent.com/26696487/33517740-93d2cd30-d79e-11e7-9309-2bb61acc3a58.png)
And here is shader log and main log ( I don't think it will be needed but anyway :D )
Before : 
shader log : 
[shaderlog 1.zip](https://github.com/RPCS3/rpcs3/files/1523969/shaderlog.1.zip)
main log : 
[RPCS3 log 1.zip](https://github.com/RPCS3/rpcs3/files/1523970/RPCS3.log.1.zip)

After : 
Shader log : 
[shaderlog 2.zip](https://github.com/RPCS3/rpcs3/files/1523971/shaderlog.2.zip)
Main log : 
[RPCS3 log 2.zip](https://github.com/RPCS3/rpcs3/files/1523972/RPCS3.log.2.zip)

also there is something wrong in rsx generating feature . I don't know how much rpcs3 ( after commit 3772 ) need to have compiled rsx to be satisfied :/ it just generate over and over again every time I lunch P5 and I now have more than 10000 compiled rsx ( for easier work for this main bug , I deleted them so your work get easier with shader log but... ) , before PR 3772 I had just 3700 compiled rsx  
tnx for your hard work , Love You ;)

**Comment by rodjun** [comment]
@M220 Test with https://github.com/RPCS3/rpcs3/pull/3827/

**Comment by FibYar** [comment]
@rodjun Is there an available build with #3827 ? Or should I build it myself?

**Comment by MarioSonic2987** [comment]
@FibYar https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-7124/artifacts

**Comment by slashiee** [comment]
WipEout HD (NPUA80105)'s menu regression still happens for me on #3827.
![2017-12-02_10-56-53](https://user-images.githubusercontent.com/15317421/33518761-9cb3a342-d74f-11e7-8243-7de066fb0294.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1524068/RPCS3.log.gz)

**Comment by FibYar** [comment]
Persona 5.
Manga-style dialog insertions have fixed.
But the bug in Takemi clinic @M220 have reported is still present.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1524073/RPCS3.log.gz)

**Comment by M220** [comment]
@rodjun
Nope...
 Still present :(

**Comment by Zangetsu38** [comment]
Regression with this PR for Siren blood, ingame cinematic and first logo is blmack screen
https://cdn.discordapp.com/attachments/283643134255038465/386619833522847744/unknown.png

**Comment by PCMRwill0956** [comment]
Regression with Okami HD. Been this way for a while. Menus don't render properly, and some text just doesn't show up
![x2qf7ew 1](https://user-images.githubusercontent.com/20408167/33585152-6f1359de-d928-11e7-875d-768c2f5216d0.jpg)

**Comment by jjsat** [comment]
Wolfenstein Demo renders some additional "shadows" on current master (for example on the right engine):
![grafik](https://user-images.githubusercontent.com/1445782/33729044-bb1d6558-db7c-11e7-9af2-14e2030b09e8.png)

Before (uses your jarves_spu branch):
![grafik](https://user-images.githubusercontent.com/1445782/33728866-302600cc-db7c-11e7-90e1-2a3fe9554183.png)

The Deus Ex: HR DC issue I mentioned in #3772 is fixed on current master.

**Comment by kd-11** [comment]
Most of the issues listed here should've been fixed by now. Please retest and update.

**Comment by M220** [comment]
Hi kd-11!
Sadly takemi clinic bug in persona 5 doesn't fixed in latest master.

**Comment by kd-11** [comment]
I have pushed a fix for broken stencils in the latest PR

**Comment by M220** [comment]
@kd-11
Nicly fixed ;)
Tnx ♡

**Comment by Asinin3** [comment]
**Fixed:**
Takemi's clinic In P5 is fixed:
![image](https://user-images.githubusercontent.com/15137035/34461464-cc96a752-ee7a-11e7-87c1-0fbec8539e78.png)
Manga style insertions also fixed:
![image](https://user-images.githubusercontent.com/15137035/34461488-6fcec346-ee7b-11e7-9feb-59c32c065517.png)
Vesperia regression was fixed

**Still broken**
Wipeout HD menu's
![image](https://user-images.githubusercontent.com/15137035/34461513-1b889d4c-ee7c-11e7-9c9a-16f225143b55.png)
Tales of Graces f
![image](https://user-images.githubusercontent.com/15137035/34461564-4782d7ae-ee7d-11e7-843d-3dcf1f092ce8.png)

**Not a regression:**
Jak & Daxter Issue was a regression from a different PR
Vesperia issue may be from a completely different PR.

@jjsat Please retest Wolfenstein
@Zangetsu38 Please retest Siren Blood

**Comment by jjsat** [comment]
Wolfenstein issue still present on current master. You can also sometimes see these artefacts ingame when dynamic lights are present.

**Comment by Megamouse** [comment]
The menu on okami is fixed afaict (the build used is current master + some unrelated commit)

![image](https://user-images.githubusercontent.com/23019877/37559775-feaa20b0-2a2b-11e8-8db1-372f4bb74cb7.png)

**Comment by kd-11** [comment]
Okami report was completely unrelated, its just a spammer.

**Comment by HHCHunter** [comment]
Have noticed that Skate 3 has a graphical glitch with the character models being corrupted.
Weirdly it's only on things that are rigged/have animation.

![image](https://user-images.githubusercontent.com/18048891/38775992-f005b658-40c1-11e8-81dc-2310a3ea2e49.png)

**Comment by LukeUkk** [comment]
Did jak and daxter ever get fixed ?
E {PPU[0x1000007] Thread (fios mediathread 2) [0x01191090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUA80706/USRDIR/data/Jak1/jak1/game/dgo1/maincave-vis.dgo” [1]

F {PPU[0x100000e] Thread (GOAL) [0x0001b47c]} class std::runtime_error thrown: Unregistered PPU function

**Comment by slashiee** [comment]
Jak and Daxter is unrelated to this issue.
In other news Wipeout HD is still broken.
![2018-05-06_15-46-47](https://user-images.githubusercontent.com/15317421/39678611-b22600c0-5144-11e8-95e3-225059e22495.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1978118/RPCS3.log.gz)

**Comment by driverinla** [comment]
Outland [NPEB00463] has graphical regression for the moving character, started with this build and still persists

. You can see the missing character graphic from before and after this build images below (I circled red to point them).

![1](https://user-images.githubusercontent.com/34517212/40790190-f7c15e06-64fc-11e8-87cf-11aa7a079da3.jpg)
![2](https://user-images.githubusercontent.com/34517212/40790194-f9df7ede-64fc-11e8-8f73-8c6ba1fee552.jpg)

Attached is the log.
[Log.txt](https://github.com/RPCS3/rpcs3/files/2058815/Log.txt)
Thank you!

**Comment by legend800** [comment]
Rayman Legends flickering is still a problem as of today. 

https://github.com/RPCS3/rpcs3/issues/4412

**Comment by kd-11** [comment]
I have the fixes for this issue ready so please stop updating it.

**Comment by kd-11** [comment]
Closing as fixed by https://github.com/RPCS3/rpcs3/pull/4973
