### ISSUE TITLE
Teenage Mutant Ninja Turtles: Mutants in Manhattan regression

### ISSUE THREAD

**Issue by Kravickas** [RPCS3/rpcs3#4049]
From ingame to nothing after PR #3611

[turtles_master_after.txt](https://github.com/RPCS3/rpcs3/files/1627243/turtles_master_after.txt)
[turtles_master_before.txt](https://github.com/RPCS3/rpcs3/files/1627244/turtles_master_before.txt)

**Comment by Megamouse** [comment]
true. but i have not a clue what's wrong

**Comment by Megamouse** [comment]
found the issue but it needs investigations

**Comment by Kravickas** [comment]
from devs or testing

**Comment by Megamouse** [comment]
from devs obviously

**Comment by Megamouse** [comment]
this will most likely be fixed with Jarveson's next PR

**Comment by Asinin3** [comment]
Still an issue on RPCS3 v0.0.5-6578-63fa50080
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1844693/RPCS3.log.gz)

**Comment by Megamouse** [comment]
still jarves wip. fpnt spam issues
