### ISSUE TITLE
rsx: Hair rendering glitch [BLJM61064]

### ISSUE THREAD

**Issue by pickywu** [RPCS3/rpcs3#4211]
Game: Soccer Tsuku Pro Soccer Club o Tsukurou [BLJM61064]
Commit: v0.0.5-6470-3d694383
Renderer: Vulkan 
Specs: i5-8600k / GTX980 / 16GB RAM

Issue :
This game works well, but there is a problem with the hair texture, see the following illustration.

PS3
![2](https://user-images.githubusercontent.com/36804800/36638887-e2c81ad8-1a3a-11e8-9d42-54cd1b2ffd46.jpg)

RPCS3
![1](https://user-images.githubusercontent.com/36804800/36638883-d33a6120-1a3a-11e8-8b40-d6a5f452aedf.jpg)
![3](https://user-images.githubusercontent.com/36804800/36638890-e636bb20-1a3a-11e8-8284-23b9ad379216.jpg)

Sincerely hope to solve this problem, thank you for your work.

**Comment by hcorion** [comment]
should be fixed in latest master, please retest.

**Comment by pickywu** [comment]
Thank you for your letter, but are you referring to 0.0.5-6541?
I'm still the same after testing,Or need to have different settings?




--------------------------------------------
18/3/15 (週四)，Zion <notifications@github.com> 寫道：

 主旨: Re: [RPCS3/rpcs3] rsx: Hair rendering glitch [BLJM61064] (#4211)
 收件者: "RPCS3/rpcs3" <rpcs3@noreply.github.com>
 副本: "pickywu" <picky-wu@yahoo.com.tw>, "Author" <author@noreply.github.com>
 日期: 2018年3月15日,四,下午2:43
 
 should be fixed in latest master,
 please retest.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by hcorion** [comment]
Hmm, yes, it should be fixed with 0.0.5-6541, perhaps try clearing the shader cache.
To do so, right click the game and select Delete Shader Cache.

**Comment by MarioSonic2987** [comment]
@pickywu Delete your shaders cache.

**Comment by kd-11** [comment]
Now that rpcs3 has its own capture mechanism, an RRC capture would go a long way here. Just start rpcs3 and enable the debugger (View->Debugger) then once the glitch is on screen e.g second screenshot where the bug is clearly visible, press the rsx capture button and wait until a success message appears in the log window. Then compress capture.rrc and link it here.

**Comment by kd-11** [comment]
Any update? Didn't even get the RSX capture file.

**Comment by digitaldude555** [comment]
![Screenshot (3694)](https://user-images.githubusercontent.com/26138653/61121205-4b388600-a4a7-11e9-9465-c50c030c109d.png)
Close Issue.

**Comment by kd-11** [comment]
Closing as fixed.
