### ISSUE TITLE
QT: Game list sort order is case sensitive for grid view

### ISSUE THREAD

**Issue by MSuih** [RPCS3/rpcs3#4306]
![image](https://user-images.githubusercontent.com/19759300/37569444-f9f39866-2aea-11e8-92d3-66b509d864b8.png)
First Skate game is sorted last because it starts with lowercase S.

![image](https://user-images.githubusercontent.com/19759300/37569453-26286db2-2aeb-11e8-898d-1c124ad11c72.png)
List view sorts it after the other Skate games.

**Comment by Megamouse** [comment]
the referenced Pull Request should fix it

**Comment by MSuih** [comment]
Yep, tested the PR and ordering is consistent now. Still don't like how it sorts spaces before punctuation (f.ex Uncharted in the first screenshot or skate in the latter) but I don't have large enough game library to see if changing it would affect other game series.

**Comment by Megamouse** [comment]
it's not the code's fault that they chose to give their game such a stupid name: "skate."
:)
