### ISSUE TITLE
[BLUS30701] Hyperdimension Neptunia - Corrupted dialogue textures

### ISSUE THREAD

**Issue by rekongstor** [RPCS3/rpcs3#4348]
I've got a RenderDoc capture for this bug. Looks like it uses one of the previous buffers instead of a texture for character in dialogues. 

Bug usually appears randomly but at the certain phrases in dialogue (when new texture loads?). Probably reproduces with higher chance by skipping dialogues (it makes textures to load more frequently I think)

Here goes wrong buffer
![image](https://user-images.githubusercontent.com/18365300/37940167-de025ff8-316f-11e8-9c1d-6ee3c3e3fc52.png)
And what happens 
![image](https://user-images.githubusercontent.com/18365300/37940177-e76a4876-316f-11e8-8583-bead52fdde1d.png)
In-game
![image](https://user-images.githubusercontent.com/18365300/37940185-f5da982a-316f-11e8-8af8-3cec4c55cbee.png)

Same situation but with an older RenderDoc version:
![image](https://user-images.githubusercontent.com/18365300/37940132-b20ca688-316f-11e8-8ded-1ec3ad8f061b.png) 

Running on:
OS; Win 10
CPU: i7 7700
GPU: AMD Radeon  R7 370
SSD for both game and RPCS3

Also I tried to use Framelimit by 30 FPS - doesn't matter.
Bug affects on both APIs OpenGL and Vulcan.

And here's RenderDoc captures: 
[for RenderDoc 1.00 with purple haired chick (1-3 screenshots)](https://www.dropbox.com/s/83apow7jxkmnymt/BLUS30701_issue.rdc?dl=0)
[for RenderDoc 0.91 with blue haired flat chick (4th screenshot)](https://www.dropbox.com/s/yod3t904l2u2eae/NepIssue.rdc?dl=0)

**Comment by ruipin** [comment]
I believe this is fixed by #5115. If you have time, please confirm.

**Comment by rekongstor** [comment]
@ruipin 
I haven't seen any issues on Vulkan if most shaders are compiled already but there's a similar (kinda similar) issue for OpenGL:
![o_gl](https://user-images.githubusercontent.com/18365300/45789012-4db2c080-bc86-11e8-9095-ff5d6a686636.png)
Basically this issue is closed for Vulkan so, if you don't need more info about OpenGL situation, this issue can be closed.

**Comment by ruipin** [comment]
I'm not sure you understood me. I was saying that PR #5115 should fix these issues (both VK and OGL) and you should test it if you have time, and let me know if you see it again.

**Comment by rekongstor** [comment]
@ruipin 
I've just tested it and this issue is absolutely fixed for VK and not fixed for OGL. At the same time, bugged (on OGL) textures differ from what they were before.

**Comment by ruipin** [comment]
You are testing master (build 7365), not the PR #5115. You need to go to the PR and down the WIP build there, then test it. I believe it fixes the bug for OGL as well.

**Comment by rekongstor** [comment]
@ruipin 
running your build rpcs3-v0.0.5-ad341ddb_win64
![image](https://user-images.githubusercontent.com/18365300/45790890-cec28580-bc8f-11e8-8b23-623b252df7eb.png)
same thing with OGL

**Comment by rekongstor** [comment]
The issue is closed.  PR #5146 fixes the bug in the previous post. Still, there's some bug with eyes on OpenGL  (attached pic) but at least it's not that bad as it was. Vulkan is okay and I didn't notice a single bug with this API.
![image](https://user-images.githubusercontent.com/18365300/45845933-1815e200-bd2f-11e8-955e-ecdd0cc0a8da.png)

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/5146
