### ISSUE TITLE
[BLJS10053] Tales of Vesperia - Remaining rendering issues

### ISSUE THREAD

**Issue by GeniusMage** [RPCS3/rpcs3#4357]
Continuation of #2707.

Issues to fix:
- [x] Black characters
- [x] Blue veil
- [x] Shadows: Not every character gets their shadow, but it's no longer a square.
- [x] Scrambled text
- [x] Lighting issue
- [x] Frame persistence issue
- [ ] Half-screen issue
- [ ] Wrong colors on characters textures (unrelated to SRM, the issue appears even without it)
- [ ] Requires Strict Rendering Mode

<details><summary>Screenshots</summary>

![bandicam 2018-03-29 10-19-59-500](https://user-images.githubusercontent.com/27543170/38077968-1d118698-333b-11e8-9a01-50314e57e5f4.png)
![bandicam 2018-03-29 10-21-49-058](https://user-images.githubusercontent.com/27543170/38077983-252e7ad4-333b-11e8-8dc3-42eecec96a47.png)
</details>

[Log](https://github.com/RPCS3/rpcs3/files/1859189/RPCS3.log.gz)

**Comment by kd-11** [comment]
Requires strict mode is not a bug. The solution would be to make strict mode permanent then everyone is forced to use it all the time.

**Comment by kd-11** [comment]
A patch.yml entry could force the game to not do the risky stuff (really only one thing) but thats for interested community members to do. Requires a hex editor and replacing 2560 with 1280 where it creates that bugged double-width surface declaration.

**Comment by Illynir** [comment]
I tested a little, the shadows work randomly, sometimes some characters have, sometimes not. The portrait during the fights is green, there is a problem with the alpha, we see a rectangle around the portrait and the fountain at the beginning. The chain on the dog at the beginning also makes a strange movement

![unknown](https://user-images.githubusercontent.com/22648460/38169874-47e590f2-3576-11e8-9657-c1c4a12e6380.png)
![unknown2](https://user-images.githubusercontent.com/22648460/38169875-53e110fc-3576-11e8-80cd-e9ef680296cb.png)

**Comment by Illynir** [comment]
Ok for the green portrait, however just checked on a real PS3 and the dog chain on the intro is quite normal...

There also remains the alpha problem of the fountain and the portrait.

**Comment by wakka1** [comment]
Tested after the latest animation speedup.
Current issues i noticed : 

1- fountain glitch
![untitled4](https://user-images.githubusercontent.com/22716011/40581381-d1f3058c-614e-11e8-92d3-eb835b7863c3.png)

2- half-screen issue during menus and some cut-scenes
![half-width](https://user-images.githubusercontent.com/22716011/40581364-8657e9c6-614e-11e8-9fa2-075cdff222df.png)

3- Character outline are jagged (aliasing?)
4- wrong colors. Noticeable on pink hair and the guard on the left
5- i may be wrong on this one, but i think a faint bloom is missing on the emulator (faces + clouds)
![rpcs3](https://user-images.githubusercontent.com/22716011/40581367-9214c842-614e-11e8-9321-820ad84dad18.png)
![real ps3](https://user-images.githubusercontent.com/22716011/40581368-93d25726-614e-11e8-826a-bf201375e0b1.png)

**Comment by GeniusMage** [comment]
Those are all listed (except the bloom, I'll check and add it if necessary)
Character edges are obviously jagged, since it's 720p and FXAA is not applied by the emulator.
The dog chain glitch is not a bug, it happens on real hardware (and yes, I have retested, it does happen, though not consistently).

**Comment by GeniusMage** [comment]
Alright, I added the fountain glitch and the bloom issue to the first post.
I think the bloom issue is actually there because light isn't being quite properly applied to characters.
I also believe the fountain glitch could be related to the characters texture bug.

**Comment by wakka1** [comment]
Shadows bug.
https://imgur.com/OAXzgAs

**Comment by pauls-gh** [comment]
Quick update on half screen issue.  Initial idea for a fix didn't pan out, but I haven't given up yet.

**Comment by Zangetsu38** [comment]
for shadow bug, i have already report this to kd, i have see very lot game with same bug

**Comment by pauls-gh** [comment]
I think I've figured out the half-screen issue.  PR coming soon.

![half_screen_fix](https://user-images.githubusercontent.com/16286075/40867887-b9e55702-65bc-11e8-9ccf-6a33337b1bd5.png)

**Comment by pauls-gh** [comment]
https://github.com/RPCS3/rpcs3/pull/4692

This PR looks like it fixes  both
- half screen
- fountain alpha issue  (nice side effect of the half screen fix).

**Comment by pauls-gh** [comment]
kd-11 has a proper fix for the half-screen issue.  https://github.com/RPCS3/rpcs3/pull/4698

It fixes
- half-screen issue in Vesperia/Graces
- fountain issue in Vesperia
- non-aligned cell-shading in Graces

Known issues with kd-11's change.
- cell-shading is very pronounced in Vesperia.
- blue filtering (of distance objects) in town is missing.

**Comment by pauls-gh** [comment]
I spent some time looking at the character texture color issue.  This is easily seen in the first cut-scene.  The characters faces look darker (more orange) than the  PS3 version.

I used renderdoc to capture the scene on RPC3.  I then captured the same scene with Xenia (xbox360 emulator).  Xenia displays the correct skin color in the scene.

I found the same face texture on both rpcs3 and Xenia.  It appears that the skin color is simply darker in RPC3 than Xenia.  The red/yellow components looks exactly the same as Xenia, but the blue component is darker for some reason.

The face texture is BC3 (compressed, 5:6:5 alpha 8 bit).  Interestingly, the ear texture (a separate texture) is the correct color, but it is BC1 (compressed, 5:6:5 alpha 1 bit).  I'm not sure if this matters as I assume both textures are read directly from the TOV ISO files.   I don't think there is any conversion done by rpcs3.


**Xenia (xbox 360 emulator) - correct face color**

![renderdoc_facecolor_xenia](https://user-images.githubusercontent.com/16286075/41070272-b8f5d342-69a6-11e8-8076-48692b9fcf03.png)

**rpcs3 - incorrect face color**

![renderdoc_facecolor_rpcs3](https://user-images.githubusercontent.com/16286075/41070273-bb310c44-69a6-11e8-8081-5aca04d278ba.png)

**Comment by pauls-gh** [comment]
If you zoom in around the eye lid, you can see there are splotches of the correct color.  It's almost like the artist gave up, or a failed flood fill.  Strange.

**Comment by Ristelle** [comment]
@pauls-gh If you look REALLY closely at the Xenia one, there is a slight color difference in xenia's. the eyelids and the rest of the face. I guess its once of those RPCS3 cklor issues.

**Comment by pauls-gh** [comment]
@Ristelle - you're right.  The "Night Light" on Win10 was masking the difference for me.

**Comment by Ristelle** [comment]
On entering Capua Nor for the first time, Game Freezes with Trap Exception:  
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2086959/RPCS3.log.gz)

**Comment by GeniusMage** [comment]
Trap errors happen in specific areas when compiling some shaders.
Usually, you can reload the game after a crash and go past a spot.
Knowing where those spots are can help, as you'd know where to *absolutely* save, though I recommend always saving before leaving or entering any new area (town or dungeon), if possible.

**Comment by elad335** [comment]
Still an issue?

**Comment by GeniusMage** [comment]
Just tested on one of the latest builds, the texture bug is still there, and the bloom is apparently also lacking (looks like wakka1's screenshot from May 27th, point 5).
Though to be fair, the same texture bug appeared on official WIP screenshots from the remaster (textures that weren't revamped yet), it could be an issue with the textures themselves or how a PC driver treats them.

**Comment by Ristellise** [comment]
Well I really shouldn't be bumping a dead post but as of Build 52ac0a901acac98d05ed9c989069b9ea107082b4, the Game has a constant spam of `RSX TODO: Resource used before memory initialization`

**Comment by GeniusMage** [comment]
It's not closed, so feel free to post.
I've found this too:
![Deidon](https://user-images.githubusercontent.com/27543170/50735259-8088b200-11ac-11e9-82eb-2abe55355c67.png)
The blue effect is out of place.
![No SRM](https://user-images.githubusercontent.com/27543170/50735813-e711ce00-11b4-11e9-8d88-be0a0fbb04c9.png)
There's also been some changes without SRM, though I'm not sure how new this is.

**Comment by Parthorisian** [comment]
Not problem anymore, Sega just ported this game to Windows yet :)

**Comment by AniLeo** [comment]
doesn't matter, the game port doesn't magically make it fixed on the emulator

**Comment by Ristellise** [comment]
Also, it aint Sega but Bandai Namco.

**Comment by kd-11** [comment]
Needs an update or close.

**Comment by Illynir** [comment]
Always present.

**Comment by GeniusMage** [comment]
Couldn't do extensive testing since my PC seems to hate the emulator currently (Vulkan doesn't work on my end, and OGL is pretty slow, I blame my iGPU).
SRM is no longer needed, and from what I've seen the last two issues are still there.
I'll try to test more once I've changed my CPU sometime next month.

**Comment by GeniusMage** [comment]
Re-tested on latest download version, and managed to get it to work on Vulkan (turns out it was Turing's fault).
The last two issues are still there. I'm still unsure if that texture issue can be fixed.

**Comment by digitaldude555** [comment]
It is time for update @GeniusMage

**Comment by GeniusMage** [comment]
There doesn't appear to be any changes.
![Face](https://user-images.githubusercontent.com/27543170/76424615-c5a80580-63a8-11ea-8f77-975d74e6032b.PNG)

**Comment by Realmantik** [comment]
@GeniusMage, time to retest. Kd-11 added updates to texture rendering, that have solved problems in visuals in many games.

**Comment by digitaldude555** [comment]
@GeniusMage retest.

**Comment by Illynir** [comment]
![Sans titre](https://user-images.githubusercontent.com/22648460/121789109-7a942800-cbd3-11eb-9fa9-1315371f8139.jpg)

Not fixed, alas.

**Comment by Mrlinkwii** [comment]
how is this on the latest release

**Comment by Illynir** [comment]
Nothing has changed. Alas.

**Comment by digant73** [comment]
@Illynir is there an update on fixed issues?

**Comment by Triticum0** [comment]
Don't think so

**Comment by digant73** [comment]
please re-test on latest build. Hopefully some textures and reflections issues have been fixed by recent build 0.0.39-18790

**Comment by digant73** [comment]
please an update on current build

**Comment by Triticum0** [comment]
Still an issue (Look at the hair/Blending issse?)

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/117bd804-2d03-4790-b285-49995fc9dd92" />

Didn't test the bloom issue. here the demo id  NPJB90185

**Comment by keikof070623-gif** [comment]
Can someone who has this game, re-test and see if any of the issues that are unticked are still occuring?
