### ISSUE TITLE
Uncharted: Drake's Fortune [BCES00065] crashes if debug output is enabled

### ISSUE THREAD

**Issue by MSuih** [RPCS3/rpcs3#4487]
Tested on: 98b715d8c
Renderer: Vulkan (OpenGL doesn't crash)

Crash occurs during intro, the exact moment varies but it usually crashes during first two seconds. The log is spammed full of messages along the lines of "You are adding [command] to command buffer [buffer] that is invalid because bound DescriptorSet was destroyed or updated" during those few seconds. 

>Unhandled Win32 exception 0xC0000005.
Segfault reading location 0000000000000040 at 00007ffb42d21f36.
Instruction address: 00007ffb42d21f36.
Function address: 00007ffb42d21ea0 (base+0x1c1ea0).
Module name: 'VkLayer_core_validation.dll'.
Module base: 00007ffb42b60000.
RPCS3 image base: 0000000000010000.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1948164/RPCS3.log.gz)

**Comment by kd-11** [comment]
Retest, especially with newer SDK version this may have been fixed.

**Comment by MSuih** [comment]
Retested using 7077 (f0a9799b4) and SDK 1.1.77.0. no changes. 

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2173000/RPCS3.log.gz)

**Comment by MSuih** [comment]
Tested with 660bfeab & SDK 1.1.97.0, the validator still crashes.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2796410/RPCS3.log.gz)

**Comment by MSuih** [comment]
Still an issue with 8118 / a016728a.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3187570/RPCS3.log.gz)

**Comment by MSuih** [comment]
Fixed with #5995
