### ISSUE TITLE
Yakuza 0 & 3, Bugs and Crashes [BLES00834], [BLJM61249]

### ISSUE THREAD

**Issue by MsDarkLow** [RPCS3/rpcs3#4489]
I'll be leaving here all the problems I have encountered in Yakuza Games, mainly 0 and 3.
All of these issues have been there since the very day they got ingame, there has been a few improvements here and there but the bugs persist.
The build test for the post: https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.5-6692/artifacts

Laptop: i5-7300HQ + GTX 1050 + 16GB RAM

Yakuza 0 (Ryu Ga Gotoku 0) [BLJM61249]
Current issues:

- Pre-rendered cutscenes have stutters (All Yakuza games)
The cutscenes are pretty stuttery even if you have constant 30 FPS.
Log: [Yakuza 0 Pre-Rendered Cutscenes and LogSpam.log.gz](https://github.com/RPCS3/rpcs3/files/1952267/Yakuza.0.Pre-Rendered.Cutscenes.and.LogSpam.log.gz)

- All characters go black (Also at: #4141 )
This one is pretty bizarre, whenever I launch the game sometimes all the characters go black and sometimes they look completely normal.
Upscaling the game and tweaking the AF seem to make this occur almost 100% of the time.
Images: https://imgur.com/a/By0aOrc
Log Normal: [Yakuza 0 Color Normal.log.gz](https://github.com/RPCS3/rpcs3/files/1952261/Yakuza.0.Color.Normal.log.gz)
Log Black: [Yakuza 0 Color Black.log.gz](https://github.com/RPCS3/rpcs3/files/1952262/Yakuza.0.Color.Black.log.gz)

- The blood in combat has a T-Pose Model
This one is self-explanatory with the pictures
Images: https://imgur.com/a/v3AkwyH
Log: [Yakuza 0 Blood T-Pose.log.gz](https://github.com/RPCS3/rpcs3/files/1952263/Yakuza.0.Blood.T-Pose.log.gz)

- 1 FPS Lock (Temporary fix)
The default settings in RPCS3 lock the game to 1FPS, there is a temporary solution that fixes it.
Go to game's config.yml and change Driver Recovery Timeout to a lower ammount.
The lower the value, the higher the framerate, setting around between 1 to 100 is good
Log Value 1: [Yakuza 0 No 1 FPS Lock.log.gz](https://github.com/RPCS3/rpcs3/files/1952271/Yakuza.0.No.1.FPS.Lock.log.gz)
Log Value Default: [Yakuza 0 1 FPS Lock.log.gz](https://github.com/RPCS3/rpcs3/files/1952270/Yakuza.0.1.FPS.Lock.log.gz)

- Log spam: 
_E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x40300FE0_
This simply shows up whenever something is being displayed on the screen, the more frames, the more spam!
Use the log from Pre-rendered cutscenes have stutters. (You'll find this in every log)
Image: https://i.imgur.com/JY26hEH.jpg

- Freezing when going out of focus, no output from the log (All Yakuza games)
Sometimes when you tab out of RPCS3's game window, the game freezes.
You can still control RPCS3, you can't give any input and the audio works flawlessly.
Video: https://youtu.be/oOEm7tXg1sw
Note: The log is not the same as in the video, the one I got here was at the very start of the game
Log: [Yakuza 0 Crash Going Out Of Focus.log.gz](https://github.com/RPCS3/rpcs3/files/1952278/Yakuza.0.Crash.Going.Out.Of.Focus.log.gz)

- Crashes after some time (Driver Crash)
This one is certain, as soon as I go ingame and play for a little while the game will crash, and if I try to shut it down it freezes RPCS3, leaving me the only option to terminate RPCS3 through the task manager.
Error: F {rsx::thread} class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:937)
Image: https://i.imgur.com/kMxjKcX.png
Log: [Yakuza 0 Crash.zip](https://github.com/RPCS3/rpcs3/files/1952280/Yakuza.0.Crash.zip)

Gameplay Video: https://youtu.be/U4ahYjgDCHA

Yakuza 3 [BLES00834]
Current issues:

- Pre-rendered cutscenes have stutters (All Yakuza games)
The cutscenes are pretty stuttery even if you have constant 30 FPS.
Log:  [Yakuza 3 Pre Rendered Cutscenes.log.gz](https://github.com/RPCS3/rpcs3/files/1952247/Yakuza.3.Pre.Rendered.Cutscenes.log.gz)

- Exploding Vertices and Missing Visuals
Early in the game you'll find trees with broken LOD and exploding Vertices.
Images: https://imgur.com/a/kjPkCQ7
Log: [Yakuza 3 Exploding Vertices and Missing Rendering.log.gz](https://github.com/RPCS3/rpcs3/files/1952240/Yakuza.3.Exploding.Vertices.and.Missing.Rendering.log.gz)

- Freezes randomly, no output from the log (All Yakuza games)
The game tends to freeze with no output from the log and its pretty random, sometimes it even freezes at the startup.
Take this one as an Example: https://gfycat.com/BrokenJubilantCockatoo
Log:  [Yakuza 3 Freezing at startup.log.gz](https://github.com/RPCS3/rpcs3/files/1952248/Yakuza.3.Freezing.at.startup.log.gz)

I look forward in providing info, logs, renderdocs or anything, whenever necessary.
Discord: MsLow#2316

**Comment by kd-11** [comment]
Retest and update. A lot has changed since april.

**Comment by MsDarkLow** [comment]
A lot sure has changed since April.
Instead of testing on my laptop, I switched to my upgraded Desktop, this made testing a lot faster.
i7-8700K @ 4.5GHz | GTX 1070 | 16GB RAM

Note: I kept the Driver Recovery Timeout at default (3300)
Build: rpcs3-v0.0.5-7077-f0a9799b_win64
PPU LLVM | SPU ASMJIT | SPU Thread: 6


Found a few different results. I have to say that SPU Threads are slightly important on this.
Tested both SPU Thread 2 and 6.
6 or Auto offers the best performance for this CPU. 1 Offers the best for 4 core CPUs.
##  **Yakuza 0 (Ryu Ga Gotoku 0) [BLJM61249]** ##

- ### Pre-rendered cutscenes have stutters ###
Completely Flawless on this system. Needs testing on slower systems tho.
Example: https://youtu.be/HCEiRJWgn94

- ### All characters go black ###
Something changed here, its no longer random.
When there are no shaders created, the game will have all the models correctly rendered but once the game is restarted all the models will be rendered black. 

Note: When certain cutscenes are played, the models are rendered properly.

Example of me Starting with no shaders, restarting and delete&restart: https://youtu.be/Vlorxn9lDrQ

Also noticed the FPS are much lower when compared to playing with black models.
Example of FPS difference: https://youtu.be/HuO8VqFfzlw


Log Blacc: [0 Extended Gameplay Blacc.log.gz](https://github.com/RPCS3/rpcs3/files/2173007/0.Extended.Gameplay.Blacc.log.gz)
Log White: [0 Extended Gameplay White.log.gz](https://github.com/RPCS3/rpcs3/files/2173008/0.Extended.Gameplay.White.log.gz)


- ### The blood in combat has a T-Pose Model ###
Remains the same
Video examples
Fighting Blacc: https://youtu.be/7jdNhdUi6M8
Fighting White: https://youtu.be/hIyDWsb6-d0

Log Fighting Blacc: [0 Fighting Blacc.log.gz](https://github.com/RPCS3/rpcs3/files/2172957/0.Fighting.Blacc.log.gz)
Log Fighting White: [0 Fighting White.log.gz](https://github.com/RPCS3/rpcs3/files/2172958/0.Fighting.White.log.gz)

- ### Log spam: ###
_E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x40300FE0_

**_(Use the Extended gameplay logs!)_**
This still occurs but, only when the models are all fine!
Playing with the buggy black models, this RARELY shows up!

__Images__
Blacc models have no log spam: https://i.imgur.com/mA3njBS.png
Normal models have log spam: https://i.imgur.com/eaZSlG7.png

- ### Freezes randomly, no output from the log (All Yakuza games) ###
During the tests I didn't encounter a single crash/freeze/whatever, I found this.... weird.

If you want me to do a very long test, should I start without or with shaders? Or wait until the models are fixed?

- ### Flickering w/ bad SPU Theads ###
When using the wrong SPU Thread like 1 or 2 on this system, the cutscenes will have flickering and explosive vertices.
Video Example: https://youtu.be/GOEGy15MAdI

Log SPU Thread 2: [0 Karaoke SPU Thread 2.log.gz](https://github.com/RPCS3/rpcs3/files/2173002/0.Karaoke.SPU.Thread.2.log.gz)
Log SPU Thread 6: [0 Karaoke SPU Thread 6.log.gz](https://github.com/RPCS3/rpcs3/files/2173003/0.Karaoke.SPU.Thread.6.log.gz)

## **Yakuza 3 [BLES00834]** ##
- ### Exploding Vertices and Missing Visuals ###
Still broken.

Images: https://imgur.com/a/Rbn7fGW
Log: [3 Missing Visuals and broken.log.gz](https://github.com/RPCS3/rpcs3/files/2173009/3.Missing.Visuals.and.broken.log.gz)

**Comment by Neucomac3** [comment]
I found something to add to Yakuza 3 [BLUS30494]
I haven't checked the rest of the games yet, but Yakuza 3 is spamming a message saying SPU: GETLLAR took too long. It's constantly spamming these messages similar to the semaphore error. On top of that, it's still crashing randomly with no error message in the output log.
Here's the log file for one of these random crashes.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2301959/RPCS3.log.gz)

**Comment by MsDarkLow** [comment]
> Update: Black Models fixed at #5146
> Should take effect on the following games: Yakuza Dead Souls, Yakuza Ishin!, Yakuza 0, Yakuza Kiwami, Yakuza 5

Another small bonus update, on the same games. "The blood in combat has a T-Pose Model" seems to no longer show up either.

**Comment by MsDarkLow** [comment]
Update: Exploding Vertices fixed at #5229 
Should take effect on every Yakuza Game (not counting 1&2HD).

Remaining major problems:
Common crashes.
Slow Performance (Micro-stuttering? 1% and 0.1% being at half the fps)

**Comment by MsDarkLow** [comment]
Some news related to the crashes.

A month or less ago, I figured out there was a log spam (seen in Trace mode), this was most likely the cause of the random crashes I tried to disable every bit of log spam along with using `Accurate GETLLAR` (I haven't tested without it).
I only tested this on Yakuza Kiwami, Ishin, Dead Souls and 5 on an i7-8700k but hopefully it should apply to every single Yakuza game. (Maybe that explains why Kenzan! never crashed!)

I have set this in the bottom of the config.yml:
`Log: {sys_semaphore: Fatal, sys_fs: Fatal, sys_vm: Fatal, sys_memory: Fatal, RSX: Fatal, sys_lwmutex: Fatal, sys_spu: Fatal, sys_event: Fatal, sys_rsx: Fatal}`


This is not written in the issue but there was an issue with Yakuza Ishin where it would crash if the user didn't have option `Disable ZCull Occlusion Queries", enabled. This was fixed in #5697

**Comment by MsDarkLow** [comment]
Small update. Most of the issues still remain up to today.
Merged fixed stuff into a small section (Fixed Issues).

The (Y3) Pre-rendered Cutscene stuttering has been moved to Fixed Issues for performing so much better! Although Yakuza 0 is still very stuttery and is most likely due to the CPU (i5-7300HQ) being quite weak, it rarely happens with an i7-8700k.

Added a quick manual temporary fix for the random crashes (all yakuza games).

1 FPS Lock issue seems to be happening less often? Need further testings. May be due to my temporary fix shenanigans.

Other 1: Yakuza Dead Souls, 5, Ishin, 0 and Kiwami have horrible upscaling, this can be somewhat fixed using CPU Blit in the debug tab / game's config.yml. Ishin, 0 and Kiwami will contain visual glitched.

Other 2: So far all these games seem to be completable if we fix the crashes. I have completed Yakuza Kenzan, Ishin, Dead Souls and 3 w/ i7-8700k. Performance strays far from getting them to the playable section tho, being mostly RSX bottlenecked. (Except Kenzan ofc)

**Comment by MsDarkLow** [comment]
Updated the whole issue. This time only featuring the possible issues found with a 8700k paired with a GTX 1070.
Made it more clean and added more issues not mentioned before.
Also some errors were only on my 7300HQ and I no longer have it so, I'll find those issues irrelevant also because the CPU does not meet the Recommended Requirements anyways.

**Comment by MsDarkLow** [comment]
Added another issue, incorrect shadows on Yakuza 5, 0 Ishin and Kiwami. Used 5 as an example.
This issue is mainly noticed when doing upscaling but it exists at 100% if you zoom in closely. The shadows kinda look like in a grid or something, the image examples speak for themselves.

**Comment by MsDarkLow** [comment]
Added another issue, incorrect snow visuals on yakuza 5 characters during a specific scene (and also happens ingame).

**Comment by MsDarkLow** [comment]
Added another issue, missing light on yakuza 4 spotted on a cutscene, when comparing it to the PS3 and PS4 versions, it has a blue tone to it, where RPCS3 doesn't.

**Comment by MsDarkLow** [comment]
#8106 Adds Shader Interpreter Only, and this option seems to solve the Yakuza 4 Light issue, or at least makes it much closer to real hardware.
Added the Interpreter Only picture example. (In this comment, two of them)
<details>
 <summary>Image Examples</summary>
Legacy, Async Only, Async w/ Shader Interpreter

![7](https://user-images.githubusercontent.com/9060436/80767947-fe5e9280-8b40-11ea-9f65-57136fed4f5c.jpg)
![7 1](https://user-images.githubusercontent.com/9060436/80767943-fd2d6580-8b40-11ea-8387-e861340dc93d.jpg)



Interpreter Only
![7Interpreter](https://user-images.githubusercontent.com/9060436/80767951-01598300-8b41-11ea-8062-0c89760ed9bc.jpg)
![7 1Interpreter](https://user-images.githubusercontent.com/9060436/80767953-01f21980-8b41-11ea-9222-2e50622b93d8.jpg)


</details>

**Comment by Marthgun** [comment]
I've played through 3, 4, and 5 with minimal issues.  I had to set Accurate GETLLAR in the debug tab, I followed the advice on the wiki pages with rec'd settings and turning off log spam.  I also noticed that, at least for me, turning on Multithreaded RSX in the options seemed to stop all crashes.   Y3 was definitely the sketchiest game, If i played for more than 3 hours or so straight it would sometimes freeze and I'd have to exit out.  4 and 5 had no problems.  for Y3 I had set it to 3x res, 2x for the other 2 games as the framerates would dip under 30 occassionally.  Y4 ran almost entirely stable at 30fps, 3 same, 5 was the outlier, it had relatively low dips in Shinada's town which could get down to 23-25 fps and drop a few frames here and there in Kamurocho.  Nothing too bad but Shinada's town was the worst by far.  I would put it down to all kinds of crazy shit going on in the background/distance in the town.  
my specs:
i9-9900k
1070ti
32gb ram
13mb sexy women folder
 I hope this helps.

**Comment by MsDarkLow** [comment]
Yakuza 4 color fixed by KD in #8243

**Comment by MsDarkLow** [comment]
Little update on  "Sun / Lens Flare goes through objects". This issue is only present in Yakuza Ishin not in 0 and Kiwami. Upon further inspection they seem totally different issues. They have been seperated respectively.

**Comment by MsDarkLow** [comment]
Yakuza Kenzan shadows fixed in #8367

**Comment by MsDarkLow** [comment]
Just to keep the issue status updated, all currently mentioned bugs still exist.
Yakuza 1&2HD on Vulkan regressed on the cutscenes some long time ago (months), it's just as blurry as OpenGL, I forgot to mention it on the page because I was simply lazy, I'll find the regression pr and update the page at a later date.
I've also changed my 1070 to a 3080, no new bugs were introduced.

**Comment by MsDarkLow** [comment]
Yakuza 1&2HD no longer has Blurry Scenes, both on OpenGL and Vulkan!
Fixed by KD in #9354

**Comment by MsDarkLow** [comment]
Small update and new info on the listed issues.

The Incorrect Shadows (in 5, 0, Ishin, Kiwami) are not actually an issue, it's how the games actually render the edges of the shadows, I removed it entirely.

The Incorrect Snow Visuals on Characters can be fixed when using WCB but it has to be without CPU Blit which will lower the performance. And since I'm not sure if rpcs3 is intended with this behavior I'm keeping it as an issue.
I verified this by checking the following settings:
- Ideal World = Bugged
- WCB = Good
- WCB + CPU Blit = Bugged
- WCB + RDB + WDB + RCB = Good
- RDB + WDB + RCB = Bugged
- Nothing = Bugged

All other listed issues still persist the same way up to this day. (I will update the logs / rsx captures when requested.)

**Comment by kd-11** [comment]
In future, WCB+WDB and RCB+RDB will be merged, so the way I see it, the only problem here is that CPU blit is not working as intended. That is obviously not very high priority as it is a debugging-only path.

**Comment by Long-FA** [comment]
I don't know who moved Yakuza Dead Souls to playable, but it still suffers from random freeze. I have to redo the near-ending battle in front of Millenium Tower with Kiryu & Ryuji no less than six times because it just freeze out of nowhere.
In my 20 hours playthrough, the most frequent freeze are:
- At the start of Kiryu's part.
- At the ending battles of the game.
FPS also heavily drop when:
- Character is in an open area with lots of zombie, like in front of the Millenium Tower or Theater Square.
- Any character firing any version of Gatling Gun. The muzzle flash of Gatling Gun tanks FPS hard.

**Comment by AniLeo** [comment]
ssshadow moved it a few months ago, I played the game last month and it only crashed randomly once throughout the entire game, including a consecutive 7h30m play session.

**Comment by MsDarkLow** [comment]
Yakuza 0 and Kiwami no longer have broken exposure effect.
I'll identify the PR that fixed it and edit this comment later.
Here's how it looks now: ![7BXQTBryPy](https://user-images.githubusercontent.com/9060436/142702737-726de0c5-7563-4157-9aab-1958fe868a6f.gif)

**Comment by Marthgun** [comment]
Dead Souls is also randomly freezing for me to the point it's unplayable (for me).  Sometimes I can play for 2 hours straight, sometimes it freezes (music still works) within 10 minutes of starting.  It appears randomly.
I set Accurate GETLLAR and CPU Blit to true in config.yml and used the MLAA script, set vsync on and followed all advice on the wiki page and sshadow forum post including setting resolution to 513x513 (can't hit 512x512 for whatever reason) and having upscale to 125x for MLAA script.  Maybe it's due to my chip being Intel.  I wonder if @AniLeo has an intel or amd?  Otherwise the game runs and looks great.  No other problems.  I'm running everythign from my HDD but I could try moving it to my M2 drive but I'm not sure if I need to move the game files, RPCS3 or both.
my specs:
i9-9900k
1070ti
32gb ram

**Comment by DerinHalil** [comment]
On my M1 Macbook Pro, Dead Souls [BLUS30826] has this issue where there are a bunch of black polygons all over the screen.

<img width="1440" alt="Screenshot 2023-03-01 at 10 15 01" src="https://user-images.githubusercontent.com/50413946/222074597-852afd16-0cde-485d-bf18-318574e51bdf.png">
<img width="1440" alt="Screenshot 2023-03-01 at 10 15 14" src="https://user-images.githubusercontent.com/50413946/222074676-48da6bf3-51fc-4cf6-b94c-50d4f772bdb0.png">
<img width="1440" alt="Screenshot 2023-03-01 at 10 29 20" src="https://user-images.githubusercontent.com/50413946/222074758-0de895f0-e01d-4104-97f9-99ff3927f72d.png">

Apparently this may be related to the Vulkan renderer, but obviously I can't just switch to OpenGL on MacOS, so no idea what to do.

**Comment by R-033** [comment]
@DerinHalil I had this issue in Yakuza 3 on M1. Managed to fix it by turning on "Disable MSL Fast Math" under Advanced tab. Attaching my full config file just in case.
[config.yml.zip](https://github.com/RPCS3/rpcs3/files/15076659/config.yml.zip)

**Comment by AniLeo** [comment]
Random freezing/crash needs update with latest build

**Comment by MsDarkLow** [comment]
I marked "Incorrect Snow Visuals on Characters" as fixed by enabling WCB (which I found and commented years ago, idunno why I never marked it as fixed).
The "Sun / Lens Flare goes through objects" & "Room with wrong colors" still persist.

And lastly, Yakuza Dead Souls still Crashes
[RPCS3.log.gz](https://github.com/user-attachments/files/15693427/RPCS3.log.gz)

**Comment by PFLI2** [comment]
Random crashes are still an issue in Dead Souls.  Accurate Getllar is now forced on at all times in RCPS3 and the game still often just freezes for no real reason with the music being the only thing to keep playing. Tried to save a state just to see what would happen, nothing happens.

**Comment by PFLI2** [comment]
Pachinko has massive issues at least in Dead Souls. Getting in or out of pachinko is a coin flip. The Virtua Fighter machine brings you to a black screen you're trapped at, I managed to exit out once blindly but it crashed one time I did that. King Camel works but you can't exit out. CR Aladdin Destiny EX fully works, can get in and out.

**Comment by kd-11** [comment]
"force cpu blit" used without full GPU R/W options acts like a hack to skip SPU post-processing. It's upscaling because the image didn't get properly treated by the engine.

**Comment by kd-11** [comment]
Any change with the visual glitches? Would be good to retest and update.

**Comment by MsDarkLow** [comment]
The issues are still persisting. WCB, WDB, RCB, RCB, CPU Blit, also don't help fix the issue.
[RPCS3.log.gz](https://github.com/user-attachments/files/18633447/RPCS3.log.gz)

<details><summary>Pictures</summary>
<p>

![Image](https://github.com/user-attachments/assets/e074c6db-8d1a-4444-af85-9135f732f271)
![Image](https://github.com/user-attachments/assets/156f337f-e140-4e69-81d8-a0455a57b37d)

</p>
</details>

**Comment by nierjero** [comment]
I'm experiencing this visual glitch with Ishin where every time a heat action is used, the textures break and turn into these rainbow colors as in the images attached below.
![Image](https://github.com/user-attachments/assets/f3d01cf9-5c63-45f7-92a8-bf90213fb1c2)

![Image](https://github.com/user-attachments/assets/77434b7d-8943-4745-a126-1993cdf5ed0f)

**Comment by MsDarkLow** [comment]
@nierjero That is not an issue, please reset your settings back to default. For any extras please follow the settings from the wiki.
You are currently using just CPU Blit - which that causes that problem, that setting is not necessary to run & display visuals of the game.

**Comment by GoldenLumia** [comment]
RPCS3 Version: 0.0.35-17646-f9a72e8d Alpha
Ryzen 5700X3D
GTX 1080
Tested on Vulkan and OpenGL

Getting random freezes after about ~5 of gameplay in Dead Souls. Tried setting RSX FIFO accuracy to Atomic, but this didn't seem to change the crash frequency. Just reporting it still seems to be an issue.

**Comment by Nydrogen** [comment]
I have spent around 20 hours playing with these settings with no crashes or issues:

![Image](https://github.com/user-attachments/assets/4f8c03df-d0f9-497b-ad6f-d5a438e670d5)

![Image](https://github.com/user-attachments/assets/c6c9bcf9-00a1-4b91-8b51-4299750f736d)

![Image](https://github.com/user-attachments/assets/59d66bc4-e835-4dd5-8b0d-7fb14d448be3)

![Image](https://github.com/user-attachments/assets/8de00af3-c466-471b-8371-8c1a39e7a2fb)

![Image](https://github.com/user-attachments/assets/d46de5ae-a3f5-433b-98a0-2fa4a7bdb264)

![Image](https://github.com/user-attachments/assets/4f1219dd-a1c2-4b8a-b29f-ac0bf502cc7c)

![Image](https://github.com/user-attachments/assets/0e6bb9ae-ee5d-4ac3-8612-7895648b4fa3)

![Image](https://github.com/user-attachments/assets/caa1efe4-cfcc-4db0-8493-2b30c8357931)

![Image](https://github.com/user-attachments/assets/0b972989-e16c-44cf-bfa4-257d8e3b74fb)

I am using:
RPCS3 Version: 0.0.26-14775-f2155b49 Alpha | master
Ryzen 7 5700X
GTX 1660
16GB RAM

**Comment by Nydrogen** [comment]
For Yakuza 3 and 4 i spent 30 hours playing with no issues with these settings:

![Image](https://github.com/user-attachments/assets/9befa7e1-0a27-4d92-8b57-fa6b882b7e92)

![Image](https://github.com/user-attachments/assets/ab384a18-86e6-4835-876b-d4010e2a3aab)

![Image](https://github.com/user-attachments/assets/4e2048d5-4577-4e9d-9f04-1e54df957449)

![Image](https://github.com/user-attachments/assets/3df6a9e4-6a8b-43cf-b7ae-108777700346)

![Image](https://github.com/user-attachments/assets/f834513a-d2dd-4d33-9526-f6ae314dad8b)

![Image](https://github.com/user-attachments/assets/f31b158d-c91a-49d1-b92a-01b58fab2e11)

![Image](https://github.com/user-attachments/assets/5a13973f-527d-44b0-80a9-03059d102708)

**Comment by Nydrogen** [comment]
> RPCS3 Version: 0.0.35-17646-f9a72e8d Alpha Ryzen 5700X3D GTX 1080 Tested on Vulkan and OpenGL
> 
> Getting random freezes after about ~5m of gameplay in Dead Souls. Tried setting RSX FIFO accuracy to Atomic, but this didn't seem to change the crash frequency. Just reporting it still seems to be an issue.

The settings i posted for Yakuza 4 and 3 should work with Dead Souls as well:
https://github.com/RPCS3/rpcs3/issues/4489#issuecomment-2754913299

**Comment by udance4ever** [comment]
> [@DerinHalil](https://github.com/DerinHalil) I had this issue in Yakuza 3 on M1. Managed to fix it by turning on "Disable MSL Fast Math" under Advanced tab. 

which M1 hardware do you have and what build of RPCS3 are you using where Yakuza 3 gets in-game?

Tried the [config recommended in our wiki](https://wiki.rpcs3.net/index.php?title=Yakuza_3#Configuration) and [your config](https://github.com/RPCS3/rpcs3/files/15076659/config.yml.zip) on a 2020 M1 MBP 16GB and they both hang in the same place after the black screen with the Yakuza 3 watermark in the lower righthand corner.

the only way I've gotten in-game is on a ROG Ally.

**Comment by R-033** [comment]
@udance4ever I've used M1 Mac Mini 2020 8GB and RPCS3 0.0.31-16374. Didn't test in newer versions since then, perhaps it could've regressed. In that version is crashed from time to time but it was playable. I managed to complete most of the storyline.

**Comment by udance4ever** [comment]
> I've used M1 Mac Mini 2020 8GB and RPCS3 0.0.31-16374. Didn't test in newer versions since then, perhaps it could've regressed. In that version is crashed from time to time but it was playable. I managed to complete most of the storyline.

thank you so much for isolating the build that worked for you!  I just downloaded [the Intel binary](https://github.com/RPCS3/rpcs3-binaries-mac/releases/download/build-862727e9bf3f78c22683d5d256b6550e55f0adbc/rpcs3-v0.0.31-16374-862727e9_macos.7z) and you're absolutely right, it doesn't hang and you're able to get in-game.

So for the record, the cumulative changes (1554 commits!) to 0.0.36-17928 (both arm64 and Intel) hang Yakuza 3 on Apple Silicon (2020 M1 MBP)

**Comment by digant73** [comment]
please re-test on latest build. Hopefully some textures and reflections issues have been fixed by recent build 0.0.39-18790.
- `Sun / Lens Flare goes through objects` was possibly fixed by a previous build fixing ZCull
- `Room with wrong colors` is hopefully fixed by latest build 0.0.39-18790

**Comment by LoweysLitsman** [comment]
Thanks for the headsup digant73! We now have one less issue.
Sun / Lens Flare goes through object is now fixed! And I can safely confirm PR #18019 fixed it. 

https://github.com/user-attachments/assets/212fea0d-e9bb-4212-b791-69406740c1f4

![Image](https://github.com/user-attachments/assets/2f7d8cea-778d-4226-b599-b3886bcc4f2c)

The room with wrong colors issue is still present
<details><summary>Image preview</summary>
<p>

![Image](https://github.com/user-attachments/assets/c68c5727-1582-43de-80c7-ccad58b2ad14)

</p>
</details> 
I'll update the rsx capture & log just in case.

**Comment by Ludoloque** [comment]
I've just finished Yakuza: Dead Souls and there is still an issue with random freezes. These aren't frequent, but I would still recommend using savestates, especially because checkpoints don't save your game and save points are scarce. Just remember to enable SPU comaptible savestates mode.

**Comment by LovelySquid** [comment]
In Ryu ga Gotoku 1 & 2 HD, the game crashes when I try to take a taxi at night in the 1 HD game.
I tried reverting to version 01.00, but it still crashes.
SYS: RPCS3 v0.0.42-20028-accfecd2 Alpha | master
SYS: Architecture: x64
SYS: AMD Ryzen 5 5600X 6-Core Processor | 12 Threads | 15.89 GiB RAM | TSC: 4.200GHz | AVX+ | FMA3
SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19045, Service Pack: none
RSX: Found Vulkan-compatible GPU: 'NVIDIA GeForce RTX 3070 Ti' running on driver 610.47.0.0
SYS: LLVM version: 22.1.8
SYS: Firmware version: 4.92

[龍が如く １ ２ ＨＤ EDITION \[BLJM60471\].log.gz](https://github.com/user-attachments/files/32524817/EDITION.BLJM60471.log.gz)

**Comment by keikof070623-gif** [comment]
@LoweysLitsman or anyone else, can you check and see if the room with the incorrect lighting colors is still happening?

**Comment by LoweysLitsman** [comment]
The issue is still persisting in 0.0.42-20039. I also tested shader on ultra, all buffers + cpu blit, rsx memory tiling.

<details><summary>Screenshot
</summary>
<p>

<img width="1602" height="932" alt="Image" src="https://github.com/user-attachments/assets/d366d24c-0693-4499-a2d0-25cf7fd8eac3" />


</p>
</details>
