### ISSUE TITLE
Regression in Borderlands [NPUB30413] after v0.0.5-6718

### ISSUE THREAD

**Issue by Josivan88** [RPCS3/rpcs3#4576]
The game works fine before 6718 and was almost playable. After the game still runs at 20-30fps but hangs and crash often. before the game was running at 20-30fps too. the problem still persists in 6737.
Default settings.
Cleared LLVM Cache and Shader cache does nothing.
details below:

![borderlands](https://user-images.githubusercontent.com/36341425/40008719-6219a07c-5776-11e8-9ea0-c03b68f67176.jpg)
Log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2001589/RPCS3.log.gz)

**Comment by Josivan88** [comment]
Problem still persist in 6815 @kd-11 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2023209/RPCS3.log.gz)
With line:
F {PPU[0x1000000] Thread (main_thread) [0x00556a14]} MEM: Access violation writing location 0x3

**Comment by Josivan88** [comment]
The problem still persist in 6880
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2060800/RPCS3.log.gz)
With line:
F {PPU[0x1000011] Thread (RenderingThread) [0x01005ab8]} MEM: Access violation reading location 0x48ff2a98

**Comment by kd-11** [comment]
Likely fixed with recent master, retest and close if fixed.

**Comment by Josivan88** [comment]
@kd-11  problem persists in 7077, different errors, 3 attempts:
1 - Hangs when tried to go ingame
2 - Crash with log 
[RPCS3.log_1.gz](https://github.com/RPCS3/rpcs3/files/2173161/RPCS3.log_1.gz)
3 - Crash with log
[RPCS3.log_2.gz](https://github.com/RPCS3/rpcs3/files/2173162/RPCS3.log_2.gz)

**Comment by Josivan88** [comment]
Fixed since #5314
