### ISSUE TITLE
Regression: Last RPCS3 master build doesn't show UI

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#4625]
In latest master build I just can't get the emulator work: It just think some seconds on launch, then nothing happens to me, and its process continues hanging in Task Manager. I tried the new clear copy installation inside other disk place, and it doesn't help too. Logs are clear and shows ready to launch state. What the hell? 

My current OS is Win 7 Home Premium x64, CPU: Core i5-2500, 8 GB RAM. System is okay.

**Comment by 13xforever** [comment]
It's a known issue with builds 6798 and newer.

---

Please read [the guidelines](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [our forums](https://forums.rpcs3.net/forum-18.html) or discord server for that.

**Comment by kd-11** [comment]
Strange indeed. Doed it only affect windows 7?

**Comment by Psycho-A** [comment]
> Strange indeed. Does it only affect windows 7?
Don't know, since I have WIn7 only for now. 
I have one of latest nVidia drivers with Vulkan Runtimes.

> Using build before Scribam removed VulkanLayers dependency fixes this. And afaik, it only affects first launch on fresh install.
It affects me any launches I do, and its not seems to be normal behavior.

**Comment by 13xforever** [comment]
I meant that once rpcs3 has booted successfully and created all the needed configs/data, newer builds will work as well.

**Comment by Megamouse** [comment]
I just set up a new build from zero and it worked fine. Might this be nvidia related?

**Comment by plasterstatue** [comment]
I can't get any 6798+ build to open when installed over a pre-6798 build that worked fine, or fresh install. Just sits in the task manager doing nothing.

Windows 10 Pro, AMD FX-6300, 12GB RAM, Nvidia GTX 1060.

**Comment by scribam** [comment]
I will have a look into this. I have something I would like to try. I will post a link to a build when it will be ready.

**Comment by scribam** [comment]
Can someone try this build?
https://ci.appveyor.com/api/buildjobs/84lyvjdwrouc79ee/artifacts/rpcs3-v0.0.4-6816-7827b5e4_win64.7z

**Comment by Moocow9m** [comment]
@scribam That build has the same effect as the current master for me, UI doesn't show and stays in task manager till killed.

CPU: AMD A8-7650K Radeon R7. OS: Windows 10 Insider, Driver, App, Bugfix build. GPU: NIVIDIA GTX 970

**Comment by scribam** [comment]
Could you please update your comments with your nvidia driver version?

**Comment by scribam** [comment]
You can also try to install the VulkanRT (https://vulkan.lunarg.com/sdk/home#windows), file "VulkanRT-1.1.73.0-Installer.exe". Let me know if there are changes.

**Comment by Moocow9m** [comment]
@scribam No changes. Tried master and your build.

**Comment by scribam** [comment]
Maybe two other things to test:
- Update to the latest beta driver 397.76 available here: https://developer.nvidia.com/vulkan-driver
- Try to run this app: [vulkan-cube.zip](https://github.com/RPCS3/rpcs3/files/2023413/vulkan-cube.zip)

**Comment by Moocow9m** [comment]
Updated Driver to latest, no change. Cube program exits with no error, however no interface opens either.

**Comment by Psycho-A** [comment]
> Can someone try this build?

Works for me without manipulations with drivers or something.

**Comment by scribam** [comment]
New build to test:
https://ci.appveyor.com/api/buildjobs/4grtnj2svvnuqy01/artifacts/rpcs3-v0.0.4-6817-63a17317_win64.7z

@plasterstatue Are you using Windows 10 Insider?
@Moocow9m @plasterstatue Are you able to run a PC game which uses a Vulkan renderer?

**Comment by Moocow9m** [comment]
@scribam I was able to use previous builds of RPCS3 with Render set to Vulkan

**Comment by plasterstatue** [comment]
@scribam I'm not using Windows 10 Insider, and I'm able to run pre-6798 builds with render set to Vulkan as well. The new build has the same behavior as the other post-6798 builds for me.

**Comment by scribam** [comment]
Time for a new build:
https://ci.appveyor.com/api/buildjobs/0dolbproxh8pc9oo/artifacts/rpcs3-v0.0.4-6817-b7728926_win64.7z
I hope this one should be able to show at least the UI.

**Comment by kd-11** [comment]
Dont hide the issue though - if the official vulkan test sample does not start vulkan should be disabled.

**Comment by Psycho-A** [comment]
All test builds from this thread works for me, unlike official ones.

**Comment by eighttailedfox** [comment]
with 6815, the program doesn't launch.

And with 6816 and 6817 I get this error trying to launch

![screenshot 743](https://user-images.githubusercontent.com/17698364/40360096-c749d756-5d79-11e8-8ba2-3bcf26d63b09.png)

**Comment by raffi00** [comment]
I have same issue as plasterstatue  and others, gui is never showing.
I think rpcs3-v0.0.5-6795-6b3eebc9_win64_st.7z was latest build that started fine.
It is the same for overwritting old folder, like for putting it into new clean one.
rpcs3 is in process list doing nothing.
there is no log anything, only RPCS3.buf is created, 
RPCS3.log and RPCS3.log.gz are 0 in size
Process Monitor is showing a lot of entries like
14:32:50,4905817	rpcs3.exe	7728	WriteFile	C:\ProgramData\NVIDIA Corporation\ShadowPlay\CaptureCore.log	SUCCESS	Offset: 485 118, Length: 85, Priority: Normal
and then nothing
14:32:50,5307256	rpcs3.exe	7728	QueryNameInformationFile	D:\iso-emu\rpcs3-tt\rpcs3.exe	SUCCESS	Name: \iso-emu\rpcs3-tt\rpcs3.exe
Windows 10 latest updates, latest official nvidia driver, GTX 950

**Comment by Asinin3** [comment]
https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/1.1.73.0/windows/VulkanSDK-1.1.73.0-Installer.exe installing this should fix it.

**Comment by raffi00** [comment]
I installed VulkanSDK-1.1.73.0-Installer.exe using defaults on c: drive.
No change
rpcs3-v0.0.5-6815-c9669818_win64.7z is not starting.
I just tried scribamrpcs3-v0.0.4-6817-b7728926_win64.7z
And this one is starting fine.
It has extra warning about unofficial build, plus i had change d12 to opengl.

**Comment by plasterstatue** [comment]
@scribam the most recent build posted in here is still not showing any UI for me.

**Comment by Moocow9m** [comment]
@scribam Sorry for late test, Without even rolling back the beta driver suggested, this build solves the user interface problem for me.

**Comment by Psycho-A** [comment]
Continuing this epic...
I updated my nVidia drivers to the latest official ones with VulkanRT included (397.93, Win7), and the issue repeated - even after merging #4639.

**Comment by Psycho-A** [comment]
Will someone work on this issue? I still can't get any last build work on my system. It's okay for Win10, but Win7 seems to be partially broken. I have clear last official nVidia drivers installation, and system is okay, so no any buggy exceptions. Why wouldn't just back to old pre-6798 behavior, if it always worked for everyone? 

I'm just an user and I'm judging the program by its end result, and now it's just doesn't work for me, no matter which internal improvements were done.

**Comment by kd-11** [comment]
You mentioned all test builds work for you already. Does that mean only master builds are not working? Try changing exe name yo something else then in case window has some flags set for rpcs3.exe. When an issue only affects a handful of users devs cannot fix it properly, it becomes a guessing game. If that doesn't work maybe scribam can explain how his build differs from master.
In the end, the only real solution would be to have you assist in debugging by building rpcs3 on your system so we can see where it is hanging and why.

**Comment by plasterstatue** [comment]
The test build worked for me, and the master still doesn't. Same as @Psycho-A

**Comment by Psycho-A** [comment]
Windows 10 shows success result on launch, but Win 7 is still down...

**Comment by raffi00** [comment]
I just tried currently latest build rpcs3-v0.0.5-a422a93c_win64.7z
rpcs3 is still not showing gui.
After a bit of reading it seems that gtx 950 do not support vulcan.
Still rpcs3 should at least start

**Comment by Psycho-A** [comment]
> After a bit of reading it seems that gtx 950 do not support vulcan.

It supports Vulkan as well as my Gtx 750 and 760. But yes, even if some card doesn't, the emulator must launch.

**Comment by raffi00** [comment]
Hi
GTX 950 is on a list on https://developer.nvidia.com/vulkan-driver
GeForce 900 Series: GeForce GTX 960, GeForce GTX 970, GeForce GTX 980, GeForce GTX 980 Ti, GeForce GTX Titan X
But in older builds i could select and use emulator with vulcan,
Regards

**Comment by Psycho-A** [comment]
My card is in supported list, but what does it change? In fact, Vulkan supports by any card that support OpenGL 4.5, and even my ancient GTX 560 (dead now..) worked good in Vulkan mode last year. The problem is definitely not Vulkan supporting, but Vulkan versions, because for one it works, but for other already not.

**Comment by Lakumakkara** [comment]
I had the same problem of rpcs3 not showing the UI. Updated drivers and installed the VulkanSDK but that didn't help. However, I found a way to get the post-6796 builds to work as intended. I opened regedit and in "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\Drivers" the first entry was "C:\Windows\System32\amd-vulkan64.json". I previously had an AMD gpu but currently I have a nVidia one, so I deleted that entry and now everything works.

**Comment by plasterstatue** [comment]
@Lakumakkara This worked for me. Same situation where I used to have an AMD card and switched to nvidia. Thanks a ton.

**Comment by Psycho-A** [comment]
@Lakumakkara Helped for me too! Thanks a lot! 

Now, since the reason is known, I think it's needed to provide this issue bypassing in the emulator, because a very few users know how to fix this...

**Comment by 13xforever** [comment]
Interesting case from discord today. User has fixed the issue by copying a 32-bit version of `vulkan-1.dll` from sdk accidentally.

It also worked with a 64-bit version later.

**Comment by spyropt** [comment]
@raffi00 vulkan works fine on a 950 gtx, I have one and it's working fine on windows 7 and windows 10, even my old 650 ti worked fine. The supported list must be wrong

**Comment by raffi00** [comment]
**Spyropt** thanks for info. i hope it is like you are saying
**Lakumakkara** 
Thank you for sharing, 
Deleting this registry key helped :)
"HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\Drivers" the first entry was "C:\Windows\System32\amd-vulkan64.json". 
latest rpcs3 is working for me now :)

I also had an amd card in that computer, like a year ago.

**Comment by Jorerim** [comment]
I have RPCS3 on a network drive shared through SMB. I tested with a lot of different compiled versions and the last that works is r6697-753d8170. With version r6718-737db900 and up, the process rpcs3.exe shows in task manager but doesn't load the GUI. Win10 v1803, Nvidia 398.11 driver and VulkanRT 1.1.73.0 installed. Tried r6817-b7728926 and nothing through SMB. but if I extract r6817-b7728926 to a USB drive it opens fine! There is no entry inside "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\Drivers"

**Comment by AniLeo** [comment]
This is not an issue on latest builds if you have drivers correctly installed.

If this is an issue even after using DDU to do a full driver reinstall on the latest master, please try installing the Vulkan Run-Time. If it's still an issue please open a new issue detailing what you attempted to do and what's your issue specifically (e.g. doesn't open, opens and doesn't show gui, etc).
