### ISSUE TITLE
NieR [BLUS30481] Flickering lighting

### ISSUE THREAD

**Issue by Kosyne** [RPCS3/rpcs3#4708]
RPCS3-0.0.5-6887

Settings are default with the exception of:
WCB is on, frame limiter is set to 30

As mentioned in the latest test results on the forum, the lighting flickers lighter/darker periodically. The effect is minor, and is not constant.

For me it was more noticeable in the area after the intro/snowy scene.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2067323/RPCS3.log.gz)

**Comment by nitrohigito** [comment]
It is pretty consistently present for me though.

I also observed that this flickering affects the black bars around the game's viewport too, when in desktop mode and the window is maximized. This might be important.

**Comment by evangelos-ch** [comment]
Experiencing this too, seems like a dynamic lighting issue. Useful to note that this flickering was in RPCS3's [NieR YouTube video from 06/06/2018](https://youtu.be/Tcx78ktgPMM?t=03s), precisely starting 0:03 on the right screen, until 0:19, so I'll assume this is a known issue. It'd still be great to get it fixed though.

**Comment by Asinin3** [comment]
I only played a little but it seems to happen more when the camera is at a low angle.

**Comment by kd-11** [comment]
Maybe fixed by https://github.com/RPCS3/rpcs3/pull/4784, but I'm not overly optimistic.

**Comment by jjsat** [comment]
After #4794 this issue seems to be fixed with Vulkan. Still present with OpenGL though.

**Comment by Illynir** [comment]
No, the problem always exist on vulkan, depends of the scene. Maybe minimized in some cases but still present.

**Comment by knzchaos** [comment]
It's a bit more noticeable in Replicant though, Gestalt isn't that bad.

**Comment by edpenz** [comment]
This issue has completely disappeared for me in recent builds, although I am running a different game version (Nier Replicant BLJM60223). My setup is rpcs3-v0.0.5-7044, Vulkan renderer, 200% scaling, 128x128 threshold, 30FPS framelimit.

**Comment by Illynir** [comment]
Confirmed fixed, tested on last master Nier and Nier Replicant, both works without problem for me and no flickering. 

It can probably be closed.

**Comment by jjsat** [comment]
Still flickers for me on current master with OpenGL (0.0.5-7069):
[OpenGL](https://www.youtube.com/watch?v=a3P3zEdZlN4)
Fine with Vulkan:
[Vulkan](https://www.youtube.com/watch?v=pSo6pCm7kp4)

Also shows the difference in #4837 for me.

In general everything is a bit too overexposed when compared to a PS3.

**Comment by HernanRC2** [comment]
The issue still continues in the latest version, it's not so serious but the flickering tires my eyes a bit.
I have played about 3 hours but I will probably wait for now, to see if they can fix it.

**Comment by Caxhiel** [comment]
I recently really got into NieR go I started emulating Replicant, but the lighting flickering is quite extreme so far for me. It varies with intensity depending on the area, but in general, it's pretty bad. 

Is there still no known fix to it? For me, it mostly happens whenever either the camera or character are moving. When standing still it usually just sticks to whatever the lighting was like in that position.

**Comment by soredake** [comment]
Still a problem with BLJM60223

**Comment by fpiesche** [comment]
FWIW: on real hardware the game does this whole "slow adjust" faux-HDR effect that was popular in games at the time from playing this for an hour or so (after playing many, many many hours of it on an actual PS3) it looks to me like this might be that shader adjusting the brightness too quickly to match changes in the image.

**Comment by nitrohigito** [comment]
iirc the issue is caused by the game's faux hdr.

**Comment by AfterRebelion** [comment]
#6483 seems to greatly reduce this.
