### ISSUE TITLE
Demon's Souls with v7077

### ISSUE THREAD

**Issue by Dani1977** [RPCS3/rpcs3#4857]
hi, with v7077 thre is no more ragdoll problem; but I have flashing and flickering screen problem.
I have Nvidia gtx 1080. 
this is my config (hope do not something wrong)
![immagine](https://user-images.githubusercontent.com/31347274/42412736-47cf475a-8212-11e8-9197-8a2bacfe0eb6.png)
![immagine](https://user-images.githubusercontent.com/31347274/42412738-59d86f8a-8212-11e8-9539-760017aec172.png)

thanks, regards.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2172903/RPCS3.zip)

**Comment by spyropt** [comment]
I can confirm the same problem

**Comment by Dani1977** [comment]
flickering in every stage, training, nexus, boletaria etc...

**Comment by psennermann** [comment]
with the same settings I can't even start the game, it always crashes at loading or logo screen...

**Comment by tommis15** [comment]
Yes, I'm also having the same issue with the flickering.

**Comment by isshininu** [comment]
Huh, I noticed black flickering when travel from Nexus to first Boletaria archstone. After that screen goes white flash somehow.

**Comment by trevorbennett** [comment]
I'm experiencing the same issue as @psennermann . I can't even hit the title screen, the emulator seems to freeze anywhere from the launch of the game, to the from software logo.

**Comment by psennermann** [comment]
It's almost a relief, finally someone else that's experiencing the same issue...I think PR responsible should be #4750 but I'm not 100% sure because according to the thread only ASMJIT should be "broken", while I'm experiencing crashes in LLVM as well...

**Comment by isshininu** [comment]
I think it's latest @kd-11 PR

**Comment by kd-11** [comment]
Which bug? I played about a half hour before merging, it does have sporadic flickering but I checked older builds with a patch to disable the hang and the flicker was still there. It regressed (flickering) some time back, not recently. Its just that it was not playable so no one noticed. As for the freezing, I cannot reproduce on Ryzen.

**Comment by psennermann** [comment]
No, it's not the latest kd-11, for me last working build (except ragdoll proble) was 6978, then with 6980 came out the crashes unrelated to radgoll problem, while I admit that latest builds 7xxx crash more often, so maybe the already existing issue was a little amplified by another PR...

**Comment by SiIdur** [comment]
Can't reproduce crashes on 7077, flickering mostly happens during inital load of the game / area.
Xeon x3440, gtx 960 vulkan, both asmjit and llvm suffer from flickering.

**Comment by psennermann** [comment]
I don't think flickering are due to 7077: while bisecting builds for the other issue, I noticed some flickering in 69xx builds as well

**Comment by Finoderi** [comment]
@psennermann I'm not sure it will help, but try to uncheck 'Run this program as an Administrator' in the rpcs3.exe's properties. For me Demon's Souls crushes more often when this option is enabled.

**Comment by trevorbennett** [comment]
For what little it's worth, I pulled the binary for 6998 and it ran fine. I don't currently have the time to regression test but the braking change seems to have come in the last two weeks. Also unlike @miho171 it's a consistent failure for me on 7077.

**Comment by Joltee** [comment]
I have 8700k with gtx 1080oc running Windows 10 and I also have flickering issues. Flickering is happening everywhere, sometimes it crashes the game as the screen goes complete white.

**Comment by Parthorisian** [comment]
[Black screen ](https://i.imgur.com/EiodRaS.png)after loading any location, even after reloading current location caused some dying.
[blackscreenDemonSouls_RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2212104/blackscreenDemonSouls_RPCS3.zip) . And yes, no any flickering issue noticed

**Comment by Parthorisian** [comment]
[Infinite loading screen](https://streamable.com/t22v0
), eyes in left bottom corner keep moving, both of them
Log [infiniteloadingscreenDemonSouls_RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2215833/infiniteloadingscreenDemonSouls_RPCS3.zip)

**Comment by Dani1977** [comment]
thanks for reply; the flickering still present with 7117, I have  try every setting in spu section but i haven't see any difference.
regards.

**Comment by kd-11** [comment]
retest with https://github.com/RPCS3/rpcs3/pull/5013

**Comment by Dani1977** [comment]
hi, but I don't know how to download the build.
thanks

**Comment by HenningJW** [comment]
@Dani1977 https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.5-8bfe38b3/artifacts you can click on the  green check mark on the newest code (the one furthest below) in the PR (pull request). Then click on details on AppVeyor for Windows builds and TravisCI for Linux.

**Comment by Dani1977** [comment]
@HenningJW , thanks .
@kd-11 , I try only windows version

**Comment by Dani1977** [comment]
Hi,
I tried the build 7298, Nexus, Boletaria 1-1 and 1-2 it seems that there are no more black/white flickering.

i try to do more levels .
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2349818/RPCS3.log.gz)

Regards,

**Comment by kd-11** [comment]
I finally isolated the black flickering, but it needs a lot of work to fix properly. You can try [this branch](https://github.com/kd-11/rpcs3/tree/des_fbo_fixes) if you have this problem and report if it is improved or fixed.

**Comment by Dani1977** [comment]
Hi @kd-11,
thanks for reply, sure i can try, where can i find the build ?
This branch fix also the problem with cpu with 4/4 core, otherwise i can't start the game, it stuck then crash after i press start button.

Regards

**Comment by kd-11** [comment]
Latest build that removes almost all the flickering for me is https://ci.appveyor.com/project/kd-11/rpcs3/builds/21175314, but the branch is still experimental and subject to constant changes.

**Comment by Dani1977** [comment]
Hi @kd-11 
I try the build but i can't test it:

the game, like other versions of RPCS3, game crash (emulator too) after or FromSoftware, or Havok or Intro cut-scene or in pg creation screen.

i'm sorry, i can do to much.

this log after Havok cut-scene crash

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2703636/RPCS3.zip)

**Comment by jbaribeault** [comment]
@kd-11 That build fixes the flickers; BUT it seems to have re-introduced the Z-Cull issue (bright sun coming through walls, like in the Nexus)....

**Comment by greentop** [comment]
The des_fbo_fixes branch also corrected the flicking in some of the Tales Of games.

**Comment by educobuci** [comment]
Hi all, I found a workaround for this issue on Nvidia cards. Just force v-sync for RPCS3 on Nvidia panel.

**Comment by miho171** [comment]
@educobuci you've just resolved the painful 4 core condition one year long! seriously, tested vsync on my i5 7600k with version 7652 passed logos section (basically a miracle), loading save and a straight hour of gameplay. never happened in versions with spu llvm and async compiling implemented.

**Comment by kd-11** [comment]
Hanging on quad cores was fixed in a recent PR by GalCiv (RipleyTom). The remaining flicker issues are fixed in my fbo_fixes branch, but it may be a while before it is merged into master as well.

**Comment by miho171** [comment]
@kd-11 yeah, sorry. saw the game work and thought was the vsync just enabled for testing. too much excitement gave me to the head. by the way, great work, thank you.

**Comment by ovitus** [comment]
Still getting lots of white flicker with fbo_fixes branch. It's really distracting. I'm on Fedora 29.

**Comment by ovitus** [comment]
Was on the wrong branch.. flicker is nearly gone, it did come back in force once in the Nexus, also the lens flare glitch someone mentioned. Separate issue, but any chance of fixing the audio stutter? It's really terrible on Linux using PulseAudio and not much better on Windows. I have it set to ALSA now, which just mutes it entirely.

**Comment by ovitus** [comment]
Ok, adding this to config.yml this does the trick for now:
Disable ZCull Occlusion Queries: true

Keep up the good work.

**Comment by kd-11** [comment]
Fbo fixes is merged into master now so it should work correctly without any workarounds on the master branch. The des_fbo_fixes branch is missing a lot of work that went into fbo_fixes PR instead which is why zcull was broken on it.

**Comment by kd-11** [comment]
As for audio, you need https://github.com/RPCS3/rpcs3/pull/5456. If flickering is gone with master, update this issue so we can close it.

**Comment by Parthorisian** [comment]
> 
> @ovitus
> .. flicker is nearly gone, it did come back in force once in the Nexus

Yep, flickering is almost gone except some small in World4-2 begin

**Comment by ovitus** [comment]
Yeah flickering does happen randomly it seems, then fixes itself when I reload the game or warp somewhere else.

[#5456](https://github.com/RPCS3/rpcs3/pull/5456) does fix the audio.. on WIndows with XAudio2. No solution for Linux I guess. I know these are experimental branches, but I wish there was a binary available, it's a slog compiling on Windows.

**Comment by HerrHulaHoop** [comment]
Binaries for Windows are available for all PRs.

To download windows builds from a Pull request on Github:
1. Go to the specific Pull request's page
2. Click on the Commits tab 
3. Click on the :heavy_check_mark: at the bottom (always click on the bottom-most green check mark)
4. Click on the details link next to the AppVeyor build 
5. In the AppVeyor site linked, click on the Artifacts tab and download the file with the Deployment Name rpcs3. It is the largest file in the artifact list.

**Comment by ovitus** [comment]
Oh, wow hey now I see that:
[https://ci.appveyor.com/project/kd-11/rpcs3/build/artifacts](https://ci.appveyor.com/project/kd-11/rpcs3/build/artifacts)

Thanks dude!

**Comment by kd-11** [comment]
I would advise not using that branch until it is rebased properly.

**Comment by ovitus** [comment]
It's actually running almost perfectly on Linux, sound and everything, very stable. I had snd_aloop enabled before which is why I wasn't hearing anything over ALSA... 

Zcull is still disabled. I'm not able to enforce Vsync for some reason? Any ideas? I have official Nvidia drivers installed (Linux).

**Comment by kd-11** [comment]
Vsync on nvidia vulkan does not work in any application, rpcs3 included. You need to force it in nvidia driver if the option is available to you.

**Comment by ovitus** [comment]
I could have sworn it I saw it working on Windows in RPCS3. I don't think the option is available in Linux via the Nvidia control panel. No big deal though, it's just vsync. Thanks again

**Comment by ovitus** [comment]
Fixed screen tearing on Linux through the Nvidia control panel. Checked “Force Full Composition Pipeline."

How would I know when this branch has been merged with the main release?

**Comment by daBloodyBlade77** [comment]
When do you think that the experimental branch will be merged to fix the flickering issue?

**Comment by kd-11** [comment]
des_fbo_fixes is not getting merged into master, at least not in its current form and even then not for a very long time. Most of the relevant parts were already merged into master already so users of the master branch should only very rarely experience flicker if at all. Ofc if it starts flickering too much just exit and restart or warp to a different area and it should fix itself.

**Comment by daBloodyBlade77** [comment]
Im experiencing constant flickering starting in the tutorial. Do you have any advice for fixing this. I have a Gtx 170ti and a Ryzen 1600.

On Jan 15, 2019 9:55 AM, kd-11 <notifications@github.com> wrote:

des_fbo_fixes is not getting merged into master, at least not in its current form and even then not for a very long time. Most of the relevant parts were already merged into master already so users of the master branch should only very rarely experience flicker if at all. Ofc if it starts flickering too much just exit and restart or warp to a different area and it should fix itself.

**Comment by ovitus** [comment]
It happens less using the des_fbo_fixes branch, but it still pops up occasionally, sometimes with vengeance. I'm about half way through my game now and everything else seems to run well for me. Reloading sometimes helps.

**Comment by Dani1977** [comment]
Hi, 
with 7881 i have no more problem of flickering.
Thanks, Regards.

**Comment by kd-11** [comment]
Closing as fixed.
