### ISSUE TITLE
Demon's Souls always freezes at logo screen or during intro

### ISSUE THREAD

**Issue by psennermann** [RPCS3/rpcs3#4861]
Since "finally" someone else reproduced the same crash, I decided to open this new issue:
Demon's Souls is unplayable on my system due to the fact that it constantly freezes/crashes at logo screen or during intro (forcing hard-close of the emulator), I can't even reach ingame anymore.
Bisecting the builds brought me to #4750 as the first PR to experience those crashes, but I'm not 100% sure because according to the thread only ASMJIT should be "broken", while I'm experiencing crashes in LLVM as well...

Here's the log file (freeze at Sony logo):

[RPCS3-DS_log.zip](https://github.com/RPCS3/rpcs3/files/2173930/RPCS3-DS_log.zip)

My Spec:
Windows 10
Intel i5 7400 (no TSX)
GTX 1060 3gb

**Comment by YaPeL** [comment]
Guess I'm the other person, its kinda random, I managed to get to the character selection just once, but other than that, it never passes the logo screens, but its not consistent as to in which part it hangs.

**Comment by isshininu** [comment]
> Intel i5 7400 (no TSX)
> Enable TSX: Enables

Delete all config files and retry.
Also you need to tick Write Color Buffers.
And setting resolution scale to 150% is the least thing - when the whole thing is not working 👌🏻

**Comment by psennermann** [comment]
unfortunately i5 7400 doesn't support TSX and maybe that's why not everyone is experiencing this problem...

**Comment by YaPeL** [comment]
I did it with a 4690k, I don't have tsx enabled either. Did you try using the "write color buffers"?

**Comment by psennermann** [comment]
Yes I already tried that, "write color buffers" doesn't fix the problem (in fact it is supposed to fix black/missing graphic, not emulator crashes)...also resetting resolution to 100% doesn't fix it either

**Comment by psennermann** [comment]
For what it's worth, here's the log with wcb enabled and default resolution
[RPCS3-DS_log.zip](https://github.com/RPCS3/rpcs3/files/2174013/RPCS3-DS_log.zip)

As for the other user experiencing this issue, I meant @trevorbennett , maybe he can post here his system spec as well...

**Comment by psennermann** [comment]
And also I've tried a fresh install, re-delete cache, tons of other options-combinations (activation, deactivation and so on) to no avail...

**Comment by miho171** [comment]
i5 7600k tsx
32gb ddr4 3000mhz
gtx 1080
win10 1803
game performance is good but sometime experience freezes at start logos; ragdoll bug is fixed but slow the game a lot more compared to "pre bug" builds. all happen with spu llvm and asjmit, settings are stock +wcb on.

**Comment by YaPeL** [comment]
well, looks I was lucky the time I tested the game with write colors off, cus in subsequent test, I never got to ingame again, still freezes randomly, If I clean all the cache and stuff like that, seems to go a little bit further, dunno whats going on.

**Comment by psennermann** [comment]
I told ya that's supposed to fix black/missing graphic, not emulator crashes ;-)

**Comment by trevorbennett** [comment]
Just adding my comment from the other thread here as well, in case it's to anyone's benefit. I pulled the binary for 6998 and it ran fine. I don't currently have the time to regression test but the breaking change seems to have come in the last two weeks.

**Comment by psennermann** [comment]
What CPU do you have?

**Comment by Tyralyon** [comment]
I don't know if this is the same issue as the rest of you, but I only get to the very first screen, where it says Demon's Souls in the lower left corner and two souls are floating above it. I'm on a 4790k. The next screen that is supposed to appear is the one informing about the auto-save feature.

**Comment by kd-11** [comment]
@Tyralyon Delete /dev_hdd1/cache and check if there are any errors about missing files. That issue commonly happens if your hdd1 cache is corrupted or there are missing files.

**Comment by Tyralyon** [comment]
@kd-11 You're probably right. I decided to try latest build (one I had  issue with was 7084), everything seems to be working great now. Haven't tried rpcs3 since 6880 and the 2 games that I play, DeS and Ni No Kuni have seen some major performance boosts since. Impressive!

**Comment by Yessos** [comment]
@kd-11 I tried deleting /dev_hdd1/cache, also fresh install. It freezes either on one of the intro logos or on start screen. Build 7089.

**Comment by ivicamarkovic** [comment]
Yes, I haven't been able to get ingame for at least few weeks. Same as @Yessos.

**Comment by ivicamarkovic** [comment]
Windows 10, i5 4670k, HD 7870, 8Gb ram. Both write colors on and off, and with clean install.

**Comment by Tyralyon** [comment]
Well, this is strange. I had no problems on my regular computer (after doing a clean install), but on another computer I have I'm now encountering this problem and can't find a way around it. My regular computer is a 4790k with a GTX 1080 and this one is a 4690k with a GTX 1070. Everything else is pretty much the same. Same graphics driver, same version of Windows 10 etc. 
On first boot I received the same error as ivicamarkovic, but on subsequent boots it just hangs on logos. I got to character creation once, but then it hanged there. The error never returned, not even after fresh install of rpcs3 and updating graphics drivers.

**Comment by Fashish** [comment]
@psennermann Have you solved this issue yet? I am experiencing the exact same problem while having tried all the solutions mentioned here and elsewhere still to no avail.

**Comment by nlri** [comment]
I've done some testing with debug settings, the freezing happens less when using "accurate GETLLAR" and "accurate PUTLLUC", but when it reaches ingame, the performance is unplayable slow, something like 1 fps.
When running with vulkan, the screen has a lot of flickering, and i can't see anything of the game, but i can still hear the sounds.
When running with opengl, there is no flickering, but it is still unplayable.
Testing with null adapter, using sound to load the game, the fps is still something that would be unplayable slow.
I've tested some older builds, I experienced this freezing issue as far as #4705, but it seems to be less frequent in these older builds.

**Comment by Snicked** [comment]
Also have this problem with an i5 4690K, a GTX 970 with most recent drivers and Windows 10 on 0.0.5-7123. 
Can also confirm that the game runs resonable on 0.0.5-6796 and doesn't have the freezing issue.
Seems to only affect processors which have just 4 cores (without hyperthreading)
Anyone with an AMD processor havin this issue?

**Comment by psennermann** [comment]
@Fashish no solution yet (7138)...like Others said, I think it's a 4 cores problem...

**Comment by miho171** [comment]
Can't get over logo's intro, definitely 4 core issue (i5 7600 k). Tried disabling one in task manager fix the problem, but then the game is unplayable.

**Comment by isshininu** [comment]
I have 4 core, 8 threads CPU and I disagree)

**Comment by isshininu** [comment]
Surprisingly, I can confirm.
Run this game today on ivy-bridge machine with 4 cores/4 threads and it freezes at intro screen.

**Comment by Snicked** [comment]
Could there be a connection to #4473 ? 

> The thing that happens with Catherine also happens on Persona 4 Arena Ultimax.
The game freezes after the intro cutscene [Source](https://github.com/RPCS3/rpcs3/issues/4473#issuecomment-385261764)

**Comment by YaPeL** [comment]
Would be nice if someone with a 8 core processor could try disabling 4 cores and checking if the game hangs too

**Comment by Tyralyon** [comment]
@YaPeL Excellent idea! I now disabled HT on my 4790k and this issue immediately appeared, I can't get past intro logos. Enabling HT instantly made it working again.
Is this info helpful at all for someone like @kd-11?

**Comment by YaPeL** [comment]
nice, sounds like a race condition somewhere.

**Comment by Yessos** [comment]
I'm having this issue on i5-6600K which is 4 cores/4 threads as well.

**Comment by DPatligan** [comment]
I can confirm it also happens on i5 7500 (4C/4T)

**Comment by miho171** [comment]
Someone of the developer should investigate on this 4 core issue.

**Comment by Propheta21** [comment]
yes, i'm having the same issue with i5-6600k. If the game doesn't freeze(for some reason), then I'll get a win32 exception error.

**Comment by miho171** [comment]
Try to run exe in win8 compatibility mode, for me seems to work.

**Comment by Tyralyon** [comment]
@miho171 Amazing, you are indeed correct. I have now played for half an hour on my 4690k. Unfortunately you are also correct about the performance though.

**Comment by ToppestOfDogs** [comment]
Yeah, it's working for me too, but it's far too slow to play. I used to get a pretty consistent 25-30 fps, now I get about 17 at most

**Comment by miho171** [comment]
"win8 comp mode" too slow to be acceptable, we need another workaround.

**Comment by YaPeL** [comment]
Its probably hidding the bug somehow, may be a hint for the devs to realice why this is happening.

I remember there was a PR related to some timing thing affecting  a Tales of game, and I remember kd-11 writting a workaround for 4 cores cpu, I suspect thats where the problem started, but I don't have the time to test it.

**Comment by Mullmar** [comment]
The first time i runned the game i got to the character creation screen with stable 30 fps.
After that for unknow reason, the game crashes at some random point before get to that screen (It was a pleasure to meet it).
I confirm what you guys are saying, it seens to be a 4 thread processors problem, mine is I5-2310 but the question is: Why it runned perfectly on the first launch?

**Comment by AniLeo** [comment]
Hmm, is that with SPU ASMJIT, LLVM, or both?

**Comment by miho171** [comment]
@AniLeo it "was"both.

**Comment by Tyralyon** [comment]
I'd be interested to hear what the others here have to report, but at least for me it's no dice when I disable HT on my 4790k. Haven't got any of my 4690k's available for testing right now, but I suspect the result would be the same.

**Comment by ToppestOfDogs** [comment]
Nothings changed for me

**Comment by AniLeo** [comment]
Two users on reddit also commented it's not fixed. Seems like a race condition, I assume you'll start getting the issue again eventually.

**Comment by isshininu** [comment]
What is race condition? Some SPU threads are required to be executed in specific order and/or just in time?

**Comment by MSuih** [comment]
When developing a multithreaded application you have no control over how much CPU time each thread gets and thus no way to predict the order of execution across multiple threads. Race condition means that this unpredictability causes errors; for example two threads try to modify a piece of data at same time or one thread expects another to have finished execution even though it hasn't.

These kind of errors are incredibly hard to debug as debugging software hasn't really been designed for multithreaded applications. Also the most oblivous way to fix these issues, setting up a synchronization lock, can cause a performance loss as some threads will have to wait if one is using the lock (not to mention that acquiring and releasing the lock eats up some instructions as well).

**Comment by miho171** [comment]
i can confirm have no more freezes at logos section in my i5 7600k win10 rig (4c/4t) from build 0.0.5-7179, don't know what is changed but here it is. game still suffer of heavy stutter during ragdoll and contact with stuff like barrels, tables, etc. surely remains a better experience play it in 0.0.5-6718 build.

**Comment by PCMR42** [comment]
Nothings changed for me even with the latest build 7189, i5 4660 (4c/4t)

**Comment by Propheta21** [comment]
i5-6600k The issue remains for me.  (builds 7179-7182)

**Comment by ap-Di0** [comment]
Is there any clue why this started happening specifically on 4c/4t cores only?

**Comment by Lithium64** [comment]
Same bug here, on a i3-4150

**Comment by kd-11** [comment]
I tried limiting ryzen to 4c/4t and it booted fine and goes ingame. Awful performance with the low clockspeed but no lockups.

**Comment by YaPeL** [comment]
try with  2t / 2c instead? maybe your cores are too fast to trigger the bug

**Comment by PCMR42** [comment]
it boots normal and you can go in game if you set the compatibility mode to win7 or win8 as miho171 said but its unplayable with poor performance. i5 4660 (4c/4t)

**Comment by Lithium64** [comment]
I tested this game on Ubuntu 18.04 LTS and this bug does not happen, it must be a specific Windows 10 bug by the way.

**Comment by psennermann** [comment]
Still broken here with i5 7400 and Win10...

**Comment by miho171** [comment]
7231 breaks DeS, freeze at loading screen after selecting save; until 7229 i'm able to play (aside constant crashes) even with a 7600k (4 core).

**Comment by narfel** [comment]
Confirmed crash on ivybridge quadcore i5 3450/w10 with the same race condition as everyone else. build 7253.

**Comment by paulsapps** [comment]
On Windows try with "Application Verifier" and enable only the "cuzz" option. That helps to weed out threading issues (or rather it will drastically cut down the the repro time in most cases).

**Comment by ToppestOfDogs** [comment]
On the latest builds, the game crashes and closes the whole emulator instead of freezing.

**Comment by HerrHulaHoop** [comment]
@ToppestOfDogs that is a separate issue affecting multiple games. Use SPU Block Size Safe to overcome it.

**Comment by ToppestOfDogs** [comment]
@HerrHulaHoop I already am using safe

**Comment by HerrHulaHoop** [comment]
Ohh okay. Well then you can hope on over to our [discord server](https://discord.me/RPCS3) and we can try to debug it. It isn't related to this issue so best not to add messages relating to it in this thread.

**Comment by AniLeo** [comment]
Test with #5310

**Comment by josearr** [comment]
Not fixed for me with #5310:
i5 3570K
GTX 1060 6GB

Emulator crashes and closes without any message in every test I've made at this screen:

![1](https://user-images.githubusercontent.com/44747577/48025257-30a55480-e143-11e8-9f79-69c3a8ae0d9c.jpg)

Here is a log of  my last test:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2550536/RPCS3.log)

**Comment by ToppestOfDogs** [comment]
I can't test anymore because I upgraded to a Ryzen

**Comment by micaelis72** [comment]
The game is playable to me. I didn't went to much further, but it was playable in the tutorial
BLUS30443

**Comment by Yessos** [comment]
Tested on #5320. Same as josearr for me, but I don't even get the message. Just loading animation in bottom left corner and a crash with no error message.

Windows 10
i5 6600K
GTX 980
16 GB of RAM

Logs: 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2567034/RPCS3.zip)

**Comment by spleenandcigars** [comment]
I got it working with win 8 compatibility, but compiling shaders is extremely slow. 

Windows 10 64bit
i5 7600k / GTX 1070 / 16gb RAM.

**Comment by AniLeo** [comment]
Retest with #5475

**Comment by psennermann** [comment]
Yes, #5475 fixes this issue

**Comment by AniLeo** [comment]
Fixed by #5475

Closing as solved

**Comment by miho171** [comment]
Win8 comp makes all extremely slow, to really fix 4 core race condition just enable vsync in GPU settings.
