### ISSUE TITLE
Regression: Skate 3 can't get past intro video logos [BLES00760]

### ISSUE THREAD

**Issue by dustinpaluch** [RPCS3/rpcs3#4954]
First time submitting an issue. 

### Version:
RPCS3 [69af607](https://github.com/RPCS3/rpcs3/commit/69af607491cfe8f359f92b60f17693e1cbd88f27)

### Reproduce:
By intro video logos, I mean the intro videos for Black Box and EA, before you get prompted for input. I launched RPCS3, deleted Shaders/LLVM/SPU caches, double clicked on Skate 3, the game window opens, and got near the end of the EA video before it froze.

I could previously get to the live action intro video and past that to menus, but not all the way in game.

### Output from RPCS3 log:
~~RPCS3-log-output.txt~~
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2259788/RPCS3.log)

### Specs:
i5-4690 @ 3.5GHz
NVIDIA GTX 770 
8GB RAM
[DxDiag.txt](https://github.com/RPCS3/rpcs3/files/2259763/DxDiag.txt)

**Comment by AniLeo** [comment]
Missing actual log file, that's not the log file

**Comment by Asinin3** [comment]
How many times did you try? could just be a race condition (random freeeze)

**Comment by dustinpaluch** [comment]
@Asinin3, 4 or 5 times.

@AniLeo, Ah, I see now. RPCS3.log (in the same dir as RPCS3.exe) was showing as 0KB, then I closed the (frozen) game, and now it contains this:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2259788/RPCS3.log)

**Comment by Kravickas** [comment]
Well for me it crash while entering ingame, it start spamming
`E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x50000410 x9`
or
```
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0x1F800000, put=0x87FE0
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0x1F800000, put=0x8FFBC x3
E {rsx::thread} RSX: Application has failed to recover, resetting FIFO queue
E {rsx::thread} RSX: Invalid RSX method 0x2830 (arg=0x42947f3b)
(in file Emu\RSX\rsx_methods.cpp:46)
```

**Comment by NXij** [comment]
It kicks in with the semaphore_acquire error once you hit the character selection screens, eg when starting the game without a save or trying to enter the "Free skate" mode while in game.

**Comment by dustinpaluch** [comment]
Fixed in https://github.com/RPCS3/rpcs3/commit/451b3f3c9d73508ee583d0c555e23c1174c2ab57

**Comment by AniLeo** [comment]
Wasn't fixed on a readme update for sure, somewhere between your first test and that one then

**Comment by dustinpaluch** [comment]
Ha, true. I should have said "working in..."
