### ISSUE TITLE
Demon Souls freezes after 15-25 minutes of play

### ISSUE THREAD

**Issue by dukenukemx** [RPCS3/rpcs3#5037]
Using RPCS3 7247 on a Ryzen 1700 with a RX 480 latest drivers on Windows 10.  I've tried many things to try to stop this from happening.  No overclocks, no Anisotropic Filter, OpenGL or Vulkan, and 720P resolution.  Tried using LLVM SPU Decoder with Accurate xfloat and ASMJIT.  I have Write Color Buffer on.  I've tried a fresh install of RPCS3 and I've tried disabling the hard disk from going to sleep.  I use GPDSCK for mouse to  joystick but I've also tried mouse2joystick_Custom_CEMU with no difference.  I've also tried fullscreen and window mode.  

To be accurate, the screen freezes but the game is still running and I can hear my character dying.  If I give it a minute, the screen returns but it'll go back to freezing within a few seconds, which I can still hear the game running.  I'd upload the RPCS3.log but it's nearly 300 megabytes.

**Comment by ruipin** [comment]
Do you see the same issue in 7253 or 7232?

Try uploading RPCS3.log.gz next time it happens again, since I am unable to reproduce this issue. It might give us some clues as to what is going on. This file will probably not be as big as 300MB.

**Comment by dukenukemx** [comment]
I've been updating RPCS3 for the past 2 weeks constantly to see if any update fixes the problem.  I just updated to 7253 as you mentioned and ran RPCS3 again.  Again it freezes but no RPCS3.log.gz.  It has to be forced closed, no graceful shutdown.

**Comment by ruipin** [comment]
Can you upload the file somewhere? It's impossible to figure out what it could be without the log, when I can't reproduce the freeze.

**Comment by dukenukemx** [comment]
I lowered the system memory from 2933 Mhz to 2400 Mhz and still freezes.  So what I'm doing now is giving the emulator all the time in the world to exit so it can make a proper RPCS3.log.gz.  The emulator is still working but it takes minutes before I can close the emulation, and more minutes before the emulator itself exists.  Finally made a proper log file.  
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2321189/RPCS3.log.gz)

**Comment by dukenukemx** [comment]
This might be related but I disabled Enable thread scheduler to see if that has something to do with this hang and the game did freeze hard, with a verification failed.  Not sure if that's related.  Unfortunately my copy and paste didn't capture it for some reason.  I reran it and it frooze hard cause I don't hear the game running nor do I see it continue after a minute of time.  So it had to be forced closed and I zipped the RPCS3.log .  At the end of the log I see this.  This is all different cause of "Enable thread scheduler" is off.  

·W 0:37:18.980044 {PPU[0x1000000] Thread (main_thread) [0x01d55654]} RSX: Cache miss at address 0xC5140000. This is gonna hurt...
·F 0:37:18.995455 {PPU[0x1000000] Thread (main_thread) [0x01d55654]} MEM: Access violation reading location 0x48


[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2321254/RPCS3.zip)
.

**Comment by dukenukemx** [comment]
Tried it again with "Enable thread scheduler" on and pretty much like before where the game runs but the screen is stuck for a minute or two.  If I get the RPCS3 window in focus, the game seems to indefinitely run behind it, but it takes like 5 minutes before the window finally closes.  Another proper log if it helps.  

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2321517/RPCS3.log.gz)

**Comment by ruipin** [comment]
This is indeed looking more and more like a weak CPU to me - many PS3 games were never tested on different hardware so have a lot of bugs if the performance is too different between the PPUs and SPUs. 

From the logs, it doesn't look obvious what the error could be and I've been unable to reproduce this failure on my side. I was suspicious it could be related to a recent change but you said that you've been testing updates for a while, so I assume 7232 also has the same issue so that can't be the problem.

You can always try out the #help channel on the RPCS3 Discord, some people there might have a better idea.

**Comment by elhaya** [comment]
again duke,
if nothing else helps, you can always use the 'windows 8 compatibility' method which *100% works*
the only downside is being stuck at around 9 fps :\

**Comment by dukenukemx** [comment]
Yea I tried the Windows 8 compatibility and it was like 5 fps.  Gonna try 6697 to see if that has issues, cause people on reddit said that 6697 is the best version to use to have no issues.

**Comment by kd-11** [comment]
Make sure you are using the very latest build, there was a regression about two days ago causing emulator to lockup and require task manager kill but this has since been patched. Ryzen works fine on this title (I have the 1700)

**Comment by dukenukemx** [comment]
6697 will eventually freeze with this error.  I'm guessing that was fixed recently.  No strange texture blips like I see with the 7000's.  I should mention I also watch YouTube videos while I play Demon's Souls, so maybe that's causing something to get out of synchronization?  Going to try and set a certain number of Preferred SPU Threads and see if that does anything.  Maybe 3 SPU threads?  

Maybe its my combination Ryzen + AMD RX 480 graphics card that's making it an issue, where the typical Intel+Nvidia might not?   Elhaya has an issue but for him its within 1 minute, so it doesn't sound like the same issue.  Any Ryzen+AMD GPU owners having no hang or freeze issues?  

F {SPU[0x2000000] Thread (DLSpursManagerCellSpursKernel0) [0x067c8]} class std::runtime_error thrown: Unknown command (cmd=GET, lsa=0x27600, ea=0x3f800000, tag=0x0, size=0x4db4)
(in file Emu\Cell\SPUThread.cpp:1401

**Comment by dukenukemx** [comment]
@kd-11 where can I find the latest build?  I'm using 7253.

**Comment by elhaya** [comment]
@dukenukemx 7253 is the latest build, but the issue still exist.
i wanted to outline that this is not a windows specific issue, because i installed linux (fedora 28) just because someone mentioned on the forum that in linux the issue does not exist. however, i can confirm that it exists in linux as well, if not worse

**Comment by dukenukemx** [comment]
Well I ran RPCS3 7253 for over an hour and nothing happened, but it did crash when I closed the emulation window.  I set the Preferred SPU Threads to 3 and didn't have a web browser running in the background.  This time I'll set the SPU Threads to Auto and try again.  I'll see if that makes it crash again within 15-25 minutes.  

@elhaya I run Mint 19 on my HTPC with a Radeon HD 7850 and I have RPCS3 installed.  I haven't ran the emulator for more than 5 minutes since that machine isn't what I play games on.  I use Oibaf PPA for the latest Mega drivers.  I might try it on that machine and see how long it runs.

**Comment by dukenukemx** [comment]
Ran it again for nearly an hour without RPCS3 freezing, except when I exit the emulator.  Some reason it force closes twice when I do that.  Should also mention that I had SPU loop detection disabled for both times I ran it nearly an hour without issue.  It maybe that running RPCS3 with Firefox will inevitably hang it or freeze it.  Which could be either an issue with AMD Radeon drivers not playing well with multiple 3D applications or Firefox may hog too much CPU attention and it desynchronizes RPCS3 threads.  Later I'll try it with SPU loop detection on and maybe run Chrome instead of Firefox after that.  I like to run videos from Level1techs while I run around in Demon's Souls.

**Comment by dukenukemx** [comment]
I can confirm the issue is with me running Firefox playing a YouTube video while running RPCS3.  SPU loop detection doesn't change the stability of RPCS3, though it still crashes when I exit RCPS3.  I'm not sure why Firefox is causing RPCS3 to hang, but it is causing it for me, just as before within 15-25 minutes of me starting Demon's Souls.  I'm gonna try this with Chrome to see if there's any difference.

**Comment by dukenukemx** [comment]
Something happened when using Chrome & RPCS3, as it froze during loading screen and I get this error.  So the idea here is to not do anything else while running RPCS3.    

E {PPU[0x1000013] Thread (_cellsurMixerMain) [0x01547fa0]} Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x687368]
E {PPU[0x1000013] Thread (_cellsurMixerMain) [0x01547fa0]} Stat: 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [x171841]

**Comment by elhaya** [comment]
i wanted to share with you..
i was experiencing the exact same problem with demon's souls: random crashes, sometimes after a couple of seconds after starting the game!
anyhow, I don't know why but i noticed that my log file was growing insanely after only about a minute of gameplay. I reduced the log to "fatal errors" and the crashes went away!!! the game is extremely stable now and i can play for more than hour without worrying

**Comment by dukenukemx** [comment]
I'll have to give that a try.  My log grows to insane levels as well.

**Comment by PCMR42** [comment]
> i wanted to share with you..
> i was experiencing the exact same problem with demon's souls: random crashes, sometimes after a couple of seconds after starting the game!
> anyhow, I don't know why but i noticed that my log file was growing insanely after only about a minute of gameplay. I reduced the log to "fatal errors" and the crashes went away!!! the game is extremely stable now and i can play for more than hour without worrying

can you tell me how to reduce the log to fatal errors?

**Comment by dukenukemx** [comment]
Yea I haven't figured out a way to reduce it to fatal errors only.

**Comment by elhaya** [comment]
right click on the log part of the screen and choose 'fatal'

**Comment by raveskirza** [comment]
Log: {"": Fatal}

**Comment by dukenukemx** [comment]
I'm finding if the game stops once and then I just restart the emulation, the game will run just fine afterwards.  Today I got this error.  At least now I can just close the emulation window and just double click Demon's Souls to start it back up.  

F {PPU[0x1000000] Thread (main_thread) [0x01d55654]} MEM: Access violation writing location 0x150000

**Comment by ruipin** [comment]
Test #5115 again, more fixes have gone in that prevent deadlocks like what you see.

**Comment by dukenukemx** [comment]
Took a while but got this with 7376.  

F {PPU[0x1000000] Thread (main_thread) [0x01d55654]} MEM: Access violation writing location 0x0

**Comment by AniLeo** [comment]
Retest with the latest build

**Comment by kd-11** [comment]
Closing as the issue has not been updated in several months.

**Comment by Alvilos** [comment]
This might be obvious but I'm running the latest build and I'm having this problem now in 2020 and I have tried the multitude of options I have found and had no luck (such as turning off most log results, tried running in openGL and it just doesn't render properly at all, deleting hdd-1) it just reliably freezes some where between 10-30 min in every time

**Comment by griever-gf** [comment]
Same for me in 2020.
i5-6600K, GTX 970
It's crazy!
