### ISSUE TITLE
Nier OpenGL resolution scaling regression

### ISSUE THREAD

**Issue by psennermann** [RPCS3/rpcs3#5305]
PR #5115 (master 0.0.5-7385) causes NieR (Replicant) to not scale anymore the selected resolution (1920x1080) when using OpenGL

Unfortunately 0.0.5-7380 broke game graphics for this game, anyway if you look closely at the remaining portion visible, you'll notice that 7380 is high res (1920x1080 set) while 7385 is low res (open the fotos in fullscreen and look at the edge of the platform/cliff or see how much more detailed are the object in the backjground)

7380
![desktop screenshot 2018 11 04 - 11 06 25 75](https://user-images.githubusercontent.com/6342467/47962946-7ae3e400-e024-11e8-918e-23227121088b.png)

7385
![desktop screenshot 2018 11 04 - 11 10 52 48](https://user-images.githubusercontent.com/6342467/47962949-86370f80-e024-11e8-8721-b5f2201dd32c.png)

You can also see that PR #5115 killed OpenGL fps: from 30 (or more, since game is capped at 30) to 19, but that was already reported in issue #5182

My system:

Intel i5 7400
Nvidia GTX 1060 3gb
Win10

**Comment by weter11** [comment]
I analyzed this issue and understand what the problem is. As soon as the frame rate falls below 26, the game engine does not understand why it reduces the resolution from 720p to 576p. To understand this, I limit CPU clock from 1.7GHz(28-30fps) to 1.5GHz(26-27fps). So, game engine don't understand that you limited by CPU, not by GPU and change resolution of 3D elements in a game.
In general, this game is full of incomprehensible techniques, such as the frame rate limit in game 36fps. If there is no monitor with FreeSync from 30 fps(rare models), or FreeSync 2, then the picture will be jerky, or if you put a limit on 30fps, then there is a big out-of-sync video and audio in splash screens.
So this problem with a resolution is not an emulator problem itself.
By the way, the frame rate was restored in #5276 with latest commits or not? I can't compile it on my Ubuntu.  AppVeyor system compile all commits and create binaries for Windows systems instead of Travis CI, that only check can it compile or not. Its much simpler, than compile something by itself.

**Comment by psennermann** [comment]
No, unfortunately #5276 didn't brought back a single fps in OpenGL and OpenGL is important for this game because it doesn't have crackling sound like Vulkan has even at steady 30 fps...

**Comment by kd-11** [comment]
Closing since the original issue reported here is fixed for a long time.

**Comment by psennermann** [comment]
I don't know why you closed this issue: Nier with OpenGL is still low res (tested with rpcs 0.0.6-7934)

P.S. the speed regression reported in #5182 is also not fixed...

**Comment by psennermann** [comment]
Tried 0.0.8-9597 and for me NieR (Replicant) in OpenGL is still in low resolution and super slow (18-19 fps)...

**Comment by psennermann** [comment]
![image](https://user-images.githubusercontent.com/6342467/74603915-f4d49b00-50b8-11ea-9dab-4861382b6ed9.png)

**Comment by psennermann** [comment]
![image](https://user-images.githubusercontent.com/6342467/74603960-7af0e180-50b9-11ea-9b7e-a6a6148d6219.png)

As you can see, Vulkan is hi res and full speed, while OpenGL with the same settings is low res and very slow...

**Comment by kd-11** [comment]
This application has dynamic resolution. When performance drops it lowers the rendering resolution to compensate which makes it seem like it is broken. Capturing the same scene in renderdoc shows it can vary even on vulkan when I enable a bunch of logging. There is therefore no emulator bug to fix on that front.
That said, @psennermann, which GPU are you using? I have a 1050Ti hooked up via a very slow PCI-e 1.1 x4 slot and I have better performance (~27-30fps).

**Comment by psennermann** [comment]
I have a rtx 2060 Super 8gb on Intel i7 7700...I think the real problem here is that PR #5115 caused a very huge OpenGL slowdown (only?) on this game and maybe it would be interesting to investigate why

**Comment by kd-11** [comment]
5115 did not break anything, it added functionality that was correct, but is notoriously slow on OpenGL drivers. I have retested and I observe slowdown using my polaris card (9fps) but my pascal card is unaffected. We've moved some functionality away from the driver in response to these problems, but we cannot open specific tickets for these problems. This is largely because OpenGL support has been very poor from vendors since vulkan launched, it makes more sense to focus attention on that platform instead for performance related matters.
