### ISSUE TITLE
Castlevania Lords of Shadow no input

### ISSUE THREAD

**Issue by LuismaSP89** [RPCS3/rpcs3#5449]
Castlevania Lords of shadow (BLES 01047) can´t pass the "Press start screen"

The intro video can be skipped, so the input works here, maybe the problem is other, I think with the trophies.

Log attached.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2705562/RPCS3.log.gz)

Specs: Windows 10 x64
i7 4790k
16 GB DDR3
GTX 970 4GB GDDR5

**Comment by Megamouse** [comment]
I cannot recreate this issue at all.
Try using the correct gamepad

**Comment by LuismaSP89** [comment]
I tested using original DS4 and Xbox One controller (This one using xinput of course) but both doesn't work.

**Comment by LuismaSP89** [comment]
After some searching, I found some users having exactly the same issue:

https://forums.rpcs3.net/archive/index.php/thread-189914.html  _(Tayyar: Last working version is 7253.
Today's release stuck the FPS at 16 and controller input isn't working as it should. I pressed start a hundred times and it registered once, however, analog sticks are fine.)_  (I can confirm, it stucks at 16 fps and can´t pass the press start screen)

And here: https://github.com/RPCS3/rpcs3/issues/4094

**Comment by Megamouse** [comment]
I really think this is a race condition.
I never had this issue on my 7700k

**Comment by Asinin3** [comment]
It is indeed a race condition, and the issue is quite old now. There's a few factors that can fix it, such as the frame limiter. But it's inherently random. If you're in our discord server you can see my trying to debug it with someone here: https://discordapp.com/channels/272035812277878785/277227681836302338/509337337571049472

**Comment by LuismaSP89** [comment]
Tested with clean rpcs3 install, changed settings, fps limiter to off, auto, 30 fps, 60 fps, used opengl backend, vulkan, ASMJIT SPU, LLVM SPU, no changes, this is annoying. So basically, this game stucks at 16fps in the "press start screen" for some users with no reason? Wonderful...

**Comment by LuismaSP89** [comment]
So, then  is not a problem with trophies? This is the log while I´m stuck on that screen:

**Comment by Megamouse** [comment]
why dont you just try it with the trophy pr then??

**Comment by LuismaSP89** [comment]
I tried with trophy pr with no results. BTW I reached this screen after some minutes (The intro video cames in after some minutes waiting and solves the problem, you can press start now in the press start screen) but it stucks too in this new screen:

![sin titulo](https://user-images.githubusercontent.com/12205048/50385955-58924c80-06de-11e9-9a55-d86dfeca3b71.jpg)

**Comment by kd-11** [comment]
I did not notice this ticket, but I had this problem before and worked around it. I think it had something to do with fps cap iirc.

**Comment by LuismaSP89** [comment]
Good news, this problem is solved with https://github.com/RPCS3/rpcs3/pull/5435 (But I can´t get my DS4 working with it, in fact it has no response even in the first video screen with the bats of mercury steam only with Xbox One controller) But at least it works now with xinput. Closing.

**Comment by elad335** [comment]
The pull request is not merged, reopen.

**Comment by LuismaSP89** [comment]
> 
> 
> The pull request is not merged, reopen.

Mmm? Ok, as you wish, sorry.

**Comment by LuismaSP89** [comment]
Update: With latest commits of elad335's PR, the dualshock problem is fixed. Now all works perfect.

**Comment by Vykhodzev** [comment]
I think this issue is still present. I still can't get past the title screen. I keep pressing the Start button but nothing happens. Game is also stuck at 16 fps on that screen. I tried both my DS4 and Logitech F710 in Xinput mode. Inputs of both register in the controller configs.
I can skip the Mercurysteam intro video and also the video that starts playing after a while when sitting too long during the title screen.

That is on build 0.0.7-8871

I included my log here:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3721243/RPCS3.log.gz)

**Comment by LuismaSP89** [comment]
@vykhodzev Maybe it's a regression. Can you bisect, please? This was working fine in the builds 9 months ago, try different builds in order to find the guilty one.

**Comment by elad335** [comment]
@Vykhodzev Try with TSX disabled.

**Comment by Asinin3** [comment]
Happens on Ryzen too btw, it seems more like a race condition because sometimes i could get inputs to register. It seemed like using a fps limit helped, and sometimes you need to wait like 30seconds before buttons register on the title screen. I've had issues with this dating back to early 2018.

**Comment by Vykhodzev** [comment]
I think I figured it out.
It seems it was just missing the latest Visual C++ Redistributable. After that I got ingame just fine. I feel really stupid now, sorry.

Thank you nevertheless for your replies and eternal patience! :)

**Comment by monops** [comment]
I this this is happening again in 0.0.12-10943-92efaf0b Alpha
I can't pass through that page with many combinations (pad, keyboard, vulkan, OpenGL, interpreter)

**Comment by legolas119** [comment]
hi, me too, i still have this issue. I tried the game some days ago and the issue was not present, but now it is present again.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5759515/RPCS3.log.gz)

**Comment by LuismaSP89** [comment]
Strange... I played this game 1 month ago with no problems, can you @monops  & @legolas119 test with older builds in order to bisect the PR that reintroduced the problem?

**Comment by monops** [comment]
I tried it with the current build (11506) and it sort of works: It rarely
takes the input, but trying clicking multiple times (around 10-30 times),
sometimes you can get at least through to the menus.


Il giorno ven 1 gen 2021 alle ore 23:00 LuismaSP89 <notifications@github.com>
ha scritto:

**Comment by legolas119** [comment]
well, it is really strange, with same build, 11560, now it works!!! But a couple of hours ago, with same build, i had the issue...it is really strange!

I have another couple of issue, if you can help me:
1) during the opening, the fps dramatically drops down until 4/5 fps! is it possible to fix it? I decreased the resolution scale from 300% to 150%, but it didn't solved the issue.... I have a general question: as I'm using a fullHD monitor, is it useless to set Resolution scale = 300%? Is it better to set = 150%, even if I don't have performance issue?
2) during the initial tutorial the "sentence" with the tips, aren't complete, there is missing text as in the examples below:

https://i.postimg.cc/8C7RPBtc/Immagine-1.png
https://i.postimg.cc/DZs11fVK/Immagine-2.png
https://i.postimg.cc/SRf8tZNT/Immagine-3.png
is it possible to solve them?

thank you!

**Comment by legolas119** [comment]
please can anyone help me?
