### ISSUE TITLE
Differences in game boot process when booting via CLI vs from RPCS3 main screen for NPJB00073

### ISSUE THREAD

**Issue by SpiralCut** [RPCS3/rpcs3#5507]
When booting the Japanese PSN version of Braid (NPJB00073) I'm getting a trophy error (an error has occured. 8002291b) when I boot from the command line that I don't get when booting from the main RPCS3 menu.

Build 7657 for windows

Steps to reproduce;
1) Run NPJB00073 via the normal RPCS3 menu (see rpcs3_log1.zip for logs from my run
[rpcs3_log1.zip](https://github.com/RPCS3/rpcs3/files/2729541/rpcs3_log1.zip)
)
You should be able to play the game normally

2) Run NPJB00073 by dragging the EBOOT.BIN from NPJB00073\USRDIR onto rpcs3.exe (see rpcs3_log2.zip 
[rpcs3_log2.zip](https://github.com/RPCS3/rpcs3/files/2729546/rpcs3_log2.zip)

Edit: Booted from wrong folder when creating log2, use this log instead:
[rpcs3_log3.zip](https://github.com/RPCS3/rpcs3/files/2729578/rpcs3_log3.zip)

You should see the 8002291b error and be unable to play the game.

*You may need to have a save installed  If so, try this one:
[NPJB00073-SAVE.zip](https://github.com/RPCS3/rpcs3/files/2729547/NPJB00073-SAVE.zip)

P.S. I'm not sure if this affects other psn (or disc) titles yet as none of my other titles have been working correctly yet.

**Comment by 13xforever** [comment]
you're booting digital title from a dump, not from an install location, of course it won't work

**Comment by 13xforever** [comment]
I can confirm this. There's actually two problems:
1. all symlinks are resolved when the path is passed to the exe, which may result in a wrong path to the game eboot.bin
2. downloadable titles are always booted through `/root_host/`, even when the setting is not enabled

**Comment by cyberconan** [comment]
Hi! Same problem in last rpcs3 release with NPUB30625 - Virtua Fighter 5. I tried various paths combinations with root_host option but game only launch well from UI, never from command line.

**Comment by Dogway** [comment]
Same, "3rd Strike (NPEB0054)" fails to launch from CLI. (Win7 SP1, build 8331). With root_host enabled it achieves to show a few frames into the game before crashing.
[RPCS3_log.zip](https://github.com/RPCS3/rpcs3/files/3365953/RPCS3_log.zip)

**Comment by cyberconan** [comment]
Hi! More games than can't be opened from command line:
NPEB00341 - Prince of Persia
NPEB01828 - SoulCalibur II
NPUB30798 - NiGHTS into Dreams...

I saw than in UI, when launching from file menu instead double click:
Boot from ELF/SELF -> /home/karl/.config/rpcs3/dev_hdd0/game/NPEB00341/USRDIR/EBOOT.BIN -> Crash
Boot Game -> /home/karl/.config/rpcs3/dev_hdd0/game/NPEB00341/USRDIR -> Crash
Boot Game -> /home/karl/.config/rpcs3/dev_hdd0/game/NPEB00341 -> OK

I wish this can help rpcs3 developers. Thanks for your incredible work!!

**Comment by TVsIan** [comment]
Not at home to get my log, but Bomberman Ultra has the same issue. Booting from the GUI is normal, booting from CLI is a black screen (though if I show performance stats, it's definitely doing something).

I have RPCS3 installed on my small-ish boot/important programs SSD, and dev_hdd0/games is symlinked to a bigger hard drive. I also have my disc-based games symlinked individually (so dev_hdd0/disc/[game id] is linked to another folder elsewhere), but they and the other installed games I've tested are working so far.

Perhaps an alternate command line option where you could provide the game ID rather than the eboot.bin, and let rpcs3 look for a matching installed game might help with this particular issue?

**Comment by TVsIan** [comment]
I've found a workaround for the symlink issue - use a junction instead. It appears that doesn't translate the file's location to the "real" folder and passes along the linked location instead.

**Comment by SpiralCut** [comment]
I'm not sure what the correct way of handling this here is but this issue is NOT fixed as of build v0.0.8-9772-eb140c52.  I am still getting the same error with Braid Japan version (NPJB00073)
[rpcs3_log4.zip](https://github.com/RPCS3/rpcs3/files/4270313/rpcs3_log4.zip)

**Comment by sards3** [comment]
As 13xforever noted above (https://github.com/RPCS3/rpcs3/issues/5507#issuecomment-451903293), there were two separate issues.  The first was the issue with symlinks, which is the one that was fixed. The second was the host_root issue, which was not addressed by my pull request. I guess we should re-open this issue to track that second issue.

**Comment by SpiralCut** [comment]
@Nekotekina  please reopen this issue as it is confirmed not fixed by #7494 (I can’t reopen myself).

Thanks you sards3!

**Comment by Megamouse** [comment]
Please retest

**Comment by SpiralCut** [comment]
Retested using rpcs3-v0.0.15-11894-1b5cf118_win64 and issue still occurs with Braid JP
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6097134/RPCS3.log.gz)

**Comment by cyberconan** [comment]
For me now are working NPEB01828 - SoulCalibur II and NPUB30242 - Crazy Taxi. Thanks!

**Comment by Megamouse** [comment]
Please try with #9922

**Comment by SpiralCut** [comment]
Thanks for your help.  Still having the same issue with #9922 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6109685/RPCS3.log.gz)

**Comment by elad335** [comment]
Should be fixed by #10074

**Comment by elad335** [comment]
FTR the bug here was related to the use of '\' delimiter on Windows.

**Comment by Megamouse** [comment]
This is weird though. In my prior tests, the delimiter didn't make any difference.

**Comment by elad335** [comment]
Have you tried setting /dev_hdd0 path in config with such delimiter?

**Comment by Megamouse** [comment]
Probably not

**Comment by SpiralCut** [comment]
This is not fixed for me or at least it has a caused a new bug.  When launching Brain JP (NPJB00073) from the command line it gets to the end of "loading PPU modules" and then freezes.  I haven't been able to get to the game proper on #10074 when booting from the command line in Win 10.

Also, possibly related possibly not but I wasn't able to boot the game the first time I ran it through the GUI either but was able to get in after a restart.  That doesn't fix the CLI issue though.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6283591/RPCS3.log)

**Comment by elad335** [comment]
@SpiralCut Disable Native UI in System tab, your log suggests the underlying issue is fixed though.

**Comment by elad335** [comment]
@SpiralCut Also try disabling SPU cache in CPU tab.

**Comment by SpiralCut** [comment]
Disabling Native User Interface now I just get a white screen, disabling SPU cache didn't seem to fix anything but here's the log with both disabled.

Also FYI I have gotten other games to work (Disc version of 3D Dot Game Heroes JP for example)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6284272/RPCS3.log)
JP for example)

**Comment by elad335** [comment]
@SpiralCut Log says you're missing firmware, install firmware.

**Comment by SpiralCut** [comment]
Is firmware working on your side?  I've had 4.83 firmware installed in the past and it worked fine.  Based on your recommendation I installed 4.87.  The install worked fine but when I restart rpcs3 it says I'm missing firmware again.
[RPCS3_firmware_install.log](https://github.com/RPCS3/rpcs3/files/6285876/RPCS3_firmware_install.log)
[RPCS3_after_restart.log](https://github.com/RPCS3/rpcs3/files/6285878/RPCS3_after_restart.log)

**Comment by elad335** [comment]
Seems like a logging issue if /dev_flash is not mounted on default path. @Megamouse if you are interested to fix.

**Comment by Megamouse** [comment]
No. Idk what's the problem

**Comment by SpiralCut** [comment]
OK, I was able to get everything working again by reinstalling rpcs3.  I can confirm this fixes the issue with Braid so issue can be closed.  Thank you!
