### ISSUE TITLE
Ridge Racer 7[BCES00009] graphic issue

### ISSUE THREAD

**Issue by arcadee1977** [RPCS3/rpcs3#5731]
Trees are flickering and background maps are abnormal :

![未标题-1](https://user-images.githubusercontent.com/47111657/54487712-2145cd00-48d4-11e9-91f2-d0a04841a9c0.jpg)

The Sunset Heights Course is black screen(VK & OPENGL):

![未标题-2](https://user-images.githubusercontent.com/47111657/54487770-9dd8ab80-48d4-11e9-90b0-52e595bb46f8.jpg)

**Comment by AniLeo** [comment]
Missing RSX Capture

**Comment by legend800** [comment]
Tree rendering problem tracked here (with captures):
https://github.com/RPCS3/rpcs3/issues/5343

I can confirm the black screen issue on that one course.
![2019-03-17 09_32_06-Window](https://user-images.githubusercontent.com/20983844/54494461-ca220700-4897-11e9-8076-b856bafc7a0b.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2975422/RPCS3.log.gz)

**Comment by arcadee1977** [comment]
Time crisis 4 stage2 have the same issue (trees flickering):

![未标题-1](https://user-images.githubusercontent.com/47111657/54513320-0c2f7380-4992-11e9-94e9-058d2376d013.jpg)

**Comment by legend800** [comment]
The foliage issue is fixed on https://github.com/RPCS3/rpcs3/pull/5860

The issue where the screen goes VirtualBoy is still present (Sunset Height stage and some GP cinematics). 

![2019-04-18 22_55_58-Window](https://user-images.githubusercontent.com/20983844/56409554-72781200-622e-11e9-8097-6fa8fba7d205.png)

![2019-04-18 22_58_03-Window](https://user-images.githubusercontent.com/20983844/56409555-72781200-622e-11e9-8440-b527b9bcfe12.png)

**Comment by Shogun38** [comment]
Attached are the requested log and rsx cap.

[BCES00009_20190909105157_capture.zip](https://github.com/RPCS3/rpcs3/files/3591692/BCES00009_20190909105157_capture.zip)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3591693/RPCS3.log.gz)

**Comment by kd-11** [comment]
Not sure what is going on with this one, the capture seems to indicate everything is fine, but postprocessing looks to be messed up.

**Comment by legend800** [comment]
@kd-11 Yep, if you clear cache and load the stage, for a brief second it looks perfect then boom all red and stays that way. Same with cutscenes

**Comment by GrandGTA** [comment]
guys when will all of these bugs be fixed?
well the flickering trees are fixed in #5860
the Sunset heights and GP cinematics are still black screen
and if you enable 'disable async shader' the trees would flicker again
but fixes the Sunset Heights stage and the GP cinematics
also it crashes when i scroll too fast on the special machines (it crashes at the 490b or G00)
and also it lags on a part of the Lakeshore courses
where there are confetti in the beggining of the tunnel..

so here are we waiting to be fixed:
-flickering trees
-Sunset Heights and Cutscenes
-lag on Lakeshore courses
-crashes

**Comment by legend800** [comment]
There's no time table when the devs will get to a defect. 

I tried the latest build and "disable async shader" (even cleared shader cache) and it does not affect the trees or the red Sunset Heights/cinematic. I'm on Nvidia.

I can't test the special machine crash (not unlocked), but there's no lag on Lakeshore Drive for me (but didn't see any confetti), so it's just your machine (no bug). Regardless, this github issue is about gfx issues, don't add other things to the thread.

**Comment by GrandGTA** [comment]
well that leaves us to the issue..
WHEN WILL THE ANNOYING RED SCREEN BE FIXED?!

**Comment by 13xforever** [comment]
please stop spamming with requests; it will be fixed when it will be fixed
the louder you scream, the faster you will be banned from the repo, that's the only thing you can change

**Comment by AniLeo** [comment]
Maybe it should not be fixed in purpose for some time 🤔

**Comment by GrandGTA** [comment]
wait a minute
legend800 said if you clear caches it will look perfect and then red screen again
you know why its becuz if you load a stage, it will create a shader cache causing it to red screen again
if they just make a feature that will keep erasing the cache each mililisecond,
probably it will work
yeah so all we need is a feature to keep erasing the caches automatically

**Comment by Asinin3** [comment]
You mean the "feature" that already exists called "Disable On-Disk Shader Cache" found on the settings > advanced tab?

But it doesn't matter, this is still a valid issue report if it requires cleaning shaders every run, just need to be patient and wait for a fix..

**Comment by GrandGTA** [comment]
since everyone is lazy of fixing these bugs
lets just be patient and wait till the RPCS3 team will fix this
lets bet all our hopes for this
for now we just wait

**Comment by RainbowCookie32** [comment]
> since everyone is lazy of fixing these bugs
Pretty easy to just point at issues and call people lazy huh? Because all issues have the same overall priorities, they are all super easy to fix, and we have 500 devs working on the emu.

Oh wait, that's not the case!

**Comment by AniLeo** [comment]
I'm gonna get a severe case of ligma from reading this issue

**Comment by GrandGTA** [comment]
so we have 500 developers working on the emulator
lets just wait like what im doing right now
im waiting for this and NFS Heat crack
so patience and hope is our only key
lets just hope 1 of the developers see this issue

**Comment by GrandGTA** [comment]
also tell me how to install the DLC's
i have the PKG file for the DLCs and the 3D license
let me know

**Comment by AniLeo** [comment]
That thing you smoked
Where can I buy it?

**Comment by jokoputera** [comment]
> There's no time table when the devs will get to a defect.
> 
> I tried the latest build and "disable async shader" (even cleared shader cache) and it does not affect the trees or the red Sunset Heights/cinematic. I'm on Nvidia.
> 
> ![2019-11-02 21_59_41-FPS_ 59 98 _ Vulkan _ 0 0 7-9058 _ Ridge Racer7 3D License Ver (Full Game) NPUB](https://user-images.githubusercontent.com/20983844/68080760-de7f2980-fdbe-11e9-97f5-ae6a9c87c501.png)
> 
> I can't test the special machine crash (not unlocked), but there's no lag on Lakeshore Drive for me (but didn't see any confetti), so it's just your machine (no bug). Regardless, this github issue is about gfx issues, don't add other things to the thread.

basically, recent build make it Ingame from Playable (according to Compatibility List History), right? so what version does this game playable?

**Comment by GrandGTA** [comment]
is it just me?
or that it crashes when i press a button??

**Comment by kd-11** [comment]
Red tint issue is solved. You still need to disable async compiler for the first run, there are some shaders that are not cached when it is enabled. A fix for that issue is being handled separately.

**Comment by GrandGTA** [comment]
okay, im back but dont throw some bad stuff in this comment
im just going to lay down the bugs i still experience and explain them further

-Trees flickering (NVidia will flicker, AMD wont.. i will recommend AMD to fix this)

Other than graphics problem:
-The special machine crash (in Machine Connector, when i scroll fast to the special cars (3D view), it crashes... I think the reason is that RPCS3 cannot handle fast loading shaders on low end graphics card while on high end, it will not crash.. Quadro K620 is my graphics card so that sums it up)

-AV Player desync (the pre-recorded Replay will desync during start while your own replays are still working as normal... try the PPSSPP Ridge Racer, same happens... but its not much of a problem so you can cut the crap)

**Comment by GrandGTA** [comment]
Ok guys, I fixed everything about this game... No more stuff i can report... I got every single fix for my problems...

I found an AMD graphics card on my stuff and change it then trees stopped flickering... I changed my US copy into a JP release by changing the serial code on the PARAM.SFO file.. The result of changing the PARAM file is the DLCs working properly... I was right about the thing on the part where i scroll onto the special machines and then it crashes... It was the gpu's fault... Now the thing with the AV Player desync will never be fixed.. Because as i said.. Same thing happens on RR PPSSPP... And was never fixed since... This will be my last comment on the RPCS3 Community... Ain't coming back again... Don't respond to me again..... Peace...

**Comment by jokoputera** [comment]
Tried Ridge Racer 7 Sunset Height Red Tint issue and background flickering solved by clearing cache using latest master. You may close this thread.

**Comment by madmax2000** [comment]
> Red tint issue is solved. You still need to disable async compiler for the first run, there are some shaders that are not cached when it is enabled. A fix for that issue is being handled separately.

Still not fixed with Master from 16.01.2025. But this works fine. Just choose one of the not async compilers for the first start of the game. to fill the cache After that you can change it back to default. Fixed the black screen on Sunset Heights.

Thank you!
