### ISSUE TITLE
Gran Turismo 6 Colors Problems

### ISSUE THREAD

**Issue by Wizzy2018** [RPCS3/rpcs3#5874]
Hello guys :)

RPCS3 v0.0.6-8002
CPU Ryzen 7 1700
RAM DDR4-2400Mhz
GPU RX 470 4Gb

Gran Turismo 6 runs pretty well^ But colors are flashing like crazy.Blue Red Yellow all around.
Here is a picture i hope KD-11 can fix it . ( KD-11 LOVE YOU BROO YOU ARE MY HERO <3 )

![FPS_ 16 73 _ Vulkan _ 0 0 6-8002 _ Gran Turismo®6  BCES01893  21-Apr-19 12_39_03](https://user-images.githubusercontent.com/44261686/56468918-1df1b400-6433-11e9-8b01-d1e3acfc7bc8.png)

![FPS_ 14 08 _ Vulkan _ 0 0 6-8002 _ Gran Turismo®6  BCES01893  21-Apr-19 14_09_41](https://user-images.githubusercontent.com/44261686/56469845-44b5e780-643f-11e9-8b79-8e0f045fb4b1.png)

Here is a log too
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3101118/RPCS3.log.gz)

---

After updating game above 1.02 version a error with memory dissapeard but still some 3d cube errors on log here it is and screen in race is black with only text showing.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3101239/RPCS3.log.gz)

**Comment by Wizzy2018** [comment]
after i update a game above 1.02 version a error with memory dissapeard but still some 3d cube errors on log here it is and screen in race is black with only text showing.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3101239/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Known issues, but upload RSX captures for the visual glitches.

**Comment by Wizzy2018** [comment]
Can you tell me how to do it?? I take a screenshot from log console??

**Comment by RainbowCookie32** [comment]
Go to View->Show debugger. When you can see the graphical issues in the game, hit the RSX Capture button in the debugger

**Comment by Wizzy2018** [comment]
After i hit that button do i have a file or??
Here is a screnshoot
![RPCS3 0 0 6-8002-3a5f4ed7 Alpha 21-Apr-19 20_27_41](https://user-images.githubusercontent.com/44261686/56474040-11418000-6474-11e9-97a8-22b7ab8caff8.png)

**Comment by Wizzy2018** [comment]
Is this a file you need?? I am little noob around this :D Sorry if i need more help :)
[BCES01893_20190421203316_capture.zip](https://github.com/RPCS3/rpcs3/files/3101480/BCES01893_20190421203316_capture.zip)

**Comment by Wizzy2018** [comment]
Here is some screenshoots

![RPCS3 0 0 6-8002-3a5f4ed7 Alpha 21-Apr-19 20_44_55](https://user-images.githubusercontent.com/44261686/56474179-78603400-6476-11e9-9321-1f820025381e.png)

**Comment by RainbowCookie32** [comment]
I only get a black screen when running your capture. Make sure to do it when the game is running and the graphical issue is being showed on screen

**Comment by Wizzy2018** [comment]
ok so i send again a capture file right??

**Comment by RainbowCookie32** [comment]
Yes

**Comment by Wizzy2018** [comment]
Uf it will be hard cuz when i press capture RSX i got a error and can't capture it look
![RPCS3 0 0 6-8002-3a5f4ed7 Alpha 21-Apr-19 21_16_51](https://user-images.githubusercontent.com/44261686/56474493-fc1c1f80-647a-11e9-8f36-888489166a70.png)

**Comment by Wizzy2018** [comment]
Wait need to show you what happens

**Comment by AniLeo** [comment]
Don't flood this issue, go on our Discord server and ask for assistance there

**Comment by Wizzy2018** [comment]
Here it is what happend i got this error line when pressing RSX capture
F {PPU[0x1000002] Thread (_gcm_intr_thread) [0x00b7ba80]} MEM: Access violation reading location 0xc

**Comment by Wizzy2018** [comment]
Here is a screen shot to
![FPS_ 13 63 _ Vulkan _ 0 0 6-8002 _ Gran Turismo®6  BCES01893  21-Apr-19 21_22_05](https://user-images.githubusercontent.com/44261686/56474539-9c724400-647b-11e9-9edb-62bc6fb896b1.png)

Sorry Ani :(

**Comment by kd-11** [comment]
Color bug is fixed by https://github.com/RPCS3/rpcs3/pull/6179

**Comment by Wizzy2018** [comment]
It's not fixed for me. Having same color issues and now i have this error.Spu cache building stops at 99% when i want to boot GT6.

**Comment by kd-11** [comment]
The color fix has not yet been merged.

**Comment by Wizzy2018** [comment]
Oh sorry KD-11 my bad ;D Removing SPU cache fixes stucking at 99% but i need to do it every time i boot GT6.And i have this error now after i purschase a car F {RSX [0x1496500]} RSX: class std::runtime_error thrown: GetAddress(offset=0x3695f80, location=0x1): RSXIO memory not mapped
(in file c:\projects\rpcs3\rpcs3\emu\rsx\rsxthread.cpp:67)

**Comment by biz4race** [comment]
I didn't understand how solved?
