### ISSUE TITLE
Ninja Gaiden Sigma Hard Freeze (present in Ver. 8151 onwards)

### ISSUE THREAD

**Issue by EchoTM** [RPCS3/rpcs3#6010]
This seems to be an issue with the TSX Instructions.
(I've tested the version right before that, for the record)
After 8151, Ninja Gaiden Sigma crashes ~30 seconds after it starts, it hard-freezes, I even get in-game sometimes. The window becomes unresponsive and the game is stuck (I am not using fullscreen). This happens EXCLUSIVELY while using TSX Instructions. 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3214362/RPCS3.log)

**Comment by adrianocolvero** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3218616/RPCS3.log)

I'm having issues too, i attached a Guitar Hero 6 log
It freezes at a black screen while starting, used to work fine with TSX forced, but now works only disabling TSX.

So far, Guitar Hero 5 crashs the emulator at start or freezes too
Ridge Racer 7 Crashes the emu just right after the menus/loading screen. 
Rock Band 2 opens and work but after the start screen there's no sound

All of them runs fine with TSX disabled.
Used to work with TSX before the #5993 PR.

I7 4771
Windows 10

**Comment by Whatcookie** [comment]
Ninja gaiden sigma was fixed with https://github.com/RPCS3/rpcs3/pull/6020

**Comment by rajkosto** [comment]
But MGS2/MGS3 in MGS HD Collection will still have a small % to get stuck at black screen (with only logo pulsating) when they load a new area/cutscene if TSX is enabled. This is on a CPU with TSX, not TSX-FA too. With TSX disabled the games are completely playable.

**Comment by AniLeo** [comment]
Closing as NGS issue is fixed. There is #6028 for the other TSX related regressions.
