### ISSUE TITLE
Beyond Good & Evil - [NPEB00435] - Broken photos and weird rendering face.

### ISSUE THREAD

**Issue by mavethee** [RPCS3/rpcs3#6160]
RPCS3 v0.0.6-8329-ad10eb39 Alpha | HEAD | Firmware version: 4.84
Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz | 4 Threads | 7.65 GiB RAM | AVX+
![unknown](https://user-images.githubusercontent.com/47083527/60707654-861d4580-9f0c-11e9-89d5-4a54e2b8a311.png)
Broken photos present in game for some builds already.
Not sure which PR reggressed it, issue is still a thing in 8330.
![image](https://user-images.githubusercontent.com/47083527/60708167-b7e2dc00-9f0d-11e9-915d-ea9f3ec5de38.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3361751/RPCS3.log.gz)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3361732/RPCS3.log.gz)
And something is definitely wrong with his face.
RPCS3:
![unknown (2)](https://user-images.githubusercontent.com/47083527/60711785-e95fa580-9f15-11e9-9768-f4d281b09092.png)
PS3:
![unknown (1)](https://user-images.githubusercontent.com/47083527/60711610-92f26700-9f15-11e9-8c10-827f94594b90.png)

**Comment by 13xforever** [comment]
There are a lot of transparency-like rendering issues on current builds (e.g. camera lens in the photo collection, most models in the cutscenes), and also weird single-color pixels at the model edges (R/G/B).

Black photos was always an issue afaik, everything else is a regression and needs to be triaged to the appropriate builds.

**Comment by mavethee** [comment]
And here...
![image](https://user-images.githubusercontent.com/47083527/60713968-570dd080-9f1a-11e9-9017-2892a95409ad.png)

**Comment by mavethee** [comment]
RSX Captures:
[captures.zip](https://github.com/RPCS3/rpcs3/files/3362433/captures.zip)

**Comment by MSuih** [comment]
Black photos are issue in other games (f.ex. all 3 Skate games) as well. My guess is that there's some syscall which is supposed to capture the rendered frame and it's not properly implemented right now.

**Comment by mavethee** [comment]
Sky completely broke 🤔 
https://media.discordapp.net/attachments/272875751773306881/598159809140752395/unknown.png?width=1133&height=671
RSX Capture:
[NPEB00435_20190709163218_capture.zip](https://github.com/RPCS3/rpcs3/files/3373479/NPEB00435_20190709163218_capture.zip)

**Comment by Emulator-Team-2** [comment]
@mavethee 
Sky is fixed by #6177.

**Comment by mavethee** [comment]
Sky is fixed, black textures seems to be also fixed. Currently, game seems to be heavy and softlock hella easy.
Screen:
https://media.discordapp.net/attachments/485204327800242177/688092453848350725/unknown.png?width=1154&height=677
Log:
https://cdn.discordapp.com/attachments/485204327800242177/688092678822428675/RPCS3.log.gz

**Comment by TheCatCoder** [comment]
There is still a problem in Skate 3. The magazine photos that you take don't appear like they should. Is there a setting that fixes this?
![Photo Missing](https://user-images.githubusercontent.com/11698858/86865940-3debb280-c08d-11ea-8490-9f7866cc71b3.png)

**Comment by MSuih** [comment]
Enable Write Color Buffers.

**Comment by Scalee** [comment]
It looks like it's drawing lower poly models based on camera distance. The closer you move the camera the less polygons become visible. This same effect is happening to the eyes, which causes them to become full black.
![screenshot-2020_08_03_14_05_38](https://user-images.githubusercontent.com/1917337/89180934-05a79900-d593-11ea-97b2-68ec7080daa1.png)
![screenshot-2020_08_03_14_06_22](https://user-images.githubusercontent.com/1917337/89180938-06402f80-d593-11ea-971a-10e092228ff0.png)
![screenshot-2020_08_03_14_07_05](https://user-images.githubusercontent.com/1917337/89180941-06d8c600-d593-11ea-95d8-34d814be4b8c.png)

Full camera distance:
![screenshot-2020_08_03_14_07_27](https://user-images.githubusercontent.com/1917337/89180943-07715c80-d593-11ea-9747-8a31815104ec.png)

Increasing resolution scale seems to reduce the problem, but costs a ton of performance.

Full camera distance @ 400% resolution scale:
![screenshot-2020_08_03_14_13_13](https://user-images.githubusercontent.com/1917337/89181241-967e7480-d593-11ea-89ba-75a4a71d2878.png)

**Comment by digitaldude555** [comment]
But did you enable write color buffers.

**Comment by Scalee** [comment]
Write colors buffers looks like this @ 100% resolution scale:

Full camera distance:
![screenshot-2020_08_03_15_31_07](https://user-images.githubusercontent.com/1917337/89188181-9637a680-d59e-11ea-8a7a-559464f37f89.png)

Medium:
![screenshot-2020_08_03_15_31_42](https://user-images.githubusercontent.com/1917337/89188183-96d03d00-d59e-11ea-81ad-860b68eec5e5.png)

Up close:
![screenshot-2020_08_03_15_32_03](https://user-images.githubusercontent.com/1917337/89188185-9768d380-d59e-11ea-966d-dc076dbb699e.png)

Let me know if i can help in any other way.

**Comment by Scalee** [comment]
Finished the game without game breaking issues.
Only issues are graphical, The black and polygon models posted above and black pictures.

**Comment by Yahfz** [comment]
@Scalee still an issue?

**Comment by Scalee** [comment]
> 

Default settings yes, Enabling write color buffers seems to fix the issues on the character models and the black eyes and the sky. But seems to cause different issues on other sprites, but these seems to intermitted leaving the area and returning seemed to resolve the issue, Haven't tested further.

Default settings:
![Screenshot 2022-02-20 115854](https://user-images.githubusercontent.com/1917337/154839272-62605761-ce8b-47e6-9fe1-008c787c53a6.png)

Plant sprites (and camera GUI sprites, not in picture)
![Screenshot 2022-02-20 111253](https://user-images.githubusercontent.com/1917337/154839273-110384b9-0017-4e83-833b-6757163df300.png)

**Comment by AniLeo** [comment]
Write Color Buffers is the accurate setting so if it fixes the issue then it's solved. I've played the game for a few hours some time ago and I haven't seen any corruption, needs retesting because I think this issue can be closed

**Comment by JimScript** [comment]
Isn't the broken textures also tracked on issue #10960?

**Comment by AniLeo** [comment]
We can close this one then and track the remaining issues there

**Comment by TigiHof** [comment]
Why was this issue closed? The broken photos are not fixed (I just checked). They never worked and AFAIK this problem was never even looked into. Please reopen!

**Comment by AniLeo** [comment]
Photos are still working just fine as they did 2 years ago when I played half of the game to test. As I said above, requiring accurate settings such as Write Color Buffers to have working photos is not a bug.

`RPCS3 v0.0.29-15588-b5dac0c3 Alpha`

**Animal photo**
![NPEB00435_screenshot_2023_09_03_21_25_56](https://github.com/RPCS3/rpcs3/assets/10283761/921a1552-d417-4335-abb8-440cab5ed0a6)
![NPEB00435_screenshot_2023_09_03_21_26_05](https://github.com/RPCS3/rpcs3/assets/10283761/4ad64f27-f537-41d3-8388-f1fba2f919d8)
![NPEB00435_screenshot_2023_09_03_21_26_14](https://github.com/RPCS3/rpcs3/assets/10283761/ddf24d85-502c-4c36-a0ac-6d1e51df3f70)


**Personal photo**
![NPEB00435_screenshot_2023_09_03_21_26_57](https://github.com/RPCS3/rpcs3/assets/10283761/d4625b0d-bbdb-42cb-bc32-dbe346af7bba)
![NPEB00435_screenshot_2023_09_03_21_27_16](https://github.com/RPCS3/rpcs3/assets/10283761/74e0e210-03b0-434f-8b4d-e512c2bcdc2d)

**Comment by Fewnity** [comment]
@AniLeo Mhhh the Write Color Buffers fix does not work with me :/ I'm getting black pictures. Is there another setting to check?
