### ISSUE TITLE
Heavenly Sword [BCES00078] & Resistance: Fall of Man [BCES00001] Out of video memory (VRAM) Problem

### ISSUE THREAD

**Issue by Termulator** [RPCS3/rpcs3#6253]
RPCS3 v0.0.6-8411-85b1152e Alpha
Heavenly Sword [BCES00078] & Resistance: Fall of Man [BCES00001]
Out of video memory (VRAM) Problem, happens with Vulkan but works with opengl at 4k.
Using lower resolution or strict rendering will prevent the crashes as long vram is not filled up. Tested on 1080 ti & 2700X AMD with 16 gb ram.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3421453/RPCS3.log.gz)

**Comment by kd-11** [comment]
Very likely fixed by https://github.com/RPCS3/rpcs3/pull/6376. Retest.

**Comment by Termulator** [comment]
Sadly, it didnt fix it though. Still some overflow problems.
[RPCS3.log.heavenly sword.gz](https://github.com/RPCS3/rpcs3/files/3519214/RPCS3.log.heavenly.sword.gz)
[RPCS3.log.fallofmen.zip](https://github.com/RPCS3/rpcs3/files/3519215/RPCS3.log.fallofmen.zip)

**Comment by kd-11** [comment]
Try the DMA pull request then.

**Comment by Termulator** [comment]
The problems still persits with the dma pr. 
[RPCS3.log.fallofman.dma.gz](https://github.com/RPCS3/rpcs3/files/3529466/RPCS3.log.fallofman.dma.gz)
[RPCS3.log.heavenly sword.dma.zip](https://github.com/RPCS3/rpcs3/files/3529467/RPCS3.log.heavenly.sword.dma.zip)

**Comment by kd-11** [comment]
Tbf you are using 500% scaling which gives an effective resolution around 6400x3600 making the display output buffer alone be around 90MB and common rgba16 targets coming in at around 180MB a piece. A single shadow map would be almost half a gigabyte at that stage.
While the memory manager can be made a lot more aggressive to avoid this, the huge memory requirement is kinda expected.

**Comment by lainiwaku** [comment]
i suppose it can be closed ~ !?

**Comment by lainiwaku** [comment]
well not happening on resistance 1, but still happen on heavenly sword, i monitored vram used with afterburner, game use less than 2gb then when a kind of cinematic start up, Vram get instantly above 8gb 
![MSI Afterburner  03_03_2020 09_48_45](https://user-images.githubusercontent.com/1077909/75758690-baaffe00-5d34-11ea-96ea-6fcb24c6dea6.png)

**Comment by lainiwaku** [comment]
it happen less on 100% scale,  but since every PiP cinematic, memory  is not free up, little by little Vram grown, and end up crashing

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/7758

**Comment by lainiwaku** [comment]
seem like  it didn't fix it , i made  a video hoping  it could help 
normal cinematic don't increase Vram, only PiP(picture in picture) cinematics, and memory arn't freeup after
happen at 0:14 then 19:15 then at 20:55 Vram going crazy
https://www.youtube.com/watch?v=Jlqs5ABHZFc&feature=youtu.be

**Comment by kd-11** [comment]
Definitely more severe than expected, not sure what would trigger that behaviour. Check if using 'force cpu blit' debug option coupled with write color buffers option fixes the problem.

**Comment by lainiwaku** [comment]
still the same

**Comment by lainiwaku** [comment]
@kd-11 i made a video  where we can see more clearly 
at 0:29 the "PiP" cinematic start, Vram jump high
at 0:37 the "PiP" cinematic stop, Vram stay high

when an other PiP  cinematic start, Vram got high again without freeing memory at the end of the PiP.
it goes like that until the Vram got saturated, then crash with out of Vram error 

i know you may be busy fixing more important stuff, but i just wanted to explain it to be more clear to understand

**Comment by lainiwaku** [comment]
@kd-11  the bug is still there,  but i now have an error on the log exactely when the PiP cinematic start and bug begin 

`E {RSX [0x013c4bc]} RSX: Blit request denied because the destination region does not fit!
E {RSX [0x083bcac]} RSX: Blit request denied because the destination region does not fit!
E {RSX [0x083b684]} RSX: Blit request denied because the destination region does not fit!
E {RSX [0x014ab64]} RSX: Blit request denied because the destination region does not fit!
E {RSX [0x07dd944]} RSX: Blit request denied because the source region does not fit!
E {RSX [0x07df744]} RSX: Blit request denied because the source region does not fit!
E {RSX [0x00ed59c]} RSX: Blit request denied because the source region does not fit!
E {RSX [0x07f2a90]} RSX: Blit request denied because the source region does not fit!
E {RSX [0x00f4a74]} RSX: Blit request denied because the source region does not fit!
E {RSX [0x07e5fb4]} RSX: Blit request denied because the source region does not fit!`

**Comment by kd-11** [comment]
I'm going to need saves for this one.

**Comment by lainiwaku** [comment]
[BCES00078-GAMEAUTOSAVE.zip](https://github.com/RPCS3/rpcs3/files/4707711/BCES00078-GAMEAUTOSAVE.zip)
here my savefile 

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4707719/RPCS3.log)
i send you most recent log also

**Comment by kd-11** [comment]
Thanks, instant crash, very helpful.

**Comment by lainiwaku** [comment]
well my save work  on both custom config and default config, i don't know much why it not  working, maybe because  i updated the game ?

**Comment by kd-11** [comment]
I wasn't being facetious, it really does work and shows the crash very well within a few seconds. During a bug fixing investigations, it is likely to attempt reloading the scenario dozens of times, so getting crashes quickly is a good thing.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/8309.
The game still generates an absurd amount of images per frame so you still need decent VRAM. 720p for example consumes 3GB of VRAM during the PiP sections. The memory isn't leaked though, we're releasing the data, just not fast enough to offset the demands. After the cutscene is over, equilibrium is restored and the allocation does go down significantly to around 1.2GB. I could in theory make the allocation threshold used to detect overallocation dynamic, but it should work just fine as it is right now. There is a balancing act between being aggressive with cleanup and keeping performance good which is why I'm allowing VRAM to grow to 3GB at 720p.

**Comment by web1018** [comment]
Is this a possible fix only for Heavenly sword? or does it also include Resistance: Fall of Man?

**Comment by RinMaru** [comment]
> Fixed by #8309.
> The game still generates an absurd amount of images per frame so you still need decent VRAM. 720p for example consumes 3GB of VRAM during the PiP sections. The memory isn't leaked though, we're releasing the data, just not fast enough to offset the demands. After the cutscene is over, equilibrium is restored and the allocation does go down significantly to around 1.2GB. I could in theory make the allocation threshold used to detect overallocation dynamic, but it should work just fine as it is right now. There is a balancing act between being aggressive with cleanup and keeping performance good which is why I'm allowing VRAM to grow to 3GB at 720p.

is there a possibility that the VRAM issue will be lessened with more optimization's or are we all going to have to wait for the GPU shortage to cool down? im stuck with an RX480 4GB for awhile and im noticing most games cross the 4GB threshold. Whats causing the vram to be filled up so much anyways when compared to ps3? is there a more efficient way of storing things? just curious is all.

**Comment by Asinin3** [comment]
Turn Anti-Aliaising to off in RPCS3's settings and you will reduce vram consumption significantly. Also don't use extremely high res scale with Heavenly Sword, the Picture-in-Picture scenes will take up a lot of vram. I don't recommend you go over 200% scaling with a 4gb card even with AA off.

**Comment by kd-11** [comment]
> > Fixed by #8309.
> > The game still generates an absurd amount of images per frame so you still need decent VRAM. 720p for example consumes 3GB of VRAM during the PiP sections. The memory isn't leaked though, we're releasing the data, just not fast enough to offset the demands. After the cutscene is over, equilibrium is restored and the allocation does go down significantly to around 1.2GB. I could in theory make the allocation threshold used to detect overallocation dynamic, but it should work just fine as it is right now. There is a balancing act between being aggressive with cleanup and keeping performance good which is why I'm allowing VRAM to grow to 3GB at 720p.
> 
> is there a possibility that the VRAM issue will be lessened with more optimization's or are we all going to have to wait for the GPU shortage to cool down? im stuck with an RX480 4GB for awhile and im noticing most games cross the 4GB threshold. Whats causing the vram to be filled up so much anyways when compared to ps3? is there a more efficient way of storing things? just curious is all.

There will always be a cost to aggressive memory management, the cost to performance is going to be measurable due to how rpcs3 and vulkan work. Basically, you do not want to walk down the deallocation path mid-frame, so we defer all cleanup to the end of the frames. If you have a good CPU MTRSX can be a real help for this purpose in such titles as the offloader can handle cleanup in parallel with the main renderer, but I still really tried to be conservative with how much stuff is kept around.
The biggest challenge is that all these slices of virtual VRAM need to be committed before things can be deleted, which is an expensive process requiring compute shaders and GPU transfer operations. Nothing can be done about this part, the memory has to go somewhere else before deletion can happen.
