### ISSUE TITLE
Bioshock freezes on loading most save games

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#6297]
You can save the game anytime, but when you load from most saves (particularly anything after the first "Welcome to Rapture" chapter), either the loading dial keeps spinning and never goes ingame, or it appears to load and then immediately RPCS3 freezes.  

Using commit f0bd0b5a7c25cd33194c996f2a5b9c1cb2f687dd with NPUB30393, under Linux Mint 19.2 x64 with 4.18 kernel.

Logs: [RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/3463026/RPCS3.log.zip)

**Comment by digitaldude555** [comment]
Still an issue.

**Comment by Darkhost1999** [comment]
Still happens. As more recently indicated on forums.
Playing the game past the medical pavilion or loading a game save after the medical pavilion does not work on RPCS3.

**Comment by Darkhost1999** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8371549/RPCS3.log.gz)
Still happens.
Playing the game past the medical pavilion or loading a game save after the medical pavilion does not work on RPCS3 yet.

**Comment by Darkhost1999** [comment]
Medical Pavilion is now accessible 
![BioShock  NPUB30393 PM](https://user-images.githubusercontent.com/60384196/188953368-391df666-4a5a-4b7c-872f-d908202f74c2.png)

**Comment by Megamouse** [comment]
Does this mean the issue is fixed?

**Comment by Darkhost1999** [comment]
Recent tests indicated that I might've gotten lucky. I need to check my config, the build version, and confirm it isn't just regressed again. Because this issue isn't resolved yet on latest master.

**Comment by Megamouse** [comment]
Test again

**Comment by Shoegzer** [comment]
I don't have this ttile for testing anymore.  @Darkhost1999 can you please confirm if latest master (with merged PR #13492) resolved this?

**Comment by Darkhost1999** [comment]
![image](https://user-images.githubusercontent.com/60384196/224421210-58430c1b-4778-45ca-979c-4ba8e929f98e.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10945818/RPCS3.log.gz)
This does not seem fixed. I waited 3 minutes

**Comment by Darkhost1999** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11008814/RPCS3.log.gz)
TTY.log
```
EDGE ZLIB ERROR: inflate error (-3)
EDGE ZLIB ERROR: Stream decompressed to size different from expected (0 != 32768)
EDGE ZLIB ERROR: edgeZlibInflateRawData failed (-3)
```

**Comment by Darkhost1999** [comment]
Needs consistency testing
<img width="1280" alt="Screenshot 2023-08-16 122806" src="https://github.com/RPCS3/rpcs3/assets/60384196/abf5a261-9ef8-4dd1-a487-30ccdfff1929">
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12362011/RPCS3.log.gz)

**Comment by Darkhost1999** [comment]
[BLUS30166-20240326_221927.zip](https://github.com/RPCS3/rpcs3/files/14767122/BLUS30166-20240326_221927.zip)
Save file for improved testing. This issue is unresolved and ongoing. My 1st try I made it to the medical Pavillion my 2nd try endless loading screen.

**Comment by digant73** [comment]
@Darkhost1999 still an issue?

**Comment by Darkhost1999** [comment]
Yes, finishing welcome to rapture and loading the medical pavilion is still inconsistent. Having a significantly low chance of accessing the medical pavilion in your first playthrough. Averaging almost 12 attempts just to get through that 1 door then works fine after that till the end game.

**Comment by moozhub** [comment]
I can confirm on my end as well, endless loading when trying to load the Medical Pavilion level. Haven't been successful in force closing and getting passed the loading screen yet, tried probably around 10 times at this point.

RPCS3 Version: 0.0.38-18382-a3f7c0d6 Alpha | master

**Comment by Darkhost1999** [comment]
I've still got about a 3/16 success rate. I haven't found any consistent settings to aid in the efforts.
I also experimented with some savedata theories from back when Oblivion autosave had issues. They didn't help.

**Comment by alexconsole04** [comment]
Weird thing is that this happens in 1.00 too. Wiki says its related to the ng+ loadout when the game didn't initially release with ng+ in mind. What else is causing this issue to occur?

**Comment by Darkhost1999** [comment]
I don't know why it says ng+ at all. I've never attempted that feature.

**Comment by moozhub** [comment]
That's indeed strange that you all are mentioning the NG+ stuff, I started a new game and the first option in the menu was a prompt for new game plus even though I never played. The sub menu was greyed out (second being regular new game). Memory might be bad but I don't recall the menu being set up that way.

**Comment by Darkhost1999** [comment]
The PS3 only has that feature through DLC I don't have

**Comment by moozhub** [comment]
> The PS3 only has that feature through DLC I don't have

Ok, makes sense now.

**Comment by moozhub** [comment]
Any other ideas on how this one can be fixed? Any addition details or logs that I can provide?

**Comment by alexconsole04** [comment]
Testing more on 1.00, the game straight up crashes with an unknown stop code error when trying to access Medical.
As I mentioned before, the game never had NG+ when it first released. May need to test with my save from my PS3 since I completed the game on there a while back.

[RPCS3.log.gz](https://github.com/user-attachments/files/24072383/RPCS3.log.gz)

**Comment by Darkhost1999** [comment]
<img width="960" height="429" alt="Image" src="https://github.com/user-attachments/assets/6f1c441b-9c8c-4337-8a3e-fdcde39c4ff0" />
RPCS3 needed to be killed via task manager upon closing and failed to load the medical pavilion.

https://github.com/user-attachments/assets/ffe1e89e-5fcb-45e1-8ae4-29afdf61970c

[RPCS3.log.zip](https://github.com/user-attachments/files/25622726/RPCS3.zip)

**Comment by alexconsole04** [comment]
Did some more testing and looked at the TTY. the game is seemingly failing to decompress the game data for Medical Pavilion (and possibly later levels if it has said issue.)

EDGE ZLIB ERROR: inflate error (-3)
EDGE ZLIB ERROR: Stream decompressed to size different from expected (0 != 32768)
EDGE ZLIB ERROR: edgeZlibInflateRawData failed (-3) 

This is what is printed when attempting to load medical and can vary, but always the same issue. Tested with PPU Interpreter and the game loaded the level without any issue. The zlib decompression is likely handled by the PPU and is completely broken on LLVM. Done this 6 seperate times and each time loaded with succession, albeit with slower loading times.

<img width="2560" height="1392" alt="Image" src="https://github.com/user-attachments/assets/02a071de-ed36-4891-b7fb-c95dd7418c14" />

This does not seem to be related to NG+ but rather LLVM inaccuracy that causes the zlib thread to fail.

[Interpreter.log.gz](https://github.com/user-attachments/files/27464417/RPCS3.log.gz)

[LLVM.log.gz](https://github.com/user-attachments/files/27464451/RPCS3.log.gz)

EDGE ZLIB ERROR: Stream decompressed to size different from expected (8 != 32768)
EDGE ZLIB ERROR: Stream decompressed to size different from expected (16175 != 32768)
There were other instances where it seems the game managed to decompress some of the data before failing and causing said infinite loading screen.

Anyone in this thread, can you confirm this?

**Comment by alexconsole04** [comment]
Managed to beat the entire game from start to finish and every level loaded fine. This issue is specific to loading a save in Medical Pavilion.

**Comment by alexconsole04** [comment]
Tested 1.00 as the game will always output the unknown stop code crash loading into medical. PPU Interpreters also bypasses this issue. There is a possibility that the game will load the level on LLVM, but it's very rare.

<img width="2560" height="1392" alt="Image" src="https://github.com/user-attachments/assets/b62e35f4-fc46-4b5c-932b-9d2cb272ee4a" />

[Interpreter.log.gz](https://github.com/user-attachments/files/27564694/RPCS3.log.gz)

[LLVM.zip](https://github.com/user-attachments/files/27564736/RPCS3.zip)
