### ISSUE TITLE
[BLES00759] Blur game with RSX issues

### ISSUE THREAD

**Issue by jenci8888** [RPCS3/rpcs3#6356]
**First Issue:**
When you boot up without **Write Color Buffer**, ~~you get shader compiled and~~ it hangs up the Display with 0.02fps ~~which it means wouldn't able to file write it in order to shader compile it.~~

**FIXED** by unknown PR
~~Second issue:
The game has booted up with **Write Color Buffer** property.
When you boot up the first shader cache, you get result:~~
 `F {RSX [0x09c63b4]} RSX: class std::runtime_error thrown: Verification failed (e=0x6f8): file::write
(in file c:\projects\rpcs3\utilities\file.cpp:1012)`
~~I decided to reboot game in order to get boot and ingame further.~~

**FIXED** by unknown PR
~~Third issue:
When I'm done playing with BLUR game, If I wanted to play again including shader compiled, I would get segfault error. (there are different instruction address and segfault address with different shader compiled.) Same issue in the thread followed: #5747~~

**FIXED** by #6388 (partially fixed)
~~Four Issue:
The car render isn't showing display property in car selection, otherwise ingame isn't problem but the problem thing is blurred/bloom effect, it is similar to Most Wanted 2012, TLOU and Uncharted series in other cases.~~
but, partially fixed the ghost image issue, the temporary fixes switch camera (see image on the latest comment)

**Screenshot:** (Ignore other PR that was rebased from 8501)
![image](https://user-images.githubusercontent.com/40495799/63148116-7101ff00-c000-11e9-9bbb-7c9201d2645d.png)
![image](https://user-images.githubusercontent.com/40495799/63147839-a823e080-bfff-11e9-8148-f70427ad9349.png)
![image](https://user-images.githubusercontent.com/40495799/63147297-ef10d680-bffd-11e9-8824-e34b620a2d69.png)
![image](https://user-images.githubusercontent.com/40495799/63147700-3a77b480-bfff-11e9-83f7-abadc9c401f4.png)
![image](https://user-images.githubusercontent.com/40495799/63147710-43688600-bfff-11e9-9a99-424ade8d8b24.png)

**Log:**
Log - [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3508277/RPCS3.log.gz)
RSX Capture - https://drive.google.com/open?id=1L19sSjk7rnal6BZh4N_hRSDDeUiHFwgZ
RenderDoc Capture - https://drive.google.com/open?id=1SwzuMVLg4oUyJpINh0DiA-kdvu4UaO90

**Comment by Xcedf** [comment]
@jenci8888 the last screen looks like TLOU, in TLOU this stuff has spu nature and looks better with Accurate Xfloat, try to use Accurate Xfloat

**Comment by kd-11** [comment]
Looks to be interesting and may be related to some stuff I'm working on.

**Comment by kd-11** [comment]
This game does not run with any settings whatsoever. Also the hang has nothing to do with RSX (or maybe it doesn't anymore) as it just hangs unconditionally with RSX executing NOPs forever. Something else is very wrong with it at a synchronization level. Unassigning myself until its in a debuggable state.

**Comment by elad335** [comment]
Reupload log now that #7538 merged.

**Comment by jenci8888** [comment]
Sorry for wait, here's log: 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5460702/RPCS3.log.gz)

The issue shader crash is fixed, remain issue the game wouldn't go intro without WCB.
And one issue remains the ghost image effect, which it's really hard to see.
![image](https://user-images.githubusercontent.com/40495799/97621544-4f354200-1a23-11eb-855c-37e53d0e075c.png)

**Comment by SatansFavSuccubus** [comment]
> Sorry for wait, here's log:
> [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5460702/RPCS3.log.gz)
> 
> The issue shader crash is fixed, remain issue the game wouldn't go intro without WCB.
> And one issue remains the ghost image effect, which it's really hard to see.
> ![image](https://user-images.githubusercontent.com/40495799/97621544-4f354200-1a23-11eb-855c-37e53d0e075c.png)

The ghost-light issue is fixed with Asynchronus Texture Streaming enabled in the most recent RPCS3 build. There is a trade-off however, the game will then be hit with constantly flashing white lights.

These are the settings to get the US version of blur running in the most recent RPCS3 build (0.0.17-12648-c13a46b0 Alpha)

![image](https://user-images.githubusercontent.com/88169925/129884114-8bdc7770-46c0-49c7-8e40-5afc68d1db45.png)

![image](https://user-images.githubusercontent.com/88169925/129884134-786e69ec-63e9-466f-81d1-9b44900fd49b.png)

![image](https://user-images.githubusercontent.com/88169925/129884144-26ecab52-0fe9-4dc8-ba65-059f327ba59f.png)

White Light Side-Effect:
https://i.gyazo.com/64e79a858d423634208790c9a87d6786.mp4

**Comment by Olatunji556** [comment]
please i really need your help on this blur game

**Comment by kd-11** [comment]
Is this still an issue?

**Comment by Satan86** [comment]
Yes. 
![image](https://user-images.githubusercontent.com/61447828/198837527-5f288871-91ce-4af3-95bd-6a4067ad0ecb.png)
Captura RSX: https://drive.google.com/file/d/1D1UeInmm7X3OKhAWHKXoSzsEiCLVx5l_/view?usp=share_link
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9893887/RPCS3.log.gz)

**Comment by kd-11** [comment]
The blocky glitches are fixed now with using RSX detiling + WCB + RCB iirc. Let me know if there's still a glitch left.

**Comment by Ordinary205** [comment]
Sadly theres still an issue when the headlights shows bright flicker or the graphical glitches gets worse the more I try to progress the game, and the lighting is still broken with WCB+RCB+RSX Tiled memory which seems similar to frostbite titles.

Before starting the race:
![Blur 1](https://github.com/RPCS3/rpcs3/assets/125112932/1e258260-dc31-46b2-8ac8-94b13d5378f4)

After completing the race:
![Blur 2](https://github.com/RPCS3/rpcs3/assets/125112932/b5414360-6b61-459e-b242-7ed1837a123c)

Broken lighting with WCB+RCB+RSX Tiled memory:
![Blur 3](https://github.com/RPCS3/rpcs3/assets/125112932/d08f4f3f-8e7b-442c-840f-b5cd6dc3ff06)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13694639/RPCS3.log.gz)

**Comment by Ordinary205** [comment]
@kd-11 sorry for the ping, but is it fine if this issue gets reopen? The game still contains graphical glitches if you look at the screenshots from above on what I commented.

**Comment by kd-11** [comment]
@Ordinary205 After looking at the screenshots, I think we should open a clean ticket. This kind of meta ticket is a problem because it lumps different things together and makes it difficult to track.
