### ISSUE TITLE
South Park: The Stick of Truth - sceNpTrophyRegisterContext error on intro - build RPCS3 Version: 0.0.6-11b80b46 Alpha

### ISSUE THREAD

**Issue by goedzo** [RPCS3/rpcs3#6408]
When booting South Park: The Stick of Truth - sometimes (not always) it cannot go past the intro and freezes after the southpark studio's logo. 

Last error log entries are:
```
S {PPU[0x1000000] Thread (main_thread) [0x027409ac]} sys_prx: Loaded module: /dev_flash/sys/external/libhttp.sprx
U {PPU[0x1000000] Thread (main_thread) [0x027159e8]} sceNp TODO: sceNpBasicRegisterContextSensitiveHandler
E {PPU[0x100001d] Thread (np stats manager) [0x02710078]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x2, handle=0x2, statusCb=*0xdd26a0, arg=*0x301329e8, options=0x1)
```

**Comment by Megamouse** [comment]
Don't post log as text here.
Upload the actual log file after the bug occured and after closing the emulator (RPCS3.log)

**Comment by goedzo** [comment]
Ok will upload logs in the future. Some aditional info:
It was actually after the autodesk logo, and using the LLVM Recompiler as SPU Decoder.

**Comment by AniLeo** [comment]
Removed console output, added need information tag as upload of RPCS3.log is still pending

**Comment by goedzo** [comment]
Sorry but i don't have the log file anymore so cannot upload it.

**Comment by RainbowCookie32** [comment]
Then reproduce the error and upload that log. An issue without a proper log is useless

**Comment by goedzo** [comment]
The log was there. Anileo should not have deleted it.

**Comment by RainbowCookie32** [comment]
That was not a proper log

**Comment by goedzo** [comment]
Sure will try later to regenerate a log.

**Comment by goedzo** [comment]
Ok here is the log. I had to try about 6 times to boot the game before it happened. Also this time I had the SPU recompiler on ASMJIT instead of LLVM, so that doesn't seem to make a real difference.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3538694/RPCS3.log)

**Comment by mavethee** [comment]
Oh, man. Your settings are a mess 🤔

**Comment by digitaldude555** [comment]
Still an issue.

**Comment by digitaldude555** [comment]
@goedzo fixed now?

**Comment by goedzo** [comment]
No this one is still an issue. Run into this one while testing the other.

**Comment by digitaldude555** [comment]
I think its fixed now. Haven't encountered it after many runs.
