### ISSUE TITLE
Puppeteer [BCES00935] incorrect lighting & render

### ISSUE THREAD

**Issue by Parotaku** [RPCS3/rpcs3#6523]
The game goes ingame correctly but the render is incorrect and the screen is often black (see included image comparison for map/act selection) or missing rendered objects... Same results with both Vulkan & OpenGL

RPCS3 v0.0.7-8677-53e7f6c5 Alpha | HEAD | Firmware version: 4.83
Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz | 12 Threads | 15.90 GiB RAM | TSC: 3.30GHz | AVX+
Nvidia RTX 2070 Super

Incorrect render on rpcs3:
![bad-render](https://user-images.githubusercontent.com/22565307/64633563-b6e19580-d3fb-11e9-9eb2-6d3d569913d0.jpg)

Internet screenshot from real PS3:
![real-PS3](https://user-images.githubusercontent.com/22565307/64633575-bc3ee000-d3fb-11e9-8060-d866da4d5b0d.jpg)

[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/3596839/RPCS3.log.zip)

More infos : https://forums.rpcs3.net/thread-177684-post-306458.html#pid306458

**Comment by Parotaku** [comment]
I don't know which recent commit is responsable, but there's some progress with the broken rendering...
Far from perfect but it's... less dark...
![progress](https://user-images.githubusercontent.com/22565307/70268340-8e6dfb00-17a0-11ea-8b8c-fc8793228277.jpg)
RPCS3 v0.0.7-9203-c3862b74 Alpha | HEAD | Firmware version: 4.83
Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz | 12 Threads | 15.90 GiB RAM | TSC: 3.30GHz | AVX+
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3928768/RPCS3.log.gz)

**Comment by Parotaku** [comment]
Rendering has improved a lot with 10518.
The characters are now clearly visible and a lot more of the world is shown... The broken motion blur is fixed too!
Some effects like fog or bloom are still broken but it's a great improvement!
![fix1](https://user-images.githubusercontent.com/22565307/84873608-ca551780-b083-11ea-8256-a3e0a7f1f8b9.jpg)
![fix2](https://user-images.githubusercontent.com/22565307/84873621-ce813500-b083-11ea-8b1f-df7b3941fed4.jpg)

**Comment by Asinin3** [comment]
@Parotaku Isn't this completely fixed now? Users did playable reports and it looks fine to me. But i never compared it with real hardware.

**Comment by Parotaku** [comment]
It's better but some effects are still missing or incorrectly rendered (shadows, etc)...
For instance, on the first intro on real hardware, there are some foggy clouds on the foreground which are completely missing for the moment on rpcs3: look at 1m20 here https://www.youtube.com/watch?v=CXUvdoU_1MQ

**Comment by kd-11** [comment]
This ticket needs an update and new RSX captures.

**Comment by Parotaku** [comment]
Sorry, not much to report...
Vulkan, with or without Multithreaded RSX, still has broken (spiky) shadows and missing some effects like the purple fog/smoke on the intro... (there's some tiny purple haze appearing briefly on the right of the screen but nothing like on real PS3)
OpenGL rendering is still mostly pitch black...
![haze](https://user-images.githubusercontent.com/22565307/128767190-83076c1e-a2f6-4916-ba9a-72742db567ae.jpg)
kd-11, if you need something specific just tell me...

**Comment by RainbowCookie32** [comment]
He needs new RSX captures

**Comment by Parotaku** [comment]
Sorry, don't know how to capture this... 
I thought that meant screenshots with Multithreaded RSX enabled...

**Comment by RainbowCookie32** [comment]
Boot the game, get to a point where the issue is on screen, then go to `Utilities` on RPCS3's main window and click `Create RSX Capture`.

The capture will be saved to the `captures` folder on RPCS3's directory, you can then compress it and then upload it here.

**Comment by Parotaku** [comment]
Thanks for the help, RainbowCookie32.
Here it is...
[BCES00935_20210809221450_capture.zip](https://github.com/RPCS3/rpcs3/files/6957158/BCES00935_20210809221450_capture.zip)

**Comment by Parotaku** [comment]
On a more positive note, the shadowy tadpoles under the water in the swamp level are now displaying correctly... it looks very nice!
![tadpole](https://user-images.githubusercontent.com/22565307/128771817-688e5760-bdea-4854-a455-235b02b7e7a2.jpg)

**Comment by digitaldude555** [comment]
#10823 retest with this pr. @Parotaku

**Comment by sampletext32** [comment]
Please refer to [this article](https://github.com/RPCS3/rpcs3/blob/master/.github/PR-BUILD.md), if you don't know how to test a PR.

**Comment by Xcedf** [comment]
Tried demo, no difference with https://github.com/RPCS3/rpcs3/pull/10823, but the issue itself perhaps was already fixed
![image](https://user-images.githubusercontent.com/7060586/132142064-d48312f4-3e27-446a-b605-7eec76aa3e15.png)
![image](https://user-images.githubusercontent.com/7060586/132142099-f55acb8d-3e84-462a-8532-e84a2a66cba9.png)
the game itself is pretty dark, see here
https://www.youtube.com/watch?v=aSR5XCKrAas&t=256s
The only issue I noticed ofr now is missing purple smoke/mist, aside form that colors are the same to me

**Comment by Parotaku** [comment]
No change on my side either with the full game...
As @Xcedf already said, the purple smoke/mist is still missing, and many projeted shadows are still blocky/spicky (see the capture I've done of the castle from the intro... the shadows on the floor are supposed to be smooth, not blocky)

**Comment by Parotaku** [comment]
With recent builds, some flickering lighting errors have started appearing in cutscenes & ingame... (the purple band on top of the screen in my capture)
![bug](https://user-images.githubusercontent.com/22565307/164884079-7796f9ca-5793-4041-9937-7a233a904a5c.jpg)

**Comment by Parotaku** [comment]
Here's an RSX capture of it on screen:
[https://www.dropbox.com/s/po7sdipuvosdj7t/BCES00935_20220423085720_capture.zip](url)

**Comment by Jonathan44062** [comment]
Not sure if this issue is related or not, but, there's an small issue, let me show an comparison
PS3
![image](https://user-images.githubusercontent.com/78843189/166591063-b9b542d4-b070-4d89-92bb-719fa6afee01.png)

RPCS3
![image](https://user-images.githubusercontent.com/78843189/166591081-25e871d8-f557-4a7d-a942-757f65235a21.png)

Those sheets of paper that are floating to teleport you to another area, are not rendered correctly. 

RSX Capture:
https://www.mediafire.com/file/nr2w1m2bzjkz6ho/BCJS30078_20220503184055_capture.rrc/file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8616924/RPCS3.log.gz)

**Comment by Linear524** [comment]
> With recent builds, some flickering lighting errors have started appearing in cutscenes & ingame... (the purple band on top of the screen in my capture) EDIT: It's supposed to be the searchlights, following the characters movements... ![bug](https://user-images.githubusercontent.com/22565307/164884079-7796f9ca-5793-4041-9937-7a233a904a5c.jpg)

Parotaku, you need to use WCB+RCB+WDB+RDB and if needed - also activate Force CPU blit. 
This will help to render some deep layers FX, but not all unfortunately..
![BCES00935_screenshot_2022_05_04_13_07_10](https://user-images.githubusercontent.com/84367301/166639335-db0c96fa-d229-4383-b78c-3e96685b643e.png)

**Comment by Linear524** [comment]
Pupeteer is a truly brilliant game and unique title in terms of used technologies in rendering.
Right now RPCS3 is almost reached the correct image rendering state, but some functions are still broken or unimplemented...
Here I'm made some overall issues compilation for this title:
1) - Broken light shader or color clipping:
![P1](https://user-images.githubusercontent.com/84367301/166645867-ad473bca-eb15-4f14-ad82-d813a82b06de.jpg)
![P2](https://user-images.githubusercontent.com/84367301/166645871-a07eab19-f051-469a-a204-49286725cf17.jpg)
Something similar was some time ago in GoW Ascension flame pots issue, and KD-11 fixed those shaders.

2) - Broken geometry wave effect:
![P3](https://user-images.githubusercontent.com/84367301/166646300-19b20345-8cf7-434c-826f-4f6856dd1b68.jpg)
Looks like broken vertex shader or broken geometry animation.

3) - Missing dynamic particles volumetric fog:
![P4](https://user-images.githubusercontent.com/84367301/166647189-69bbe5c2-171a-4a3a-9699-c42841545962.jpg)
Puppeteer uses high quality dynamic particles fog, and RPCS3 currently doesn't have this function implemented yet. I bet some SPU/PPU instructions are missing...

4) - Dynamic shadows are pixelated/broken shadow filtering:
![P5](https://user-images.githubusercontent.com/84367301/166647817-26a18537-c579-4267-a471-7d8efdba6913.jpg)

5) - Particle rendering are missing.
    - Candles are not receiving light (subsurface scattering lighting missing ? or just light shader).
    - MLAA are not working.
![P6](https://user-images.githubusercontent.com/84367301/166648170-5921ca3d-2698-47cd-9772-9fec6137c837.jpg)

**Comment by Linear524** [comment]
I think KD-11 very close to fixing all this remaining issues, and once it will be done - a lot of other titles will have benefits too. (Like TLoU, Uncharted 2,3, e.t.c.)
![PS3](https://user-images.githubusercontent.com/84367301/166649370-e9ffd609-4cb9-4290-ae54-764b6decc0f5.jpg)
![PS33](https://user-images.githubusercontent.com/84367301/166649382-fd70f60c-a316-41d9-a0fb-87f55c568fb5.jpg)

**Comment by ThiagoAnd** [comment]
Is there a fix for the hidden gem (the one that we need to reach to jump to next screen)

**Comment by Jonathan44062** [comment]
Sadly no, just waiting for more improves in the emulator

**Comment by TryingToLove** [comment]
> Sadly no, just waiting for more improves in the emulator

Does the hidden gem issue prevent you from finishing the game? Would love to start this on my Steam Deck but don’t want to bother if I can’t complete.

**Comment by Jonathan44062** [comment]
I completed the game in the past, the only problem is some visual effects are not rendered correctly (Like R&C A Crack in Time did), are invisible, like those sheets of paper that are floating to teleport you to another area for example, is hard to see where they are, it's like playing puppeteer in hard mode

**Comment by TryingToLove** [comment]
> I completed the game in the past, the only problem is some visual effects are not rendered correctly (Like R&C A Crack in Time did), are invisible, like those sheets of paper that are floating to teleport you to another area for example, is hard to see where they are, it's like playing puppeteer in hard mode

Ok thanks. Are there any settings adjustments you recommend? Should I just use the latest default RPCS3 settings or are there any things I absolutely must change? The Wiki doesn’t really recommend any changes.

**Comment by Jonathan44062** [comment]
It works with default settings, no need for special configuration

**Comment by TryingToLove** [comment]
> It works with default settings, no need for special configuration

Sounds good…thanks.

**Comment by ThiagoAnd** [comment]
Any news on these issues? About the hidem Gem maybe?

**Comment by Jonathan44062** [comment]
Updating status, the papers that were not visible before, are now rendered correctly
![image](https://user-images.githubusercontent.com/78843189/205414406-79c743cd-8bdd-4397-b136-e361c0ff77b3.png)

**Comment by ThiagoAnd** [comment]
> Updating status, the papers that were not visible before, are now rendered correctly ![image](https://user-images.githubusercontent.com/78843189/205414406-79c743cd-8bdd-4397-b136-e361c0ff77b3.png)

Great to know that!!! Almost perfect. Besides having this paper problem I was also having problems with upscaling and anti aliasing. I will download again to test. No special configuration is needed correct? Thanks for sharing buddy.

**Comment by Parotaku** [comment]
The paper warps are indeed fixed, as are the lights... I think the only things remaining broken are the blocky shadows and the missing fog effects... Thanks for your work, devs!
![image](https://user-images.githubusercontent.com/22565307/205432445-ff6652ee-ce59-49bd-a47c-040ffc0cf81f.png)

**Comment by TryingToLove** [comment]
This is all great news, thanks! Playing the game on my Steam Deck and it runs flawlessly and looks gorgeous. Thank you Devs, you are the best! Keep up the great work!

**Comment by TryingToLove** [comment]
The game has frozen on me on Steam Deck several times, often right at the end of an act, meaning I have to start all over again. Most recent is the end of Act 6, Curtain 1.

**Comment by Parotaku** [comment]
Looking amazing now with the 'Disable MLAA' patch: https://twitter.com/Parotaku/status/1657467822040072193 
On the other hand, the patch for '60 FPS' seems to break the lights in some places (intro & first level are almost in full darkness)

**Comment by SixelAlexiS90** [comment]
Thank you for all the works on adjusting this game, hopefully these few remaining issues will be fixed as well since this forgotten gem deserve it's full preservation <3

**Comment by Parotaku** [comment]
Effects still missing as of v0.0.28-15316-8d54ddf4 Alpha.

I don't know how to help devs fix that so here's a fresh RSX capture from the map with 2 effects incorrectly rendering: the purple fog is missing from the map & the earth globe light seems to be cropped (it's darker where it should be glowing).
[https://www.dropbox.com/s/2foh8q45tx68yy1/BCES00935_20230707190517_capture.7z](https://www.dropbox.com/s/2foh8q45tx68yy1/BCES00935_20230707190517_capture.7z)

Here's how it's looking on RPCS3:
![missing](https://github.com/RPCS3/rpcs3/assets/22565307/09473407-a02a-477f-a70a-dbb564b6da0f)

And how it should look with the fog & light effects, from a PS3 captured video of the game:
![ps3](https://github.com/RPCS3/rpcs3/assets/22565307/1685941a-d738-4b47-897f-484d873dce57)

**Comment by Parotaku** [comment]
If you can, could you have a look at the shadow/lighting bug on the RSX capture, @kd-11 ? It might be related/similar to the TLoU shadow bug (https://github.com/RPCS3/rpcs3/issues/14142) you're currently working on (it looks like light is clipped)...

**Comment by Parotaku** [comment]
Two more problems I noticed while testing the game:

- the 60FPS patch has a side effect on the game physics: the hero character cannot jump as high as on the original 30 fps framerate... In consequence, some plateforms might be difficult or impossible to reach when the patch is active.

- the 'right eye' rendering when displaying the game in 3D is a bit broken compared to other games which can be rendered in 3D (like ICO): in a similar way of the 'blocky shadows' bug still present, some part of the 'right eye' rendering is duplicated or cropped which results in the 3D depth not looking correct...
It's a bit hard to explain but, for instance, if you compare (in original size) the white spikes on the ennemies' back on the foreground of my screenshot, you can see the triangles are a bit broken on the 'right eye' rendering and correct looking on the 'left eye' rendering.
![misaligned-3D](https://github.com/RPCS3/rpcs3/assets/22565307/a99afa58-190e-49e8-a002-5773727d697a)
...

**Comment by Parotaku** [comment]
The top of the screen seems to be glitching since RSX tilling was implemented...
![glitch](https://github.com/RPCS3/rpcs3/assets/22565307/38e9c9ea-0f57-446f-979e-5e358117c56f)

**Comment by Jonathan44062** [comment]
@Parotaku I can't repro, works fine on my own, the new setting is not enable either, I checked to see and everything looks fine
![image](https://github.com/RPCS3/rpcs3/assets/78843189/db322399-a87c-4b1c-90cf-d40403b0826c)
![image](https://github.com/RPCS3/rpcs3/assets/78843189/d84ef6e0-0495-4e94-9d3b-c843f85d7093)

**Comment by Parotaku** [comment]
@Jonathan44062 Indeed, you're right... My mistake... I deleted all the caches and that fixed it...
Now it's looking like it was before, missing effects included... no more, no less...

**Comment by Parotaku** [comment]
Still no idea on how to fix the remaining bugs? :-/
(missing fog/broken shadows effects & incorrect 3D)

**Comment by Parotaku** [comment]
One year later... is there any potential progress on ways to fix the missing/incorrect effects on this game, @kd-11 ?

**Comment by ThiagoAnd** [comment]
Any updates @kd-11 ? Also, thanks for the awesome job so far!!

**Comment by ThiagoAnd** [comment]
By the way @Parotaku , is there any bug when you activate 60fps? I see people saying that when you active 60fps the character cannot jump higher enough. Is been a while since the last time I played the game

**Comment by Parotaku** [comment]
> By the way @Parotaku , is there any bug when you activate 60fps? I see people saying that when you active 60fps the character cannot jump higher enough. Is been a while since the last time I played the game

Last time I checked, it still was true... and it cause problems in later levels like halloween stages, where you have to quickly jump over large gaps... so I don't use the 60fps patch.

**Comment by Snipy44** [comment]
Hi, no news for this game ?

**Comment by Jonathan44062** [comment]
3 issues to remain
1-Broken Dynamic Shadows, as you can see the curtains
![Image](https://github.com/user-attachments/assets/db492861-af22-4702-9356-44e602948d24)
2.- Broken waves
![Image](https://github.com/user-attachments/assets/a845fb5f-b0ea-46fc-976f-058e4199242f)
3.- Missing Fog
RPCS3
![Image](https://github.com/user-attachments/assets/7fb0b299-5c92-4e58-8c13-04e1baab28e7)

PS3
![Image](https://github.com/user-attachments/assets/c6aff23b-c8f7-459c-8fe5-5584d10ea118)

**Comment by Parotaku** [comment]
> 3 issues to remain 1-Broken Dynamic Shadows, as you can see the curtains ![Image](https://github.com/user-attachments/assets/db492861-af22-4702-9356-44e602948d24) 2.- Broken waves ![Image](https://github.com/user-attachments/assets/a845fb5f-b0ea-46fc-976f-058e4199242f) 3.- Missing Fog RPCS3 ![Image](https://github.com/user-attachments/assets/7fb0b299-5c92-4e58-8c13-04e1baab28e7)
> 
> PS3 ![Image](https://github.com/user-attachments/assets/c6aff23b-c8f7-459c-8fe5-5584d10ea118)

+ incorrect 3D depth rendering on the right side (see my previous post about it here : https://github.com/RPCS3/rpcs3/issues/6523#issuecomment-1704375940 )

**Comment by alexconsole04** [comment]
Don't know if anyone tested, but Write Color Buffers does somewhat render the missing fog, but it's broken.

<img width="2560" height="1401" alt="Image" src="https://github.com/user-attachments/assets/265b54fc-c8e7-4be6-8896-723584337f33" />

<img width="2560" height="1401" alt="Image" src="https://github.com/user-attachments/assets/e0a96b95-7b64-42bb-9b00-9f4e687ae28d" />

https://github.com/user-attachments/assets/539f91b1-576b-4c80-917a-49778db21b4f

[RPCS3.log.gz](https://github.com/user-attachments/files/21320314/RPCS3.log.gz)

**Comment by alexconsole04** [comment]
OpenGL renders the fog much better than Vulkan, but it is still broken as it is looks like a constantly moving flame. The fog also appears to bounce whenever the scene starts to shift, which is weird on its own.

[RPCS3.log.gz](https://github.com/user-attachments/files/21354231/RPCS3.log.gz)

[NPUA80959_20250721160337_capture.rrc.gz](https://github.com/user-attachments/files/21354232/NPUA80959_20250721160337_capture.rrc.gz)

<img width="2560" height="1401" alt="Image" src="https://github.com/user-attachments/assets/94a16509-79a6-4d96-ba45-eceda3ee506d" />

https://github.com/user-attachments/assets/4c93cfd1-83f4-4db5-b9aa-e883b7f15b3f

**Comment by Parotaku** [comment]
Just a quick 'up' to this thread to confirm that, as of October 04 2025, what was broken before (fog & shadow effects... probably SBS 3D depth looking wrong too) is still broken... :-/

**Comment by kd-11** [comment]
Needs testing with this PR: https://github.com/RPCS3/rpcs3/pull/17837

**Comment by Parotaku** [comment]
<img width="1920" height="1040" alt="Image" src="https://github.com/user-attachments/assets/f18ed81f-53ef-4f36-a51a-c769503f440d" />
@kd-11 Effects (fog & shadows) still broken with the PR here... sorry... :-/

**Comment by alexconsole04** [comment]
With WCB enabled to render the fog, it's still broken on Vulkan and OpenGL

<img width="1282" height="752" alt="Image" src="https://github.com/user-attachments/assets/4b03f19d-1c39-430d-8efa-23102948bec9" />

[RPCS3.log.gz](https://github.com/user-attachments/files/24062255/RPCS3.log.gz)

**Comment by digant73** [comment]
maybe a retest and an update please

**Comment by alexconsole04** [comment]
It is still the same.

**Comment by digant73** [comment]
please re-test on latest build. Hopefully some textures and reflections issues have been fixed by recent build 0.0.39-18790

**Comment by Parotaku** [comment]
Still the same here (broken shadows & fog, etc...)

<img width="1920" height="1040" alt="Image" src="https://github.com/user-attachments/assets/de76bdf6-a641-427a-a61a-19111276e080" />

**Comment by piotrk-dev** [comment]
Same issues, Apart from that on latest versions freeze in tutorial, can't really pass through it,
using recommended settings and patches (but it freezes also without them), only log which happened in this moment is
`E RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x40300490`

<img width="2559" height="1439" alt="Image" src="https://github.com/user-attachments/assets/45fce12c-89bd-4279-a832-0aebd521a59f" />

**Comment by matiashuarta** [comment]
Graphics are still broken, and also game freezes a lot.

**Comment by AniLeo** [comment]
Stability is unrelated to this ticket, there is another ticket for it.

**Comment by Parotaku** [comment]
A little UP for this thread because the rendering bugs are still there...

(BTW just noticed the shadow of the small castle on the map is also broken/blocky)
<img width="1920" height="1049" alt="Image" src="https://github.com/user-attachments/assets/62b7b621-c3c7-472a-8177-7de458fab89a" />

**Comment by rleonever** [comment]
> A little UP for this thread because the rendering bugs are still there...
> 
> (BTW just noticed the shadow of the small castle on the map is also broken/blocky) <img alt="Image" width="1920" height="1049" src="https://private-user-images.githubusercontent.com/22565307/631940435-62b7b621-c3c7-472a-8177-7de458fab89a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODcwNTY4MDEsIm5iZiI6MTc4NzA1NjUwMSwicGF0aCI6Ii8yMjU2NTMwNy82MzE5NDA0MzUtNjJiN2I2MjEtYzNjNy00NzJhLTgxNzctN2RlNDU4ZmFiODlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwODE4VDEyMzUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2Nzk2Mzc4NzAxNzZlNjlhZDVlMWZhMDZjYWU5ZTdjMmU3MjliNjdkZmE0NmY2MzUyYWNlMDYzODQwN2UwMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.mGTRsfHy1L5BpJrSe9A4dEtTMdDjUd9K2ShOsxJB3jo">

@Parotaku can you test again? Lots of rsx fixes happened recently

**Comment by Parotaku** [comment]
Downloaded last update... cleared all caches... unfortunately, no change...
Shadows & some effets (fog...) are still broken/missing... :-/

<img width="1920" height="1049" alt="Image" src="https://github.com/user-attachments/assets/75f05f8b-6f71-41f6-a0e5-352877a97fb0" />

**Comment by Parotaku** [comment]
OMG, @kd-11 It seems your latest commit finally fixed the game light/shadows problems!!!

<img width="1920" height="1049" alt="Image" src="https://github.com/user-attachments/assets/8bb55728-cfd5-4b85-83aa-53e26de4af0d" />

<img width="1920" height="1049" alt="Image" src="https://github.com/user-attachments/assets/0fec69f3-dcb0-4fda-a4a3-f0c3c3ebb2b2" />

Fog is also correctly rendered now!!! Amazing!

<img width="1920" height="1049" alt="Image" src="https://github.com/user-attachments/assets/d9eb5059-d948-4fe6-9f6b-438d7c02bd05" />

I will have to test more (3D is a bit more complicated to check) but this is very impressive!!! Bravo!

**Comment by AniLeo** [comment]
Can you provide a before/after comparison? Thanks!

**Comment by Parotaku** [comment]
Well, just using my previous captures:

Before:
<img width="1920" height="1049" alt="Image" src="https://github.com/user-attachments/assets/62b7b621-c3c7-472a-8177-7de458fab89a" />
After:
<img width="1920" height="1049" alt="Image" src="https://github.com/user-attachments/assets/8bb55728-cfd5-4b85-83aa-53e26de4af0d" />

Before:
<img width="1920" height="1049" alt="Image" src="https://github.com/user-attachments/assets/75f05f8b-6f71-41f6-a0e5-352877a97fb0" />
After:
<img width="1920" height="1049" alt="Image" src="https://github.com/user-attachments/assets/d9eb5059-d948-4fe6-9f6b-438d7c02bd05" />

**Comment by Parotaku** [comment]
A small blinking light band (on top left here) and shadows on the first level are still broken, but that's huge progress anyway... testing still in progress...

<img width="1920" height="1049" alt="Image" src="https://github.com/user-attachments/assets/4e4f7c57-ec8f-4258-a421-bc279485bc11" />

<img width="1920" height="1049" alt="Image" src="https://github.com/user-attachments/assets/e38001f6-13f4-4ec2-b59e-83af2711b2ba" />

<img width="1920" height="1049" alt="Image" src="https://github.com/user-attachments/assets/d1071c10-9f55-4adf-bd1d-b695ab1e2e26" />

Some fog effects seem to be horizontally misaligned...
<img width="1920" height="1049" alt="Image" src="https://github.com/user-attachments/assets/961bcf44-0189-4e6c-8de3-0c381e79a815" />

**Comment by Linear524** [comment]
Holy cow !!!
With the latest Master Puppeteer renders fully fixed graphics ! 
Here is my screens:

<img width="1863" height="1014" alt="Image" src="https://github.com/user-attachments/assets/c89b6225-5b79-4566-bb25-20c3387b48e6" />
<img width="1027" height="351" alt="Image" src="https://github.com/user-attachments/assets/e5fd234a-3526-4579-bcf9-cbec65a67fb2" />
<img width="1025" height="476" alt="Image" src="https://github.com/user-attachments/assets/e59310a9-948c-4d2e-9a2c-94845863a27a" />
<img width="1025" height="695" alt="Image" src="https://github.com/user-attachments/assets/3dad0bc3-91ec-4c55-b15e-a65bacbd8c4f" />
<img width="1024" height="547" alt="Image" src="https://github.com/user-attachments/assets/b9e6281c-44d2-495a-bbaa-08181728d042" />
<img width="1911" height="1012" alt="Image" src="https://github.com/user-attachments/assets/1659f1bc-0288-4875-80ea-a570f85052a0" />
<img width="1916" height="1013" alt="Image" src="https://github.com/user-attachments/assets/94e6e243-8a18-493d-8183-6345cd60a4fc" />
<img width="1918" height="1012" alt="Image" src="https://github.com/user-attachments/assets/2c39e797-ed5d-485b-89bc-74c59a782c3e" />
<img width="1914" height="1010" alt="Image" src="https://github.com/user-attachments/assets/86a6d7cd-c3e2-48fc-9de4-b34179d1615e" />
<img width="1900" height="1004" alt="Image" src="https://github.com/user-attachments/assets/10bc3d3c-adeb-475d-8aa9-07c26c36c0e3" />

**Comment by Linear524** [comment]
Color clipping = fixed !
Pixelated shadows = fixed !
Volumetric dynamic fog = fixed !
Finally !!!)))))

**Comment by ShadowH69** [comment]
> Color clipping = fixed ! Pixelated shadows = fixed ! Volumetric dynamic fog = fixed ! Finally !!!)))))

What's left? can you confirm 

> 

> A small blinking light band (on top left here) and shadows on the first level are still broken, but that's huge progress anyway... testing still in progress...
> <img alt="Image" width="1920" height="1049" src="https://private-user-images.githubusercontent.com/22565307/638291127-4e4f7c57-ec8f-4258-a421-bc279485bc11.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODcxNjI5NjksIm5iZiI6MTc4NzE2MjY2OSwicGF0aCI6Ii8yMjU2NTMwNy82MzgyOTExMjctNGU0ZjdjNTctZWM4Zi00MjU4LWE0MjEtYmMyNzk0ODViYzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwODE5VDE4MDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmZGQ2YTM2NTI0MGIwZjc0OTRjZjcyMzViYjNmMWVlYzNkN2QwYmZjM2NmZDExY2FlZDk5ZDU4Y2FiMDIzNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.seINtW-KlqW5U63ZU-apUbcQow_dIsoV3fbox-lm1mg"> <img alt="Image" width="1920" height="1049" src="https://private-user-images.githubusercontent.com/22565307/638293130-e38001f6-13f4-4ec2-b59e-83af2711b2ba.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODcxNjI5NjksIm5iZiI6MTc4NzE2MjY2OSwicGF0aCI6Ii8yMjU2NTMwNy82MzgyOTMxMzAtZTM4MDAxZjYtMTNmNC00ZWMyLWI1OWUtODNhZjI3MTFiMmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwODE5VDE4MDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNjdjOWMxNTljODVkZWQ5OWNkN2Y0OTYxN2EyN2U3ZjVmM2NmNjA0NWJkZjI3Yjg5MzM0NTkwYWIwNjhhNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.wtjFFD4C8ip3ES72DGJFcpCyALygZdBhIrOI7VCYW1I"> <img alt="Image" width="1920" height="1049" src="https://private-user-images.githubusercontent.com/22565307/638297944-d1071c10-9f55-4adf-bd1d-b695ab1e2e26.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODcxNjI5NjksIm5iZiI6MTc4NzE2MjY2OSwicGF0aCI6Ii8yMjU2NTMwNy82MzgyOTc5NDQtZDEwNzFjMTAtOWY1NS00YWRmLWJkMWQtYjY5NWFiMWUyZTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwODE5VDE4MDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxOThhMmI1MGE4MTAyMDJiZjMzZjM5YWI5NjFhYzE4NDEyOTFjNjllYTY4OTI1NjcwNzU2ZWViMGUxMzUwYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.WspSVScHtOsUJTntkBu_OZE-bTrSJA0zw1H8iR-6qR8">
> 
> Some fog effects seem to be horizontally misaligned... <img alt="Image" width="1920" height="1049" src="https://private-user-images.githubusercontent.com/22565307/638299348-961bcf44-0189-4e6c-8de3-0c381e79a815.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODcxNjI5NjksIm5iZiI6MTc4NzE2MjY2OSwicGF0aCI6Ii8yMjU2NTMwNy82MzgyOTkzNDgtOTYxYmNmNDQtMDE4OS00ZTZjLThkZTMtMGMzODFlNzlhODE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwODE5VDE4MDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNGE1OTYwNWIzZmY2NTg4N2VjMzA4Y2RmNWMyYjUwMDlkOGM4NzE3OGY0MTM0YjBiMzMzNTdkZDY3YjMyMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.AuQoIGOiCM2ddhEjMS0uohW2ap910N7hQD9NaQ65wrw">

**Comment by Linear524** [comment]
@ShadowH69 - everything works like on real PS3 !
Just use native 720p and all WCB+RCB+WDB+RDB+ all other necessary functions (like on my config screen).
Looks like your issues comes from resolution scaling higher than native 720p

**Comment by ShadowH69** [comment]
> [@ShadowH69](https://github.com/ShadowH69) - everything works like on real PS3 ! Just use native 720p and all WCB+RCB+WDB+RDB+ all other necessary functions (like on my config screen). Looks like your issues comes from resolution scaling higher than native 720p

One of the testers ( Alexis) will be confirming shortly as in the mean time and btw your settings are all over the place and debug settings aren't allowed either

@Parotaku can you provide a log file

**Comment by ShadowH69** [comment]
@Linear524 provide your log file please

**Comment by Linear524** [comment]
> [@Linear524](https://github.com/Linear524) provide your log file please

[RPCS3.log](https://github.com/user-attachments/files/31235110/RPCS3.log)

**Comment by Linear524** [comment]
I already completed Act3 and no issues !
Everything runs Perfect !!!

**Comment by ShadowH69** [comment]
> I already completed Act3 and no issues ! Everything runs Perfect !!!

due to the nature of your settings used they are not acceptable for comparison 
Please use and compare between the following 
 

- Default settings
-  Wiki
-  Wiki + RWCB+RWDB

and provide screenshots along with 3 separate logs for all 3 setting changes

a Log file is created properly everytime the emulator is closed , please do so after each test

**Comment by Linear524** [comment]
I don't care about what is acceptable via current default settings - because current Default settings are wrong ! And I don't like Wiki either.
RPCS3 should always be used with native 720p by default and with all PS3 gpu features activated - WCB+RCB+WDB+RDB and with all accuracy features enabled.  My aim is just reproduce original PS3 graphics without any upscaling or disabling important features...
So I have no problems with PS3 graphics emulation in RPCS3. The only issues I see now = NaughtyDog titles and GT6...
Puppeteer is perfect now :) :) :)

**Comment by ShadowH69** [comment]
> I don't care about what is acceptable via current default settings - because current Default settings are wrong ! And I don't like Wiki either. RPCS3 should always be used with native 720p by default and with all PS3 gpu features activated - WCB+RCB+WDB+RDB and with all accuracy features enabled. My aim is just reproduce original PS3 graphics without any upscaling or disabling important features... So I have no problems with PS3 graphics emulation in RPCS3. The only issues I see now = NaughtyDog titles and GT6... Puppeteer is perfect now :) :) :)

yes that's the point and the goal to work towards , eventually RWCB+RWDB will all be enabled by default , resolution scaling is a hack mainly 

Your missing the point here , your using unacceptable settings especially debug settings which isn't allowed for a play ability report , were trying to find the least amount of settings in order for the game to graphically render and work correctly , you basically enabled everything from RWCB+RWDB to CPU Blit ( debug setting ) aswell as Accurate Reservation  and  Accurate DMA which is doubtfully needed  

your report is rejected until further confirmation

**Comment by Jonathan44062** [comment]
@Linear524 You don't know what you're talking about. Don't share incorrect information about your settings so people don't complain later—we don't want that, so please avoid it.
Wiki settings are always correct and updating new info

**Comment by Linear524** [comment]
About CPU Blit - it is needed in many games where MLAA is using on SPUs, so without SPU Blit = a lot of garbage may appear, just like KD-11 said long time before.
And I using Accurate Reservation and Accurate DMA in order to avoid SPU crashes in a lot of SPU-intensive titles...
@Jonathan44062 - I know what I'm talking about, because I making my own homebrew for PS3 long time ago...
If my screenshots and settings are not welcomed here - okay then, I will stop uploading.
Wiki have a lot of wrong and outdated configs for some titles, just because most of the people don't test their titles with fully accurate and slow settings - that makes some important things and reports to be out of sight... 
Anyway - Huge thanks to all DEVs !
Puppeteer is fully rendered now ! :)
(waiting for SSAO timing fix and MLAA + VL fix for NaughtyDog games)

**Comment by ShadowH69** [comment]
> About CPU Blit - it is needed in many games where MLAA is using on SPUs, so without SPU Blit = a lot of garbage may appear, just like KD-11 said long time before. And I using Accurate Reservation and Accurate DMA in order to avoid SPU crashes in a lot of SPU-intensive titles... [@Jonathan44062](https://github.com/Jonathan44062) - I know what I'm talking about, because I making my own homebrew for PS3 long time ago... If my screenshots and settings are not welcomed here - okay then, I will stop uploading. Wiki have a lot of wrong and outdated configs for some titles, just because most of the people don't test their titles with fully accurate and slow settings - that makes some important things and reports to be out of sight... Anyway - Huge thanks to all DEVs ! Puppeteer is fully rendered now ! :) (waiting for SSAO timing fix and MLAA + VL fix for NaughtyDog games)

All the game needs is PPU reservation Priority under GPU to prevent freezing / crashing , turn off Accurate Reservation and Accurate DMA

**Comment by Parotaku** [comment]
Indeed, using native resolution + default fixed the remaining light problems I noticed before...

<img width="1920" height="1049" alt="Image" src="https://github.com/user-attachments/assets/c66a7eed-32ef-4705-bacf-6e6c56028729" />
[Puppeteer \[BCES00935\].log.gz](https://github.com/user-attachments/files/31236002/Puppeteer.BCES00935.log.gz)


BUT... with default settings, dynamic fog is missing:
<img width="1920" height="1049" alt="Image" src="https://github.com/user-attachments/assets/39460cab-66c3-4f15-8f5c-f88096ded5d9" />

It needs WCB to be rendered:
<img width="1920" height="1049" alt="Image" src="https://github.com/user-attachments/assets/2cb0b845-6813-4fdf-aad4-a45e8f9b98af" />
[Puppeteer \[BCES00935\].log.gz](https://github.com/user-attachments/files/31236699/Puppeteer.BCES00935.log.gz)

**Comment by alexconsole04** [comment]
Yes I've mentioned this before it was broken. Seems to be the only graphical setting required for accuracy.

**Comment by alexconsole04** [comment]
Testing other levels, cutcenes, and bosses with no other issues. I think its time to finally close this issue. Reopen if anything is found that was missed. The game just needs WCB for the fog.
