### ISSUE TITLE
White Screen, freeze and sound bugs in God of War HD (NPUA80490)

### ISSUE THREAD

**Issue by Emi-Be** [RPCS3/rpcs3#6541]
Hi!,so when Im playing the game it goes fine for a while but suddenly it freezes and a white screen shows up, so I have to close the game. No idea why is this happening, also it gets a strange sound bug and a fps descent for a moment in certain points. Anyone can help me with this ?? I tried to change the resolution scale, the renderer and nothing.
This is my config, and the log.

RPCS3 0.0.7-8673-aa262889 Alpha
GPU:Nvidia gtx 1050Ti
CPU: amd fx-6300 6 cores
RAM: 8gb
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3603596/RPCS3.log.gz)

![1](https://user-images.githubusercontent.com/55222017/64750890-d6a6b580-d4f0-11e9-839c-b0600d9a7865.JPG)
![2](https://user-images.githubusercontent.com/55222017/64750891-d6a6b580-d4f0-11e9-9f82-7bc8f9a16299.JPG)
![3](https://user-images.githubusercontent.com/55222017/64750892-d6a6b580-d4f0-11e9-95c0-9ea69dc8ea45.JPG)

**Comment by RainbowCookie32** [comment]
That log is a copy-paste from RPCS3's window. Reproduce the issue and attach RPCS3.log.gz from RPCS3's folder, or RPCS3.log if the emulator crashes

**Comment by Emi-Be** [comment]
> That log is a copy-paste from RPCS3's window. Reproduce the issue and attach RPCS3.log.gz from RPCS3's folder, or RPCS3.log if the emulator crashes

Sorry, where can I find the log file?

**Comment by RainbowCookie32** [comment]
RPCS3's folder as I said on my other comment. Same folder where the .exe is

**Comment by Emi-Be** [comment]
done

**Comment by Wizzy2018** [comment]
For a white screen use Write Color Buffers it fix it. But mostly you get Semaphore406 errors that's not fixed yet

**Comment by elad335** [comment]
Fixed with Driver wake up delay ?

**Comment by elad335** [comment]
Can anyone reproduce this issue?
