### ISSUE TITLE
Puzzle Dimension - [NPUB30525] missing letters on Vulkan and Opengl

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6598]
when you die the screen is missing letters
![puzzle](https://user-images.githubusercontent.com/2696404/65367714-26f7e300-dc68-11e9-9b46-59956f645646.PNG)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3638280/RPCS3.zip)
[NPUB30525_20190921085728_capture.zip](https://github.com/RPCS3/rpcs3/files/3638281/NPUB30525_20190921085728_capture.zip)

**Comment by benderscruffy** [comment]
same as vulkan aswell
![puzzle1](https://user-images.githubusercontent.com/2696404/66307988-83315700-e938-11e9-8349-6ea3c06ac835.PNG)

**Comment by benderscruffy** [comment]
here is a renderdoc
https://mega.nz/#!4yQjkYxS!2W-JclLsMZv85H4JN4isQyYRgbpFqkiDSjcMdIKWHGo

**Comment by digitaldude555** [comment]
![Screenshot (1074)](https://user-images.githubusercontent.com/26138653/73789485-8f72d700-47a7-11ea-921f-bd089d14c817.png)
Fixed in opengl and vulkan but now the menu and ui is blue color.

**Comment by digitaldude555** [comment]
![Screenshot (1150)](https://user-images.githubusercontent.com/26138653/75093200-69f81280-5588-11ea-9f63-db61950e3d49.png)
Fixed now.

**Comment by AniLeo** [comment]
Closing as fixed

**Comment by benderscruffy** [comment]
@AniLeo 
please reopen it is not fixed
Whenever digitaldude555 says it is fixed it is not
He has a Nvidia card while i have a AMD card
Thanks

**Comment by AniLeo** [comment]
Give rsx capture I'll check

**Comment by benderscruffy** [comment]
[NPUB30525_20200223192809_capture.zip](https://github.com/RPCS3/rpcs3/files/4241098/NPUB30525_20200223192809_capture.zip)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4241104/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Looks like this for me

![image](https://user-images.githubusercontent.com/10283761/75111586-8ef58f80-5633-11ea-9e28-75740aa5b777.png)

**Comment by kd-11** [comment]
Rsx captures seem to inherit the bug fully and are broken on all vendors because corrupted data was captured.

**Comment by kd-11** [comment]
Retest, should be fixed now.

**Comment by benderscruffy** [comment]
still not fixed for me
i removed all caches aswell
![puzzle](https://user-images.githubusercontent.com/2696404/75638542-4e1afd80-5c67-11ea-8b24-e869bada4d81.PNG)

**Comment by kd-11** [comment]
Are any games fixed on your system? Including boy and blob and gattling gears that is.

**Comment by benderscruffy** [comment]
yep it fixed just those 2 games that you mentioned

**Comment by Emulator-Team-2** [comment]
@kd-11 
I have the same problem with GTX 1660.
![1](https://user-images.githubusercontent.com/38318848/75700570-90b5f780-5cb2-11ea-88b4-53ff42b7fc81.png)

**Comment by kd-11** [comment]
It's not caused by GPU model. This game seems to be uploading vertex data as textures causing breakage with GPU blit. CPU blit with all the buffer options toggled fixes most of the issues. Needs more investigation.

**Comment by jokoputera** [comment]
> CPU blit with all the buffer options toggled fixes most of the issues.

Hi, what 'all the buffer options'?

**Comment by kd-11** [comment]
Behavior seems to have changed. CPU blit + WCB is almost perfect now, WCB with normal GPU accelerated blit has fixed menu and text but broken glow effect ingame.

**Comment by kd-11** [comment]
![image](https://user-images.githubusercontent.com/15904127/84525225-f9fecb00-ace3-11ea-96bb-50fb69aefacb.png)
![image](https://user-images.githubusercontent.com/15904127/84525271-0aaf4100-ace4-11ea-9fb4-800448482f3d.png)
![image](https://user-images.githubusercontent.com/15904127/84525313-18fd5d00-ace4-11ea-9b17-eba30df0d21f.png)
![image](https://user-images.githubusercontent.com/15904127/84525425-4813ce80-ace4-11ea-8856-b5f108c33217.png)
![image](https://user-images.githubusercontent.com/15904127/84525451-54982700-ace4-11ea-9002-18d36ce58e2f.png)

It's working fine with this setup, I'll isolate what still breaks visuals. It would seem CPU blit isn't even needed anymore.

**Comment by kd-11** [comment]
Seems to be broken on vulkan only on my side. That could just be a performance issue with bad synchronization, I need testers to verify what is happening with other systems.

**Comment by kd-11** [comment]
Forgot advanced tab
![image](https://user-images.githubusercontent.com/15904127/84528549-93c87700-ace8-11ea-98a3-25c6011f52c4.png)

**Comment by kd-11** [comment]
After some experimentation, this game is working correctly under OpenGL, it only needs WCB+RCB to fix all the problems. Vulkan however seems to have a bug with RCB which breaks ingame visuals. The menu text is fixed but other things tend to break.

**Comment by digitaldude555** [comment]
![Screenshot (305)](https://user-images.githubusercontent.com/26138653/106314128-f53a5780-6271-11eb-8513-55300db5ebf2.png)
Fixed.
