### ISSUE TITLE
PixelJunk Racers / Racers 2nd Lap - Cars do not render

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6751]
using vulkan and open gl
cars are just grey boxes
![pixel](https://user-images.githubusercontent.com/2696404/66695546-783e4400-ecf5-11e9-89bd-80eab13ff289.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3720247/RPCS3.log.gz)
[NPUA80100_20191012133654_capture.zip](https://github.com/RPCS3/rpcs3/files/3720248/NPUA80100_20191012133654_capture.zip)

happens in PixelJunk™ Racers 2nd Lap [NPUA80395] aswell

**Comment by benderscruffy** [comment]
here is a renderdoc
https://mega.nz/#!oyJWxQSZ!EO_lU7rysasp0ET8QDC_VFlBWDpn7vigWODE-Ya2uCY

**Comment by benderscruffy** [comment]
fixed
![pixel](https://user-images.githubusercontent.com/2696404/79067442-db835000-7cf1-11ea-9549-abeb940335f7.PNG)

**Comment by digitaldude555** [comment]
![Screenshot (2048)](https://user-images.githubusercontent.com/26138653/79069706-03b28500-7cd9-11ea-96e3-9f30aff7e181.png)
Still broken here what setting did you use?

**Comment by digitaldude555** [comment]
okay it works with read color buffers.
