### ISSUE TITLE
BlazBlue series minor texture alignment issues. Vulkan only.

### ISSUE THREAD

**Issue by Silanda** [RPCS3/rpcs3#6926]
This is a minor graphic issue that I'm noticing using the Vulkan renderer in the games of BlazBlue series. Some textures/effects have what looks like an alignment issue that manifests as a vertical line on the edge of the texture. This either only happens with the Vulkan renderer, or doesn't happen with the OpenGL renderer in the same places. I haven't played enough with the OpenGL renderer to rule the latter out. This is occurring at native resolution with strict rendering mode enabled.

I noticed it today while playing BlazBlue: Centralfiction (BLES 02230) while doing Makoto's Astral Heat move, but there's a really obvious example of what I assume is the same thing on the title screen of Continuum Shift Extend (BLES 01487). I had previously noticed it in Continuum Shift but forgot to report it.

OpenGL:
![BlazBlueGL](https://user-images.githubusercontent.com/4227434/67895509-880db300-fb52-11e9-8759-cc6f2db61109.jpg)

Vulkan:
![BlazblueVK](https://user-images.githubusercontent.com/4227434/67895538-92c84800-fb52-11e9-975f-2fe16a6f61e9.jpg)

Note the vertical lines in the centre of the screen at the top and bottom.

Attached are a log file and RSX capture of Continuum Shift's title screen.

[BLES01487_20191030200315_capture.zip](https://github.com/RPCS3/rpcs3/files/3790984/BLES01487_20191030200315_capture.zip)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3790985/RPCS3.log.gz)

**Comment by digitaldude555** [comment]
![Screenshot (39)](https://user-images.githubusercontent.com/26138653/92949570-f8b87800-f463-11ea-8a32-2b5924c484d3.png)
Fixed can be closed now.

**Comment by AniLeo** [comment]
Closing as fixed

**Comment by Silanda** [comment]
This is **not** fixed as of v0.0.12-10869. Chronophantasma Extend is a different game

**Comment by digitaldude555** [comment]
![Screenshot (316)](https://user-images.githubusercontent.com/26138653/107075776-40fd7b80-67f3-11eb-8566-f14ee8625556.png)
Fixed close it.

**Comment by kd-11** [comment]
Closing as fixed. Request to reopen otherwise.

**Comment by Silanda** [comment]
I'm still seeing it here. Same as before: vertical lines not present under OpenGL or a real PS3, present under Vulkan:
![BBCSE](https://user-images.githubusercontent.com/4227434/107079174-5ff61080-67e7-11eb-85db-329b3f3bad63.png)

Could it be an Nvidia driver issue? I'm using an RTX 3070, and was previously using a GTX1080. Also, I'm testing the European version rather than the US version pictured above. Does that make a difference? No idea, but it might be useful if someone else tests the same version as me: BLES01487.

**Comment by digitaldude555** [comment]
Put the log here, lemme see your settings.

**Comment by Silanda** [comment]
Here you go. Settings should be default since I deleted the config files in order to eliminate the possibility of settings playing a part. I've also tried clearing the caches to make sure old shaders couldn't be a problem,

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5936848/RPCS3.log.gz)

Incidentally, while rare, this isn't the only game where something similar happens. I almost added Mortal Kombat Komplete Edition into the original report, but didn't as I'm not certain the underlying cause is the same. There, the FMV sequences are framed by what looks like a single pixel wide purple border, but only when using Vulkan, not OpenGL.

**Comment by digitaldude555** [comment]
@Silanda fixed?

**Comment by Silanda** [comment]
No. I only tested the title screen but it's the same as it ever was: black lines present using Vulkan, fine using OpenGL.

**Comment by kd-11** [comment]
@Silanda Please try and grab a new RSX capture - unfortunately savestates research caused the old ones to be incompatible. If possible renderdoc captures would also be nice but not required.

**Comment by Silanda** [comment]
No problem. Here's an RSX capture and a link to a renderdoc capture of the title screen (not the same frame).

[BLES01487_20210910125530_capture.zip](https://github.com/RPCS3/rpcs3/files/7143677/BLES01487_20210910125530_capture.zip)

https://mega.nz/file/kOo2WaiA#Q9rOB7K6pGO9bpXwKkfyZuXmCAEhdyLgn-VPHxmI1EQ

**Comment by kd-11** [comment]
Same underlying cause as https://github.com/RPCS3/rpcs3/issues/11091
Specifically, border clamp behaviour during hardware blitting has different behavior on vulkan vs OpenGL. There is no real solution here, I'll eventually add a software blit solution on the GPU to get around this, of course performance won't be great, but output will be correct.

**Comment by DrLegitamate** [comment]
> Incidentally, while rare, this isn't the only game where something similar happens. I almost added Mortal Kombat Komplete Edition into the original report, but didn't as I'm not certain the underlying cause is the same. There, the FMV sequences are framed by what looks like a single pixel wide purple border, but only when using Vulkan, not OpenGL.

I have noticed the purple border in Ratchet and Clank: Tools of destruction during cutscenes

**Comment by kd-11** [comment]
Test https://github.com/RPCS3/rpcs3/pull/13901

**Comment by Silanda** [comment]
I'll have to test when I'm a little less tired, but the problem seems gone but only when upscaling.

**Comment by kd-11** [comment]
If the issue is still present, ask to reopen.
