### ISSUE TITLE
Gran Turismo 5 - Regression - MIP Mapping Scaling

### ISSUE THREAD

**Issue by HHCHunter** [RPCS3/rpcs3#6968]
Due to recently introduced changes with MIP Mapping, GT5 has developed a regression with scaling mip level 1 and beyond, with each higher MIP level, the scale of the texture also increases.

![1](https://user-images.githubusercontent.com/18048891/68521952-f3891a80-02e0-11ea-94b7-61878da45617.png)
![2](https://user-images.githubusercontent.com/18048891/68521953-f3891a80-02e0-11ea-9829-828c02f9b496.png)

A RenderDoc capture of the issue can be seen here.
![image](https://user-images.githubusercontent.com/18048891/68521793-76a97100-02df-11ea-8ab7-f62c6db52081.png)

**Comment by kd-11** [comment]
I need something to analyze and you did not provide any of that. RSX capture file (rrc) and even a renderdoc trace file would be a starting point. I would prefer the RSX capture file in this case.

**Comment by HHCHunter** [comment]
🤦‍♂️My bad, forgot to add to issue.
https://1drv.ms/u/s!AgLgPtiiLQdWj18FIJyEELmgmRVF?e=4Q1JSs

**Comment by kd-11** [comment]
I was not able to get the error. I tried with Vulkan and MSAA both enabed and disabled at 100% res scaling. From your screenshot it seems you were not using any resolution scaling anyway. For both situations the render was correct. Maybe it was fixed in recent builds? Or maybe it is driver/hardware dependent. Retest with current rpcs3 version and attach the log file so I can attempt to recreate the situation.

**Comment by HHCHunter** [comment]
hrmm - interesting, the issue still occurs.

![image](https://user-images.githubusercontent.com/18048891/69486501-1beb4a00-0e87-11ea-844d-d7cd88123bf6.png)
![image](https://user-images.githubusercontent.com/18048891/69486506-2c9bc000-0e87-11ea-86e4-de38b7d34f3a.png)

For the most important info, i'll save you downloading the log.

- PPU Interpreter (PPU Interpreter allows the game to actually be playable, instead of locking up due to RSX desync's)
- GeForce GTX 1080 Ti' running on driver 440.97.0.0, 
- Vulkan
- Resolution Scale: 300%
- MSAA Disabled

Log attached here.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3883022/RPCS3.zip)

**Comment by kd-11** [comment]
Does it happen with resolution scale of 100%?

**Comment by kd-11** [comment]
Also, a renderdoc file would be helpful here since its possible the error is not present in the capture file you gave earlier.

**Comment by HHCHunter** [comment]
> Does it happen with resolution scale of 100%?
Yep!

Weird that it only happens with what seems to be one format of texture. Would love to know more technical information on how this happens, pretty interesting.

RenderDoc File:
https://1drv.ms/u/s!AgLgPtiiLQdWkD3lvDZWuHT4jvm8?e=wdbMXl

**Comment by kd-11** [comment]
Is this still happening?

**Comment by HHCHunter** [comment]
Yeah, I can confirm this is still happening.
If you don't get caught with an RSX desync.

**Comment by kd-11** [comment]
Can you check if https://github.com/RPCS3/rpcs3/pull/7393 changes anything?

**Comment by HHCHunter** [comment]
> Can you check if #7393 changes anything?
I think we're onto a winner here, no wierd scaling issues in the same scenario.

Will look at more testing after the PR is merged, and hopefully close this issue

**Comment by kd-11** [comment]
I'll pre-emptively close this one since the results upto this point were fairly easy to reproduce on the OPs system and the PR is already merged for fixing another bug. If the issue is still there we can reopen.

**Comment by HHCHunter** [comment]
Re-opening, still occurring on latest master.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/8445, please confirm on PR.
