### ISSUE TITLE
Unhandled Exception when loading SPU caches larger than ~3500 modules

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [RPCS3/rpcs3#7033]
I've encountered an issue with the emulator itself, not any specific game.  Other people have said they're not affected by this, so it must be another edge case.

When using the LLVM SPU recompiler, it stops compiling the SPU cache on boot at around 75% and throws an Unhandled Exception error, but only when the SPU cache has reached about 3500 modules or more.  For example, Sly Cooper: Thieves in Time loads fine with the LLVM SPU recompiler when the SPU cache had around 3100 modules, but on the next boot it had just under 7000 modules and throws the Unhandled Exception error.  All of the 24 games in my library are affected by this, even ones in the Playable category such as Skate 3.

All my drivers have been updated, virus/malware/rootkit scans come up clean, Windows has been updated.  All pre-requisites have been installed, too.  This has affected me for the past 10+ builds of RPCS3.  Also, this prevents the emulator from creating a compressed (.gz) version of the log, so I'll be providing the uncompressed (.txt) version as that's all I'll get.

Specs:

Windows 10 Pro 64-bit
Alienware Aurora R5
Intel Core i7-6700K CPU @ 4.00 GHz (8 CPUs)
16384 MB RAM
NVIDIA GeForce GTX 1080
Running on a Samsung EVO 860 2TB SSD (Games also stored on this drive)

Moving the emulator folder out of Program Files didn't fix this.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3898154/RPCS3.log)

**Comment by Nekotekina** [comment]
Please upload spu-safe-v1-tane.dat file from C:/RPCS3/cache/BCUS98247/ppu-P1tPbyQv72FSLipp6by5ifNy1Wuc-EBOOT.BIN/

**Comment by SlyCooperReloadCoded** [comment]
Sorry for the late reply.  Since posting this issue, it went away and I was able to play on an SPU cache larger than 7000.  However the issue has returned and deleting the SPU cache fixes it.  I can't play Just Cause 2 anymore - the SPU cache I attatched is from that game.
[SPU Cache.zip](https://github.com/RPCS3/rpcs3/files/4008433/SPU.Cache.zip)

**Comment by AniLeo** [comment]
Could have been fixed recently, needs retesting

**Comment by digitaldude555** [comment]
@SlyCooperReloadCoded retest.

**Comment by RainbowCookie32** [comment]
I've launched games with 10k modules recently, I'm pretty sure this is no longer an issue. Should probably be closed, OP can ask to reopen if they can still reproduce.

**Comment by SlyCooperReloadCoded** [comment]
Oh no, this hasn't been an issue for months.  Someone in the Discord said it was fixed in an update and it's never happened past that point.
