### ISSUE TITLE
Ratchet and Clank: Into the Nexus Graphics Bug

### ISSUE THREAD

**Issue by SpeddieSwagetti** [RPCS3/rpcs3#7076]
Odd bug found in Ratchet and Clank: Into the Nexus. 
The game exhibits vertex explosions from the guns and volumetric lighting when launching the game normally.
However, the graphics bug disappears by launching and closing another game (doesn't matter what game) then launch Ratchet and Clank: Into the Nexus and the graphics bug will be fixed.

Graphics Broken:
![Broken](https://user-images.githubusercontent.com/48142631/70374844-1c81e700-1943-11ea-8c60-8a6a3043e63e.jpg)

Graphics Fixed:
![Fixed](https://user-images.githubusercontent.com/48142631/70374848-21df3180-1943-11ea-89f3-51121cab1871.jpg)

Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3935047/RPCS3.log.gz)

Broken Graphics RSX Capture:
https://mega.nz/#!C1h2AICT!a7CQ1SMAelLazLLNGA9san6-iNW2ihYjuGka3vMXAhY

Fixed Graphics RSX Capture:
https://mega.nz/#!7kwQmCgC!oMYjW7mXgaSq5uephxnEKeTcOtKHctLq2S5b8AAESfw

**Comment by psennermann** [comment]
"Ratchet & Clank: Full Frontal Assault" has the same problem, but it doesn't get fixed by launching and closing another game...

![Desktop Screenshot 2020 04 11 - 09 46 12 22](https://user-images.githubusercontent.com/6342467/79038464-bd2a3100-7bd9-11ea-8b30-7f983befc5e7.png)

**Comment by Mothban** [comment]
Hi, I have that exact same issue but it doesn't fix when I run another game, is there any way you can help me?

**Comment by andersfischernielsen** [comment]
I have also been unable to fix this by running other games. Playing around with all possible emulation settings does not seem to fix the exploding vertices either. This was for the european version of Nexus.

**Comment by andersfischernielsen** [comment]
![Screenshot 2020-10-23 134202](https://user-images.githubusercontent.com/5990738/97011215-abd9be00-1546-11eb-9d06-f84dac89978f.png)
![Screenshot 2020-10-23 134233](https://user-images.githubusercontent.com/5990738/97011220-ada38180-1546-11eb-8270-0321a010b1cf.png)

**Comment by andersfischernielsen** [comment]
This is still an issue on 0.0.12-11149-06ecc2ae

I've uploaded an [RSX Capture](https://mega.nz/file/jk90ULya#1dqwLTkxsU_xaVXhpYiEQZUoTUWjCaxAE8H5K7_AEvo) if you're interested.

**Comment by stuGaming** [comment]
Still an issue RPCS3 v0.0.15-11846-930895a2 Alpha

**Comment by stuGaming** [comment]
@SpeddieSwagetti Would you mind sharing which game you launched first to fix it?

**Comment by Michael82548** [comment]
Still an issue on RPCS3 Version: 0.0.15-12052-02febd3f Alpha

**Comment by Michael82548** [comment]
Does anyone know a code that removes the affected lighting entirely until this can be fixed?

**Comment by Michael82548** [comment]
Since this also shows up on some guns, this makes the game effectively unplayable for me
![image](https://user-images.githubusercontent.com/53535277/113794314-40606300-9718-11eb-9e13-6e77d6604119.png)

**Comment by kd-11** [comment]
This needs a full updated, including whether starting other games hides the issue.
This will require renderdoc traces from users with compatible devices. Anyone with a pascal card or AMD polaris can capture the bug with renderdoc and provide the trace here for fixed graphics vs unfixed graphics.

**Comment by kd-11** [comment]
Test with https://github.com/RPCS3/rpcs3/pull/10503

**Comment by SpeddieSwagetti** [comment]
Here is the renderdocs for both scenarios using #10503.
https://mega.nz/file/O4wEhQ6Q#cz-P9l9EiDk79mCyTKWqUyJTM_zqls0YE_5CzXGYCG8

Tested with:
i7 4720HQ
GTX 960m
16GB RAM

**Comment by Michael82548** [comment]
Is there even a way to patch those lighting effects out via a hack or romhack as a temporary solution?

**Comment by JimScript** [comment]
Going off of what slipsy said, booting dead nation does fix this issue:
![NPUA80642_screenshot_2021_11_10_07_07_35](https://user-images.githubusercontent.com/66685584/141145326-28b6fa2c-8fbe-481e-b44e-209d82436b00.png)

It is not just covered up as you can see by the shines in the generators and the thundercloud. You boot up dead nation and the problem is just fixed for as long you keep the emulator up. It still works even if you play other games in between, and even if you play RAC then dead nation then back, it still fixes it all the same. But when you close and reopen the emulator, the problem reappears. I don't know what persists per-session rather than per-game or why a fix of all things leaks into other games, but it is interesting.

**Comment by Megamouse** [comment]
I fixed a bug concerning the initialization of the second boot after booting any other game.
Can you try if anything changes with:
https://github.com/RPCS3/rpcs3/pull/11103

If this was the cause for the mysteriously fixed graphics, then at least we know a bit more about the potential way to fix it.
To be honest, I doubt that it changes anything.

**Comment by JimScript** [comment]
As a quick note: The dead nation fixing thread happens even if you set everything to interpreter, have no cache, and only load up to the online agreement then quit; and remains in the third, fourth, and probably all launches afterwords.

**Comment by kd-11** [comment]
Turns out there are 2 issues here:
1. Leaking state from one game to the next. I have a fix for this ready locally, but...
2. Rendering in Into the nexus is indeed broken. I know what causes the broken visuals, but I don't have a proper universal fix just yet. If I fix issue 1 without fixing issue 2 then the dead nation workaround will stop working

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/11151
Please test if the image is stable.

**Comment by andersfischernielsen** [comment]
You’re an absolute legend @kd-11 🙏🏼 
Thanks a ton for the fix!
