### ISSUE TITLE
Ratchet & Clank™: Nexus [BCES01908] Loading saves issue

### ISSUE THREAD

**Issue by mavethee** [RPCS3/rpcs3#7182]
Last working build is #7160 
Broken one is #7161
Screenshots (Last working and broken):
![unknown](https://user-images.githubusercontent.com/47083527/71720053-94e3a700-2e20-11ea-9995-ea7c47eb75cd.png)
![unknown (1)](https://user-images.githubusercontent.com/47083527/71720058-97460100-2e20-11ea-8a8c-4675efe23c06.png)
Logs (Last working and broken):
[RPCS3-9283.log.gz](https://github.com/RPCS3/rpcs3/files/4018852/RPCS3-9283.log.gz)
[RPCS3-9284.log.gz](https://github.com/RPCS3/rpcs3/files/4018853/RPCS3-9284.log.gz)

Tested game is Ratchet & Clank™: Nexus [BCES01908], but other games are indeed affected too, The Last of Us™ [BCES01585] for example :)

**Comment by Megamouse** [comment]
And what exactly is broken?
The dialog you saw in 9283 was wrong, which was fixed in the newer build

**Comment by Radu13** [comment]
I don't know if in older versions kinda worked, on latest version this issue still persist, if you boot the game with a save file already created a black screen will appear instead of the main menu.
Logs:

[log.txt](https://github.com/RPCS3/rpcs3/files/4812242/log.txt)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4812244/RPCS3.log)
[TTY.log](https://github.com/RPCS3/rpcs3/files/4812250/TTY.log)

**Comment by elad335** [comment]
Fixed by #8497

**Comment by mavethee** [comment]
Issue is back or I guess haven't been really fixed, trying to locate where I could break.
If save game exists, game can't reach main menu screen.
Slightly different hardware than once opening this issue.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7020988/RPCS3.log.gz)
![image](https://user-images.githubusercontent.com/47083527/130222774-71694444-a93c-4ac7-9ed1-43ad58767f15.png)

**Comment by mavethee** [comment]
Seems like I have a bad luck to Intel CPUs, on HP Z420 (Xeon E5-1650) and DELL 7567 (i5-7300HQ) I can't load my save data but running on M1 Mac and game loads fine, I'm so confused. I guess I need to buy a real PC.
<img width="1392" alt="Zrzut ekranu 2022-01-7 o 14 11 05" src="https://user-images.githubusercontent.com/47083527/148548957-e6b9fcef-69c5-48c5-8e78-9179954eebe3.png">
