### ISSUE TITLE
Guitar Hero 5 [BLUS30292] graphics flickering

### ISSUE THREAD

**Issue by adrianocolvero** [RPCS3/rpcs3#7256]
Guitar Hero 5 [BLUS30292] graphics flickering

This game is running almost perfectly besides a graphical glitch that makes the characters to get invisible with just the instruments/mic being displayed alone flying around.
This bug comes from long ago, not due to any recently change on the emulator code.

![capture](https://user-images.githubusercontent.com/2258137/72472484-67eda780-37c3-11ea-8579-085f743df964.jpg)

RSX Capture:
[BLUS30292_20200115181600_capture.zip](https://github.com/RPCS3/rpcs3/files/4067593/BLUS30292_20200115181600_capture.zip)

Log:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4067594/RPCS3.log)

Video sample of the glitch: 
https://youtu.be/4jw1whwxJQU

RPCS3 v0.0.8-9380-74ad5255 Alpha
Nvidia GTX 1060 6GB / Vulkan
Intel I7 4790k
16GB RAM DDR3 1600Mhz

**Comment by AniLeo** [comment]
Verified, also happens on the EU disc

**Comment by MrEWhite** [comment]
This occurs with me as well on Guitar Hero Metallica [BLUS30257] and Guitar Hero Warriors of Rock [BLUS30487]

**Comment by 3dsaul** [comment]
> This occurs with me as well on Guitar Hero Metallica [BLUS30257] and Guitar Hero Warriors of Rock [BLUS30487]

It happens me also in Guitar Hero Van Halen [BLUS30291]

**Comment by FailMicroNerd** [comment]
I can confirm this happens with all of the following Guitar Hero games:
Smash Hits [BLUS30290], Guitar Hero 5 [BLUS30292] though only occasionally, Metallica [BLUS30257], and Van Halen [BLUS30291]

I only had some audio and performance issues with Warriors of Rock [BLUS30487], but no flickering graphics surprisingly as reported above by MrEWhite. Nor did I experience any flickering in PS3 Guitar Hero games that I have not listed already.

**Comment by MrEWhite** [comment]
> I can confirm the flickering happens with all of the following Guitar Hero games: Smash Hits [BLUS30290], Guitar Hero 5 [BLUS30292] though only occasionally, Metallica [BLUS30257], and Van Halen [BLUS30291]
> 
> I only had some audio and performance issues with Warriors of Rock [BLUS30487], but no flickering graphics surprisingly as reported above by MrEWhite. Nor did I experience any flickering in PS3 Guitar Hero games that I have not listed already.

I can actually go ahead and confirm that, at some point, Warriors of Rock has been fixed. Just tried it out on 0.0.24-14132 and it doesn't happen anymore.

**Comment by FailMicroNerd** [comment]
> I can actually go ahead and confirm that, at some point, Warriors of Rock has been fixed. Just tried it out on 0.0.24-14132 and it doesn't happen anymore.

I can also confirm now that on 0.0.24-14132, Guitar Hero 5 [BLUS30292] also no longer has flickering. Though, I can unfortunately also confirm all other games I have listed still have the flickering issues.
I feel I should note that I tested these games without applying any available updates (ex: GH5 is 1.00 rather than 1.01) as the games tested are all pulled from my personal disc collection in order to test every single game.

**Comment by FlexBy420** [comment]
Is this still an issue?

**Comment by digant73** [comment]
@AniLeo maybe you could verify if the issues have been fixed

**Comment by ghost** [comment]
Someone do a quick check on this, the two comments above havent been responded to

**Comment by ScottNash042** [comment]
Please close as the OP hasn't updated this issue in nearly 6 years
