### ISSUE TITLE
Realms of Ancient War [NPUB30793] character graphics glitch on Vulkan and opengl

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#7284]
when you go to pick your character the wizards portrait is glitched 
the other 2 are correct
here is a rsx capture
![realms](https://user-images.githubusercontent.com/2696404/72677443-890e0b00-3ad7-11ea-8eb1-9de1fe80bdfa.PNG)
[NPUB30793_20200119160048_capture.zip](https://github.com/RPCS3/rpcs3/files/4082410/NPUB30793_20200119160048_capture.zip)
here is a renderdoc aswell
https://mega.nz/#!tnYxRaxQ!dD1m7hcKCJuQypIxrKv6iY-Aa7ilLf70bIAb-y3k3W8

happens on opengl aswell
![realms](https://user-images.githubusercontent.com/2696404/73236768-82b21a00-41ce-11ea-8fb4-0c1b0d7306c8.PNG)
[NPUB30793_20200128125740_capture.zip](https://github.com/RPCS3/rpcs3/files/4120717/NPUB30793_20200128125740_capture.zip)

**Comment by digitaldude555** [comment]
![Screenshot (1075)](https://user-images.githubusercontent.com/26138653/73790243-d4e3d400-47a8-11ea-8742-e1069965f34d.png)
No longer glitched.

**Comment by benderscruffy** [comment]
still a problem for me
@digitaldude555 do you have a Nvidia card
might be just an AMD card problem

**Comment by digitaldude555** [comment]
Nvidia

**Comment by kd-11** [comment]
This is fixed.

**Comment by benderscruffy** [comment]
still not fixed for me
i removed all caches aswell
![raw](https://user-images.githubusercontent.com/2696404/75626237-df0abe00-5c00-11ea-8889-20fe778af442.PNG)

**Comment by dulsan** [comment]
Will turning on the color buffers fix this issue?

**Comment by kd-11** [comment]
This is not an emulator bug, its actually a typical emulator vs realhw issue which is why it works on NVIDIA. The game ships with a custom swizzled texture format and does some math to fetch the real data from a scrambled texture. NVIDIA GPUs still largely behave the same way they did 15 years ago which is why they work - they're actually a bit less accurate than AMD but the game was designed with that in mind. For example AMD GPU can calculate a value of 0.63198 while NV GPU is rounding the math to something like 0.6320. There is then some multiplication with some very large numbers like 2048 which blows up this small error into a bigger gap.
I feel it would be unreasonable to attempt to work with such constraints, so this is largely a won't fix from my side. If anyone has any practical suggestions, feel free to pass them my way.
