### ISSUE TITLE
Modnation Racers - Texture Issues

### ISSUE THREAD

**Issue by shanzenos** [RPCS3/rpcs3#7365]
Version: Current Release (v0.0.8-9488 Alpha [2020-02-01])

Ever since it's been playable Modnation Racers has had a texture bug where character/kart textures will corrupt or combine with other characters/kart textures when in-game. Creation station shows everything correctly but modspot & races do not for most costumes, although some appear to work.  Most costumes that do render correctly have corrupted textures the next time they are loaded ingame, and stay that way afterward.

An example for characters:
![espresso_corrupt](https://user-images.githubusercontent.com/16732437/73596412-f36b7600-44ef-11ea-83f1-1b48554c4b21.png)
Texture corrupted character

![Espresso JPG](https://user-images.githubusercontent.com/16732437/73596422-0b42fa00-44f0-11ea-8e87-177e5c5fc7bf.jpg)
Original hardware/correct rendering

An example for karts:
![working kart](https://user-images.githubusercontent.com/16732437/73596551-e307cb00-44f0-11ea-8884-8b2825505680.png)
Correct kart render

![corrupted kart](https://user-images.githubusercontent.com/16732437/73596556-f155e700-44f0-11ea-918c-582d2510d44f.png)
Texture corrupted kart

**Comment by jokoputera** [comment]
Log file

**Comment by shanzenos** [comment]
> Log file
Updated main post to include log and also the instance the error occurs in the log.

**Comment by AniLeo** [comment]
Requires retesting with #8367

**Comment by shanzenos** [comment]
Tested with most recent build, issue remains the same @AniLeo

**Comment by ShockinglySane** [comment]
Can confirm that as of last night the issue STILL remains. It's a shame.

**Comment by Avaris0** [comment]
has anybody found a fix for this yet?

**Comment by martinsaenz96** [comment]
I'm having the exact same issue with mine on ver 01.11
I wish there was a way to resolve this issue

**Comment by BrunoRaji** [comment]
i7-9700KF
2070 Super

![image](https://user-images.githubusercontent.com/36604893/102026354-27543080-3d7c-11eb-90c2-2f70f1e19695.png)

**Comment by martinsaenz96** [comment]
Your having the same problem?

**Comment by ZackXevious** [comment]
As of 3/20/2021, issue remains. Other than that, the game is playable.

**Comment by SatansFavSuccubus** [comment]
Has there been any progress on this?

**Comment by Computerlabrat** [comment]
What I've noticed is if you save a custom character or a kart in creation station, it will look right in mod spot for the time being, but if you change to a different custom character or kart entirely or you restart the game, it will be problematic. This is also problematic for stuff downloaded as it's been very rare to be able to remix stuff from what I've seen.

**Comment by UngaPunga** [comment]
Hey, don't know if anyone is still active or not but I haven't found a solution to the bug. Plz, I hope someone finds it because I really love this game.

**Comment by RainbowCookie32** [comment]
The issue is still open, so it wasn't fixed yet.

**Comment by UngaPunga** [comment]
Hopefully, someday someone will find a fix for it :( I really love this game

**Comment by rbross3030** [comment]
Just discovered the same issue here, but seems to me to be stemming specifically from 1.11 update. I installed the original un-patched game, created a custom kart and character, saved the game, then installed 1.11 and created second kart and character. The new kart and character had glitched out textures, not just when using them outside of modstation, but their thumbnails at the selection screen were also glitched out, while I could still load the original kart and character created on 1.09 without issue.

**Comment by jamiefranks** [comment]
Can confirm this issue is still ongoing

side note that I’ve used the recommended settings for ModNation on the Steam Deck but there are big audio stutters and frame rate drops

**Comment by martinsaenz96** [comment]
> Can confirm this issue is still ongoing
> 
> side note that I’ve used the recommended settings for ModNation on the Steam Deck but there are big audio stutters and frame rate drops

How has this issue not been resolved yet? It's been about 2 years since I commented on this issue, and it still persists. I can't have the definitive experience (update 01.11 with all DLCs) without ever running into this issue it's infuriating!!

Someone please fix this issue!!
I love this game to pieces and I don't have a PS3 anymore, meaning that I have no other way of playing it other than emulation because of Sony's piss poor attempt at backwards compatibility on modern hardware!! );

**Comment by Asinin3** [comment]
It's been 2 years and no one has bothered to post a RSX Capture/Renderdoc*
Also complaining doesn't get things fixed faster. Do you not see how many hundreds of issues there are on the tracker? We have one graphics developer who is paid and the rest aside from neko are all volunteers.

**Comment by Revenge209** [comment]
The textures on my creations also get corrupted. Might as well stick to the UFG creations for now.

**Comment by SackBoyGMR** [comment]
Currently uploading some RSX Captures of Creation Station of the respective Kart and Mod, one in the Modspot, One at the beginning of a race and one during the end sequence along with the log itself after closing RPCS3, hopefully someone can make use of that to find the issue within what is causing this

**Comment by SackBoyGMR** [comment]
[Here is the folder containing said items](https://drive.google.com/drive/folders/1mC000s7jNQrWJSFIcGWkMkGzT9z34ym6?usp=share_link), hopefully this helps whoever wants to tackle this!

**Comment by martinsaenz96** [comment]
> Currently uploading some RSX Captures of Creation Station of the respective Kart and Mod, one in the Modspot, One at the beginning of a race and one during the end sequence along with the log itself after closing RPCS3, hopefully someone can make use of that to find the issue within what is causing this

What is this, and what does that mean?

**Comment by Jonathan44062** [comment]
@martinsaenz96 RSX Capture helps kd-11 to analyze the graphic problem, which none of you did, and that's why it was forgotten, the report was incomplete, it had no information, but thanks to that person who put the necessary information, RSX Capture, kd-11 will be able to work on it and see what is the problem of the broken textures.

**Comment by SackBoyGMR** [comment]
Hopefully the RSX captures are enough to solve this issue, I will be willing to provide more as needed when requested so hopefully kd-11 can fix this with the already provided captures.

**Comment by Dirtdobber205** [comment]
Hey just joined this thread looking for any resolution to this. Is there any version where customization works, or any progress on this version?

**Comment by DangerShadowGamer** [comment]
Any updates on the issue so far?

**Comment by martinsaenz96** [comment]
> Hey just joined this thread looking for any resolution to this. Is there any version where customization works, or any progress on this version?

For now only update 01.00 works.

**Comment by DangerShadowGamer** [comment]
Will there ever be a way to fix the issue with 01.11?

**Comment by martinsaenz96** [comment]
> When I update Modnation Racers, it corrupts the textures

That's what I've been saying. Only update 01.00 works without this issue. I wish it was fixed by now.

**Comment by SatansFavSuccubus** [comment]
If you spend long enough inside the Creation Station, the textures will be perfectly fine when you leave but I think it lasts until you start the game again.
![image](https://user-images.githubusercontent.com/88169925/227736133-6e8e4582-6f6a-454e-a712-34736808c789.png)

**Comment by Virjoinga** [comment]
I've made two RSX captures, one in the ModSpot and one in the Creation Station to hopefully narrow down the issue. The files are too big so I have uploaded them to Google Drive.
This one is for the ModSpot:
https://drive.google.com/file/d/1MPtzBV_lSUh5q7PcD45oYY9u69HzWEMs/view?usp=drive_link
This one is for the Creation Station:
https://drive.google.com/file/d/14VoV4eIa-_CpDFWFB3pwH1Qtx4c5KZHq/view?usp=drive_link
Hopefully this helps :)

**Comment by JimScript** [comment]
This is the oddest glitch on when it works and when it doesn't, apparently _sometimes_ you can fix the texture issues on a kart if you modify it through nearly any way, and somehow it also fixes other karts that have the _exact_ same paint job even if that's not what you modified. Like if you made a copy of your kart with the engine having a slightly different color, then the _original_ kart is somehow fixed for that instance, even if you load it in after you have your broken kart in first. But it breaks again if select any kart with a different paintjob, and even selecting another unique kart with the same paintjob won't fix it again, this workaround only works once per load. But it only works once with every _exact_ configuration, and not every time too. There's got to be something strange with how the game is loading in user made textures, this would make much more sense if they were just broken all the time.

**Comment by JimScript** [comment]
Here's a video demonstration:

https://github.com/RPCS3/rpcs3/assets/66685584/06342344-6f39-4d24-9c29-74f4418e7cc5

And the log to go with it:
[RPCS3MNRpaint.log](https://github.com/RPCS3/rpcs3/files/12263336/RPCS3MNRpaint.log)

**Comment by martinsaenz96** [comment]
> I've made two RSX captures, one in the ModSpot and one in the Creation Station to hopefully narrow down the issue. The files are too big so I have uploaded them to Google Drive. This one is for the ModSpot: https://drive.google.com/file/d/1MPtzBV_lSUh5q7PcD45oYY9u69HzWEMs/view?usp=drive_link This one is for the Creation Station: https://drive.google.com/file/d/14VoV4eIa-_CpDFWFB3pwH1Qtx4c5KZHq/view?usp=drive_link Hopefully this helps :)

What do these do?

**Comment by martinsaenz96** [comment]
> Here's a video demonstration:
> 
>  MNRpaint.mp4 
> And the log to go with it: [RPCS3MNRpaint.log](https://github.com/RPCS3/rpcs3/files/12263336/RPCS3MNRpaint.log)

It also does it on UFG & DLC mods and karts. I'm still hoping someone can find out the cause of it all and patch it up to where it's working like normal.

**Comment by martinsaenz96** [comment]
![image](https://github.com/RPCS3/rpcs3/assets/64726923/04346afa-0fe0-4697-8ef8-d705473fc686)

**Comment by JimScript** [comment]
Well I might as well add some RSX captures to work with:
[MNRBeforeFix.zip](https://github.com/RPCS3/rpcs3/files/12266802/MNRBeforeFix.zip)
[MNRDuringFix.zip](https://github.com/RPCS3/rpcs3/files/12266804/MNRDuringFix.zip)
[MNRAfterFix.zip](https://github.com/RPCS3/rpcs3/files/12266806/MNRAfterFix.zip)
But I'm not sure how this will help, the issue seems to happen when the game is loading in the texture rather than displaying it, unless the RSX capture records texture load ins.

**Comment by JimScript** [comment]
I knew these RSX captures would be no good, this is what _all of them_ look like when I load them in:
![TagBrokenImage](https://github.com/RPCS3/rpcs3/assets/66685584/05ba32b2-d288-4889-97e8-5320fd7e7dfb)
And Tag isn't even a broken character in the actual game:
![TagFixedImage](https://github.com/RPCS3/rpcs3/assets/66685584/ad61fe5b-c2c7-408e-8d7f-60cbacef3da4)
And when I inspect their textures in the renderdoc, I get this:
![TagBrokenTexture](https://github.com/RPCS3/rpcs3/assets/66685584/eb6d480b-035d-49ed-b323-f7bad1812942)
![TagFixedTexture](https://github.com/RPCS3/rpcs3/assets/66685584/e6403e37-0c1d-4f8e-955d-12b39ed917bf)
It's interesting that the broken texture is half the resolution as the working one, even though they're both B5G6R5_UNORM, so something is clearly wrong with how these textures are loaded in.

**Comment by martinsaenz96** [comment]
So how can we fix it?

**Comment by JimScript** [comment]
My idea is to provide enough information to the developers so that it is easier for them fix it. Speaking of which, I found where the composite textures are stored for the game, they're in the game data folder(and not the UCC one) in USRDIR/DATA/COMPOSITES. The ones the game comes with are in ROM/COMPRESSED and the ones made in the game are in LOCAL_2/COMPRESSED, and strangely enough not all base game items come pre-rendered in the ROM folder, that's why some of them appear glitchy too. Funny thing is, when you delete all the files in the LOCAL_2/COMPRESSED folder all the stuff works exactly _once_, meaning if there's a duplicate item with the same texture it'll be glitchy while the first item rendered will be fine. So that could mean that the game is making garbage B5G6R5 files, but that doesn't explain why Tag's texture(which is in the ROM/COMPRESSED folder) is broken in RSX captures, so maybe it is how the game loads the textures in(or both).

**Comment by kd-11** [comment]
A lot of the bugs reported here (assuming I'm reading this correctly) aren't about a whole texture being wrong, but a normal correct texture with corrupted data added to it. In that case it's runtime corruption likely due to DMA race conditions.
1. Does the problem occur with OpenGL?
2. If using vulkan, does the "Host GPU Labels" option make any difference?
3. How about accurate RSX reservations + the above?

**Comment by JimScript** [comment]
Nope, nothing changed with any of these settings, I think I even tried Strict Rendering Mode before. The best workaround I can get going is flushing out the USRDIR/DATA/COMPOSITES/LOCAL_2/COMPRESSED folder. (Oh yeah and sorry for the bug report spam)

**Comment by Virjoinga** [comment]
> Nope, nothing changed with any of these settings, I think I even tried Strict Rendering Mode before. The best workaround I can get going is flushing out the USRDIR/DATA/COMPOSITES/LOCAL_2/COMPRESSED folder. (Oh yeah and sorry for the bug report spam) Edit: OK so turning these on and flushing the textures worked, so thank you very much.

So what does that mean? Did that fix the problem?

**Comment by JimScript** [comment]
Yeah, but I'm currently testing to see which part cured it, I just put all of them at once.

**Comment by Virjoinga** [comment]
> Yeah, but I'm currently testing to see which part cured it, I just put all of them at once. Edit: Well it looks like OpenGL fixed it, so I guess the problem is that Vulkan is making garbage B5G6R5 textures(or at least garbage files with added stuff).


I forgot to ask, how did you "flush" the textures? I booted the game with OpenGL and the textures are still messed up.

**Comment by JimScript** [comment]
> I forgot to ask, how did you "flush" the textures? I booted the game with OpenGL and the textures are still messed up.

Maybe saying "flush" is the wrong word, but what I did was I when into the game data folder and then in went into USRDIR/DATA/COMPOSITES/LOCAL_2/COMPRESSED and deleted every file in there(well actually I deleted the whole COMPRESSED folder then made another empty one). It should fill back up again with textures that OpenGL is making correctly, although that means you can't turn it back to Vulkan until this issue is fixed, or you'll get more broken textures in the mix.

**Comment by Virjoinga** [comment]
> > I forgot to ask, how did you "flush" the textures? I booted the game with OpenGL and the textures are still messed up.
> 
> Maybe saying "flush" is the wrong word, but what I did was I when into the game data folder and then in went into USRDIR/DATA/COMPOSITES/LOCAL_2/COMPRESSED and deleted every file in there(well actually I deleted the whole COMPRESSED folder then made another empty one). It should fill back up again with textures that OpenGL is making correctly, although that means you can't turn it back to Vulkan until this issue is fixed, or you'll get more broken textures in the mix.

Oh so the graphics API creates textures to be displayed in-game? It is just how Vulkan is doing it is wrong in this game?

**Comment by JimScript** [comment]
> Oh so the graphics API creates textures to be displayed in-game? It is just how Vulkan is doing it is wrong in this game?

It seems to put it all together correctly(as the first instance looks right), it just doesn't seem to save it all that well(at least the diffuse ones, the normal and specular map seem fine).

**Comment by Virjoinga** [comment]
> > Oh so the graphics API creates textures to be displayed in-game? It is just how Vulkan is doing it is wrong in this game?
> 
> It seems to put it all together correctly(as the first instance looks right), it just doesn't seem to save it all that well(at least the diffuse ones, the normal and specular map seem fine).

From what you said earlier, I wonder if Vulkan cannot create these B5G6R5 correctly but for whatever reason, OpenGL can. It is weird though that updating the game version introduces the issue.

**Comment by JimScript** [comment]
> From what you said earlier, I wonder if Vulkan cannot create these B5G6R5 correctly but for whatever reason, OpenGL can. It is weird though that updating the game version introduces the issue.

Upon closer inspection of the file created, it looks like the BC1 Normal and Specular files _can_ be broken(or at least distinct from OpenGl's), just less often and in less obvious ways. So the issue is just Vulkan generally not saving textures well.

**Comment by kd-11** [comment]
Is there any reliable way of triggering the bug that doesn't involve playing the game for any reasonable amount of time?

**Comment by Virjoinga** [comment]
> Is there any reliable way of triggering the bug that doesn't involve playing the game for any reasonable amount of time?

When using Vulkan all you need to do is go to the creation station and then leave, after that all mods and karts will have corrupt textures.

**Comment by JimScript** [comment]
Or just spawn directly into Modspot, it'll build the textures right away.

**Comment by Virjoinga** [comment]
> Or just spawn directly into Modspot, it'll build the textures right away.

yes it will but you won't see the effects until reloading the level/ area/ or game.

**Comment by JimScript** [comment]
> yes it will but you won't see the effects until reloading the level/ area/ or game.

Actually reloading is as simple as flipping between karts/characters, it's much faster.

**Comment by martinsaenz96** [comment]
Would this mean that the issue is fixed? And if so, how would I employment it?

**Comment by Virjoinga** [comment]
> Would this mean that the issue is fixed? And if so, how would I employment it?

No, this does not fix it. Using OpenGL just seems to fix the diffuse textures but not the reflection maps. It also runs worse because OpenGL is a software renderer. If you want to play the game with OpenGL with mostly correct visuals, go ahead, but you are better off waiting for a fix.

**Comment by martinsaenz96** [comment]
I'm just gonna wait and see if there's a fix

**Comment by Virjoinga** [comment]
> > > Would this mean that the issue is fixed? And if so, how would I employment it?
> > 
> > 
> > No, this does not fix it. Using OpenGL just seems to fix the diffuse textures but not the reflection maps. It also runs worse because OpenGL is a software renderer. If you want to play the game with OpenGL with mostly correct visuals, go ahead, but you are better off waiting for a fix.
> 
> Did you get that the reflection maps in OpenGL are broken from me or did you observe it yourself? OpenGL seems to work as intended, but you're right in that it's no replacement with how badly it runs compared to Vulkan(along with OpenGL have visual glitches in Linux).

I observed it myself, it is a pretty obvious bug. Also we should stop talking here unless if we have more information on the bug.

**Comment by martinsaenz96** [comment]
Is it on the emulator's end that's causing this issue?
And how has the fix progress been going?

**Comment by DangerShadowGamer** [comment]
Any news?

**Comment by JimScript** [comment]
No, I'm guessing the developers are busy with other things, we shouldn't pester them.

**Comment by knifecat35** [comment]
I do too also have this issue, and I hope it gets fixed sometime,

**Comment by DangerShadowGamer** [comment]
Let's just wait patiently and some day it will get fixed. Best thing we can do atm.

**Comment by Crimson03Ghost** [comment]
Can someone direct me to a place where I can get 1.0, or somehow downgrade my current version so I can at least play that? Someone said 1.0 doesn't have the texture bug

**Comment by Virjoinga** [comment]
> Can someone direct me to a place where I can get 1.0, or somehow downgrade my current version so I can at least play that? Someone said 1.0 doesn't have the texture bug

Does the bug still occur for you on the latest release? For me it no longer occurs, it only affects the Mod statues in the ModSpot for me now.

**Comment by JimScript** [comment]
> > Can someone direct me to a place where I can get 1.0, or somehow downgrade my current version so I can at least play that? Someone said 1.0 doesn't have the texture bug
> 
> Does the bug still occur for you on the latest release? For me it no longer occurs, it only affects the Mod statues in the ModSpot for me now.

![BCUS98167_screenshot_2024_03_06_20_54_00](https://github.com/RPCS3/rpcs3/assets/66685584/3a6646fa-f82f-4454-8f79-fc1037712b9f)
Still occurs for me, and I made sure these were freshly made texture files. Are you sure it works on your end, have you made a new thing then flip though it twice to show the saved texture? Because Mod statues apparently have distinct texture files from the Mods themselves, unlike Karts which use the same one. Here's a log file for my end:
[RPCS3_Modnation_Texture_Error.log](https://github.com/RPCS3/rpcs3/files/14518978/RPCS3_Modnation_Texture_Error.log)

**Comment by Virjoinga** [comment]
> > > Can someone direct me to a place where I can get 1.0, or somehow downgrade my current version so I can at least play that? Someone said 1.0 doesn't have the texture bug
> > 
> > Does the bug still occur for you on the latest release? For me it no longer occurs, it only affects the Mod statues in the ModSpot for me now.
> 
> ![BCUS98167_screenshot_2024_03_06_20_54_00](https://github.com/RPCS3/rpcs3/assets/66685584/3a6646fa-f82f-4454-8f79-fc1037712b9f)
> Still occurs for me, and I made sure these were freshly made texture files. Are you sure it works on your end, have you made a new thing then flip though it twice to show the saved texture? Because Mod statues apparently have distinct texture files from the Mods themselves, unlike Karts which use the same one. Here's a log file for my end:
> [RPCS3_Modnation_Texture_Error.log](https://github.com/RPCS3/rpcs3/files/14518978/RPCS3_Modnation_Texture_Error.log)
> 

I rechecked and no it doesn't work still, sorry for late reply.

**Comment by Drflash55** [comment]
Seems like it's still an issue past mid-2024, huh?
It's very persistent at sticking around, that's for sure.

**Comment by Snewper16** [comment]
> Seems like it's still an issue past mid-2024, huh? It's very persistent at sticking around, that's for sure.
> 
> EDIT: If you join the ModNation Racers Discord server (for derole), they have a patch in the "#useful-links" channel for 01.11 that fixes the texture issues by disabling the customization cache, in exchange for slower load times.

The invite for the server seems to have expired, is there anywhere else I can find this patch?

**Comment by Strawberry-Fox** [comment]
> > Seems like it's still an issue past mid-2024, huh? It's very persistent at sticking around, that's for sure.
> > EDIT: If you join the ModNation Racers Discord server (for derole), they have a patch in the "#useful-links" channel for 01.11 that fixes the texture issues by disabling the customization cache, in exchange for slower load times.
> 
> The invite for the server seems to have expired, is there anywhere else I can find this patch?

I grabbed the patch from the server a few days ago, I'll post it here.
[imported_patch.zip](https://github.com/user-attachments/files/17897018/imported_patch.zip)

**Comment by Jonathan44062** [comment]
Still an issue
![Image](https://github.com/user-attachments/assets/70314f42-2d0e-4a5c-aa61-844d61c8b227)

I hope this RSX Capture can help
[BCUS98167_20250308202953_capture.rrc.gz](https://github.com/user-attachments/files/19147123/BCUS98167_20250308202953_capture.rrc.gz)

**Comment by T3362** [comment]
Cause of the texturing issue has been identified.
( still unknown for Mod statues ).

It appears that if VBlank is set higher than 60Hz, the kart and mod textures are not loading correctly both during and after the race/After exiting the Creation station
(The same goes for creating a course)

![Image](https://github.com/user-attachments/assets/c43980f2-b176-4457-8ba0-56bd5ca5f163)
in 60Hz after Race/After exiting the Creation station. Textures did not break.

![Image](https://github.com/user-attachments/assets/40f2e264-c502-472f-a82d-a7492aea645c)
but in 90 Hz or higher after Race/After exiting the Creation station. It breaks texture.

**Comment by cotamilhas** [comment]
a new patch is available 

right click > manage game patches > enable customization cache

**Comment by jokoputera** [comment]
> a new patch is available
> 
> right click > manage game patches > enable customization cache

hopefully this patch able to let RPCS3 teams pinout which one is the problem

**Comment by kd-11** [comment]
The issue with this engine is how it packs assets. To debug the issue you basically have to record the API calls over a few minutes then comb over them frame by frame, draw by draw to figure out when the corruption happened internally. That would take several days to analyze assuming no other work is undertaken.
I'm not saying it won't get fixed, I'm just saying it's better to use the patch in the meantime.

**Comment by digant73** [comment]
@JimScript, @Jonathan44062 is that still an  issue?

**Comment by Virjoinga** [comment]
> [@JimScript](https://github.com/JimScript), [@Jonathan44062](https://github.com/Jonathan44062) is that still an issue?

Yes. There is a patch to disable caching but that's not a proper fix to the problem.

**Comment by digant73** [comment]
please re-test on latest build. Hopefully some textures and reflections issues have been fixed by recent build 0.0.39-18790

**Comment by Jonathan44062** [comment]
<img width="2559" height="1388" alt="Image" src="https://github.com/user-attachments/assets/0fc083a1-d10e-434b-b812-5ca7bdf7ad68" />
Still an issue, latest

**Comment by cotamilhas** [comment]
I had no reflections issues but textures have the same issue

**Comment by Strawberry-Fox** [comment]
Can confirm, reflections look perfect, but the texture cache corruptions still appear to be happening. The texture corruption I got here is quite interesting. Tag is fine, but like, half of my kart has this weird line pattern which isn't anything like the ones we were getting before. Kicking myself that I didn't take more screenshots or a frame capture.
<img width="5760" height="2160" alt="Image" src="https://github.com/user-attachments/assets/ee99ba85-baea-4133-826f-61531a6a5c67" />
This screenshot also includes my RPCS3 window, which has a bit of the log in it which might be helpful. I tried to upload the actual log file, but it's failing for some reason. Sorry about that.

**Comment by Virjoinga** [comment]
> please re-test on latest build. Hopefully some textures and reflections issues have been fixed by recent build 0.0.39-18790

idk if this is related to the issue but the weird pinky purple thing still occurs.

<img width="3440" height="1342" alt="Image" src="https://github.com/user-attachments/assets/10344cb9-0bfd-4b12-9535-fe2c603e2315" />

**Comment by Jonathan44062** [comment]
@Virjoinga That's because of res scaling issue, native 100% 720p looks normal, since resolution is a hack, does not work in every game, these reports are not valid

**Comment by JustMoneko** [comment]
"Pinky purple thing" is a known issue when upscaling, read the recommended configs on the wiki to fix it. 
Not the same issue as texture corruption.

**Comment by alexconsole04** [comment]
Still broken
<img width="2560" height="1401" alt="Image" src="https://github.com/user-attachments/assets/f4705598-003a-433a-a5b3-d3fcc9bc9f0a" />

[RPCS3.log.gz](https://github.com/user-attachments/files/27152322/RPCS3.log.gz)

**Comment by rleonever** [comment]
Hello, can someone test again? @alexconsole04 with recent RSX improvements, this issue may be fixed.

**Comment by Jonathan44062** [comment]
Still broken
<img width="2559" height="1390" alt="Image" src="https://github.com/user-attachments/assets/4170d68d-235a-4779-b4ec-ac3ba4fd0c60" />

<img width="2559" height="1394" alt="Image" src="https://github.com/user-attachments/assets/76d0c89f-8719-452e-8dce-fb0de88ed7ae" />

**Comment by Strawberry-Fox** [comment]
I can also confirm that it is still not working.

I made sure to delete my old customization cache, and of course I disabled the patch.
<img width="960" height="540" alt="Image" src="https://github.com/user-attachments/assets/23c8b08f-14d5-4528-896e-f7167808f9de" />

**Comment by cotamilhas** [comment]
the latest update appears to have fixed most of the texture corruption issues with mods and karts, most textures now render correctly in game

however, there is still a graphical issue with the material/color effects. the game allows applying effects such as transparency, metal, rubber and candy to sticker colors and mod/kart colors, but these effects are not rendered correctly

current update
<img width="768" height="601" alt="Image" src="https://github.com/user-attachments/assets/12946152-b667-41cd-8997-c82fa831bab0" />

<img width="1143" height="812" alt="Image" src="https://github.com/user-attachments/assets/334be402-127f-4f91-8b7f-531a9bff42e7" />

current update with "Disable Customization Cache" patch

<img width="926" height="573" alt="Image" src="https://github.com/user-attachments/assets/f471ec03-00b5-4450-a5c2-b48478966e99" />

<img width="866" height="757" alt="Image" src="https://github.com/user-attachments/assets/7f185bdb-011c-42f9-b4a4-602cec1b7fb8" />

Logs

[ModNation Racers \[NPUA80535\].log.gz](https://github.com/user-attachments/files/32072270/ModNation.Racers.NPUA80535.log.gz)

**Comment by Drflash55** [comment]
Whoa...that's insane to see how far this bug has come to being fixed.

**Comment by JimScript** [comment]
I just noticed that the composite textures scale with the Resolution Scale, but they're saved all at the same resolution. Meaning if you play at 300% resolution it'll make your texture that much more detailed but then the game will compress it down to how its normally suppose to be, and that may have some effect on some of the textures that need more precision. To me it feels like a justification to keep the patch on even with the fix.

**Comment by Strawberry-Fox** [comment]
Unfortunately it doesn't seem like the problem is solved.

I updated RPCS3. I cleared the customization cache before this test. I did not clear it during the test. I do not have the patch on.

I took the first screenshot when I first loaded in, and then took another after entering and exiting the Creation Station, and then repeating that.

<img width="960" height="540" alt="Image" src="https://github.com/user-attachments/assets/dd3a295f-47a9-4071-b90a-d1d96aa63736" />
<img width="960" height="540" alt="Image" src="https://github.com/user-attachments/assets/31229ff8-164f-4a94-84a2-e4ba33901e9a" />
<img width="960" height="540" alt="Image" src="https://github.com/user-attachments/assets/c1247a6c-7b27-43af-9197-ae7ea0d7c635" />
<img width="960" height="540" alt="Image" src="https://github.com/user-attachments/assets/6d4f6bb6-dd83-4aa9-88d5-0f07f7b5d044" />
<img width="960" height="540" alt="Image" src="https://github.com/user-attachments/assets/87b90f98-5a3c-4d80-a457-31ba4c5323ea" />
<img width="960" height="540" alt="Image" src="https://github.com/user-attachments/assets/d41eb199-2ce4-4d45-aa35-86964ceba1c6" />

I then decided to close the game and open it again. This was the results immediately, followed by a single "Creation Station" reload.

<img width="960" height="540" alt="Image" src="https://github.com/user-attachments/assets/169f6462-89eb-4e8f-86d5-9426ce80497b" />
<img width="960" height="540" alt="Image" src="https://github.com/user-attachments/assets/b18bfa24-e587-4c83-a8c2-1e4b9a1e9219" />

This is very odd. It seems like closing the game and opening it again temporarily makes the problem go away. This _could_ be due to the fact that I did my testing with a built in kart, so I'll have to check it with a custom one, but I feel this is still important information.
And another thing, certain parts of the karts texture appear to be corrupted one time, but then fine afterwards. Particularly the bonnet.
Not to mention the fact that the corruptions in screenshots 2, 4 and 8 appear to look very similar, if not identical.

**Comment by kd-11** [comment]
It's because the data is procedurally generated as the level is loading. The only way to solve that is by forcing legacy shader compiler if the ssync+interpreter option is not precise enough. If the asset generation steps skip or are rendered incorrectly during that one draw call, then the effect persists until reload.

**Comment by jokoputera** [comment]
Isnt that solved by using 'Strict Rendering'?

**Comment by kd-11** [comment]
I cannot recall if strict render forces legacy, it probably does and I forgot.

**Comment by jokoputera** [comment]
Sorry, i mean, if you force Strict Rendering, shouldnt this be solved: "The only way to solve that is by forcing legacy shader compiler if the ssync+interpreter option is not precise enough"?

Because its : strict rendering, right? I dont know, maybe i miss interpret the option, as i dont have Modnation
