### ISSUE TITLE
Ratchet&Clank Trilogy [BLES01503] - games fails to boot with 'RSX multithread' since 0.0.8.9693

### ISSUE THREAD

**Issue by Sgtbomber91** [RPCS3/rpcs3#7613]
Latest working release: 0.0.8.9688
[RPCS3_0.0.8.9688_OK.log.gz](https://github.com/RPCS3/rpcs3/files/4262140/RPCS3_0.0.8.9688_OK.log.gz)

First non-working release: **0.0.8.9693**
[RPCS3_0.0.8.9693_KO.log.gz](https://github.com/RPCS3/rpcs3/files/4262136/RPCS3_0.0.8.9693_KO.log.gz)

Doesn't work on current build (0.0.8.9739)

Game selector works fine. Selecting a game freezes and crashes the emulator.
I had to manually kill the process and zip the log.

Changing PPU and/or SPU recompiler/interpreter doesn't change the result.

**Comment by jeremybris** [comment]
I am also experiencing this regression in 

- God of War Ascension [NPUA80918]
- Metal Gear Solid 4 [NPUB31633]

Since #7566 
It is only prevalent if you check "GPU - Multithreaded RSX"
There is a workaround if you uncheck that, but I think you will lose FPS.

**Comment by Sgtbomber91** [comment]
I retested with "RSX Multithread" disabled.

**0.0.8.9693** the game boots, level loads nicely.
Performance impact seems negative (off-topic, i think saw a 1-2 FPS improvement without RSX Multithread; Ryzen 1700 @3.9Ghz)
[RPCS3_0.0.8.9693_no_RSX_multithread.log.gz](https://github.com/RPCS3/rpcs3/files/4262892/RPCS3_0.0.8.9693_no_RSX_multithread.log.gz)


Against current build - **0.0.8.9739**:
when you select a game from game selector, the emulator render window freezes completely.
Pressing "stop" in emultor, everything stops as expected, but after about 1 second, the game you were supposed to boot, starts booting  up (weird!)
[RPCS3_0.0.8.9739_no_RSX_multithread.log.gz](https://github.com/RPCS3/rpcs3/files/4262900/RPCS3_0.0.8.9739_no_RSX_multithread.log.gz)

**Comment by lainiwaku** [comment]
same  with resistance 1 since a recent build, game crashed when multithread activated ona  recent build but i was not sure since wich one,  i suppose it related

**Comment by money123451** [comment]
yap resistance 1 also dose and on linux with any build beyond that it will cause issues as well with hanging

**Comment by Nekotekina** [comment]
Should be fixed now, please retest.

**Comment by money123451** [comment]
resistance is fixed. other people will have to test the other games.

**Comment by Sgtbomber91** [comment]
latest 0.0.8.9758 **doesn't** fix Ratchet&Clank Trilogy [BLES01503]
[RPCS3_0.0.8.9758.log.gz](https://github.com/RPCS3/rpcs3/files/4268333/RPCS3_0.0.8.9758.log.gz)

"RSX Multithread" still crashes the emulator when a game is selected from the game selector.

**Comment by jeremybris** [comment]
- God of War Ascension [NPUA80918]
- Metal Gear Solid 4 [NPUB31633]
- Advanced Warfighter 2 [BLUS30034]

Still do not run with "GPU - Multithreaded RSX" checked.

**Comment by MSuih** [comment]
Unable to reproduce in Ratchet & clank trilogy

**Comment by Sgtbomber91** [comment]
i did a quick retest with latest build **0.0.9.9815**

"RSX Multithread" still causes the emulator to freeze upon game selection.
Pressing "stop" from main emulator window, the emulator locks up completely.
[RPCS3_0.0.9.9815_RSX_Multithread.log.gz](https://github.com/RPCS3/rpcs3/files/4288192/RPCS3_0.0.9.9815_RSX_Multithread.log.gz)


without "RSX Multithread" the behavior is the same, except that the games boots up only after a manual "stop" from emulator main window
[RPCS3_0.0.9.9815.log.gz](https://github.com/RPCS3/rpcs3/files/4288172/RPCS3_0.0.9.9815.log.gz)

**Comment by jeremybris** [comment]
I am no longer experiencing this on **build 0.0.9.9832** in

- God of War Ascension
- Metal Gear Solid 4
- Advanced Warfighter 2

I did completely reinstall the emulator fresh though. See if that makes a difference for you.

**Comment by Sgtbomber91** [comment]
Last attempt with 0.0.9.9930 works fine, performance aside.
