### ISSUE TITLE
[NPEA00418] - Killzone HD - Broken Graphics in Cutscenes & Menu

### ISSUE THREAD

**Issue by web1018** [RPCS3/rpcs3#7854]
##  Quick summary
This is a known issue that has been around for a while now. Intro cutscene and in game cutscenes  Do not work. When entering the Menu section, the Graphics are not showing at all. Only a static lines are being shown. Sometimes the menu screen shows only black screen completely.

## Details
RPCS3 v0.0.9 - 10023 - 158e34fa Alpha | Hardware Specs :
Nvidia GeForce GTX 960M | Intel Core i7 6700HQ | 16GB of Ram | Windows 10

This is a PS2 port of the Killzone series that was remastered in HD for PS3 as a standalone and Trilogy version

## Screenshot
![Broken Graphics Menu](https://user-images.githubusercontent.com/51851411/77565836-2e0fe000-6e9b-11ea-938c-3405823da0a2.PNG)
![Capture11](https://user-images.githubusercontent.com/51851411/77565840-2fd9a380-6e9b-11ea-8065-6e4b5eda0ea7.PNG)
**2nd photo is taken from a cutscene**

**Links to Menu & Cutscene Comparison (How it is suppose to be)** 
https://www.youtube.com/watch?v=ZXAugWfVb0E
https://www.youtube.com/watch?v=0YPQAilKtyE

## Log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4382494/RPCS3.log.gz)

**Comment by lainiwaku** [comment]
as i have said on the forum, it look like similar  to this issue, but since i'm not dev, i don't know  if  it's similar or not related at all
https://github.com/RPCS3/rpcs3/issues/7349

**Comment by web1018** [comment]
I am not sure if its the same thing as the issue #7349. Perhaps @kd-11 would know which issue this is closely related to.

**Comment by kd-11** [comment]
In other games in this series, this bug is fixed by enabling write color buffers. Maybe it will help here too.

**Comment by web1018** [comment]
Unfortunately @kd-11 write color buffer doesnt fix the issues with cutscenes or the menu. It just degrades the ingame performance to 12-15fps. 
![Capture-option2](https://user-images.githubusercontent.com/51851411/78458232-bfdad280-767d-11ea-8111-eb8d77c63990.PNG)

**Comment by lainiwaku** [comment]
yeah, on killzone 2 without WCB it's appear on gameplay
on killzone 1 it's the video  playback  that bug, UI/subtitle anything else than video playback are draw fine

**Comment by kd-11** [comment]
This bug is caused by buggy video decoding. The game thinks the decoded frame is 2048x1024 with a pitch of 5120, but I have checked the source of the memory and it is indeed a 1280x720 divx video. This bug is outside RSX, but I'll keep it open on my list until we have a possible workaround or solution.

**Comment by web1018** [comment]
Alright, Thanks. let us know if any testing is required for a possible fix.

**Comment by kd-11** [comment]
I have fixed the RSX side of this bug so there is no more video frame corruption, but it looks like the video playback is stuck on the first frame or something which is not something I'm going to investigate any further at this time. See https://github.com/RPCS3/rpcs3/pull/8568

**Comment by kd-11** [comment]
Looks like I had the right idea, its fixed with https://github.com/RPCS3/rpcs3/pull/8568
