### ISSUE TITLE
Visual bug: Ratchet and Clank Trilogy holes in geometry. [BCUS98282]

### ISSUE THREAD

**Issue by Cervoxx** [RPCS3/rpcs3#7873]
## Quick summary
There are holes in the world that seem to flicker in and out of existence as you move your camera around, letting you see things you're not meant to see. 

## Details
- Logs are from the first game in the Trilogy, Ratchet and Clank.

- RSX capture: https://files.catbox.moe/kacno8.7z

- Logs: https://files.catbox.moe/j0gc3e.gz

- Video: https://youtu.be/zKUbZNYPPQE

- Serial: BCUS98282

A render-doc could not be acquired as it kept crashing the emulator and/or my system. 

Screenshot: 
![screenshot-2020_03_26_20_30_34](https://user-images.githubusercontent.com/12489208/77713094-8205ec00-6fa3-11ea-96dd-934b79e5459b.png)

**Comment by kd-11** [comment]
Try the option "Disable fifo reordering"

**Comment by Cervoxx** [comment]
Still occurs. 

RSX capture: https://files.catbox.moe/3xbchd.7z

Logs: https://files.catbox.moe/ntcs3s.gz

![screenshot-2020_03_27_02_01_45](https://user-images.githubusercontent.com/12489208/77730708-513bac00-6fcf-11ea-9a03-b223ce4ae6c2.png)

**Comment by asp0909** [comment]
> Try the option "Disable fifo reordering"

![Captura](https://user-images.githubusercontent.com/29218473/78059033-cf40df80-734e-11ea-807e-e1de4558e879.PNG)
 

does not affect   "Disable fifo reordering"

**Comment by elad335** [comment]
it is a regression I think, track down offending pr.

**Comment by asp0909** [comment]
I think it is not regression ... I have tested this game for a long time and that error has always been there

**Comment by isJuhn** [comment]
no, it's regression from #5315 I think

**Comment by asp0909** [comment]
you are right guys

**Comment by kd-11** [comment]
Disable FIFO reordering skips most of the additions added in that PR. Maybe a log with FIFO reordering disabled can be provided.

**Comment by asp0909** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4411131/RPCS3.log.gz)

**Comment by kd-11** [comment]
There doesn't seem to be any errors or warnings from the log. That moves this to RSX capture debugging.

**Comment by Cervoxx** [comment]
> Disable FIFO reordering skips most of the additions added in that PR. Maybe a log with FIFO reordering disabled can be provided.

Didn't I provide one though?

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/8583

**Comment by Josivan88** [comment]
An identical problem is shown in the issue #8360, and problem persists
