### ISSUE TITLE
rsx: Unimplemented unnormalized sampling for texture type 3

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#8154]
List of known games:

- Ratchet & Clank: A Crack in Time (Demo and Full Game)

- Resistance 2

**Comment by kd-11** [comment]
The reason this is still unimplemented is because I was really hoping no game was using this kind of setup. Unfortunately, APIs do not natively support 16-bit data being upstreamed and encoding and decoding the values is not free. I'll think of a clean way to do it, but this may end up causing us to stream more data to the GPU per draw call, something which eats at performance.

**Comment by lainiwaku** [comment]
sorry for the newbee question but, if not much game use it, could it then ba activated by an option, so only game that need it would use  the thing ?

**Comment by kd-11** [comment]
Yes, but that introduces more shader variations for the same code which is not desirable. It also makes it harder to extend functionality down the line. There should be a few bits that can be sacrificed from the remaining field in the set.

**Comment by NoXCxC** [comment]
Seems like it could be related to Insomniac Games only, since Resitance 3 and R&C A Crak In Time came from them, just 1 years appart

**Comment by NoXCxC** [comment]
It appereas that the same issue occur in Resistance 2 when entering water or when large amount of water is visible in the field of vision.
Again, it's a game from Insominac Games, so it's seems that the issue will be present in every games from them, maybe?
Still, the game is palyabale and no crash occurs.
![rs](https://user-images.githubusercontent.com/46874841/82068903-e6574900-96d2-11ea-9ad1-24552995dbdc.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4635367/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Red corrupted water on ACiT was fixed by a recent PR, this error persists and seems to be the cause of missing water effects

**Comment by revetix** [comment]
Same issue here, I believe this is what's causing #8500. Hope it gets fixed soon.

**Comment by MRuth** [comment]
Are there currently any plans on a fix for this issue?  Hoping it would fix the missing weapon effects and other effects in the newer Ratchet and Clank games as reported in #8500  and #8086.

**Comment by kd-11** [comment]
Yes

**Comment by jessenjonas** [comment]
Any updates on a fix?

**Comment by AniLeo** [comment]
No, if there was one it would show here, don't need to ask every month

**Comment by Jujumatic** [comment]
Given that there are so few games that require this feature, I wouldn't expect any updates for a long while. There are likely way higher priority items first before dealing with this particularly snowflakey issue. Especially given how much of a performance hit this could cause to everything else.

**Comment by kd-11** [comment]
This will be handled slowly during maintenance sprint as it requires several drastic changes that will only benefit a handful of games. Adding more data to the data block blindly will just cause issues, although some simple hack can be thrown together before then.

**Comment by Pichock** [comment]
Just want to ask if at the current update is there already a way to see particles in crack in time? Or this is still being worked on?

**Comment by AniLeo** [comment]
Not being worked on yet. As already said above, don't need to ask, when it's fixed the issue will be updated. If it's not updated, it's not fixed.

**Comment by Pichock** [comment]
Oh ok, i thought it already a work around like a canary patch or something,
sorry about that.

**Comment by Jujumatic** [comment]
This issue also affects the bat flying effect in inFamous Festival of Blood

PS3:
![image](https://user-images.githubusercontent.com/34321231/123540178-02367680-d73e-11eb-9eb3-5bf80f423038.png)

RPCS3:
![image](https://user-images.githubusercontent.com/34321231/123540525-bbe21700-d73f-11eb-8423-7b7382d2cf9f.png)

So potentially the other inFamous games and/or games made by Sucker Punch contain this issue as well

**Comment by lainiwaku** [comment]
@everyone should get fixed with #10501

**Comment by kd-11** [comment]
Unnormalized texture type stuff is different than that and requires a substantial rewrite of some parts of the renderers. Not difficult, but a lot of work and needs to be done when there aren't any other tasks being handled.

**Comment by kd-11** [comment]
3D renormalization is implemented in https://github.com/RPCS3/rpcs3/pull/10637
However, the water in these games is still broken and needs to fixed separately.

**Comment by kd-11** [comment]
The remaining reflection bug is caused by gamma issues. I can make it appear correct with hacks but the underlying problem is not fully understood yet. I'll close the 3d unnormalized error though.
