### ISSUE TITLE
vulkan: Build failure with vulkan-headers 1.2.140 (deprecated VK_DYNAMIC_STATE_RANGE_SIZE)

### ISSUE THREAD

**Issue by z0z0z** [RPCS3/rpcs3#8196]
Build failure seems to be related to files changed about ~12 days ago with the vulkan/shader recompiler work.

Regular updated Arch x86_64

[rpcs3build.txt](https://github.com/RPCS3/rpcs3/files/4616290/rpcs3build.txt)

**Comment by psyhlo** [comment]
I have the same problem with Mandjaro 20.0.1 64bit

**Comment by psyhlo** [comment]
i thing the problem is after this update
![Screenshot from 2020-05-12 22-14-43](https://user-images.githubusercontent.com/1803170/81736117-c0496300-949e-11ea-91e5-53689f80c3b9.png)

**Comment by AniLeo** [comment]
Known issue, already signaled on #8190

**Comment by psyhlo** [comment]
i think these issues are not exactly the same

**Comment by z0z0z** [comment]
The latter part of his issue is.

**Comment by AniLeo** [comment]
Fixed by #8202

**Comment by Cervoxx** [comment]
Still fails to build, this time with error `VK_DYNAMIC_STATE_LINE_WIDTH`

Logs here: https://paste.ubuntu.com/p/wCVKkX9JD7/

**Comment by AniLeo** [comment]
VK_DYNAMIC_STATE_RANGE_SIZE still used on

https://github.com/RPCS3/rpcs3/blob/8f0af6a6feb69ac3fcab3e65f9bb49931616d1b4/rpcs3/Emu/RSX/VK/VKTextOut.h#L123
https://github.com/RPCS3/rpcs3/blob/142a1da0e06433023897d5017cb4d3c0b5cf6296/rpcs3/Emu/RSX/VK/VKShaderInterpreter.cpp#L436
https://github.com/RPCS3/rpcs3/blob/8f0af6a6feb69ac3fcab3e65f9bb49931616d1b4/rpcs3/Emu/RSX/VK/VKOverlays.h#L210

**Comment by psyhlo** [comment]
everything compiles again
Thanks
