### ISSUE TITLE
[BCUS98281] Jak II HD Graphics Issues

### ISSUE THREAD

**Issue by JohnHolmesII** [RPCS3/rpcs3#8377]
## Quick summary
Jak II is almost correctly rendered, however one of the remaining issues is the flashing of the sky.

## Details
There is a hysterical amount of spam in the log about texture pitch. I tried all buffers, SRM, CPU blit, nothing has any affect. Not sure how important the details are, but this is something that seems to "decay". When you first get to the menu, you get a few seconds of correct sky. Then it starts flashing white. Then it turns into a disco show.

![image](https://user-images.githubusercontent.com/8901018/83961420-b3265680-a847-11ea-8e7c-1950e5de0ea2.png)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4741453/RPCS3.log)
[RSX Capture](http://144.202.67.63/misc/jakii_rsx.7z)
[Render docs](http://144.202.67.63/misc/jakii.7z)

**Comment by jeremybris** [comment]
Add Jak 3 HD, because it is the same. 

This issue is reminiscent of [#7031](https://github.com/RPCS3/rpcs3/pull/7031) in its strobe effect.

**Comment by kd-11** [comment]
Texture pitch issue was fixed some time ago when killzone HD videos got fixed. Retest and update.

**Comment by JohnHolmesII** [comment]
Same issue. Log spam is all the same too.

**Comment by jeremybris** [comment]
> Texture pitch issue was fixed some time ago when killzone HD videos got fixed. Retest and update.

This is still an issue for me. Here is an ([RSX capture](https://github.com/RPCS3/rpcs3/files/5059021/Jak.3.zip)) Jak 3 with the same bug.

**Comment by jeremybris** [comment]
This was almost fixed by v. 0.0.14-11619, PR #9613 . Great job! 

@kd-11 , since you have some regressions linked to this PR, I thought you may want to know about this, before you change anything back. Perhaps, this game can help in your understanding those regressions as well.

**Comment by gamrXerus** [comment]
Issue is still there. On Vulkan the flickering happens during the title sequence when I tested. However it doesn't seem to happen with OpenGL. The problem with OpenGL though, is that the ground is invisible or black.
OpenGL: ![Jak2 OpenGL](https://user-images.githubusercontent.com/19245344/109226228-c7730080-7794-11eb-82e9-304b4d468ea2.jpg)
Vulkan (sky flickering): 
![Jak2 sky ](https://user-images.githubusercontent.com/19245344/109226488-35b7c300-7795-11eb-810e-1e963196305a.jpg)

RSX capture OpenGL: https://drive.google.com/file/d/1S-5_RhiRg8gdKtHSdLmT5j43TE0LEuia/view?usp=sharing
RSX capture Vulkan: https://drive.google.com/file/d/1w_yR5HiRXfZbpOFJvIM6z_ZU2WCUsXkj/view?usp=sharing

**Comment by achristrophe** [comment]
This issue is active, but slightly different than first reported in June as the disco color strobe effect. Currently it is only a white flicker on the sky texture.

`E RSX: Invalid texture pitch setup, width=256, height=1, format=0xa5(0x85) x1194`

Did some digging and testing and regarding Jak2, this issue doesn't appear to be fixed by the fix for the killzone HD videos (assume you're talking [#8568](https://github.com/RPCS3/rpcs3/pull/8568)). I tested back at that version and latest.

Encountered the issue with Jak2 & vulkan at version: 

0.0.11-10646, PR [#8568](https://github.com/RPCS3/rpcs3/pull/8568) (color strobe effect)
0.0.14-11619, PR [#9613](https://github.com/RPCS3/rpcs3/pull/9613) 	(white strobe effect)
0.0.15-12167, [latest](https://github.com/RPCS3/rpcs3/pull/10201)	(white strobe effect)

[BCUS98281_20210428220901_capture.rrc](https://github.com/achristrophe/rpcs3jak2issues/raw/master/BCUS98281_20210428220901_capture.rrc) (at latest)
[log_0.0.15-12167-64a109d2](https://raw.githubusercontent.com/achristrophe/rpcs3jak2issues/master/log_0.0.15-12167-64a109d2)
[log_0.0.14-11619-22584fb2](https://raw.githubusercontent.com/achristrophe/rpcs3jak2issues/master/log_0.0.14-11619-22584fb2)

**Comment by rowedahelicon** [comment]
Tested this with latest version 0.0.16-12331-046d029e Alpha, sky is still flickering and a number of smaller graphical issues occur as well. Running on Vulkan

**Comment by gamrXerus** [comment]
@kd-11 Did some regression testing today. It seems that the OpenGL backend displays correctly up to version 0.0.14-11605 but after PR#9613 the floor is black or transparent.
0.0.14-11605
![screen01](https://user-images.githubusercontent.com/19245344/125172741-58b5a300-e189-11eb-9831-bf9eef9921c1.jpg)
PR#9613
![screen02](https://user-images.githubusercontent.com/19245344/125172756-6a974600-e189-11eb-8e42-ac49475ec9bb.jpg)

**Comment by kd-11** [comment]
@gamrXerus Please provide a capture of the issue.

**Comment by gamrXerus** [comment]
@kd-11  Here you go.
RSX capture 0.0.14-11605 (floor ok)
https://drive.google.com/file/d/1omO9yPXg_k6aR8LfqJqUpW4owzauXp3U/view?usp=sharing
RSX capture PR #9613  (floor black)
https://drive.google.com/file/d/1mp7JO5Cn5_rVqiSSkymC-uAxs0nX7VQL/view?usp=sharing

**Comment by gamrXerus** [comment]
@kd-11 Should I open a ticket for the regression, or tracking it here is fine?

**Comment by kd-11** [comment]
Here is fine, the existing issue still needs investigation anyway and the resolution will be the same.

**Comment by Gr33nLight** [comment]
Hi, I am experiencing the same issue on Jack 3 as well. With OpenGL the sky flickering is gone but the floor is black in some parts. 
I am using version 0.0.17-12634-b928cb02 Alpha
Do you guys have any updates on this? 
Or if its possible to have a rolled back version of the build made available to install.

**Comment by gamrXerus** [comment]
@Gr33nLight In the meantime, you can try the 0.0.14-11605 build while we wait for a fix.
https://rpcs3.net/compatibility?b&p=23 
23/01/2021 build date. You can download it there.

**Comment by Gr33nLight** [comment]
> @Gr33nLight In the meantime, you can try the 0.0.14-11605 build while we wait for a fix.
> https://rpcs3.net/compatibility?b&p=23
> 23/01/2021 build date. You can download it there.

Thanks will do!

**Comment by Zorklis** [comment]
![rpcs3_oIUYeoWSNu](https://user-images.githubusercontent.com/85455465/131502048-e871b046-1180-4a23-aaee-bf7ccdc86d4c.jpg)
Sky flashing still not fixed. It's more consistently correct though (less random flashes)

**Comment by Decards** [comment]
Hello :) 

The sky is still disco, Still no fixes or workarounds ?

**Comment by EmulationPundit** [comment]
I tried playing on the older version like the others stated here in the comments, I even tried v0.0.14-11603 but on both version I still have the glitches on OpenGL.

I don't get how years has passed and the sky glitch + the transparency glitch hasn't been fixed yet. Seems like a small job to do but it's just a guess. 
If these two bugs would just get fixed then the Jak trilogy would be perfectly playable other than the small fps dips,

**Comment by Zorklis** [comment]
> If these two bugs would just get fixed then the Jak trilogy would be perfectly playable other than the small fps dips
The save/load problem would still be present

**Comment by gamrXerus** [comment]
@EmulationPundit  That's strange. I played Jak 2 yesterday on Linux for 2 hours and had no major problems. I used the latest build of rpcs3 and chose OpenGL as my renderer. I tested it on Windows 10 too and the sky and floor is fine. I have an AMD RX6800. Try the latest build and use OpenGL and see if it works. Hope its not an NVIDIA problem. And just like Zorklis said the save/load problem is still there but it is minor.
![jak2okwindows](https://user-images.githubusercontent.com/19245344/139504205-22ad785c-a24b-4430-ba37-0b3d80a2eed6.PNG)

**Comment by Zorklis** [comment]
> Hope its not an NVIDIA problem.

Tested on the latest Nvidia driver 496.49 (Windows 10) and have the same experience as you (No sky glitches). Tested on GTX 1060 6GB in Jak 2/II, performance is noticeably slower on OpenGL(15-20fps) than Vulkan (30fps) but that's to be expected on i7-3770

**Comment by kd-11** [comment]
Test with https://github.com/RPCS3/rpcs3/pull/11080

**Comment by gamrXerus** [comment]
@kd-11  I just tested #11080 It doesn't fix the problem unfortunately. On Vulkan, the sky is now rainbow horizontal lines and on OpenGL the sky is now orange.
Vulkan:
![vulkan](https://user-images.githubusercontent.com/19245344/139534630-cbe92347-90de-405b-b71b-e6fe06a4679a.jpg)
OpenGL:
![opengl](https://user-images.githubusercontent.com/19245344/139534642-f2e735e2-9808-40d5-af17-4dd30ae8fc38.jpg)

**Comment by gamrXerus** [comment]
@kd-11 Interesting... I just tested on Windows 10 and PR #11080 seems to fix this issue. Maybe there is an issue with Mesa on Linux.

**Comment by kd-11** [comment]
Interesting that there is a difference with drivers. I'll have to investigate that first.

**Comment by JohnHolmesII** [comment]
Issue is fixed for me on windows finally, which is great. Will test laneeks.

**Comment by kd-11** [comment]
I fixed the problem with linux, it turned out to be my fault not properly initializing the memory that is consumed by the image. It seems windows driver architecture forces the memory to be zeroed which hides the problem.

**Comment by Zorklis** [comment]
Tested the latest commit and the problem still occurs, now with it's the stripes!
Here's how it looks during the intro https://youtu.be/cIeD-9mz4vc . Also there's some strange lines in the middle

**Comment by JohnHolmesII** [comment]
The issue is completely fixed for me on latest master. Are you sure you updated?

**Comment by Zorklis** [comment]
> The issue is completely fixed for me on latest master. Are you sure you updated?

Yes I updated to the current one 0.0.18-12970-e31173e3 (Current Merge by elad335).
Previously I didn't have the stripes and only flashing sky

**Comment by Decards** [comment]
I confirm that is not fixed. It is still ocurring for me too but it took a little while before the sky started flashing again.

**Comment by gamrXerus** [comment]
I can also confirm that Vulkan is not fixed for me on Windows or Linux. OpenGL works fine. This bug has proven to be tricky.

**Comment by EmulationPundit** [comment]
Just tried on the latest build on Windows and with OpenGL, sky flickering is fixed but as could be seen even before this fix, between the flickering the sky is pixelated for some reason. 
Even tho the flickering is fixed on OpenGL, the framerate is completely unplayable for me personally so I'm really looking forward to a fix for Vulkan.

**Comment by SlyCooperReloadCoded** [comment]
Okay, so it's not just me, thank goodness.  The new flashing is mostly just white flashing, but very quickly, so quickly that OBS can't properly record it for reports, not to mention it's probably seizure-inducing.  I noticed that the skybox's intended textures look garbled as well.

**Comment by JimScript** [comment]
I think this is a vendor problem, like #10955, as both kd and JohnHolmesII use AMD hardware and don't experience any issue. I have NVIDIA hardware and I have the problem, but I don't know if this is consistent with everyone else here.

**Comment by kd-11** [comment]
I'll check what's up with it, different drivers and hardware have wildly different results. Even when it was broken I had different results on AMD with the 3 available drivers (windows, AMDVLK and RADV) with all of them having different results. I'll check with a pascal card and see if I can reproduce this.

**Comment by garouvulps** [comment]
I have an RX 550 AMD card and is also still broken with flashing sky and lines appearing at random.

**Comment by kd-11** [comment]
Try https://github.com/RPCS3/rpcs3/pull/11104
I have an idea why the previous patch worked for me when testing on linux. It is a coincidence. The game will render correctly on some drivers if we just upload a black texture. The sky is night so it just happens to work if you have a driver that is zero-initializing the buffers and crap if it is not.

**Comment by Yahfz** [comment]
![image](https://user-images.githubusercontent.com/17715080/140068029-4a41facd-0ce1-4797-acec-dc6fb0f6d9a4.png)
Fixed
