### ISSUE TITLE
Skate 3 (BLUS30464) Lighting issue

### ISSUE THREAD

**Issue by Iam2smart** [RPCS3/rpcs3#8739]
There are bright spots all over the map

Here is the log file of rpcs3
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5079908/RPCS3.zip)
Here is the RSX capture also (since it's a graphical issue)
https://drive.google.com/file/d/19lJ561mMZFRz2qwRPbb6hpyY1rdYl6eb/view?usp=sharing

Here are some Screenshots of rpcs3

![Skate 3 Img 2](https://user-images.githubusercontent.com/25376595/90325672-b91d6f80-df3b-11ea-9eeb-6594deb4cbe1.PNG)
![Skate 3 Img 3](https://user-images.githubusercontent.com/25376595/90325675-be7aba00-df3b-11ea-9677-e3a1bd153858.PNG)
![Skate 3 Img 4](https://user-images.githubusercontent.com/25376595/90325677-c175aa80-df3b-11ea-8e44-829b0a61462f.PNG)

Here is a real ps3(screenshots were shot with my phone)

![IMG-0228](https://user-images.githubusercontent.com/25376595/90325685-e9fda480-df3b-11ea-96fe-ef2a936587c3.jpg)
![IMG-0226](https://user-images.githubusercontent.com/25376595/90325689-f255df80-df3b-11ea-91bb-32cf37b76ec4.jpg)
![IMG-0227](https://user-images.githubusercontent.com/25376595/90325692-f681fd00-df3b-11ea-8f19-4d6921ed1257.jpg)

* OS Windows 10
* CPU i5-9400
* GPU RTX 2060
* Driver version latest

**Comment by jeremybris** [comment]
I think that's how the game is supposed to be. Check out this video at 2:20, 2:30, and 2:58 on a PS3:

- https://youtu.be/Bf7ZcZOW92M?t=140 (ground on the left)
- https://youtu.be/Bf7ZcZOW92M?t=150 (ground straight ahead)
- https://youtu.be/Bf7ZcZOW92M?t=177 (the sidebar)

You can adjust the brightness of TV maybe to counter it.

**Comment by Iam2smart** [comment]
Yes my ps3 looked like that and at first I thought that’s how it was supposed to look but when you get closer the ps3 renders it in and looks normal rpcs3 never renders it it just stays bright. It might just be me though

**Comment by jeremybris** [comment]
> Yes my ps3 looked like that and at first I thought that’s how it was supposed to look but when you get closer the ps3 renders it in and looks normal rpcs3 never renders it it just stays bright. It might just be me though

Yes, you are right. I tested this myself. It seems the dynamic brightness found at https://youtu.be/Bf7ZcZOW92M?t=147 is missing.

**Comment by illusion0001** [comment]
Try wcb

**Comment by Iam2smart** [comment]
Ok I tested  it with Write Color Buffers on but now I get white flashing across the screen. I recorded a clip on my Computer for you to see(my computer did some weird cropping of the video but you can still see the flashing white).
https://drive.google.com/file/d/1H6ql9SFt4F-8ih2-LarxHWa3nzjRtCvG/view?usp=sharing

**Comment by kd-11** [comment]
If by flashing white you mean the momentary brightness spikes when in shadow isn't that just dynamic exposure doing its job? Rpcs3 usually reacts faster to lighting changes than realhw for some reason. Other than that, maybe mention timestamp of an example where the flashing happens since most devs are not familiar with how these games normally look like.

**Comment by Iam2smart** [comment]
Ok the time stamp is at 0:43-0:45 that’s when it happens.

**Comment by kd-11** [comment]
@Iam2smart Are you using resolution scaling when using WCB?

**Comment by Iam2smart** [comment]
> @Iam2smart Are you using resolution scaling when using WCB?

Nope I turned it off trying to eliminate as many things as possible to see if i turned on a setting that wasn’t meant to be turned on

**Comment by kd-11** [comment]
Ok, I'll try to repro. Its likely solved with some obscure combination of configuration settings.

**Comment by Iam2smart** [comment]
If you want I can create a video on how to reproduce the issue

**Comment by kd-11** [comment]
Please retest with current rpcs3 master and WCB on. From quick testing, I do not get any flickering or excessive glare when out in the sunlit areas. Dynamic exposure still works (while in shadowed arches bloom is slightly exaggerated)

**Comment by Iam2smart** [comment]
Seems like that it has been fixed. I don’t get any flashing anymore.

**Comment by Satan86** [comment]
I still get it in this specific spot


https://user-images.githubusercontent.com/61447828/120902565-fffa6400-c638-11eb-9a30-e7f9a229e63c.mp4

Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/6603069/RPCS3.zip)

**Comment by kd-11** [comment]
@Satan86 Does it happen at stock (30 fps)?

**Comment by Satan86** [comment]
Yes

**Comment by Satan86** [comment]
also happens with cameraman mode disabled, which runs at 60 FPS by default, no patches

**Comment by Megamouse** [comment]
needs testing again
