### ISSUE TITLE
Persona 5 visual glitches when using Asynchronous Texture Streaming

### ISSUE THREAD

**Issue by EthanRios37** [RPCS3/rpcs3#8768]
Text in game corrupted

Appears to work fine on the intro of the game up till the first 2 minutes or so. Yellow text with convoluted letters appear within the text boxes all of a sudden, making it unreadable

Utilities capture- [NPEB02436_20200824004022_capture.zip](https://github.com/RPCS3/rpcs3/files/5115791/NPEB02436_20200824004022_capture.zip)

RenderDoc capture- https://www.dropbox.com/s/t03802wdi37ml4x/Persona%205%20intro.zip?dl=0  (idk if i did this right sry. Im a normie)

Screenshot- ![Annotation 2020-08-24 005243](https://user-images.githubusercontent.com/62739258/91005531-1e5d0a80-e5a5-11ea-809b-1efd408b0a51.png)

Comparison- ![Annotation 2020-08-24 005835](https://user-images.githubusercontent.com/62739258/91005539-2321be80-e5a5-11ea-907b-6fbe6d9c2e28.png)

Specs-

Windows 10
Ryzen 5 3600
AMD RX 5600 XT
20.8.2

Sorry if any of this was done wrong, I tried my best :/

Also it may be important to know that I wasn't having this issue about a month ago I don't think.
I read up on Reddit and it seems to have something to do with the AMD GPU's newest version.
Also plz fix fast :( 
Thanks!

**Comment by dio-gh** [comment]
Did you update your drivers in the past month? If not, this is a regression and needs bisecting (finding which build it broke with).

**Comment by AniLeo** [comment]
Known regression on AMD drivers, needs to be bisected to find which driver introduced this issue, pretty sure it's not our bug

**Comment by EthanRios37** [comment]
Eh. Yeah I have updated my gpu's drivers, I don't really know how to downgrade my drivers to tell which it broke with; however, I've read up that it's started at about 20.4.1, correlated by two people on reddit

**Comment by dio-gh** [comment]
Still an issue?

**Comment by EthanRios37** [comment]
Downgraded my cards drivers. Can’t pinpoint the exact drivers that broke it.. believe it may have been in about May

**Comment by AniLeo** [comment]
Needs update from testing on latest drivers, maybe it has been fixed

**Comment by digitaldude555** [comment]
@EthanRios37 update the issue.

**Comment by perogee** [comment]
Hello! Just created an acc to report that the issue still persists on 20.11.2 & 21.2.3

![screenshot-2021_03_17_05_27_56](https://user-images.githubusercontent.com/80791376/111382399-e86aa980-86e1-11eb-954e-25b06360ddde.png)

**Comment by HoRoBi70** [comment]
I have the same issue with windows and linux so i don't think it's OS related. And i tried both the disk version and the PSN package with the same result,

**Comment by AniLeo** [comment]
Is it solved if you turn off "Asynchronous texture streaming" on Settings > GPU?

**Comment by HoRoBi70** [comment]
> Is it solved if you turn off "Asynchronous texture streaming" on Settings > GPU?

YES, thank you

**Comment by Asinin3** [comment]
Is this still an issue with it turned on? Async texture streaming had a few changes recently

**Comment by HoRoBi70** [comment]
> Is this still an issue with it turned on? Async texture streaming had a few changes recently

Itried with 0.0.21-13411-f4d02861 Alpha and it seems fixed

**Comment by kd-11** [comment]
Closing as fixed.
