### ISSUE TITLE
Regression: Resident Evil 0 [NPEB02226] - Unable to access the game data (#8835)

### ISSUE THREAD

**Issue by dyno0** [RPCS3/rpcs3#8930]
After #8835 the game won't continue after booting.

Short snippet:

```
·W 0:00:36.799087 {PPU[0x1000000] Thread (main_thread) [HLE:0x00e103d0, LR:0x00a9625c]} cellSysutil: cellMsgDialogOpen2(type=0x80, msgString=“Unable to access the game data.
Please delete the game and re-download it to play.”, callback=*0xcb8068, userData=*0x0, extParam=*0x0)
·E 0:00:36.799090 {PPU[0x1000000] Thread (main_thread) [HLE:0x00e103d0, LR:0x00a9625c]} cellSysutil: “Unable to access the game data.
Please delete the game and re-download it to play.”
·W 0:00:36.799095 {PPU[0x1000000] Thread (main_thread) [HLE:0x00e103d0, LR:0x00a9625c]} cellSysutil: open_msg_dialog(is_blocking=0, type=0x80, msgString=“Unable to access the game data.
Please delete the game and re-download it to play.”, callback=*0xcb8068, userData=*0x0, extParam=*0x0)
```

Works on release just before - 10857. Current master also not working.

[firstWhichBrokeIt.log.gz](https://github.com/RPCS3/rpcs3/files/5248835/firstWhichBrokeIt.log.gz)
[lastWorking.log.gz](https://github.com/RPCS3/rpcs3/files/5248837/lastWorking.log.gz)

**Comment by digitaldude555** [comment]
Fixed now. Close.
![Screenshot (266)](https://user-images.githubusercontent.com/26138653/105906914-f7f83b00-602c-11eb-9845-fc556f160f5c.png)

**Comment by dyno0** [comment]
No it's not fixed. Cleared all and tried reinstalling.

![NOIDONTTHINKSO](https://user-images.githubusercontent.com/54358666/106398003-ad9e0200-6410-11eb-8120-20c2ef3f1dc2.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5900640/RPCS3.log.gz)

**Comment by RainbowCookie32** [comment]
Looking at the log, there's a decryption error before the game shows the message.

```
·E 0:00:13.489565 {PPU[0x100000f] Thread () [0x01101174]} EDAT: EDAT: Block at offset 0x120 has invalid hash!
·E 0:00:13.489605 {PPU[0x100000f] Thread () [0x01101174]} EDAT: Error Decrypting data
```

**Comment by dyno0** [comment]
Sry my bad, my lidl app for organising dumped raps does ToUpper on file names so .rap got caught in it.
Works now ty, and sry for spam.
