### ISSUE TITLE
Siren: Blood Curse [BCES00294] nvoglv64.dll crashed on dead sight jack screen

### ISSUE THREAD

**Issue by Puxirepublic** [RPCS3/rpcs3#8978]
## Quick summary
At the first beginning level, the cop will be keep shooting you, you need to run away. But if you let him catches you or shoots you to death, a dead splited red sight jack screen shows up, then the whole game immediately crashed with nvoglv64.dll fatal error.

And I also found that the game will be randomly freeze when you quick skipped cut·scene sometimes.

#### 1. Please attach RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5286243/RPCS3.log.gz)

#### 3. Please attach screenshots of your problem.
![Untitled](https://user-images.githubusercontent.com/5261049/94331498-78674a80-ffff-11ea-91ac-d1d32963958f.png)
![2](https://user-images.githubusercontent.com/5261049/94331503-81f0b280-ffff-11ea-8edf-4dd181d99811.png)

#### 5. Please provide your system configuration:
* OS: Windows 10 2004
* CPU: E3-1230 v2
* GPU: GTX 650
* Driver version: 456.38

**Comment by bevanweiss** [comment]
I think your problem might be reclaim related..
·! 0:05:46.012567 {RSX [0x001204c]} RSX: Video memory usage exceeding 75%. Will attempt to reclaim resources.

I suspect that rpcs3 might be throwing away a resource that we then proceed to use, which is a bit frowned upon.
More VRAM would obviously help here... since then rpcs3 wouldn't need to try to reclaim anything.

**Comment by bevanweiss** [comment]
It might be worth trying an old copy of rpcs3 prior to this PR #8618 
I think it will actually make things worse, but I've been wrong before.

**Comment by Puxirepublic** [comment]
Thanks. Tested #8617 build, no more crashes.

**Comment by bevanweiss** [comment]
If you could bisect and test #8618 it would be appreciated. If it crashes then this becomes a regression (although not a particularly recent one, so not a quick fix I suspect).

**Comment by kd-11** [comment]
If it truly started with #8618 then fixing it would (luckily) not be too difficult, I just need to be more strict with the memory handling, either way, the GPU is already screwed without memory, might as well take the time to sync properly.
Do verify the first failing build and note that PRs are not always merged in order (although in this case I think 8617 was merged just before 8618 iirc).

**Comment by Puxirepublic** [comment]
Not quite followed the "bisect" means, is that mean to test #8618 build with a clean, separate and independently? If so, I've tested, no crashes, and when the dead sight jack screen shows up, the FPS still stabled (not like #8617 and before crashed build will be drop down a lot). 

But there's one thing on that clean #8618 build I noticed when I first boot the game, if I get quick skipped the cutscene, it freezes 100% everytime, until let the cutscene play and finished, then in the next boot, you can skip cutscene normally without freeze (not sure it will be randomly freezes like before I mentioned).

Here's the log of the first boot and skip cut scene 100% freezes,
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5303023/RPCS3.log.gz)

Another one thing I must say is I actually tried #8618 build before #8617 (by mistaken your comment) ... It crashed. But whether #8618 or #8617, they both used overwrite way before.

**Comment by bevanweiss** [comment]
Bisect is to 'split into two'.  So what we'd be looking to find is the commit where before it worked, and after it crashed.

I thought that #8618 would have introduced the trigger for your situation, but if you say that you tested #8618 and it did not crash, then I think that it's no longer the guaranteed cause.
It would then be worth you testing more recent releases, to see which release introduces the crash behaviour for you.

The optimum way to do such testing is to take the range of possible releases, and pick the one in the middle.  Test it.  If it crashes, then you want to go to an older release, and again the optimum way is to pick the release in the middle of your new 'maybe good' set.  Eventually you will get down to a single release where before it, you had no crashes, and after you had crashes... you have bisected the set to identify the release that causes your crashes, and hence have narrowed down where the rpcs3 code might not be playing nicely with your environment (i.e. in telling the dev team what release introduced the crashes, you have dramatically increased your chances of having the crashes fixed for you).

**Comment by Puxirepublic** [comment]
Wait, you were right... It's indeed the #8618 trigger that crash. I was wrong before testing the clean build of #8618, I was so hurried want to test, forgot that default GPU render option's OpenGL, So I was in the OpenGL before, that's why it was no crash and why the FPS stabled. Now I tested again with Vulkan, it crashed again.
Here's the log,
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5310449/RPCS3.log.gz)

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/9041

**Comment by Puxirepublic** [comment]
Does #9043 included the fix or it's just another PR that skipped of #9041? Since have tested #9043, it still gets exactly the same crashed. 

The log of #9043,
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5346555/RPCS3.log.gz)

**Comment by bevanweiss** [comment]
@Puxirepublic nope, unless a PR is 'merged' then it's separate from other PRs.
When it gets 'merged' then it becomes a part of the main code base, and all other PRs / code includes it.
