### ISSUE TITLE
Regression: Corrupted shader output on NVIDIA (#8984)

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#8990]
Regressed by #8984

Affected:
- Windows 10 with GTX 1080
- Windows 7 with GTX 960M
- Windows 7 with HD 530

Not Affected:
- Linux Mesa radv with R9 280X
- Linux Mesa anv with HD 530

Does not happen on OpenGL, only on Vulkan

---

**NVIDIA GTX 960M**
![image](https://user-images.githubusercontent.com/10283761/94381897-b7e28380-0132-11eb-9255-df43155bfdfc.png)

**Intel HD 530**
![image](https://cdn.discordapp.com/attachments/277227681836302338/759952216504926218/unknown.png)

**Comment by Mew89** [comment]
l

**Comment by Mew89** [comment]
L

**Comment by kd-11** [comment]
Cannot reproduce on 1050Ti. Also, that is the wrong build to be testing with, should use 10953.

**Comment by Yahfz** [comment]
Cannot reproduce on a 1080Ti (driver 456.38) either.

**Comment by Kravickas** [comment]
Well i add mine here.

`WIN 10 - 980ti - 452.06`

**NHL Legacy**

Black screen with UI in cutscenes/replays. Vulkan only.
_________________

**RDR**

Before PR
![obrazek](https://user-images.githubusercontent.com/29986095/94466329-8f559a80-01c1-11eb-94ae-26d20956db6c.png)

After PR
![unknown](https://user-images.githubusercontent.com/29986095/94466422-b0b68680-01c1-11eb-969c-f16e296250ea.png)

**Comment by kd-11** [comment]
Turns out its a driver/hw problem, should be resolved by #8992.

**Comment by kd-11** [comment]
NOTE: Why do some people not have the bug? Because it is fixed in the NVIDIA beta vulkan drivers! 
https://developer.nvidia.com/vulkan-driver

**Comment by sampletext32** [comment]
If this is fixed by drivers, should this PR even exist? I think it's not a RPCS3 problem. Am I right?

**Comment by AniLeo** [comment]
Regardless, this generates smaller code, and that driver is Beta either way, we'd have to tell everyone to install that driver

**Comment by kd-11** [comment]
Also remember intel is broken as well, although that is not really surprising. I decided to go with the op lowering as it generates smaller bytecode on older GPUs which points to some kind of instruction emulation going on there.

**Comment by Kravickas** [comment]
Well new drivers fixed both of my issues.

**Comment by z0z0z** [comment]
Judging from some posts/screenshots on discord I think this bug may still be effecting some games (possibly katamari damacy) still.

Not confirmed, just saying I wouldn't be surprised.

**Comment by AniLeo** [comment]
Nope, this one is fixed as I've tested it. Regardless, do testing on the latest NVIDIA driver with clear shader cache

**Comment by z0z0z** [comment]
![2020-09-30-222915_1299x237_scrot](https://user-images.githubusercontent.com/12925873/94758992-3edf6800-038e-11eb-9bb0-f4d2b175cf1f.png)

Person's description of this problem in Nier. Nvidia card, RPCS3 0.0.12-10959

Clearing shader cache didn't work they said `also, i tried clearing cache.  for a split second the lighting was normal but then it went back to overblown bloom again`

They said it worked after installing latest beta vulkan nvidia driver.

I've seen a couple other similar cases, including someone posting basically the same exact P5 menu screen on 0.0.12-10959

**Comment by ipkpjersi** [comment]
I am still experiencing this issue on 0.0.13-11287 in RDR with all caches cleared on Ubuntu 18.04 with a GTX 1070 and NVIDIA driver version 450.80.2.0:
![2020-11-21_13-28-1_1605983281771741806](https://user-images.githubusercontent.com/33754783/99884585-68ce4180-2bfd-11eb-975c-c44ef9b8a71f.png)


Am I correct in understanding that the only way to fix this would be upgrading to the beta driver version 455.46.01 here: https://developer.nvidia.com/vulkan-driver or is there another way to fix this? I suppose one way would be waiting until the 455 branch hits stable?

**Comment by kd-11** [comment]
You have to update to their less buggy drivers. It won't fix all the nvidia problems, but it is much better than this mess.
