### ISSUE TITLE
{RSX [0x02a6238]} VM: Access violation reading location 0xcf900000 (unmapped memory) (Dynasty Warriors 8 XL)

### ISSUE THREAD

**Issue by Archim119** [RPCS3/rpcs3#9055]
![image](https://user-images.githubusercontent.com/72658167/95656461-7c6a9080-0b06-11eb-85f2-f4b7e73ccc03.png)

The game crashes when entering a stage, always within the first few seconds. I can get through a few minutes of the tutorial before the same happens.

Debug console mode changes the error from: F {RSX [0x0399668]} VM: Access violation reading location 0xcf900000 (unmapped memory)

To: F {PPU[0x1000000] Thread (main_thread) [0x00441ca4]} VM: Access violation writing location 0x0 (unmapped memory)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5359105/RPCS3.log)

**Comment by jy95** [comment]
@Archim119 Did you use a RPCS3 patch ? I got a similar message on another game https://github.com/RPCS3/rpcs3/issues/8985

**Comment by Archim119** [comment]
@jy95 With or without patches enabled, the game still freezes at the same point. Did you manage to get yours to work?

I've tried enabling certain libraries to solve the issue, while it does get rid of the access violation it is then replaced with this: E {PPU[0x1000000] Thread (main_thread) [0x014b8a30]} SYS: 'sys_mutex_create' failed with 0x80010005 : CELL_ESRCH [1]

I've also tried disabling accurate LLVM DFMA, but this didn't work either.

**Comment by Darkhost1999** [comment]
Last comment is approximately 2 years old. Is this still an issue?

**Comment by Jimertons** [comment]
@Darkhost1999 yes, sadly still an issue

**Comment by KirkixSaturnex** [comment]
I've recently come back to emulating PS3 games and after playing most of my favorite games i played Dynasty Warriors 8 and i discovered this crash too. I tested the game for a while and now i discovered the issue and why this happens. It is a problem with the rendering of the level of detail with the soldiers. After a few seconds the game crashes because the game has an issue with loading the low level of details of the soldiers. The RAM has an error that might just be one byte that is unmapped. This error happens on every Dynasty Warriors 8 version, including the japanese and chinese versions, except Dynasty Warriors 8 Empires. I made a screenshot of one of my last tests and this is my conclusion. You can finish the tutorial and you can finish every stage but you need to point the camera at the floor to not load the low level of details and if there are not enough soldiers around you could look up but only in the tutorial. This screenshot is the frame that is crashed on. This is literally 60 frames after the low level of detail of this one soldier was loaded
![1](https://user-images.githubusercontent.com/128988799/227786698-530ff1fb-d0ad-479d-abfc-abdd3eeafe7c.png)

**Comment by ReLyf47** [comment]
3 years later and still not fixed

although i got a different access violation code
F {RSX [0x004cfbc]} VM: Access violation reading location 0xcf90f7c0 (unmapped memory)
which might or might not help the dev figure something out

Game ID is: NPJB00511 (DW8XL JPN Digital version)

**Comment by elad335** [comment]
Upload updated log and savedata.

**Comment by elad335** [comment]
I think I figured it out: We assume that the highest vertex index is the frequency divider when modulo op is used because there are vetex indices higher than it. But in reality we should do max_index = max(index % frequency, max_index) for each index. This is of course slower, but it can be optimized to not do it if we have a lot of free memory range left.

**Comment by ReLyf47** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12381489/RPCS3.log.gz)
[NPJB00510-SAVEDATA.zip](https://github.com/RPCS3/rpcs3/files/12381508/NPJB00510-SAVEDATA.zip)

Here is my log and savedata (mind you im not the original poster)
and also save data is maybe _useless_, due to the crash literally happening on any stage that you starts

**Comment by elad335** [comment]
Test #14505

**Comment by ReLyf47** [comment]
sorry for not replying
i couldnt test DW8XL since i deleted the game install both from PS3 and RPCS3 and would not rather redownload a 23GB game on my current network situation

BUT
i have another DW game that suffer from the same issue
and surprise surprise using #14505 build it worked

this was the error code before i used the build 0xcf906420 (nearly identical with DW8XL error code)
and here is my log for this other DW game (BLJM61347)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12392129/RPCS3.log.gz)

as pointed out on the comments in #14505 the fallback handler "This sucks" appears also 1x every like 1-2 second

**Comment by QJYEAH** [comment]
> WIP ![image](https://user-images.githubusercontent.com/18193363/261673159-75e80ee4-5cd9-4004-ae6c-77614942759d.png) ![image](https://user-images.githubusercontent.com/18193363/261673229-1007c7d8-f19e-46fa-8314-a7f2e75e953e.png)

![QQ图片20230822204849](https://github.com/RPCS3/rpcs3/assets/15781690/a53c73d4-da9c-4f83-bc6e-0672758c56bc)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12408782/RPCS3.log)
the game sometimes wii be crashed

**Comment by ReLyf47** [comment]
Somewhere in the update broke this again
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12837535/RPCS3.log.gz)

Last known good build:
Honestly idk probably #14505 

Old error code: 0xcf906420
New error code: 0xcf905960

seems like its in the same ballpark of issue

**Comment by luixal** [comment]
Just got the same error while playing MGS Rising :Revengeance:

```VM: Access violation reading location 0xcf900000 (unmapped memory)```

Thanks!

**Comment by FlexBy420** [comment]
Is this still an issue?

**Comment by KirkixSaturnex** [comment]
Sometimes the game still crashes because of that reason or a similar reason but it has become better. For me it mostly crashes in the Ambition Mode. I was able to port my 100% save file to the emulator and i can say that if it runs well without crashes it's actually running like it is supposed to run but it uses a lot of CPU (which isn't a problem but it's important to say that). Give it another year or two and this will be completely resolved :)

**Comment by digant73** [comment]
is that still an issue?

**Comment by lllljj1991** [comment]
Yes, it also appeared in BLUS30690 (Dynasty Warriors 7).
F {RSX Offloader} VM: Access violation reading location 0xcf900000 (unmapped memory)

**Comment by guss0ar** [comment]
Got the error on NPUB31633 (Metal Gear Solid 4).
F {RSX [0x0a2aacc]} VM: Access violation reading location 0x4239b7c0 (unmapped memory)

Can't even try to avoid it with camera or menu since it happens in the opening cutscene.

**Comment by ReLyf47** [comment]
@guss0ar this is only a thread for Dynasty Warrior games

also im pretty sure you just havent done MGS4 correct settings if it happens on opening cutscene

**Comment by lllljj1991** [comment]
<img width="1123" height="281" alt="Image" src="https://github.com/user-attachments/assets/df7a2aea-084d-44fc-87e9-a47ec474be0d" />
I changed some codes in RSXThread.cpp, it seems can fix this problem. idk whether it'll cause other issue.
@elad335 @digant73

**Comment by digant73** [comment]
I would also tag @kd-11 for a possible issue on RSX

**Comment by kd-11** [comment]
> <img alt="Image" width="1123" height="281" src="https://private-user-images.githubusercontent.com/169359566/518181562-df7a2aea-084d-44fc-87e9-a47ec474be0d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQwMDI1MzgsIm5iZiI6MTc2NDAwMjIzOCwicGF0aCI6Ii8xNjkzNTk1NjYvNTE4MTgxNTYyLWRmN2EyYWVhLTA4NGQtNDRmYy04N2U5LWE0N2VjNDc0YmUwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEyNFQxNjM3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTA1MWE4MjVlMGI4N2I5MzA3MDEwNTVmZTdhYzMyZTMwZjVhYjA3NDBlOTU3N2U2Mjk1YTJjOGJiMDE5MWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2BGFSDLhooeFP2ajfa59U4B-Bptr-J419qcJbRZMWqE"> I changed some codes in RSXThread.cpp, it seems can fix this problem. idk whether it'll cause other issue. [@elad335](https://github.com/elad335) [@digant73](https://github.com/digant73)

This is wrong, continue is the right action there.
The real problem appears to be the index range, but I'm 99% sure it would also have crashed a real PS3 when going out of bounds.
How do you reproduce the issue quickly?

**Comment by lllljj1991** [comment]
> > <img alt="Image" width="1123" height="281" src="https://private-user-images.githubusercontent.com/169359566/518181562-df7a2aea-084d-44fc-87e9-a47ec474be0d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQwMDI1MzgsIm5iZiI6MTc2NDAwMjIzOCwicGF0aCI6Ii8xNjkzNTk1NjYvNTE4MTgxNTYyLWRmN2EyYWVhLTA4NGQtNDRmYy04N2U5LWE0N2VjNDc0YmUwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEyNFQxNjM3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTA1MWE4MjVlMGI4N2I5MzA3MDEwNTVmZTdhYzMyZTMwZjVhYjA3NDBlOTU3N2U2Mjk1YTJjOGJiMDE5MWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2BGFSDLhooeFP2ajfa59U4B-Bptr-J419qcJbRZMWqE"> I changed some codes in RSXThread.cpp, it seems can fix this problem. idk whether it'll cause other issue. [@elad335](https://github.com/elad335) [@digant73](https://github.com/digant73)
> 
> This is wrong, continue is the right action there. The real problem appears to be the index range, but I'm 99% sure it would also have crashed a real PS3 when going out of bounds. How do you reproduce the issue quickly?

Because it'll happen after enter some certain battles immediately. After change this code, the issue is disappeared.

I have recorded and uploaded a video to compare them.

https://www.bilibili.com/video/BV16aUkB3ETC/

**Comment by ReLyf47** [comment]
> > <img alt="Image" width="1123" height="281" src="https://private-user-images.githubusercontent.com/169359566/518181562-df7a2aea-084d-44fc-87e9-a47ec474be0d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQwMDI1MzgsIm5iZiI6MTc2NDAwMjIzOCwicGF0aCI6Ii8xNjkzNTk1NjYvNTE4MTgxNTYyLWRmN2EyYWVhLTA4NGQtNDRmYy04N2U5LWE0N2VjNDc0YmUwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEyNFQxNjM3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTA1MWE4MjVlMGI4N2I5MzA3MDEwNTVmZTdhYzMyZTMwZjVhYjA3NDBlOTU3N2U2Mjk1YTJjOGJiMDE5MWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2BGFSDLhooeFP2ajfa59U4B-Bptr-J419qcJbRZMWqE"> I changed some codes in RSXThread.cpp, it seems can fix this problem. idk whether it'll cause other issue. [@elad335](https://github.com/elad335) [@digant73](https://github.com/digant73)
> 
> This is wrong, continue is the right action there.
> The real problem appears to be the index range, but I'm 99% sure it would also have crashed a real PS3 when going out of bounds.
> How do you reproduce the issue quickly?

Just by playing, itll crash in like 3 minute of gameplay usually, especially using Lu Bu

**Comment by kd-11** [comment]
It's still wrong. You can also just disable the function and it wont crash. Restart indices are a normal part of graphics rendering. first + count is generating a value too large, that's the real issue.

**Comment by kd-11** [comment]
I'll give the game a shot later and try to recreate it. I have no idea what the series is about, so hopefully just standing still or watching some cutscenes can cause it to fail.

**Comment by lllljj1991** [comment]
Thanks. Hope this issue can be fixed correctly!

**Comment by matrox471** [comment]
> hopefully just standing still or watching some cutscenes can cause it to fail.

DYNASTY WARRIORS 8 [BLES01865]

welp, that's how i got the crash and found this issue.
I was waiting for a few of the demos to run to generate of bunch of shaders and one of the demo caused the crash.
Seems to be a pretty reliable way to get the crash.

- Launch the game
- skip intro
- wait for demo 1
- skip it
- wait for re intro
- skip it
- wait for demo 2
- crash

https://github.com/user-attachments/assets/fa19bf69-1401-4b91-8ec0-6a3f34a6da53

**Comment by GIOT66** [comment]
so, any lead?
is it still bugged?

**Comment by ReLyf47** [comment]
Not sure what  happened in the last week or so
but somehow i can run the game fine????

Either the issue is fixed, or that the error is somehow Windows Exclusive?
usually when i played this on my windows machine, 3 minutes into the game itll crash, but now it didnt crash on around the same place i usually do

LOG: 

[DYNASTY WARRIORS 8 Xtreme Legends \[NPEB01970\].log.gz](https://github.com/user-attachments/files/25710991/DYNASTY.WARRIORS.8.Xtreme.Legends.NPEB01970.log.gz)

**Comment by lllljj1991** [comment]
It still an issue.

LOG:

[RPCS3.log.gz](https://github.com/user-attachments/files/25717154/RPCS3.log.gz)

**Comment by ReLyf47** [comment]
So either i got a very lucky 8 minutes straight gameplay with no issue, or its a windows issue

No way its a game version issue right?

**Comment by matrox471** [comment]
> So either i got a very lucky 8 minutes straight gameplay with no issue, or its a windows issue

clearly not a windows only issue. my video detailing how to crash was recorded on arch linux.

I retried today to see if it still crashed and yeah.

- updated the flatpak
- deleted all caches
- booted with default config
- followed the instruction on my previous post
- still crash

**Comment by AniLeo** [comment]
Issue reports from unofficial builds such as the flatpak are not accepted.

**Comment by matrox471** [comment]
Fine ... i downloaded the appimage from the website just now.
redid the exact same things
same crash

**Comment by elad335** [comment]
While exploring how LV1 RSX works for VSH stuff, I understand now how it should be handled.

**Comment by ghost** [comment]
@elad335 was your pr #18909 suppose to fix this issue or is it something unrelated?

**Comment by matrox471** [comment]
Downloaded the linux (x86) appimage.

<img width="290" height="60" alt="Image" src="https://github.com/user-attachments/assets/b071806d-99f6-43d7-8bcd-4db66a3a930c" />

~~reproduced the same crash as described before.~~
I forgot to clear all caches of the appimage vs the last time i reproduced it.

The new version manage to not crash during the second demo.
as far as i can tell, at least in DW8. This issue seems fixed !

**Comment by matrox471** [comment]
Did some more sanity testing and 
rpcs3-v0.0.41-19484-e5cdae8c_linux64.AppImage -> crash
rpcs3-v0.0.41-19488-e429f8cf_linux64.AppImage -> crash
rpcs3-v0.0.41-19489-c1263eeb_linux64.AppImage -> Works !

<img width="1161" height="29" alt="Image" src="https://github.com/user-attachments/assets/64b5f76a-59c2-4799-ba54-f34a35748ec4" />

So yeah #18909 Fixes this ! nice work.

**Comment by lllljj1991** [comment]
> Did some more sanity testing and rpcs3-v0.0.41-19484-e5cdae8c_linux64.AppImage -> crash rpcs3-v0.0.41-19488-e429f8cf_linux64.AppImage -> crash rpcs3-v0.0.41-19489-c1263eeb_linux64.AppImage -> Works !
> 
> <img alt="Image" width="1161" height="29" src="https://private-user-images.githubusercontent.com/95183029/617276246-64b5f76a-59c2-4799-ba54-f34a35748ec4.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODMzMjUwNDIsIm5iZiI6MTc4MzMyNDc0MiwicGF0aCI6Ii85NTE4MzAyOS82MTcyNzYyNDYtNjRiNWY3NmEtNTljMi00Nzk5LWJhNTQtZjM0YTM1NzQ4ZWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNzA2VDA3NTkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYzlhMWMyY2EwY2M0YjljZWQ2YjQyNWI5NWQ0YWE2MTZhYThlNjRkOGRlYjkwMTUzOTVjNjhiOGE0ZGFmYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.DVQNlo6M9pFeQzel9pW0krwnN8NaZq7F70jcjJ85n8k">
> So yeah [#18909](https://github.com/RPCS3/rpcs3/pull/18909) Fixes this ! nice work.

I'm afraid that still an issue.

Tested on v0.0.41-19559 Windows x64 version.

LOG:

[RPCS3.log.gz](https://github.com/user-attachments/files/29692992/RPCS3.log.gz)

**Comment by matrox471** [comment]
@lllljj1991 out of curiosity, did you clear all caches for the game ? if not, you may  be using the old ones and they would still crash regardless of having the fix. (saying that because i forgot to clear before testing yesterday lol)

<img width="518" height="106" alt="Image" src="https://github.com/user-attachments/assets/e7fe306a-e0b9-43d5-9328-d21e0d9751ec" />

**Comment by lllljj1991** [comment]
> [@lllljj1991](https://github.com/lllljj1991) out of curiosity, did you clear all caches for the game ? if not, you may be using the old ones and they would still crash regardless of having the fix. (saying that because i forgot to clear before testing yesterday lol)
> 
> <img alt="Image" width="518" height="106" src="https://private-user-images.githubusercontent.com/95183029/617570664-e7fe306a-e0b9-43d5-9328-d21e0d9751ec.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODMzNTQ4MjAsIm5iZiI6MTc4MzM1NDUyMCwicGF0aCI6Ii85NTE4MzAyOS82MTc1NzA2NjQtZTdmZTMwNmEtZTBiOS00M2Q1LTkzMjgtZDIxZTBkOTc1MWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNzA2VDE2MTUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MjcwZDRiZmIzZTNmOGVhMDRmNDFhMTM3MDVkMzUxYjk4ZDI0ODNlYTZhYmYxYjk1OTQxNTVkMGRmNWYyYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.X0uzHDQ1PMoR9TcnyiSwqZOWZjOIaVifBcnBe8ZiA4U">

Of course I do. There's a method to reproduce the issue through loading a certain stage. You can try to play Battle of Bowangpo (DLC/Cao Cao Forces).

**Comment by QJYEAH** [comment]
> [@lllljj1991](https://github.com/lllljj1991)出于好奇，你有没有清除游戏的所有缓存？如果没有，你可能还在使用旧缓存，即使安装了修复程序，游戏仍然会崩溃。（我这么说是因为我昨天测试前忘了清除缓存，哈哈）
> 
> <img alt="图像" width="518" height="106" src="https://private-user-images.githubusercontent.com/95183029/617570664-e7fe306a-e0b9-43d5-9328-d21e0d9751ec.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODMzNDg1MzAsIm5iZiI6MTc4MzM0ODIzMCwicGF0aCI6Ii85NTE4MzAyOS82MTc1NzA2NjQtZTdmZTMwNmEtZTBiOS00M2Q1LTkzMjgtZDIxZTBkOTc1MWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNzA2VDE0MzAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlMDViMzcwYWJkNzBiN2U0N2E0ZjBhMjYyY2Y4N2ZhODIzYTJmM2QyMDgwMzM5ZjNkOGQ5ZTNiZDIwOWE2MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.DPTRD4nbIIMx_aaJh_Q29ml4RrCRVXB3TwdJ8nLhdLk">

in Ambition Mode，the game stii crash sometimes.maybe you should test in this mode

**Comment by matrox471** [comment]
> in Ambition Mode，the game stii crash sometimes.maybe you should test in this mode

Yep, got it to crash after playing 5 minutes top. just opened Ambition and picked the first skirmish lol.

> Of course I do. There's a method to reproduce the issue through loading a certain stage. You can try to play Battle of Bowangpo (DLC/Cao Cao Forces).

I don't have the DLC to test but i can comfirm the crash still happen. funny how one got fixed liked that.

<img width="525" height="18" alt="Image" src="https://github.com/user-attachments/assets/7beb52e5-664e-4d2d-8e4c-3b33d812a3a3" />

**Comment by QJYEAH** [comment]
> 在研究 LV1 RSX 如何用于 VSH 相关内容时，我现在明白了应该如何处理它。

in Ambition Mode，the game stii crash,the problem still
