### ISSUE TITLE
NCAA Football 14 Freeze and Crash

### ISSUE THREAD

**Issue by munchnbeaver** [RPCS3/rpcs3#9057]
## Quick summary
Play Now and Practice mode loads in, however if I start a road to glory mode, loading into a match freezes it. Then when trying to stop the game, the emulator crashes.

## Log
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5360081/RPCS3.log)

## Error Code
RSX [0x024b7a8]} SIG: Thread terminated due to fatal error: Unknown vkFormat 0x7e
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKFormats.cpp:462)

## System Configuration:
* Windows 10 x64
* Ryzen 7 3700x
* RTX 2070 Super
* 456.71

**Comment by kd-11** [comment]
I added the missing format at some point and it looks like it got lost somewhere. I'll republish the fix.

**Comment by munchnbeaver** [comment]
> I added the missing format at some point and it looks like it got lost somewhere. I'll republish the fix.

Is it fixed right now or will it be fixed in the next update?

**Comment by MrFuzzihead** [comment]
I wanted to update and say on the latest build (RPCS3 v0.0.15-11863-7c0b93f8 Alpha), I am still getting this error in the exact same gamemode as OP

> ·F 9:49:08.475919 {RSX [0x026b23c]} SIG: Thread terminated due to fatal error: Verification failed
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKRenderTargets.h:606[:10], in function as_rtt)
