### ISSUE TITLE
Bug: Missing or barely visible dragon logo in the Skyrim menu

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#9184]
In the Skyrim menu, which is supposed to look somewhat like this: 
![image](https://user-images.githubusercontent.com/1712979/97775603-aabe1780-1b6a-11eb-92d0-5b427bcee811.png)
the logo on Vulkan is entirely missing:
![Screenshot_13](https://user-images.githubusercontent.com/1712979/97775610-b90c3380-1b6a-11eb-88d3-beee8db9c492.png)
VK log: [vk.log.gz](https://github.com/RPCS3/rpcs3/files/5468817/vk.log.gz)
and barely visible on OpenGL:
![Screenshot_14](https://user-images.githubusercontent.com/1712979/97775612-c0334180-1b6a-11eb-80bb-c9e940f449e9.png)
GL log: [gl.log.gz](https://github.com/RPCS3/rpcs3/files/5468818/gl.log.gz)

RRC: 
[BLUS31202_20201031111100_capture.zip](https://github.com/RPCS3/rpcs3/files/5468816/BLUS31202_20201031111100_capture.zip)

RPCS3 v0.0.12-11134-5d55e509
Ryzen 7 2700
RX 580 20.10.1
Windows 20H2

**Comment by xddxd** [comment]
Further testing has revealed that it works correct when only the Shader Interpreter is enabled.

**Comment by kd-11** [comment]
The interpreter meme continues.

**Comment by xddxd** [comment]
I've retested it again, turns out it was a fluke when it worked a few times on the interpreter. It's much worse with it. 
![image](https://user-images.githubusercontent.com/1712979/97925993-0820b700-1d6b-11eb-9517-699d8054f871.png)

**Comment by digitaldude555** [comment]
![screenshot-2021_06_22_13_14_51](https://user-images.githubusercontent.com/26138653/122907548-f15fbc80-d35b-11eb-835e-87e9f76864ec.png)
Fixed.

**Comment by MSuih** [comment]
Further reports suggests that the issue still persist. Might be AMD-specific.

**Comment by xddxd** [comment]
Issue still persists for me.

**Comment by AphelionWasTaken** [comment]
This issue is indeed AMD-specific. Unable to reproduce on a 3080, but it occurs on a 5700XT.

**Comment by Darkhost1999** [comment]
Once you install the DLC from the PS3 extra folder and boot the game this is what the game looks like.
![Screenshot_20220218-163338_Moonlight.png](https://user-images.githubusercontent.com/60384196/154771101-76acff20-f1fd-4997-96f6-654131947e59.png)
If you do not have the DLC installed then you will not get this red effect on the start screen.
(I'll edit and upload log from my PC)

**Comment by Darkhost1999** [comment]
All 9 (English/French/Spanish) dlc independently tested: Screen is normal
English DLC:
With all 3 dlc installed: screen turns red
Dawnguard & Dragonborn: screen turns red
Dragonborn & Hearthfire: screen is Normal
Dawnguard & Hearthfire: screen is normal
All DLC combinations in Spanish and French reacted exactly the same as English.

Something about mixing Dawnguard and Dragonborn together is reactive.
Dawnguard [D000] (English) & Dragonborn [D007] (Español): screen turns red
Even across languages

**Comment by Darkhost1999** [comment]
PPU interpreter
![image](https://user-images.githubusercontent.com/60384196/161398297-a34fecaa-f65f-4b6f-91c9-db6f37cb9641.png)
PPU LLVM
![image](https://user-images.githubusercontent.com/60384196/161398346-6d12321c-196c-4b2f-bc49-682c43f8be04.png)

**Comment by Darkhost1999** [comment]
<details>
<summary>OpenGL</summary>

PPU interpreter
![image](https://user-images.githubusercontent.com/60384196/161399051-63e1ac7a-9c8d-497d-a988-11032f23ff82.png)
PPU LLVM
![image](https://user-images.githubusercontent.com/60384196/161398899-e2acc23e-14e4-4efe-ada4-2f4d2e304973.png)

</details>

Let's go back to Vulkan and show off shader modes while the shader label still exists

<details>
<summary>All Shader modes using PPU Interpreter</summary>

Legacy
![image](https://user-images.githubusercontent.com/60384196/161399486-1b83a528-ca1e-4de3-9495-3eff8713be9f.png)
[PPU Interpreter Shader Legacy](https://github.com/RPCS3/rpcs3/files/8403303/RPCS3.log)
Async
![image](https://user-images.githubusercontent.com/60384196/161399315-5ab305fb-67a1-417e-b0b5-06bf65ee6914.png)
[PPU Interpreter Shader async](https://github.com/RPCS3/rpcs3/files/8403296/RPCS3.log)
Async with Shader Interpreter
![image](https://user-images.githubusercontent.com/60384196/161399932-6ce6a8eb-9a45-4528-a06d-299c33d47f02.png)
[PPU Interpreter Shader async + Interpreter](https://github.com/RPCS3/rpcs3/files/8403322/RPCS3.log)
Shader Interpreter
![image](https://user-images.githubusercontent.com/60384196/161400124-0ecb77b2-184c-4d0e-af54-879a9964c007.png)
[PPU Interpreter Shader Interpreter](https://github.com/RPCS3/rpcs3/files/8403334/RPCS3.log)

</details>

As you can see the initial reported issue by OP looks solved.
The remaining issue is caused by PPU
This issue requires
Dawnguard & Dragonborn dlc Installed
and is not AMD specific or graphics renderer specific {anymore}

**Comment by Darkhost1999** [comment]
For my red screen issue that is not a missing or barely visible dragon logo in the Skyrim menu. But has been labeled a duplicate.

I have discovered
This build is always broken
![Screenshot 2022-05-30 231152](https://user-images.githubusercontent.com/60384196/171095078-a2c1771b-b7ae-4ff8-ac65-509684152c51.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8802119/RPCS3.log)

This build is sometimes broken
![Screenshot 2022-05-30 231335](https://user-images.githubusercontent.com/60384196/171095271-d2dff4a3-1eef-4ab1-b9c3-f6c5d2b8753e.png)
[1st boot Red 2nd boot normal](https://github.com/RPCS3/rpcs3/files/8802151/RPCS3.log)
![Screenshot 2022-05-30 230927](https://user-images.githubusercontent.com/60384196/171095280-2c04071e-3c47-4b40-aa00-65d44b20fb95.png)
[Both boots normal](https://github.com/RPCS3/rpcs3/files/8802141/RPCS3.log)

This build is again Sometimes broken
![image](https://user-images.githubusercontent.com/60384196/171096295-1ff64893-bb07-4ea3-a177-7ab9606472d1.png)
[1st boot red 2nd boot normal](https://github.com/RPCS3/rpcs3/files/8802162/RPCS3.log)
![Screenshot 2022-05-30 230348](https://user-images.githubusercontent.com/60384196/171095309-2f0dc15f-65d4-4457-8fb2-308f09362bbc.png)

So due to some builds being sometimes broken it is very difficult to pinpoint 1 singular PR aside from the always broken build made the issue worse

**Comment by kd-11** [comment]
Needs an updated RSX capture file.

**Comment by Darkhost1999** [comment]
I can provide for red screen but I don't have the hardware for the partial dragon logo. Hence why I made a separate issue because they're not the same.

**Comment by Darkhost1999** [comment]
Red screen is solvable via PPU Interpreter so it's not a graphics issue

**Comment by xddxd** [comment]
Seems to be fixed

**Comment by Darkhost1999** [comment]
![Screenshot_20221031-183722.png](https://user-images.githubusercontent.com/60384196/199129270-34295f9a-e27f-40a1-9ccf-23dee2b65043.png)
