### ISSUE TITLE
[GIT version] Most recent update of util/atomic.cpp seems to cause segfault while starting any game

### ISSUE THREAD

**Issue by heavysink** [RPCS3/rpcs3#9386]
OS:
Archlinux, i7-10750H, RTX2070 Max-Q
rpcs3 git version, cmake option: cmake -DCMAKE_BUILD_TYPE=Debug

Summary:
Most recent update GIT version seems to have segfault when starting any game.

gdb output:

Thread 14 "..pool" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff47fff640 (LWP 123614)]
atomic_wait_engine::wait(void const*, unsigned int, long long __vector(2), unsigned long, long long __vector(2), atomic_wait::info*) (data=0x76fd400 <thread_base::finalize(unsigned long)::s_pool_ctr>, size=8, old_value=..., 
    timeout=18446744073709551615, mask=..., ext=0x7fff47ffbbd0) at /home/heavysink/src/rpcs3/rpcs3/util/atomic.cpp:1149
1149			atomic_fence_seq_cst();
(gdb) bt
#0  atomic_wait_engine::wait(void const*, unsigned int, long long __vector(2), unsigned long, long long __vector(2), atomic_wait::info*)
    (data=0x76fd400 <thread_base::finalize(unsigned long)::s_pool_ctr>, size=8, old_value=..., timeout=18446744073709551615, mask=..., ext=0x7fff47ffbbd0) at /home/heavysink/src/rpcs3/rpcs3/util/atomic.cpp:1149
#1  0x00000000005d8a4c in atomic_wait::list<2u>::wait(atomic_wait_timeout) (this=0x7fff47ffbba0, timeout=atomic_wait_timeout::inf) at /home/heavysink/src/rpcs3/rpcs3/util/atomic.hpp:302
#2  0x00000000005d4023 in thread_base::finalize(unsigned long) (_self=140734401345088) at /home/heavysink/src/rpcs3/Utilities/Thread.cpp:2124
#3  0x0000000008003014 in  ()
#4  0x0000000000000000 in  ()

RPCS3.log attached
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5655034/RPCS3.log)

**Comment by arabek** [comment]
Same here.

**Comment by Hirato** [comment]
can get the segfault by invoking `Create Firmware Cache` too.
It's a little random, but it will sometimes print things like this to stdout as well.

```Segfault writing location 00000000d5d49060 at 00000000006553a7.
Emu Thread Name: 'Progress Dialog Server'.
Thread id = 140556392252992.

RPCS3: Segfault writing location 00000000d5d49060 at 00000000006553a7.
Emu Thread Name: 'Progress Dialog Server'.
Thread id = 140556392252992.

Found exec link: /usr/bin/rpcs3
Debugger: 0
```

**Comment by arabek** [comment]
```
Thread 14 "..pool" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff60a26640 (LWP 171054)]
0x000000000065c0b7 in atomic_wait_engine::wait(void const*, unsigned int, long long __vector(2), unsigned long, long long __vector(2), atomic_wait::info*) ()
(gdb) bt full
#0  0x000000000065c0b7 in atomic_wait_engine::wait(void const*, unsigned int, long long __vector(2), unsigned long, long long __vector(2), atomic_wait::info*)
    ()
No symbol table info available.
#1  0x000000000069793c in thread_base::finalize(unsigned long) ()
No symbol table info available.
#2  0x0000000005003014 in ?? ()
No symbol table info available.
#3  0x0000000000000000 in ?? ()
No symbol table info available.
(gdb) c
Continuing.
Segfault writing location 0000000060a23120 at 000000000065c0b7.
Emu Thread Name: 'Progress Dialog Server'.
Thread id = 140734814643776.
```

**Comment by gamrXerus** [comment]
I can confirm from pr 9376, rpcs3 crashes when trying to boot up a game. I'm on Lubuntu 20.10

**Comment by Nekotekina** [comment]
I hope it's fixed now, sorry.

**Comment by arabek** [comment]
Confirming, fixed by https://github.com/RPCS3/rpcs3/pull/9388

**Comment by nitroos-ai** [comment]
Still broken for me.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5663552/RPCS3.zip)

**Comment by MSuih** [comment]
Does it happen if you switch from SPU ASMJIT to LLVM?

**Comment by MSuih** [comment]
#9399 might fix any lingering issues.

**Comment by nitroos-ai** [comment]
Yes #9399 fixes my issue. Thanks.
