### ISSUE TITLE
Broken text in some menu windows in Gran Turismo 5 Prologue [NPUA80075]

### ISSUE THREAD

**Issue by PY3AN** [RPCS3/rpcs3#9558]
Broken text in some menu windows in Gran Turismo 5 Prologue spec II [NPUA80075] like сar view window in car dealership or some Event windows.

![Broken_text_GT5P](https://user-images.githubusercontent.com/76910089/103791388-762b7800-5053-11eb-853c-4e7d6c7d1aa3.png)

![Broken_text_GT5P_Event](https://user-images.githubusercontent.com/76910089/103793665-22ba2980-5055-11eb-8608-ed912e2b04ae.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5776903/RPCS3.log.gz)

System configuration:

    RPCS3 v0.0.14-11518
    Firmware version: 4.86
    OS Windows 10 20H2, 19042.685
    CPU AMD Ryzen 5 3600
    GPU AMD Radeon RX 580 8G
    Memory Crucial Ballistix Sport 16G
    Driver version 2.0.168

**Comment by kd-11** [comment]
Just enable MSAA and the problem is fixed. PS3 uses MSAA to render the text and for some yet unknown reason it falls apart when we try to cheat and render without it.

**Comment by kd-11** [comment]
Wrong game, I was thinking of GT5. Sorry.
Looks like MSAA is enabled for this one and its still broken.
Can you maybe try with a large resolution scale and see if anything changes?

**Comment by PY3AN** [comment]
Resolution scale at 15% (1920x1080), text still broken.

![Broken_text_GT5P_2](https://user-images.githubusercontent.com/76910089/104130884-44cce800-5384-11eb-88f1-43c52fc2d5d6.png)

[Broken_text_GT5P_2_Settings.zip](https://github.com/RPCS3/rpcs3/files/5793041/Broken_text_GT5P_2_Settings.zip)

**Comment by Augusto7743** [comment]
Here works fine without text issues.
using an GT 640.

**Comment by Megamouse** [comment]
I only have minor issues with similar settings.
"Strict Rendering Mode" fixes it for me.

**Comment by Augusto7743** [comment]
Look how if is an issue with GPU driver.
see  9610

**Comment by digitaldude555** [comment]
@PY3AN retest

**Comment by PY3AN** [comment]
On RPCS3 v0.0.17-12522 and AMD driver 21.4.1 broken text is still there.

**Comment by Blackbird88** [comment]
I can confirm that Strict Rendering mode indeed fixes it.
GRAN TURISMO HD Concept [NPUA80019] has same issue.

**Comment by Megamouse** [comment]
closing. fixed with SRM
